remix-run/remix

- contributors.yml
- docs/tutorials/blog.md
Following the blog tutorial and found some typos:
- `serever` instead of  `server`
- missing `export` on the `type Post` in the first refactor section
- misc. typos in the 90's playlist
> Typos in docs/tutorials/blog.md

- contributors.yml
- packages/create-remix/templates/fly/package.json
I'm guessing this doesn't do anything since we moved on to open-source.
> Remove REMIX_TOKEN from fly.io template

- contributors.yml
- packages/create-remix/templates/fly/README.md
REMIX_TOKEN was removed from the package.json deploy script in #519 but the README.md still referenced it.
> Remove reference to REMIX_TOKEN from fly.io readme

- packages/create-remix/templates/vercel/api/index.js
- packages/create-remix/templates/vercel/gitignore
- packages/create-remix/templates/vercel/remix.config.js
This change will prevent the `_build` directory within `api` from receiving its own dedicated Serverless Function, which will speed up the build because it prevents unnecessary transformations.
> chore: Allow for faster Builds on Vercel

- contributors.yml
- docs/tutorials/jokes.md
As @kentcdodds mentioned in [yesterday's live stream](https://youtu.be/hsIWJpuxNj0?t=18158) while going through the Jokes App tutorial, the `<Meta />` component needs to be placed above the `<title>` tag in the root's `Document`. 
I just spent quite some time wondering why my titles weren't showing up, before finally checking the live stream replay to watch Kent figure it out. Apparently, browsers take the first `<title>` tag to name their tabs.
> [Docs] SEO - Move the Meta component above title tag

- docs/api/remix.md
- docs/guides/api-routes.md
- docs/guides/data-writes.md
- docs/guides/mdx.md
- docs/guides/optimistic-ui.md
- docs/tutorials/blog.md
- examples/basic/app/root.tsx
- examples/blog-tutorial/app/root.tsx
- examples/blog-tutorial/app/routes/admin/new.tsx
- examples/jokes/app/root.tsx
- fixtures/gists-app/app/root.jsx
- fixtures/gists-app/app/routes/blog/index.tsx
- fixtures/gists-app/app/routes/fetchers.tsx
- fixtures/gists-app/app/routes/gists.jsx
- packages/create-remix/templates/_shared_js/app/root.jsx
- packages/create-remix/templates/_shared_ts/app/root.tsx
- packages/remix-react/components.tsx
To make @kentcdodds happy
https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx
> refactor: use ternaries rather than && in JSX

- contributors.yml
- packages/create-remix/templates/_shared_js/gitignore
- packages/create-remix/templates/_shared_ts/gitignore
- packages/create-remix/templates/remix/gitignore
Updated gitignore template files to include .env files by default so they are not committed to a repo. Adds feature request #760
> added .env to gitignore

- packages/remix-react/transition.ts
It's never used & also not exported as a public API
> chore(remix-react): remove `SubmissionTransition` type

- docs/tutorials/blog.md
tiny-invariant was imported at line 828 in blog.md but not used actually, so I removed the unnecessary import.  Additionally I added highlight for its first use in new.tsx.
> Fix tiny-invariant import and highlight in new.tsx

- fixtures/gists-app/package.json
This *technically* shouldn't be necessary, but since we don't actually install Remix in the gists fixture we don't get its dependencies, which means React Router was missing and all of our tests were failing. Tragic!
> Add `react-router-dom` dependency to gists fixture

- contributors.yml
- docs/tutorials/blog.md
"the file" didn't have any context yet, so it was not clear which file
was being referred to.
In the phrase "find into the Layout component" it appears "into" is an
extra word.
fixes: https://github.com/remix-run/remix/issues/793
> docs: clarify instruction in blog tutorial

- contributors.yml
- rollup.config.js
Remove the trailing space after `#!/usr/bin/env node` when inserting the executable banner in
- @remix-run/dev/cli.js
- @remix-run/serve/cli.js
The trailing space causes builds to fail when deploying to Digital Ocean's Apps Platform with error
`/usr/bin/env: 'node ': No such file or directory`
> fix(dev,serve): remove trailing space in executableBanner in cli

- contributors.yml
- docs/api/remix.md
Kent tweeted [this](https://twitter.com/kentcdodds/status/1466409430694576128?t=DiZ4XoBq09mr1I2KDScNaw&s=19) in response to a tweet this evening and while reading I noticed a reference to `value.showBanner` rather than `cookie.showBanner` in the loader function of an example, so I fixed it!
> chore(docs): fix typo

- contributors.yml
- docs/guides/resource-routes.md
This PR:
- Adds an explanation to the resource routes doc explaining to use `loader` for `GET` requests and `action` for `POST`, `PUT`, `PATCH` and `DELETE` requests.
I was a bit confused and asked in the Discord and ran my own test. Hopefully this will short-circuit that for future people.
> Docs: Explain how to handle different request methods with resource routes

- docs/api/remix.md
Fixes a typo in page - https://remix.run/docs/en/v1/api/remix#link
> fix typo: repeated words

- packages/remix-react/components.tsx
```tsx
export default function ProductFilters() {
return (
<Form method="get">
<label htmlFor="nike">Nike</label>
<input
type="checkbox"
id="nike"
name="brand"
value="nike"
/>
<label htmlFor="adidas">Adidas</label>
<input
type="checkbox"
id="adidas"
name="brand"
value="adidas"
/>
<button type="submit">Update</button>
</Form>
);
}
```
Serializing that should end up with `brand=nike&brand=adidas` but it only keeps the last one since it was using `set`
> append to formData/searchParams

- docs/api/conventions.md
I'm pretty sure the section about `HtmlMetaDescriptor`  is meant to be under `meta` instead of under `links`.
> docs: move 'HtmlMetaDescriptor' to be under 'meta' instead of 'links'

- docs/tutorials/jokes.md
- examples/jokes/app/routes/jokes/new.tsx
- examples/jokes/app/routes/login.tsx
When a request is sent to the server and there's something invalid about
the request, the server should return a 4xx status to accurately
represent the response.
We could have all the error cases use the `json` function directly, but
then we loose the advantage of the helpful typechecking `ActionData`
provides.
```ts
export const action: ActionFunction = async ({ request }) => {
//...
return json({ wrongActionDataErrorKey: "oops!" }, { status: 400 }));
```
For this reason, I've introduced the `badRequest` helper function so
that we can still get typechecking for `ActionFunction` returns, while
returning the accurate status in the Response.
```ts
const badRequest = (data: ActionData) => json(data, { status: 400 });
export const action: ActionFunction = async ({ request }) => {
//...
// and …
```
> fix: jokes tutorial actions should return 400 status for errors

- packages/create-remix/templates/fly/package.json
> fix(fly): use remote-only deploys

- packages/remix-react/errorBoundaries.tsx
when an error surfaces from the transition manager it's not thrown from the react render stack, rather set in the app state and surfaced through props
> feat: surface errors from fetch submissions

- packages/remix-react/routes.tsx
- packages/remix-react/transition.ts
fix: take into account redirect before catch for actions
> fix: stop routes that won't render from loading

- fixtures/gists-app/tests/error-handling-test.ts
- packages/remix-react/browser.tsx
- packages/remix-react/components.tsx
- packages/remix-react/entry.ts
- packages/remix-react/errors.ts
- packages/remix-server-runtime/__tests__/server-test.ts
- packages/remix-server-runtime/__tests__/utils.ts
- packages/remix-server-runtime/data.ts
- packages/remix-server-runtime/entry.ts
- packages/remix-server-runtime/errors.ts
- packages/remix-server-runtime/responses.ts
- packages/remix-server-runtime/routeData.ts
- packages/remix-server-runtime/server.ts
goals:
- simplify shared server runtime
- simplify loop that tracks boundaries
- simplify how actions / loaders are called
- make sure all boundary cases are surfaced properly
addresses https://github.com/remix-run/remix/issues/599 (todo: add tests)
> wip: re-work server runtime

- docs/api/conventions.md
- examples/basic/remix.config.js
- examples/blog-tutorial/remix.config.js
- examples/jokes/remix.config.js
- packages/create-remix/templates/_shared_js/remix.config.js
- packages/create-remix/templates/_shared_ts/remix.config.js
- packages/create-remix/templates/arc/remix.config.js
- packages/create-remix/templates/cloudflare-workers/remix.config.js
- packages/create-remix/templates/express/remix.config.js
- packages/create-remix/templates/fly/remix.config.js
- packages/create-remix/templates/netlify/remix.config.js
- packages/create-remix/templates/remix/remix.config.js
- packages/create-remix/templates/vercel/remix.config.js
`browserBuildDirectory` is deprecated and `assetsBuildDirectory` should be used instead
> feat: use `assetsBuildDirectory` instead of deprecated `browserBuildDirectory` config option

- contributors.yml
- docs/api/remix.md
Remix is great! Thanks for making it open source. I found this little mistake reading through the docs.
> docs(api): fix variable id → timer

- packages/remix-react/components.tsx
- packages/remix-react/index.tsx
When running `yarn build`, you get the following warning:
```sh
(!) Circular dependency
packages/remix-react/components.tsx -> packages/remix-react/scroll-restoration.tsx -> packages/remix-react/components.tsx
```
This PR fixes the circular dependency
> fix(remix-react): fix circular dependency

- docs/other-api/constraints.md
- packages/remix-react/scroll-restoration.tsx
Runtimes such as Deno have a window defined making this check not work.
> fix: use document over window for browser check

- packages/remix-cloudflare-workers/globals.ts
- packages/remix-dev/compiler.ts
- packages/remix-node/globals.ts
This will help avoid descrepancies at runtime between it being defined for the browser and a different runtime value for the server. This has been a source of issues for many regarding surfacing `<LiveReload>` in production.
> feat: define process.env.NODE_ENV for server build

- contributors.yml
- docs/api/conventions.md
because it leads to client side navigation errors: the canonical URL has no trailing slash
--- 
I noticed that on https://remix.run/docs/en/v1/api/conventions#handle, the `﻿useMatches﻿` link redirects to https://remix.run/docs/en/v1.0.6/api/remix/#usematches
When SSR'd (e.g: open in new tab) it renders properly because of a 302 to https://remix.run/docs/en/v1.0.6/api/remix#usematches (trailing URL slash removed).
On client side navigation it leads to a 404.
https://user-images.githubusercontent.com/75968/145932105-126839c6-3b0e-4b4e-96d7-88a1e9ff560c.mp4
I've only searched for occurrences in this documentation page. The doc may contain other ones.
It may also be considered as a bug with Remix itself and may need a fix in the client-side navigation default patterns? (not sure what does the …
> fix(doc): remove trailing slash from anchored links

- contributors.yml
- docs/api/conventions.md
Navigating to https://remix.run/docs/en/v1.0.6/api/remix/#usematches directly will strip the last slash and correctly resolve to https://remix.run/docs/en/v1.0.6/api/remix#usematches, but using this link [here](https://remix.run/docs/en/v1/api/conventions#handle) directs to a 404.
> chore(docs): Use fragment of remix page.

- contributors.yml
- docs/tutorials/blog.md
There's a couple of spots in the New Blog form section that don't quite match the previous code snippets. 
One has `ActionFunction` imported with the other remix imports instead of the seperate type-only import it was previously defined as, and the others are some missing highlighting of new code.
> fix(doc): fix code snippets imports and highlighting in new blog tutorial

- .gitignore
- contributors.yml
- packages/remix-react/components.tsx
This is a small tweak to @jacob-ebey's #403 that removes the window property. It achieves the same result as #390 but with minimal changes to Remix and no hydration mismatch concerns. Remix's `components` module is only instantiated once, so a module variable is sufficient for tracking `isHydrated` state.
> Skip script rendering after hydration

- contributors.yml
- docs/api/remix.md
Expanded description and added example for NavLink component, with an example taken from react-router docs, as this component is taken from react-router.
> docs: add example for <NavLink> taken from react router

- contributors.yml
- docs/guides/styling.md
Since Tailwindcss has been updated to v3, the document page of install tailwindcss has been updated
about tailwindcss v3 https://tailwindcss.com/blog/tailwindcss-v3
Tailwindcss upgrade guide https://tailwindcss.com/docs/upgrade-guide
> doc: Updated to support tailwind css v3

- fixtures/gists-app/server.js
This should clean up our CI logs a bit and make it easier to spot real problems in tests!
> chore: Clean up test output in gists app

- packages/remix-dev/compiler.ts
reverts #1076 and uses inline source maps as the previous fix broke asset loading 😭
> fix(dev/compiler): use inline sourcemaps for server build

- contributors.yml
- docs/guides/styling.md
I noticed `stylesheet` was missing quotes under the `links` demo in `guides/styling`. This should cover all the usages I found!
> Fix: missing quotes around "stylesheet" on guides

- contributors.yml
- docs/pages/contributing.md
- docs/tutorials/blog.md
I noticed an error with the blog tutorial. In the section titled "💿 Add validation messages to the UI", exactly the opposite lines as what actually changed in the file are highlighted. This PR changes the line highlights to show the correct changes from the file's previous state.
While reading the contributing page, I also saw a `[` that appears to have accidentally been left in the text when a link to CodeSandbox was swapped for a link to StackBlitz. This PR also removes that bracket.
> Fix highlighting error in blog tutorial and typo in contributing page

- packages/create-remix/templates/cloudflare-pages/README.md
- packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
- packages/remix-cloudflare-pages/index.ts
- packages/remix-cloudflare-pages/package.json
- packages/remix-cloudflare-pages/worker.ts
- yarn.lock
- Band-aid solution for [the `If-None-Match` caching bug in Pages](https://github.com/cloudflare/wrangler2/issues/117).
- Rename `createFetchHandler` to `createPagesFunctionHandler`
- Couple of tweaks to the create-remix README for Pages.
> Cloudflare Pages tweaks

- packages/remix-architect/server.ts
- packages/remix-express/server.ts
- packages/remix-netlify/server.ts
- packages/remix-server-runtime/data.ts
- packages/remix-vercel/server.ts
The code used `url.href` in places and `url.toString()` in others. Be consistant throughout and use the more concise `url.href`.
> refactor: use url.href vs url.toString()

- docs/api/remix.md
- docs/guides/disabling-javascript.md
- fixtures/gists-app/app/pages/one.mdx
- fixtures/gists-app/app/pages/two.mdx
- fixtures/gists-app/app/routes/blog/hello-world.mdx
- fixtures/gists-app/app/routes/blog/second.md
- fixtures/gists-app/app/routes/blog/third.md
- fixtures/gists-app/app/routes/one.mdx
- fixtures/gists-app/app/routes/two.md
- packages/remix-react/browser.tsx
- packages/remix-react/components.tsx
- packages/remix-react/routes.tsx
- packages/remix-react/server.tsx
We're pushing `react-jsx` in our templates
https://github.com/remix-run/remix/blob/f5a551ee139484f8d821220986a0515f95a69ce2/packages/create-remix/templates/_shared_ts/tsconfig.json#L6
> chore: remove all `React` default imports

- docs/api/remix.md
- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/transition.ts
Previously `fetcher.data` was erroneously removed when a fetcher was reloaded or resubmitted, this required apps to duplicate the state into their own app state to build a UI that didn't flicker data.
> fix: persist `fetcher.data` through re-fetches

- packages/remix-cloudflare-pages/worker.ts
We're accessing the request twice (once with the `env.ASSETS.fetch` and once by Remix). This clones it in the first case so the body can still be accessed by Remix.
> fix: Clone the request body to better handle POSTs

- rollup.config.js
The `@remix-run/serve` build is currently broken because it does not emit the `env` module. Unsure if this is the right long-term fix but I think it should be sufficient for a patch. Fixes https://github.com/remix-run/remix/issues/1128.
> fix(serve): Build not emitting env module

- contributors.yml
- packages/remix-cloudflare-pages/worker.ts
On Windows, `If-None-Match` header causes an error, this PR changes the header to the lowercase version.
> Fix header casing windows cloudflare pages

- contributors.yml
- docs/api/conventions.md
I spent a lot of time wondering why I was getting a `426 Upgrade Required` response back from my local application when running `remix dev`. I had made the assumption that `devServerPort` was the port of my applications server, but it is in-fact the port of the websocket server. This PR specifies in the docs that for anyone in the future who might make the same assumption.
> Specifying that the devServerPort is specifically for the websocket server

- packages/create-remix/templates/arc/package.json
The Arc team says that the aws-sdk dep is huge and delays cold boot times by 2-3 seconds, so it shouldn't be a regular dep. Instead, continue to suggest that people install it as a global dep like the README says.
> fix(arc): aws-sdk should be a global install

- packages/remix-react/data.ts
- packages/remix-react/links.ts
The prefetch link tag and the actual data being fetched were not the same because the data fetching code sorted the params. I'm the dork that sorted it in the first place, it was a mistake.
Now the href's match up and prefetching is actually useful for link with search params:
```jsx
// given this anchor
<Link to="/page?same=thing" />
// prefetch link
<link rel="prefetch" href="/page?same=thing&_data={routeId}" as="fetch" />`
// data fetch
fetch(`/page?same=thing&_data={routeId}`)
```
Updated the prefetch search params to use `set` instead of `append` because `_data` is a remix-reserved param, apps don't get to use it.
> fix: stop sorting params on data fetch

- examples/mantine/package.json
codesandbox can't resolve the hooks package and throws an error; so we have to add it manually. I will check again when server container is out of beta.
> Docs (Example): codesandbox fix - added "@mantine/hooks" package

- .github/workflows/format.yml
Pretty certain this should work to push the commits as the remix bot so it can get in without protections blocking it.
> chore(format): use github bot token to push

- .github/workflows/format.yml
@kentcdodds was soooo close in #1454
this led me to resolving the issue https://www.paulmowat.co.uk/blog/resolve-github-action-gh006-protected-branch-update-failed
here's a quick example before i delete the repo https://github.com/remix-run/gh-action-push-to-protected-branch/commits/dev
> ci: checkout repo using GH_BOT_TOKEN

- contributors.yml
- docs/guides/data-loading.md
Was passing `e.target` to `useSubmit`, which is incorrect and won't type-check. The other example of `useSubmit` on this page uses `e.currentTarget`, as do the [docs for useSubmit](https://remix.run/docs/en/v1/api/remix#usesubmit)
> Docs: Fixes error in useSubmit example

- contributors.yml
- docs/api/remix.md
When using Cloudflare KV storage to store a session it's important to use file name `sessions.server.ts` with the `.server` keyword in order for Remix to only bundle this code on the server bundle.
Spent a couple of hours trying to figure out why a route that has a `loader` and a `default` export with the UI would throw an error although the session is only handled on the loader (server side) and this was the solution.
> docs: update cloudflare KV example

- contributors.yml
- docs/tutorials/blog.md
There is an error that appears when users go through the _[Creating Blog Posts](https://remix.run/docs/en/v1/tutorials/blog#creating-blog-posts)_ tutorial steps. The error indicates the `app/styles` directory does not exist:
This directory [existed before](https://github.com/remix-run/remix/pull/1114/files#diff-d04ce6f8a6ca906b75f64b36cd1b9f156968ab7742c006555fcefefb7f3fa80aL149), but the starter template was recently changed. This PR adds a `mkdir` step so that users do not encounter the error seen above while going through the tutorial.
> docs: update blog example step

- contributors.yml
- examples/redis-upstash-session/app/sessions/upstash.server.ts
Method `getSeconds()` returns the seconds of the specified date (from 0 to 60) and it leads to incorrect expiration time calculation.
For correct total time difference calculation should be used method `getTime()` - it returns milliseconds since the Unix Epoch.
> docs(examples): fix expires calculation in redis session

- contributors.yml
- docs/api/remix.md
It wasn't clear where the `NewsletterSignup` component was rendered at the beginning of the newsletter example for `useFetcher`. I hope this change makes it clearer.
> docs: clarify newsletter useFetcher example in the docs

- contributors.yml
- packages/remix-express/__tests__/server-test.ts
- packages/remix-vercel/__tests__/server-test.ts
- packages/remix-vercel/server.ts
…e a stream passed as the response body
See #1244 for additional info
> fix(vercel): allow for streams to be returned as the response body

- packages/remix-cloudflare-workers/worker.ts
Part 1 from PR https://github.com/remix-run/remix/pull/924 by @GregBrimble.
~~This was pulled into its own PR because I don't think we can do part 2 because unless I misunderstand CF's edge cache, they operate on the `max-age` header and not `s-maxage`. This would land you in cases where you want to `max-age=5` or some small value for a piece of user-specific content in just their browser and have it end up cached at the edge and served to other visitors.~~ I forgot about the `private` directive 🤦‍♀️
Still good to pull it into its own PR to give it a good test run and make sure CF isn't caching things we don't expect them to be.
> feat(cloudflare-workers): edge cache static assets

- packages/remix-dev/cli/commands.ts
- packages/remix-dev/config.ts
- packages/remix-dev/package.json
- yarn.lock
uses [get-port](https://github.com/sindresorhus/get-port) instead of incrementing by 1 like #844 and #746
also applies the port checking to the `devServerPort`
closes #863, #844, and #746
> feat(dev): get available port if not available

- contributors.yml
- packages/remix-architect/__tests__/server-test.ts
- packages/remix-architect/server.ts
Separate multiple request cookie header values by semi-colon instead of comma.
Closes #1663
> fix(remix-architect): fix forwarding of request cookie headers

- contributors.yml
- docs/guides/accessibility.md
This is important because in the current [guide](https://remix.run/docs/en/v1.1.3/guides/accessibility#links) the navlink component is getting rendered as an empty html element rendering the text "Remix also provides the which behaves..." while it should have been "Remix also provides the <NavLink> which behaves...."
> Change < and > in Acessibility guide to their html escaped versions

- contributors.yml
- docs/guides/data-writes.md
I noticed that the wrong lines were highlighted on some of the code samples on the "Data Writes" guide. This should fix that! That said, I couldn't find a way to actually preview the documentation site locally to triple check the highlighting - is there any way to do that?
> fix: Highlight correct lines on Data Writes guide

- contributors.yml
- packages/create-remix/templates/express/server.js
- packages/remix-serve/index.ts
I do not know how to write a test for it because I do not know what to set as `buildPath`:
packages/remix-serve/\_\_tests\_\_/index-test.ts
```typescript
import { createApp } from "../index";
describe("createApp", () => {
it("x-powered-by header is disabled", async () => {
const buildPath = "????";
const app = createApp(buildPath);
expect(app.disabled("x-powered-by")).toBe(true);
});
});
```
jest.config.js
```javascript
module.exports = {
projects: [
...
{
displayName: "serve",
testEnvironment: "node",
testMatch: [
"<rootDir>/packages/remix-serve/**/*-test.[jt]s?(x)",
],
setupFiles: ["<rootDir>/jest/setupNodeGlobals.ts"]
},
...
],
...
}
```
I solved it for Express, but maybe it should be part of `ServerPlatform` to disable this header?
Resolves: #1710
> feat: Remove x-powered-by header (#1710)

- contributors.yml
- docs/api/remix.md
fixed a small misnaming of `application/x-www-form-urlencoded` in the docs
> DOC: changed application/x-www-urlencoded to application/x-www-form-urlencoded

- contributors.yml
- docs/api/remix.md
Hi. Just a little fix on the highlight lines in the documentation site. see #1683 for more details.
URL: https://remix.run/docs/en/v1/api/remix
> fix(docs): fixing highlight lines Close remix-run#1683

- contributors.yml
- docs/tutorials/jokes.md
The `validateJokeName()` described as the sample code in this section is `name.length < 2`, so I fixed the description for the validation rule in docs.
> docs: fix name validation rule in Mutations section

- contributors.yml
- docs/guides/styling.md
Corrected the syntax for linking.
I stumbled across this issue in the docs and also found a bug report to have the same issue, I have linked it to this PR.
closes #704
> fix(docs):#704 Invalid link to route-module-links

- contributors.yml
- docs/tutorials/jokes.md
Earlier in the tutorial the pattern have been using `db` in stead of `prisma`. When `prisma` suddenly is used in the seed and only the highlighted diff is copied to the editor, the seed function will fail as `prisma` is not defined. However, `db` is if the user have copied `seed.ts` from earlier in the tutorial.
> update tutorial to use db variable for continuity

- contributors.yml
- docs/tutorials/blog.md
I mistakenly tried going through the quick-start guide on Node v12 which lead me to encounter an error where `@remix/server` was not found, even after trying to install it manually.
I thought maybe i'd done something wrong so I repeated the process and hit the same issue.
A simple fix is to just add a docs-warning to the top of the remix-quickstart guide.
> Enhancement: Added docs-warning to quickstart guide

- fixtures/gists-app/package.json
- packages/remix-dev/compiler.ts
- packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
- packages/remix-dev/setup.ts
- packages/remix/index.ts
fix: add mainFields to client build to resolve ESM
fix: force sideEffects false for browser route modules
> fix: avoid `export *` in magic files for shaking

- packages/remix-dev/cli/commands.ts
- packages/remix-serve/cli.ts
fixes an issue discovered in discord https://canary.discord.com/channels/770287896669978684/771068344320786452/937765256879554711, and brought to my attention by @BenMcH
this used to work prior to #1328, but now that we log the ip address of the server, it no longer starts due to throwing an error about being offline
> fix: allow remix dev and remix-serve to work offline

- contributors.yml
- docs/tutorials/jokes.md
Fly.io has now a free tier also for hosting databases (3GB). They have written a [blog post about that](https://fly.io/blog/free-postgres/).
I have followed the jokes tutorial yesterday and the volume for the database created automatically was 1GB instead of 10GB I guess before.
They are asking a credit card during the account creation though.
> docs(examples): indicate in jokes tutorial that fly.io has now a free tier for hosting databases

- scripts/deployment-test/fly.mjs
will use fly’s docker setup instead of github’s so we should get some better docker caching
> ci: update fly deployment test to use —-remote-only

- fixtures/gists-app/app/routes/methods.tsx
- fixtures/gists-app/tests/form-test.ts
- packages/remix-react/components.tsx
Fixes #1720.
This wasn't working because the `onClick` handler used to detect the submit button is placed on the `form` element itself. By adding the listener to the entire window and checking the form associated with the button, we can catch any submit button.
> fix: support submit buttons outside of the form

- contributors.yml
- docs/tutorials/jokes.md
Correction of a minor typo in the documentation.
> docs: fix typo in Jokes App tutorial (peak -> peek)

- contributors.yml
- docs/tutorials/jokes.md
Just a grammar nit to change `it's` to the possessive `its`. Thanks for the great tutorial, loving it so far! 😊
> docs: fix typo -- remove erroneous apostrophe

- contributors.yml
- docs/guides/data-loading.md
Hello, just a really small typo fix here (my way to kinda thank you for this exciting project)
> chore(docs): typo in internal link

- contributors.yml
- docs/guides/styling.md
Fix a typo in guides docs [styling.md](https://github.com/remix-run/remix/blob/main/docs/guides/styling.md)
> docs: fix typo in docs/guides/styling.md

- examples/blog-tutorial/app/routes/admin/new.tsx
- examples/client-side-validation/app/root.tsx
- examples/client-side-validation/package-lock.json
- examples/route-modal/app/routes/invoices/$id/edit.tsx
- examples/route-modal/app/routes/invoices/add.tsx
I have found 3 examples in which `<label>` elements were not linked to their fields, and linked them correctly.
I have also removed a `pattern` attribute on an `<input type="number">` as it is not supported on that type (cf. [the MDN documentation](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes/pattern)).
As for the modifications in `examples/client-side-validation/package-lock.json`, it's simply the result of running `npm install` in that example folder.
> docs(examples): link labels with their fields in examples, to enhance accessibility

- contributors.yml
- docs/api/remix.md
Line 58 of the code example uses `useLoaderData()`, but it's not imported at the top of that example.
> [Docs] – Add `useLoaderData` import to "Using Sessions" example

- contributors.yml
- docs/api/remix.md
Just noticed that in this example, `text` is not used in the render.
> Correct code example in Remix Package docs for transition.type

- docs/api/conventions.md
The code is missing `export` and `async` .
> docs: correct `requireUserSession()` in conventions

- contributors.yml
- docs/api/conventions.md
I was reading through the page and saw `invoiceCatch` referenced in the template. I think you meant `caught`.
> docs: fix variable name in CatchBoundary example

- contributors.yml
- docs/tutorials/blog.md
👋 Hi,
I'm new to this library and tried to follow along with the tutorial but results in an error. Then I discovered that we need Node v14 while digging through the issues page (and later in the [Jokes App](https://remix.run/docs/en/v1/tutorials/jokes#prerequisites) page).
I think it would be great to add prerequisites to the page directly or have it on its own page.
Thank you.
> docs(blog): Add prerequisites to Developer Blog page

- contributors.yml
- docs/api/remix.md
Type '"POST"' is not assignable to type 'FormMethod | undefined'.ts(2322)
> docs: fix type error `POST` to `post`

- contributors.yml
- docs/guides/data-loading.md
This PR adds an example of **Prisma Client generated types** when using a **LoaderFunction**. This is similar to other samples found on the example projects and video guides on Remix YouTube channel.
> docs: Adds example of Prisma generated type

- DEVELOPMENT.md
- package.json
- scripts/release.js
- scripts/tsconfig.json
- scripts/utils.js
- scripts/version.js
- yarn.lock
This PR introduces a `release` script to simplify the release process based on our branching strategy. I will need to stress test a few of the processes during the next release process, but I first want to make sure the flow is correct and accounts for the various types of releases we work with.
> chore: Create `release` script

- contributors.yml
- docs/api/remix.md
Copied a piece of docs from the React Router docs, had trouble finding this when I wanted to only show the parent route active when navigating to the parent route and not when a child route is active.
> (fix:docs) Added information about the `end` prop for NavLink

- packages/create-remix/templates/express/server.js
otherwise it's always 1 hour https://canary.discord.com/channels/770287896669978684/777863745321304104/941061633000763444
> fix(create-remix/express): update caching to be dynamic based on path

- contributors.yml
- integration/headers-test.ts
- packages/remix-server-runtime/__tests__/server-test.ts
- packages/remix-server-runtime/headers.ts
- packages/remix-server-runtime/server.ts
This should fixes issue: https://github.com/remix-run/remix/issues/1140
The issue came from `routeLoaderResponses` not taking into account that some parent route might not have loaders hence no response. Because `getDocumentHeaders` matched the response to the `index` position in `routeLoaderResponses`, this could provoke a mismatch.
I replaced `routeLoaderResponses` from an array to a `Record<string, Response>` (matching the route's id instead of the index) which would solve the issue.
I also created a test but I think it might not be in the right place, feel free to move it if needed.
Thanks for your awesome work, I love Remix !
> fix(remix-server-runtime): fix headers function access to loaderHeaders when parent has no loader

- .github/workflows/format.yml
This was causing failures on my fork
https://github.com/MichaelDeBoey/remix/actions/runs/1814598064
> chore: run workflows on main repo only (`dev` branch)

- contributors.yml
- docs/tutorials/blog.md
This PR fixes faulty line numbers for new code lines in one of the code blocks in the blog tutorial
> docs: fix wrong new code line marking in blog tutorial

- docs/tutorials/blog.md
I just realized the blog example was also a tutorial. So this PR is following #1821 to make one of the labels in the tutorial match the code in the examples folder.
> docs(tutorial): link label with its field in blog tutorial, to enhance accessibility

- contributors.yml
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli.ts
Added new flag for remix CLI `--debug`.
This allows CLI commands to be started with Node's debug port open and attach a debugger to the backend process.
This resolves #337
And provides a working solution and resolves #795
example:
```
> remix --debug dev
```
Will print:
```
Debugger listening on ws://127.0.0.1:9229/039d309a...0be9c662c954
...
Watching Remix app in development mode...
💿 Built in 100ms
```
> feat: implement debug flag to attach debugger (#337, #795)

- packages/remix-react/scroll-restoration.tsx
ScrollRestoration is rendering a inlined script that is not being parsed by esbuild to support older browser when possible.
The tsconfig.json generated by the CLI is configured to target ES2019 but that inlined script is using `??` which is a ES2020 feature, this is breaking support for iOS 13 (based on a Discord discussion, see https://discord.com/channels/770287896669978684/771068344320786452/941472115163537499).
The PR changes `??` to `||`, it should work similar, just adding the scenario where the value from localStorage is `""` so it will use `"{}"` which I don't think it's a problem anyway.
> Change ?? to || in ScrollRestoration inlined code

- .github/workflows/test.yml
- contributors.yml
CI will now use the built-in cache strategy from `setup-node` instead of manually setting the cache keys.
See:
https://github.com/actions/setup-node#caching-packages-dependencies
https://github.blog/changelog/2021-07-02-github-actions-setup-node-now-supports-dependency-caching/
Tested with my fork with https://github.com/c43721/remix/pull/1, this performs similar given margin of error while also being a bit more cleaner to read.
This bumps the action `setup-node` to version **2**. This should be a consideration before merging as it could become an issue.
> fix(ci): use built in cache strategy

- packages/remix-react/components.tsx
- packages/remix-react/transition.ts
Fixes https://github.com/remix-run/remix/issues/1148
The error messages shown in the console when `useFetcher().load` or `useFetcher.submit` are called incorrectly wasn't very helpful. This PR throws new error messages explaining what went wrong.
> Update fetcher load/submit error message

- contributors.yml
- docs/tutorials/blog.md
On some operating systems touching a file without having a directory folder will fail. This extra step of explicitly creating the styles directory will ensure that this works for everyone.
> Add missing mkdir step to create the directory

- packages/remix-cloudflare-pages/worker.ts
[`Response.ok` is true only when returning a 2XX status](https://developer.mozilla.org/en-US/docs/Web/API/Response/ok).
[Cloudflare Pages can return a 3XX if the developer creates a `_redirects` file](https://developers.cloudflare.com/pages/platform/redirects) in their `public` folder.
This PR checks that the status code is between 200–399 inclusive and if so, returns that response directly from Pages.
Replaces a dud #1236.
> Add native _redirects support for Cloudflare Pages

- packages/remix-express/server.ts
- packages/remix-vercel/server.ts
cloudflare handles this for us via native use of fetch Response, note there doesn't seem to be a way to send status text in the other adapters.
> fix: add status text to express & vercel packages

- contributors.yml
- docs/tutorials/jokes.md
`replaceAll` is not supported in  node **v14.***, see https://github.com/nodejs/node/blob/master/doc/changelogs/CHANGELOG_V15.md#v8-86---35415
should fix https://github.com/remix-run/remix/issues/1156
> Use replace instead of replaceAll in jokes tutorial

- packages/create-remix/cli.ts
NPM can work off a local cached version so it'd be good to surface the version number in the welcome text like:
```
R E M I X - v1.1.1
💿 Welcome to Remix! Let's get you set up with a new project.
```
Closes https://github.com/remix-run/remix/issues/310
> feat(#310): display version number in create-remix cli

- packages/remix-react/links.ts
It appears as though #1096 was a bridge too far with its optional object key. What about this?
> refactor: getStylesheetPrefetchLinks (one more time)

- docs/api/remix.md
I'm on `v1.1.3` and it's still `unstable_parseMultipartFormData` and not (yet) `parseMultipartFormData`
unless I'm missing something?
> docs: fix typo in /api/remix

- contributors.yml
- packages/remix-react/components.tsx
Memoize the matches returned by `useMatches()` in order to not have a new reference of the array (and of all its items) at every re-rendering. As these matches are made to be looped over, I think it's more performant to memoize them.
> chore(useMatches): memoize matches

- contributors.yml
- docs/tutorials/jokes.md
- examples/jokes/app/routes/jokes.tsx
- examples/jokes/app/utils/session.server.ts
resolves: #673
Jokes example returns `passwordHash` in body. 
this happens because the whole user data was returned in the loader function.
> docs(jokes): fix passwordHash included in body on /jokes/* response in

- contributors.yml
- packages/create-remix/templates/cloudflare-pages/public/_headers
this PR adds the _header file described here:
https://developers.cloudflare.com/pages/platform/headers
and sets the same Cache-Control value as the netlify template:
https://github.com/remix-run/remix/blob/712ca2b5b08eb3200b5cb1bbf29e8faa77f556d1/packages/create-remix/templates/netlify/netlify.toml#L18
Todo
> Add cache-control header to cloudflare pages template

- contributors.yml
- packages/remix-react/__tests__/components-test.tsx
- packages/remix-react/components.tsx
- packages/remix-react/scroll-restoration.tsx
For inline scripts, instead of directly injecting JavaScript using a template literal:
- Write a function with the desired code, using params for external values
- Convert this function to a string using [`Function.prototype.toString()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString)
- Inject the resulting string, and call the function with the required values
This provides the following benefits for inline scripts:
- Problem checking with ESLint
- Type checking with TypeScript
- Consistent formatting with Prettier
- Consistent baseline indentation
I haven't added or changed any tests since this isn't strictly a bug fix or new feature.
> chore(remix-react): make inline scripts more robust

- contributors.yml
- docs/pages/philosophy.md
It appears the server-filtered gist example omits the `description` field from the response payload, but the field is still referenced client-side in the `Gists` function/component. This proposed change is meant to render the gist description rather than referencing an undefined property, but I'm unsure if this will result in inaccurate statistics pertaining to response payload size in the following paragraph. Should the response payload be re-evaluated with the `description` property serialized?
> docs: fix missing property serialization

- contributors.yml
- packages/remix-react/scroll-restoration.tsx
There's currently a bug on scroll restoration when the route has a hash and user scrolls to very top of the page. Instead of the scroll be restored from there, it was restoring the scroll to the hash element when navigating back.
> fix: restore scroll position for hashed routes

- contributors.yml
- docs/tutorials/blog.md
Earlier the `Link` was added to `app/root.tsx`.It changed in https://github.com/remix-run/remix/commit/d1e2c34441b31cd09b11a98d63d77dd8f601a916.
The `app/routes/index.tsx` file doesn't have any `<Outlet />` or `<Scripts/>`.
> [Doc][Tutorial][Developer Blog] Delete obsolete line

- contributors.yml
- packages/create-remix/templates/cloudflare-pages/gitignore
Make /functions/[[path]].js ignored by git in cloudflare-pages template project.
> fix(create-remix): escape [ and ] in .gitignore

- contributors.yml
- docs/tutorials/jokes.md
- examples/jokes/app/routes/jokes/$jokeId.tsx
- examples/jokes/app/routes/jokes/new.tsx
- examples/jokes/app/routes/login.tsx
Hello Remix-Team 💿 👋 
While going through the jokes-tutorial I noticed some minor errors and changes for tiny improvements, which I bundled up into this PR. I split up the changes into multiple commits, each doing one and only one thing. I tried to be descriptive in the commit messages, and again it's all about minor details. Just leave a comment if some changes or intentions behind them are not clear. 😊
> docs(jokes): minor fixes and improvements

- contributors.yml
- docs/tutorials/blog.md
Replaced the short-form "cause" with because.
> docs: fix typo in tutorials/blog

- packages/create-remix/templates/express/server.js
Use multiple `app.use` calls instead of trying to combine into one and doing manual path manipulation.
Supersedes #1861
Also related to #977
> Simpler asset caching strategy in Express template

- packages/remix-dev/config.ts
> fix(remix-dev): update `serverModuleFormat` deprecation notice

- integration/compiler-test.ts
- packages/remix-dev/compiler.ts
The regex is wrong? Not sure how this got changed or stopped working between release 🤷‍♀️
Closes: #
> fix: strip ".client" files from server bundle

- docs/pages/gotchas.md
- examples/pm-app/app/utils/index.ts
- packages/remix-react/components.tsx
`typeof window` isn't a good way to determine whether you're running on the server thanks to Deno supporting a global `window`. So this updates all our code/examples to use `typeof document` instead. This PR also adds a note about this in the gotchas page.
I've added support for "good" in our code blocks on the website repo as well so you can now have "bad" and "good" code blocks :)
> fix(components): use typeof document

- packages/remix-dev/compiler.ts
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Esbuild can't hoist `require("xyz")` calls to `import "xyz"`, this leads to an issue every time you try to re-map a require'd version in external code to a URL.
Closes: #1993
> fix: use browser polyfills for deno node builtins

- contributors.yml
- packages/remix-dev/cli/commands.ts
Related to #1710 and #194 which are fixed in `remix serve` but this also removes the header from `remix dev`
> fix(remix-dev): Remove x-powered-by header from Express dev server

- packages/remix-dev/build.ts
We set `process.env.NODE_ENV` to `"test"` when running our test suite, but `yarn build` overrides anything other that `"development"` or `"production"` which makes env-based mocking more difficult. This PR allows `"test"` as a valid `NODE_ENV` value.
> fix: Allow `process.env.NODE_ENV === "test"` in build

- .github/workflows/deployment-test.yml
- scripts/deployment-test/_shared.mjs
- scripts/deployment-test/arc.mjs
- scripts/deployment-test/cf-pages.mjs
- scripts/deployment-test/cf-workers.mjs
- scripts/deployment-test/fly.mjs
- scripts/deployment-test/netlify.mjs
- scripts/deployment-test/vercel.mjs
This PR improves the reliability of our deployment tests for CF Pages and Fly by running a check to make sure the DNS resolves as well as returns a 200 status code before attempting to run cypress, it will run each check every 10 seconds, with a max of 10 times before giving up and failing
It also adds a new GitHub Action workflow to allow manually running the deployment tests
and finally this PR also adds some `npm publish` verification to make sure packages are published and readily available to be installed by `npm`
> ci: add retry logic to fly and cf pages deployments

- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
https://nodejs.org/api/esm.html#node-imports
closes #1229
> fix(dev/compiler): mark imports using node protocol as external

- contributors.yml
- docs/guides/data-loading.md
Minor typo: `Primsa` => `Prisma`
> docs: fix typo

- packages/remix-architect/package.json
@architect/architect v10 came out on Monday and requires @architect/functions v5
we could also update docs to say to use arc 9, but that seems less than ideal
Closes: #
> chore(remix-architect): bump @architect/functions to v5

- integration/prefetch-test.ts
- packages/remix-react/links.ts
This PR fixes a bug where asset chunks were not prefetched unless the destination route contained a loader
Closes: #1091
> fix: prefetch asset chunks for routes without loaders

- .github/workflows/test.yml
Avoid duplicate runs of the `test` workflow on PRs by limiting the `push` trigger to only run for `dev`/`main`/`release/*` branches.  Pushes to open PR branches will be run via the `pull_request` trigger
> ci: only run test workflow on main/dev/release branches

- docs/tutorials/jokes.md
The log should only have 'id' and 'username' according to the code in session.server.ts
Updating the log to match the real result
> update to actual console log

- scripts/deployment-test/_shared.mjs
- scripts/deployment-test/cf-pages.mjs
This PR changes how we wait for deployments for Cloudflare Pages but pinging the api instead of a setTimeout, it also adds support for "fast builds" once they enable it to be configured via the API - if they don't, it'll be enabled by default on April 1st.
Closes: #
> ci: use cloudflare api to determine if deployment is done

- contributors.yml
- examples/jokes/README.md
This is a docs improvement in the example jokes app.
Without these additional instructions trying to use the app results in errors:
```
PrismaClientKnownRequestError: 
Invalid `prisma.joke.count()` invocation:
The table `main.Joke` does not exist in the current database.
at Object.request (/workspaces/remix/examples/jokes/node_modules/@prisma/client/runtime/index.js:39809:15)
at PrismaClient._request (/workspaces/remix/examples/jokes/node_modules/@prisma/client/runtime/index.js:40637:18)
at loader5 (/workspaces/remix/examples/jokes/build/route:/workspaces/remix/examples/jokes/app/routes/jokes/index.tsx:12:17)
at Object.callRouteLoader (/workspaces/remix/examples/jokes/node_modules/@remix-run/server-runtime/data.js:73:14)
at handleDataRequest …
```
> docs(examples): add instructions for prisma migration to the example 'jokes' app README

- examples/blog-tutorial/app/routes/index.tsx
Currently this link is targetting `http://localhost:3000/reactrouter.com/docs`.
> docs(examples): fix broken link in blog app

- examples/redis-upstash-session/app/sessions.server.ts
The previous implementation didn't really added correctly the EXPIRATION_DURATION_IN_SECONDS
> docs(examples): Fix expire bug in redis-upstash-session example

- contributors.yml
- packages/create-remix/templates/express/package.json
The Express template has an issue that takes a lot longer time than necessary to restart the server, whenever the code is updated. Restarting is triggered so many times after I **updated a single file**: 
```
[nodemon] restarting due to changes...
[nodemon] starting `node ./build/index.js`
💿 File changed: server.js
💿 Rebuilding...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to changes...
[nodemon] restarting due to …
```
> fix(create-remix:express): Fix nodemon unnecessarily watches public/build

- rollup.config.js
This PR adds magicExports for any "server" adapter that uses the "getServerConfig" function to generate it's rollup build config
(cherry picked from commit 187970c94130645fd551e6fb1c05a713a5d43e78)
> fix: include createArcTableSessionStorage in remix exports

- packages/remix/index.ts
This shows one way to fairly straightforwardly fix this issue with pnpm https://github.com/remix-run/remix/issues/2031
Closes: #2031
> fix(remix): export a type so that remix/index.d.ts is not empty

- packages/create-remix/templates/express/README.md
- packages/create-remix/templates/express/package.json
The `start:dev` script no longer exists in the express template
the `npm-run-all` dependency is only required for the `dev` script so can safely be made into a devDependency.
> fix(create-remix): express template docs and move npm-run-all to devDependencies

- docs/tutorials/jokes.md
- examples/bullmq-task-queue/package-lock.json
- examples/bullmq-task-queue/package.json
- examples/file-and-cloudinary-upload/package-lock.json
- examples/file-and-cloudinary-upload/package.json
- examples/form-to-notion-db/README.md
- examples/form-to-notion-db/package-lock.json
- examples/form-to-notion-db/package.json
- examples/ioredis/package-lock.json
- examples/ioredis/package.json
- examples/redis-upstash-session/package-lock.json
- examples/redis-upstash-session/package.json
- examples/remix-auth-auth0/package-lock.json
- examples/remix-auth-auth0/package.json
- examples/remix-auth-supabase/package-lock.json
- examples/remix-auth-supabase/package.json
- examples/sanity/app/entry.server.jsx
- examples/sanity/package.json
- examples/sanity/yarn.lock
- packages/create-remix/templates/fly-stack/package.json
As a follow-up of @brophdawg11's #2063
> chore: remove `dotenv` references

- contributors.yml
- docs/tutorials/jokes.md
This fixes a minor issue in the Jokes tutorial. In the [error boundaries section](https://remix.run/docs/en/v1/tutorials/jokes#unexpected-errors), it says:
> Ok great, with those in place, let's check what happens when there's an error. Go ahead and just add this to the default component, loader, or action of each of the routes. Here's what I get:
This indicates there should be some code sample for the user to add to the code. However, none is provided.
This PR simply adds some.
See also: https://github.com/remix-run/remix/pull/530#issuecomment-976873148
> docs(jokes): add example code to test error boundaries

- docs/api/conventions.md
- examples/gdpr-cookie-consent/remix.config.js
- examples/graphql-api/remix.config.js
- examples/jokes/remix.config.js
- examples/remix-auth-supabase-github/remix.config.js
- examples/stitches/remix.config.js
- fixtures/gists-app/remix.config.js
As suggested by @kentcdodds in https://github.com/remix-run/remix/pull/2158#discussion_r818948749
> docs(examples): remove `devServerPort` from `remix.config.js`

- packages/create-remix/templates/arc-stack/remix.config.js
- packages/create-remix/templates/arc/remix.config.js
- packages/create-remix/templates/cloudflare-pages/remix.config.js
- packages/create-remix/templates/cloudflare-workers/remix.config.js
- packages/create-remix/templates/deno/remix.config.js
- packages/create-remix/templates/express/remix.config.js
- packages/create-remix/templates/fly-stack/remix.config.js
- packages/create-remix/templates/fly/remix.config.js
- packages/create-remix/templates/netlify/remix.config.js
- packages/create-remix/templates/remix/remix.config.js
- packages/create-remix/templates/vercel/remix.config.js
As suggested by @kentcdodds in https://github.com/remix-run/remix/pull/2158#discussion_r818948749
> docs(create-remix): remove `devServerPort` from `remix.config.js` in templates

- DEVELOPMENT.md
- babel.config.js
- package.json
- packages/remix-react/transition.ts
- yarn.lock
This adds a bunch of helpful `console.debug` statements to the transition manager to help debug the heavily async nature of it.  To avoid cluttering the console in normal application usage, I added https://babeljs.io/docs/en/babel-plugin-transform-remove-console/ to strip all `console.debug` statements during the build.  For local development, setting `REMIX_DEBUG=true` will leave them in for debugging.
> chore: add local debugging logs for transition manager

- contributors.yml
- docs/tutorials/jokes.md
- examples/jokes/app/routes/jokes/new.tsx
The message that appears when there's an formError is missing, so I added it.
I referred to this [login.tsx](https://github.com/remix-run/remix/blob/main/examples/jokes/app/routes/login.tsx#L183).
> docs(jokes): add missing form error message

- DEVELOPMENT.md
- docs/api/remix.md
- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/transition.ts
> fix: keep fetcher in loading state during action submission redirect

- docs/api/conventions.md
- docs/api/remix.md
- docs/guides/api-routes.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/guides/envvars.md
- docs/guides/mdx.md
- docs/guides/not-found.md
- docs/guides/optimistic-ui.md
- docs/guides/resource-routes.md
- docs/guides/styling.md
- docs/pages/faq.md
- docs/pages/gotchas.md
- docs/pages/philosophy.md
- docs/pages/technical-explanation.md
- docs/tutorials/blog.md
- docs/tutorials/jokes.md
- examples/jokes/app/routes/jokes.tsx
- examples/jokes/app/routes/jokes/$jokeId.tsx
- examples/jokes/app/routes/jokes/index.tsx
- examples/jokes/app/routes/jokes/new.tsx
This PR updates our docs and some examples to explicitly return a response for all loaders/actions. (internal team: see REM-779 in Linear for context)
> chore(docs): Explicitly return `Response` in loader/action examples

- packages/create-remix/templates/netlify/gitignore
- packages/create-remix/templates/netlify/netlify.toml
- packages/create-remix/templates/netlify/remix.config.js
- packages/remix-dev/config.ts
This PR changes the Netlify template, and the default `serverBuildPath` to use the internal functions directory. This is preferred for frameworks because it is in a directory that is already gitignored, and does not interfere with the user's own functions. The redirects do not need changing, because the URL is unchanged.
> fix(netlify): use Netlify internal functions dir

- packages/remix-dev/cli/commands.ts
- packages/remix-serve/cli.ts
there are pretty major differences in how `localhost:3000` and ip addresses work (besides 127.0.0.1) in browsers as localhost is deemed a ["secure" context](https://developer.mozilla.org/en-US/docs/Web/Security/Secure_Contexts#:~:text=Locally%2Ddelivered%20resources%20such%20as%20those%20with%20http%3A//127.0.0.1%20URLs%2C%20http%3A//localhost%20and%20http%3A//*.localhost%20URLs%20(e.g.%20http%3A//dev.whatever.localhost/)%2C%20and%20file%3A//%20URLs%20are%20also%20considered%20to%20have%20been%20delivered%20securely.), so [Client Hint](https://developer.mozilla.org/en-US/docs/Web/HTTP/Client_hints) HTTP headers aren't sent and secure cookies don't work 
Closes: #
> chore: update remix-dev and remix-serve start message

- packages/remix-react/components.tsx
- templates/arc-ts/app/root.tsx
- templates/arc/app/root.jsx
- templates/cloudflare-pages-ts/app/root.tsx
- templates/cloudflare-pages/app/root.jsx
- templates/cloudflare-workers-ts/app/root.tsx
- templates/cloudflare-workers/app/root.jsx
- templates/deno-ts/app/root.tsx
- templates/express-ts/app/root.tsx
- templates/express/app/root.jsx
- templates/fly-ts/app/root.tsx
- templates/fly/app/root.jsx
- templates/netlify-ts/app/root.tsx
- templates/netlify/app/root.jsx
- templates/remix-ts/app/root.tsx
- templates/remix/app/root.jsx
- templates/vercel-ts/app/root.tsx
- templates/vercel/app/root.jsx
@kentcdodds mentioned this a couple of times in his streams that he wanted to have this, so all `meta` tags are arranged by the `<Meta />` component
> feat(remix-react): add support for `charset` in `meta` function

- packages/remix-dev/create.ts
broke it here https://github.com/remix-run/remix/commit/d7e2d535ff71cfd5fbbe1705924a4ed3b16374ea 🤦‍♂️
the other option would be to change the template name
Closes: #
> fix(remix-dev/create): move getRepoInfo check after example/template check

- templates/arc-ts/package.json
- templates/arc/package.json
- templates/cloudflare-pages-ts/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers-ts/package.json
- templates/cloudflare-workers/package.json
- templates/deno-ts/package.json
- templates/express-ts/package.json
- templates/express/package.json
- templates/fly-ts/package.json
- templates/fly/package.json
- templates/remix-ts/package.json
- templates/remix/package.json
- templates/vercel-ts/package.json
- templates/vercel/package.json
As discussed with @chaance, all `cross-env` references should be removed when calling Remix scripts
---
Follow-up of 9e3f164e
> fix(templates): remove `cross-env` references

- docs/guides/styling.md
- examples/tailwindcss/package.json
> The following 2 commands are the same.
> The `run-s` command is shorter.
> 
> ```
> $ run-s clean lint build
> $ npm run clean && npm run lint && npm run build
> ```
https://github.com/mysticatea/npm-run-all/blob/master/docs/run-s.md
> docs(examples): fix `build` script of Tailwind example

- packages/create-remix/README.md
- packages/remix-architect/README.md
- packages/remix-cloudflare-pages/README.md
- packages/remix-cloudflare-workers/README.md
- packages/remix-dev/README.md
- packages/remix-express/README.md
- packages/remix-netlify/README.md
- packages/remix-node/README.md
- packages/remix-react/README.md
- packages/remix-serve/README.md
- packages/remix-server-runtime/README.md
- packages/remix-vercel/README.md
- packages/remix/README.md
Just like in #2204, this makes the commands easier to copy/paste in your own terminal
If wanted, I can also remove them from CLI helper texts
https://github.com/remix-run/remix/blob/0c8318a3fb00991a5dfde62514d9e1ffb0ee03f2/packages/remix-dev/cli.ts#L8-L11
https://github.com/remix-run/remix/blob/0c8318a3fb00991a5dfde62514d9e1ffb0ee03f2/packages/remix-dev/cli.ts#L24-L33
> chore: remove `$` from command lines

- docs/other-api/dev.md
- examples/bullmq-task-queue/README.md
- examples/graphql-api/README.md
- examples/ioredis/README.md
- examples/redis-upstash-session/README.md
- templates/arc-ts/README.md
- templates/arc/README.md
- templates/cloudflare-pages-ts/README.md
- templates/cloudflare-pages/README.md
- templates/cloudflare-workers-ts/README.md
- templates/cloudflare-workers/README.md
- templates/netlify-ts/README.md
- templates/netlify/README.md
This makes the commands easier to copy/paste in your own terminal
> docs(examples/templates): remove `$` from command lines

- contributors.yml
- packages/remix-eslint-config/package.json
Right now `jest-testing-library.js` isn't included when publishing to NPM while this should be the case.
This PR fixes it by adding it to the `files` array in `package.json`
> [@remix-run/remix-eslint-config] Include jest-testing-library.js

- packages/remix-dev/create.ts
This PR adds a check for the old private registry config. If it's still configured, it causes errors such as those reported in #2202 and #2215 and others I've seen in Discord.
I can't find any docs on migrating from the private beta, but there could be a link to these if they exist.
> fix: check for private registry config

- contributors.yml
- docs/guides/performance.md
Fixes small typo where "it's" (contraction of it is) is used instead of the grammatically correct "its" (possessive)
> Fix typo in performance guide docs (it's -> its)

- examples/blog-tutorial/app/routes/demos/actions.tsx
This `<div>` is not allowed as child of `<label>` (cf. [div spec](https://html.spec.whatwg.org/multipage/grouping-content.html#the-div-element)).
And it's not needed here even for visual purposes because the `<input>` below is already set to `display: block; width: 100%;` [in the CSS](https://github.com/remix-run/remix/blob/9ea7d4ae37c59082cff9d8011f609268b42e15dd/examples/blog-tutorial/app/styles/global.css#L66).
> docs(examples): remove not allowed and unneeded div in blog example

- contributors.yml
- docs/tutorials/jokes.md
The jokes tutorial instructed to delete `app/styles`, which did not exist at this point.
> docs(tutorials/jokes) - Fix delete files instructions 

- contributors.yml
- docs/tutorials/blog.md
- docs/tutorials/jokes.md
When going through the tutorials I was thrown off by the introduction of stacks - being asked to choose which type of app I want. This guides the user to select "Just the basics" so they can continue with the tutorials as they work now.
> docs(tutorials): mention stacks to avoid confusing new comers

- docs/guides/styling.md
> docs(styling): remove `cross-env` references from Tailwind example

- docs/guides/envvars.md
The default mode used by remix build seems to be "production":
https://github.com/remix-run/remix/blob/c736dcb414eb5bc5282e5e889a0f169c1e2e835b/packages/remix-dev/cli/commands.ts#L47
> docs: Clarify default mode used by remix build

- fixtures/gists-app/package.json
- fixtures/gists-app/server.js
Got irritated with the server crashing with `yarn dev` when I have another app running on port `3000`, so this should fix it.
Unfortunately top-level `await` isn't supported in esbuild with our target, and we're building our server in the gists app. That's a task for another day.
> chore: use get-port in gists app

- contributors.yml
- docs/tutorials/blog.md
Fixed blog tutorial highlighting, in the docs, by changing the highlighted lines from `13-28` -> `13-29`.
> Fixed Blog Tutorial Highlight

- contributors.yml
- examples/framer-motion/README.md
The link now is pointing to the basic example, with this change it will open the 'framer-motion' example.
_(This is a docs change)_
> docs(examples/framer-motion): Fix wrong codesandbox link on README.md

- contributors.yml
- docs/guides/styling.md
> docs(styling): fix broken link in CSS preprocessor section

- integration/set-cookie-revalidation-test.ts
- packages/remix-react/routes.tsx
- packages/remix-react/transition.ts
- packages/remix-server-runtime/server.ts
Consider this use case:
- Root loader reads the cookie to flash messages in one location
- User signs up, but need to verify their email address before they can create new projects
- User is logged in, and visits /projects/new but have not yet verified their email
- The projects/new loader redirects them to /account and sets a cookie with a flash message why they were redirected `session.flash("You need to add an email address and verify it")
- The root loader will not get called and therefore no flash message happens because Remix's optimizations didn't call the root loader.
Today we revalidate for three reasons:
- After an action (POST/PUT/PATCH/DELETE) because loaders usually read from the database and this will capture it
- If the url search params change because any loader can use …
> feat: revalidate on redirect if cookies were set

- .github/ISSUE_TEMPLATE/bug_report.yml
- fixtures/gists-app/app/routes/meta.tsx
- fixtures/gists-app/tests/meta-test.ts
- packages/remix-react/components.tsx
- packages/remix-react/routeModules.ts
- packages/remix-server-runtime/routeModules.ts
Currently, if a meta key is `null` or `undefined`, we will render an empty tag. Our types also don't support an empty meta key, which is a bit annoying if you're working with optional data.
```js
export function meta({ data }) {
return {
title: data.title, // always there, cool
description: data.description // optional, don't bother with a tag but please don't yell at me!
};
}
```
> fix: Keep empty meta from rendering a tag

- fixtures/gists-app/server.js
- integration/errory-boundary-test.ts
Adds a few tests that ensure our internal `ErrorBoundary` is always rendered if no boundary exists in the route tree. Resolves REM-632.
> chore(tests): Assert that apps without an ErrorBoundary renders internal boundary

- docs/api/conventions.md
- docs/api/remix.md
- integration/meta-test.ts
- packages/remix-react/components.tsx
- packages/remix-react/routeModules.ts
- packages/remix-server-runtime/routeModules.ts
Took inspiration of the OG tags: if people want to use the `http-equiv` tag, they'll have to do
```ts
export const meta: MetaFunction = () => ({
'http-equiv:refresh': '3;url=https://www.mozilla.org',
});
```
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#attr-http-equiv
@kentcdodds Not sure how this would best fit in the docs, so I'll leave that up to you if you don't mind.
---
Closes #941
> feat(remix-react): add support for `http-equiv` in `meta` function

- templates/cloudflare-pages-ts/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers-ts/package.json
- templates/cloudflare-workers/package.json
cloudflare-workers and cloudflare-pages are no longer separate setup targets.
I believe we can merge directly into `main` since these are template changes that we should have shipped last week.
> chore: Use `remix setup cloudflare` for CF templates

- contributors.yml
- docs/tutorials/jokes.md
- examples/jokes/app/routes/login.tsx
Re-opening https://github.com/remix-run/remix/pull/2473 (as I think I messed up the rebase)
This change validates the URL based on /jokes, /, and https://remix.run to prevent the open redirect vulnerability that exists in the jokes tutorial.
https://cheatsheetseries.owasp.org/cheatsheets/Unvalidated_Redirects_and_Forwards_Cheat_Sheet.html
> docs(examples/jokes): add validation to prevent open redirect on login

- integration/catch-boundary-data-test.ts
- integration/catch-boundary-test.ts
- integration/error-boundary-test.ts
- integration/headers-test.ts
- integration/loader-test.ts
- integration/prefetch-test.ts
- integration/rendering-test.ts
- integration/set-cookie-revalidation-test.ts
- integration/splat-routes-test.ts
- integration/transition-test.ts
As @chaance suggested in https://github.com/remix-run/remix/pull/2451#discussion_r832642948, this will better represent a real app in our tests.
> test(integration): represent real app in `app/root.jsx`

- contributors.yml
- docs/tutorials/jokes.md
In the User Registration section of the Jokes tutorial, there are incorrect lines of code highlighted in `routes/login.tsx`
https://remix.run/docs/en/v1/tutorials/jokes#user-registration
> fix(docs/tutorials): fix highlighted code lines in Jokes tutorial

- templates/deno-ts/README.md
- templates/deno-ts/remix-deno/crypto.ts
- templates/deno-ts/remix-deno/implementations.ts
- templates/deno-ts/remix-deno/index.ts
- templates/deno-ts/remix-deno/server.ts
- templates/deno-ts/remix-deno/sessions/fileStorage.ts
- templates/deno-ts/server.ts
Removes the unneeded `installGlobals` call from the deno template.
> fix: deno template adjustments

- contributors.yml
- docs/tutorials/blog.md
> fix(docs/tutorials): fix typo in blog tutorial

- contributors.yml
- packages/remix-dev/cli/create.ts
I noticed there was an issue when @kentcdodds switched to indie stack templates here: https://github.com/remix-run/remix/commit/28ef6426861e6f6b670b6bd654272726b3c5c936
so I investigated the issue and created a simple fix to avoid setting header values when nothing should be set.
> fix(remix-dev): avoid setting blank Authorization header in `isRemixTemplate` functions

- contributors.yml
- packages/remix-server-runtime/__tests__/sessions-test.ts
- packages/remix-server-runtime/sessions/cookieStorage.ts
Closes: N/A
Session storage inside a cookie is great for smaller things and
normally "just works". For newer developers (and older forgetful ones
like myself), the storage limit can be a source of errors that is
easily missed.
This makes the commit action for cookie session storage throw an
error describing the problem if data is attempted to be persisted that
will exceed the browser max of 4096 bytes.
> feat(remix-server-runtime): throw error when cookie limit is reached

- packages/create-remix/cli.ts
Per @mcansh's comment in #2500, this PR simply changes the error handling behavior of the CLI to prevent spitting out the full stack trace on errors. We should be handling those errors internally unless the `--debug` flag is provided.
I'd like to hold on #2500 until we have an opportunity to make the tests more robust, but this is a simple change we can easily merge before the next release.
> fix(cli): stop CLI from logging full stack trace on known errors

- packages/remix-react/components.tsx
Follow-up of #2331.
This implementation is created with thinking that `flatMap` is the same as `flat().map()`, but instead it's `map().flat()`
> The `flatMap()` method returns a new array formed by applying a given callback function to each element of the array, and then flattening the result by one level. It is identical to a [`map()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map) followed by a [`flat()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flat) of depth 1, but slightly more efficient than calling those two methods separately.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/flatMap
Since we have our `if`-statements in the callback, this doesn't really …
> fix(remix-react): use `.flat().map()` instead of `flatMap` in `Meta` component

- examples/blog-tutorial/sandbox.config.json
It was deleted on accident in #2502
> chore(examples): add `sandbox.config.json` again to `blog` example

- packages/create-remix/cli.ts
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/create.ts
- packages/remix-dev/cli/run.ts
- packages/remix-dev/package.json
Instead of fetching early to detect template types in the CLI, we can simplify the code and speed up the setup process with a few heuristics:
1. Check if the user passed a local file. If they hand us an explicit file URL, we'll validate it first. Otherwise we just ping the filesystem to see if the string references a filepath and, if not, move on.
2. If the provided template contains no slashes, spaces, or special chars, we assume it is one of our templates and attempt to fetch it.
3. If the template is a GitHub URL or shorthand :org/:repo, we fetch the repo.
4. Any other URLs are assumed to be direct tarball URLs, so we try to fetch them.
Worth noting that there are probably more opportunities to improve error handling. We'll want to iterate here.
> fix(remix-dev/cli): Remove excess fetching and improve error handling

- docs/api/conventions.md
Updated the documentation to remove bare objects returning from the loader.
> docs(loader): remove section about returning plain objects

- templates/express/.gitignore
- templates/express/package.json
- templates/express/remix.config.js
- templates/express/server.js
If Remix bundles your server entry point:
- you get to use server.ts
- you get to share bundled deps between your server and app folder code
- have to use virtual module id to get the server build
- have to use a process manager, like nodemon or pm2 in dev
- have to reconnect to your database each time you change a file in dev
If your server.js is separate:
- you get to avoid side effects because server.js only runs once (e.g. pass db connections through using getLoadContext)
- have to require('./build') to get the server build
- changes surface to the browser quicker
Closes: #
> chore: use external server for express template

- packages/remix-cloudflare-pages/package.json
- packages/remix-cloudflare-pages/tsconfig.json
- packages/remix-cloudflare-workers/package.json
- packages/remix-cloudflare-workers/tsconfig.json
- packages/remix-cloudflare/package.json
- packages/remix-cloudflare/tsconfig.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers/package.json
- yarn.lock
Follow up for #645 
I made a mistake and deleted the fork repository and now I cannot push any commit to the original PR. So I open a new one here:
> Cloudflare released an [update](https://github.com/cloudflare/workers-types/releases/tag/v3.0.0) for `@cloudflare/workers-types` last month. It is now automatically generated from the source as announced [here](https://blog.cloudflare.com/automatically-generated-types/) and this ensures typing to be always up-to-dated with the latest runtime.
>
> However, the current CF adapter has a peerDependency of v2 only. It would be nice if we could add support of v3 as well.
This will also makes experimenting with new ESM worker easier (as all new types are only defined on v3) before official support is ready. 
>
> Thanks for all the great work!
- …
> feat(cloudflare+cloudflare-pages+cloudflare-workers+templates): add support for `@cloudflare/workers-types` v3

- packages/remix-react/components.tsx
Prior to this change, if `config.devServerPort` was changed either manually or automatically (something already running on 8002), the port inlined to LiveReload was 8002 anyways. I went through some testing locally in `node_modules` and this was the solution. with our current testing infrastructure, I wasn't sure where to write a test for this, so if anyone has an idea, please let me know :)
Closes: #
> fix(remix-react): make `LiveReload` work for ports other than 8002

- packages/remix-architect/server.ts
> fix(remix-architect): set request URL scheme to `http` when running arc sandbox

- examples/turborepo-vercel/apps/remix-app/package.json
Seems like this was missed in #2585 🙈
> docs(examples): run `replace-remix-imports` migration on `turborepo-vercel` example

- docs/api/conventions.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/guides/disabling-javascript.md
- docs/guides/mdx.md
- docs/guides/not-found.md
- docs/guides/optimistic-ui.md
- docs/guides/resource-routes.md
- docs/guides/styling.md
- docs/other-api/dev.md
- docs/other-api/serve.md
- docs/pages/faq.md
- docs/pages/gotchas.md
- docs/pages/philosophy.md
- docs/tutorials/blog.md
- docs/tutorials/jokes.md
Mostly syntactic/mechanical changes taking into account changes to the highlighted lines in codeblocks.
Semantic/prose changes within:
- `other-api/dev.md`
- `api/conventions.md`
- `api/remix.md` (TODO)
> Docs: replace `remix` imports

- docs/tutorials/blog.md
Docs were updated in #2627, so this shouldn't be a problem anymore.
This reverts commit 25049aeb29fa9f577065e47ac2caefbb4b427af7.
> Revert "docs: note about remix setup"

- templates/vercel/package.json
`@vercel/node` is in `@remix-run/vercel`'s `peerDependencies`
https://github.com/remix-run/remix/blob/22a618f93556d7cf57f3630273d8ae6c689656fc/packages/remix-vercel/package.json#L17-L19
> fix(templates/vercel): fix dependencies

- docs/guides/routing.md
I think this was missed in #2627
> docs: run `replace-remix-imports` migration

- packages/remix-cloudflare-pages/index.ts
- packages/remix-cloudflare-pages/package.json
- packages/remix-cloudflare-pages/worker.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/map-normalized-imports/package-exports.ts
Seems like this was forgotten in #2359, so wanted to make `remix-cloudflare-pages` consistent with all other adapter packages.
> feat(remix-cloudflare-pages): add `GetLoadContextFunction` & `RequestHandler` types + remove `@remix-run/server-runtime` dependency

- examples/pm-app/typings/remix.d.ts
These are incorrect with latest specific packages + are already in the remix codebase
> chore(examples): remove `remix` types from `pm-app` example

- docs/api/conventions.md
- docs/api/remix.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/guides/mdx.md
- docs/guides/optimistic-ui.md
- docs/guides/resource-routes.md
- docs/guides/styling.md
- docs/other-api/node.md
- docs/other-api/serve.md
- docs/pages/faq.md
- docs/pages/gotchas.md
- docs/pages/philosophy.md
Also, switch from `@remix-run/node` to `@remix-run/{runtime}` in API, Guides  and general pages to be server-runtime-agnostic.
> docs(api/remix): replace `remix` imports

- packages/remix-eslint-config/rules/typescript.js
Adds the typescript [consistent-type-imports](https://github.com/typescript-eslint/typescript-eslint/blob/main/packages/eslint-plugin/docs/rules/consistent-type-imports.md) rule to the eslint config to enforce consistent separation of `import type` and `import`.
> chore: add @typescript-eslint/consistent-type-imports rule

- packages/remix-react/components.tsx
Without this you get an error in the console indicating `port` is `undefined`.
> fix(remix-react): pass `port` to inline script of `LiveReload`

- packages/remix-dev/__tests__/fixtures/stack/app/entry.client.tsx
- packages/remix-dev/__tests__/fixtures/stack/app/entry.server.tsx
- packages/remix-dev/__tests__/fixtures/stack/app/root.tsx
- packages/remix-dev/__tests__/fixtures/stack/package.json
Seems like this one was missed in #2655
> chore(remix-dev/tests): run `replace-remix-imports` migration over stack fixture

- integration/compiler-test.ts
- packages/remix-dev/compiler/dependencies.ts
- packages/remix-dev/config.ts
feat: surface error message if remix.config fails to load
Closes: #
> fix(remix-dev/compiler): make `getDependenciesToBundle` more resilient to misconfigured `packages.json`s

- packages/remix-server-runtime/responses.ts
1. Remove type of `any`.
2. Avoid duplicate assignment.
> refactor(remix-server-runtime): simplify `responseInit` assign in `json` helper

- packages/remix-server-runtime/routes.ts
why? self documenting (i.e. `route` vs `manifest[key]`)
also, the old code used `key` in one loop and `id` in another. very confusing
> refactor(remix-server-runtime): use `Object.entries` instead of `Object.keys` in `createRoutes`

- contributors.yml
- packages/remix-dev/cli/create.ts
Removes a dead branch found inside the CLI code for validating project directories.
> chore(remix-dev/cli): simplify `validateNewProjectPath` in `create` command

- contributors.yml
- docs/pages/technical-explanation.md
While reading the [technical explanation docs](https://remix.run/docs/en/v1/pages/technical-explanation), it seemed like the code highlighting in the [Browser Framework section](https://remix.run/docs/en/v1/pages/technical-explanation#browser-framework) was off. I _believe_ the inside of the form should be highlighted as well as the `FadeIn`.
This PR updates the code highlighting to highlight the features discussed in the section.
> docs(pages/technical-explanation): update code highlighting

- contributors.yml
- docs/guides/constraints.md
Fixed `removeTrailingSlash` helper example which incorrectly handles root path which caused infinite redirection loop.
> docs(guides/constraints): handle root path in `removeTrailingSlash` helper

- packages/remix-eslint-config/rules/core.js
- packages/remix-eslint-config/rules/packageExports.js
This way people will know that all `remix` exports are considered deprecated & that they can use the `replace-remix-imports` migration to fix it all.
I needed to copy over all values from `packageExports` of `replace-remix-imports`' migration, since those values are only available in `@remix-run/dev`.
https://github.com/remix-run/remix/blob/main/packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/mapNormalizedImports/packageExports.ts
> feat(remix-eslint-config): add ESLint warning when using deprecated `remix` imports

- contributors.yml
- docs/tutorials/blog.md
> docs(blog): add imports

- contributors.yml
- docs/api/remix.md
Add missing id that added on [#1348](https://github.com/remix-run/remix/pull/1348)
> docs(api/remix): add missing `id` on match object from `useMatches`

- integration/bug-report-test.ts
So that we can properly see the failure, and then the fix.
> chore(issues-template): Clarify instructions when the user have a fix 

- packages/remix-eslint-config/rules/core.js
We're not officially deprecated yet.
> chore(eslint): disable deprecated imports rule

- integration/compiler-test.ts
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
some packages like `@heroicons/react` use a subdirectory package.json for things, like `@heroicons/react/solid`
closes #2691
Closes: #
> chore(remix-dev): use fullImportPath to resolve package

- packages/remix-dev/package.json
- yarn.lock
@chaance already commented it out in 952b0ce3, but `chalk-animation` was still in `dependencies` list.
`chalk-animation` is also causing high severity vulnerabilities warnings, so let's just remove the dependency for now.
- https://github.com/remix-run/remix/discussions/2505
- https://github.com/remix-run/blues-stack/issues/24
Since we're using git, we can always get this back if we ever want to.
> chore(remix-dev): remove unused `chalk-animation` dependency

- packages/remix-react/components.tsx
no more stringifying a func and dangerously setting innerHTML
Closes: #
> fix: LiveReload only executes on client

- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
E.g. `"netlify"` is an `Adapter` whose package is `@remix-run/netlify`
> fix(cli/migrate): remove `@remix-run/` prefix when checking for remix adapter

- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
Same bug fix for `dev`: #2784 
E.g. `"netlify"` is an `Adapter` whose package is `@remix-run/netlify`
> fix(cli/migrate): remove `@remix-run/` prefix when checking for remix adapters

- .github/workflows/nightly.yml
- scripts/version.js
update nightly releases to use version.js script
I'm not sure why we're getting a "dirty" working directory though.. perhaps we just `git commit -m "idk man"`
Closes: #
> ci: more nightly updates

- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
like `encoding` when using prisma and a custom output directory
we warn earlier on if a package is used without being in package.json so this seems fine, if we fail to build, the reason will be right there
closes https://github.com/remix-run/remix/issues/2691
Closes: #2691
> fix(remix-dev): add try/catch to `warnOnceIfEsmOnlyPackage` for when a package's dependency isn't installed

- .github/workflows/deployments.yml
the `@remix-run/dev` version is bumped by our version script so that it uses the most up to date version, so we can't have a lock file
Closes: #
> ci: opt out of caching deployment test dependencies

- .github/workflows/release.yml
> ci: restore some changes lost in a merge conflict

- contributors.yml
- packages/remix-dev/cli/create.ts
Rolls back a change made in e93f08773ff0cad8f9f09ee24f9d32916b52d07d.
Closes: #2714
---
The tests don't run on Windows (or at least, not on my machine) - not sure what to do about a related regression test.
> fix(cli): don't use system path separator on remote repo URLs

- docs/pages/gotchas.md
> docs(pages/gotchas): make more clear what's good/bad in `unstable_createFileUploadHandler` example

- templates/deno/remix-deno/server.ts
See https://github.com/remix-run/remix/pull/2359/commits/bd2fadfe548498028ceee242364fcedf7df7af48
> fix(templates/deno): remix's `createRequestHandler` no longer has a `platform` arg

- .github/workflows/deployments.yml
- .github/workflows/nightly.yml
- scripts/version.js
a copy of #2780 and #2789 for dev
(cherry picked from commit 8c071d7)
(cherry picked from commit a7c6a49)
Closes: #
> ci: more nightly updates (dev)

- docs/api/conventions.md
- docs/api/remix.md
- docs/guides/routing.md
Adds a section to the routing docs on the `?index` parameter used on Index Routes
> docs: add docs on ?index query param

- packages/remix-eslint-config/package.json
I also added `engines` for convenience
> chore(remix-eslint-config): cleanup `peerDependencies`

- integration/transition-test.ts
- package.json
- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/transition.ts
Existing loaders were not being properly revalidated during `fetchActionRedirect`
Closes: #1616 and #2361
> fix: Ensure parent loaders are called on fetchActionRedirect

- contributors.yml
- templates/arc/remix.config.js
- templates/cloudflare-pages/remix.config.js
- templates/cloudflare-workers/remix.config.js
- templates/express/remix.config.js
- templates/fly/remix.config.js
- templates/netlify/remix.config.js
- templates/remix/remix.config.js
- templates/vercel/remix.config.js
Updates the default ignoredRoutes pattern to include dot files in route subdirs too.
Currently the default is `".*"` which ignores them in the root directory, but not in any subdirectories.
The project I'm using remix on has team members that are not developers. One of which was using Finder on OS X to browse the routes dir and it generated .DS_Store files. Other users in the ticket referenced below mention programs like Emacs and I believe vanilla vim also generate dot files to store backups so it seems like it would be helpful to fix this.
Without that change, Remix breaks with a somewhat cryptic error if the generated dotfile is not correctly formatted as a route file.
Please let me know if there's any context I'm missing.
Closes: #2488
> chore: Ignore dotfiles in route subdirs too

- packages/remix-dev/cli/create.ts
the CLI needs to work on Node 12, but replaceAll wasn't added until [Node 15](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replaceAll#browser_compatibility)
Closes: #
> fix(remix-dev/create): use path.split and path.join to always make path posix style

- contributors.yml
- templates/arc/remix.config.js
- templates/cloudflare-pages/remix.config.js
- templates/cloudflare-workers/remix.config.js
- templates/express/remix.config.js
- templates/fly/remix.config.js
- templates/netlify/remix.config.js
- templates/remix/remix.config.js
- templates/vercel/remix.config.js
cherry-picked #2739 onto `main`, as changes to `templates` should go to `main`
> chore(templates): ignore dotfiles in route subdirectories too

- integration/helpers/cf-template/remix.config.js
- integration/helpers/node-template/remix.config.js
- packages/remix-dev/__tests__/fixtures/stack/remix.config.js
> chore(tests): ignore dotfiles in route subdirectories too

- packages/remix-dev/config.ts
- packages/remix-react/__tests__/components-test.tsx
- packages/remix-react/components.tsx
fix: manually set REMIX_DEV_SERVER_WS_PORT in config for users running `remix dev`
fix: read devServerPort from ENV at build time
Closes: # https://github.com/remix-run/remix/pull/2783#issuecomment-1102169177
> fix: re-inline live reload script

- packages/remix-dev/cli/commands.ts
> feat: clean directories before initial builds

- contributors.yml
- docs/tutorials/blog.md
The highlighted lines were all off by one so this PR fixes that:
> docs(tutorials/blog): update line highlighting

- packages/remix-dev/__tests__/replace-remix-imports-test.ts
Testing Strategy: I ran the tests locally and they run fast on my machine. I'm guessing the windows powershell thing is really slow or something, so my testing strategy is CI here to see whether the test times out in CI on windows.
> test: increase timeout of test for windows

- integration/cf-compiler-test.ts
- integration/compiler-test.ts
- integration/esm-only-warning-test.ts
- integration/helpers/create-fixture.ts
- integration/path-mapping-test.ts
- integration/server-code-in-browser-message-test.ts
- integration/tsconfig-test.ts
- packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
follow up to #2786
the merging worked prior to 02b60f5 in the PR due to parsing the config before writing the defaults, but now it happens after that due to the tsconfig loader being there temporarily. the writing of _just_ the missing options to the resolved tsconfig is new behavior
> chore(remix-dev): resolve `extends` in tsconfig when applying defaults

- docs/other-api/serve.md
Due to the changes introduced by https://github.com/remix-run/remix/pull/431, the documentation about purging the require cache is not accurate anymore and causes confusion, see https://github.com/remix-run/remix/issues/1832 and https://github.com/remix-run/remix/issues/1818 . Instead of purging the cache when files change, it is purged for every request.
See here for implementation:
https://github.com/remix-run/remix/blob/2c2d5abef37fa8ba5fa194df3c7e602f78a5f91c/packages/remix-dev/cli/commands.ts#L171
This PR updates the documentation by removing incorrect statements and points out that the require cache is purged for every request.
> docs: remove misleading information about cache purge on file change

- docs/guides/constraints.md
Best I could do right now since the utils are not documented on https://reach.tech/ yet.
But feel free to close this PR if you decide it will be better to keep the TODO until remix supports
`import {useIsometricLayoutEffect} from 'remix'` 😅
> docs(guides/constraints): link to Reach UI's `useIsomorphicLayoutEffect`

- contributors.yml
- examples/graphql-api/README.md
- examples/graphql-api/package.json
Closes: #3011 
Test the changes in local via
```
cd expamples/graphql-api && yarn && yarn dev
```
> docs(examples): add `graphql` to `dependencies` of `graphql-api` example

- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/__tests__/github-mocks.ts
- packages/remix-dev/__tests__/msw.ts
- packages/remix-dev/cli/create.ts
This PR clears up some error messaging when we cannot validate `--template` options.  We had some nested `try`/`catch`'s where specific errors were getting swallowed by an outer `catch` with a more generic error.
Before - with a non-existent github template that would return a 404:
```sh
~> npx create-remix@latest --template brophdawg11/junk
🚨 There was a problem verifying the template. Please ensure you are connected to the internet and try again later.
```
After (stack trace is only because of the direct `node` execution):
```sh
~> node ../remix/build/node_modules/@remix-run/dev/cli create --template brophdawg11/junk
Error: 🚨 The template could not be verified. Please double check that the template is a valid GitHub repository and try again.
at Object.validateTemplate …
```
> fix: provide clear error messages for create-remix errors

- docs/api/conventions.md
- docs/guides/typescript.md
- integration/js-routes-test.ts
- packages/remix-dev/compiler/routes.ts
- rollup.config.js
We currently support JSX syntax in `.js` files *except* for route modules. This PR should fix that.
> fix(remix-dev): support JSX in `.js` route files

- package.json
- packages/remix-dev/__tests__/replace-remix-imports-test.ts
- packages/remix-dev/package.json
- yarn.lock
fixes lint warnings about conditional `expect`
> test(replace-remix-imports): use cross-platform `grep` to avoid conditional `expect`

- contributors.yml
- docs/api/conventions.md
I think the comment `// content => name` was swapped around and `// name => content` is more logical, as the key is the name and the value is the property.
> docs(api/conventions): fix typos

- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/cli/create.ts
Closes: #2828
This test covers this code: https://github.com/remix-run/remix/pull/3087/files#diff-44fd7b47d36d99648d628196603ec193162f8cc64062cde2d76bbe36f89c6356R624
I also ran the build `yarn build` and ran the following:
success cases:
```shell
cd ~/Desktop && \
mkdir test && \
cd test && \
node ~/<path-to-remix>/build/node_modules/create-remix/cli.js .
```
and also
```shell
mkdir ~/Desktop/test && \
node ./build/node_modules/create-remix/cli.js ~/Desktop/test
```
failing cases:
```shell
cd ~/Desktop && \
mkdir test && \
cd test && \
touch .some-file && \
node ~/<path-to-remix>/build/node_modules/create-remix/cli.js .
```
and also
```shell
mkdir ~/Desktop/test && \
touch ~/Desktop/test/.some-file && \
node ./build/node_modules/create-remix/cli.js ~/Desktop/test
```
> chore(remix-dev): only check if dir is empty, not if it exists

- packages/remix-dev/cli/commands.ts
This clears the `public/build` directory before the build when running `remix build`, to avoid stale artifacts from persisting on subsequent builds/deploys
Closes: #83
Testing Strategy: Not a great way to write a unit test for this, but it can be tested locally via:
* `npm run build`
* Inspect `public/build/routes/` for a given route JS file
* Rename the route TS/JS file
* `npm run build`
* Inspect `public/build/routes/` and confirm the old route file is no longer present and the new route exists
> fix: clear build directory before new builds

- packages/remix-dev/cli/migrate/jscodeshift.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/options.ts
- packages/remix-dev/package.json
- yarn.lock
Fixed the problem @lensbart mentioned in https://github.com/remix-run/remix/issues/683#issuecomment-1103507342
> fix(remix-dev/cli/migrate): directly use `jscodeshift` instead of via CLI

- rollup.config.js
We made a small change in #3059 that broke the playground live reload trigger from the rollup build.  This fixes that and also adds the same live reload for usages of `REMIX_LOCAL_DEV_OUTPUT_DIRECTORY`
* Test out live-reload of playground apps
* Or try using `REMIX_LOCAL_DEV_OUTPUT_DIRECTORY=../path/to/remix/app yarn watch` and confirm live reload works there as well
> fix: fix rollup playground livereload

- docs/guides/api-routes.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/pages/contributing.md
- docs/pages/faq.md
- docs/tutorials/blog.md
Typos fixed:
• Instances where `it's` is used instead of `its`.
• Capitalized `GET` since it's an HTTP verb.
• `cancelations` -> `cancellations`
• `allowes` -> `allows`
• `teminal` -> `terminal`
• `resiliant` -> `resilient`
> docs: Fix typos

- templates/.gitignore
Just like in `examples`, we don't want to have lockfiles in `templates` either.
We're running `npm/yarn/pnpm install` in our CLI (both when creating & on `init`), so this could cause unnecessary lockfiles if the user's package manager is different from the one we included the lockfile for.
https://github.com/remix-run/remix/blob/a511d347a3c452c7532ddb396a16d246ae8ba70e/packages/remix-dev/cli/create.ts#L225-L228
https://github.com/remix-run/remix/blob/a511d347a3c452c7532ddb396a16d246ae8ba70e/packages/remix-dev/cli/commands.ts#L71-L74
> chore(templates): ignore lockfiles

- packages/remix-server-runtime/README.md
I think this counts as docs, right?
> docs(remix-server-runtime): fix `remix-deno` link

- contributors.yml
- docs/guides/data-loading.md
Improves type inference code example in Data Loading guide. The previous implementation wasn't accurate.
The proposed one lacks handling case when no product is found in the database, but since it is covered in one of next sections I think it's fair to leave it unaddressed.
> docs(guides/data-loading): fix type inference example

- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/cli/run.ts
Some issues from the npm CLI prove that it should indeed be `npm_config_user_agent` instead of `npm_user_agent`:
- https://github.com/npm/cli/issues/1834
- https://github.com/npm/cli/issues/2960
---
Follow-up of #2562
Closes #3108
> fix(remix-dev): fix package manager detection

- packages/remix-dev/cli/commands.ts
This will otherwise give the following error:
```sh
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path .../remix.init/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '.../remix.init/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 
npm ERR! A complete log of this run can be found in:
npm ERR!     .../.npm/_logs/2022-05-09T22_37_36_176Z-debug.log
```
> fix(remix-dev/cli/init): only run `npm install` when `package.json` is available

- packages/remix-dev/cli/commands.ts
This way, the `remix.init` script can call `npm/yarn/pnpm install` if needed.
The use-case I'm thinking about is having different dependencies when using JavaScript or TypeScript.
> feat(remix-dev): pass `packageManager` to `remix.init` script

- scripts/release/octokit.mjs
> ci: fix regex when parsing pr body for mentioned issues

- integration/compiler-test.ts
- packages/remix-dev/compiler/loaders.ts
- packages/remix-dev/modules.ts
webmanifest files are *just* json files with a different name https://developer.mozilla.org/en-US/docs/Web/Manifest
closes #2954
> chore(remix-dev): add support for importing `*.webmanifest` files

- docs/guides/migrating-react-router-app.md
- Removed `react` imports
- Added some good/bad annotations
> docs(guides/migrating-react-router-app): small updates

- contributors.yml
- docs/api/conventions.md
Adds `actionHeaders` in the description and example of the `headers` Route Module API since they aren't mentioned in the documentation at all.
> docs(api/conventions): mention `actionHeaders` in `headers`' arguments

- templates/cloudflare-pages/.gitignore
Every time we run the dev script, the `/functions/path.js.map` is generated. So, it's unneccessary to commit it to the Git repo.
> chore(templates/cloudflare-pages): ignore `/functions/[[path]].js.map`

- packages/remix-dev/cli/run.ts
resolves #3000
I ran the build and ran `node ./build/node_modules/create-remix/cli.js`, then i ran `yarn test` to make sure they all still passed
> chore(remix-dev): default to "just the basics"

- packages/remix-server-runtime/data.ts
> fix(remix-server-runtime): update error message when route doesn't have exports

- docs/decisions/0002-do-not-clone-request.md
- packages/remix-server-runtime/responses.ts
- packages/remix-server-runtime/server.ts
chore: remove duplicate method definition
Since loaders map to "GET" and "HEAD" requests, those by definition can't have a body and therefore there is no reason to pass it in to use-code. This also avoids exclusive locks on the body when multiple loaders are executed in parallel.
Changes:
- Action recieves OG request and can choose to read the body.
- handleDocumentRequest recieves OG request, if the action read the body it will be locked and `bodyUsed` will be true. Atempting to read the body again will throw
- Loaders recieve a copy of the OG request without the body.
Closes: https://github.com/remix-run/remix/issues/3003
> feat(remix-server-runtime): strip `body` from `request` before calling `loader`s

- contributors.yml
- templates/vercel/.gitignore
In the Vercel template,  `/api/index.js.map` should also be ignored along with `/api/index.js`. Otherwise, that mapping file would be committed into version control, which is not desired.
This PR only touches `/templates`, therefore requesting merge at `main` instead of `dev` branch.
Testing Strategy: `git commit`
> fix(templates/vercel): add `index.js.map` to `.gitignore`

- packages/remix-server-runtime/__tests__/handler-test.ts
- packages/remix-server-runtime/server.ts
Spreading a Request object yields an empty object. This explicitly passes through the init to the new Request.
> fix: change how request is "cloned" for loaders

- packages/remix-deno/index.ts
This PR brings feature parity with the Cloudflare & Node runtimes
> feat(remix-deno): export new `@remix-run/server-runtime` upload functions & types

- packages/remix-dev/__tests__/replace-remix-imports-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/create.ts
- packages/remix-dev/cli/getPreferredPackageManager.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
- packages/remix-dev/cli/migrate/run.ts
- packages/remix-dev/cli/migrate/types.ts
- packages/remix-dev/cli/run.ts
Now that we have `packageManager` available since #2562, we can also use it in the migrations
> feat(remix-dev/cli): let `replace-remix-imports` migration re-install to update lockfile

- scripts/publish-private.js
- scripts/publish.js
Publishing without a tag to npm will default to use `latest`, which we definitely don't want for experimental releases. It looks like npm requires a dist-tag when publishing, so we will use `experimental` instead.
I also noticed we were doing something different for the private publish script. Not sure if this even matters any more, but I fixed that as well.
> fix(scripts): Prevent publishing without a tag

- packages/remix-server-runtime/README.md
since it's now a proper package
> docs(server-runtime): update link for deno server runtime package

- contributors.yml
- docs/guides/migrating-react-router-app.md
- examples/google-analytics/app/utils/gtags.client.ts
- examples/image-resize/app/routes/assets/resize/$.ts
- examples/infinite-scrolling/app/routes/offset/advanced.tsx
- examples/infinite-scrolling/app/routes/page/advanced.tsx
- examples/io-ts-formdata-decoding/app/routes/index.tsx
- examples/pm-app/app/routes/dashboard/projects/$projectId.tsx
- examples/pm-app/app/styles/global.css
- examples/route-modal/app/routes/invoices/$id/edit.tsx
- examples/route-modal/app/routes/invoices/add.tsx
> fix(examples, docs): fix typos

- templates/cloudflare-pages/remix.env.d.ts
The globals file got removed in a previous commit and the d.ts has not been updated to reflect that change.
> fix(templates/cloudflare-pages): fix runtime globals reference

- examples/stitches/README.md
We have removed the reference to `server.context.tsx` from the documentation, as it appears that `server.context.tsx` is not used in the sample source files.
> fix(examples): fix `README` of `stitches` example

- templates/deno/server.ts
`process.env.NODE_ENV` works, but VSCode unnecessarily complains and it also doesn't feel Deno-y enough so I would propose changing it to the appropriate `Deno.env.get("NODE_ENV")`.
Please correct me if I'm mistaken 🙏
Also so happy to finally get Deno Remix just working, with the latest Deno and all 🥳 Thanks so much @pcattori  👏
> fix(templates/deno): use `Deno.env` instead of `process.env`

- .vscode/deno_resolve_npm_imports.json
- contributors.yml
- packages/remix-deno/README.md
- packages/remix-server-runtime/README.md
- scripts/utils.js
- templates/deno/.gitignore
- templates/deno/.vscode/resolve_npm_imports.json
- templates/deno/.vscode/settings.json
- templates/deno/README.md
- templates/deno/app/entry.client.tsx
- templates/deno/app/entry.server.tsx
- templates/deno/app/root.tsx
- templates/deno/app/routes/index.tsx
- templates/deno/package.json
- templates/deno/remix.config.js
- templates/vercel/.gitignore
Reverts remix-run/remix#3225
Accidentally merged other commits from `main`.
> Revert "chore: update Deno import maps on release"

- contributors.yml
- docs/tutorials/jokes.md
- packages/remix-dev/cli/run.ts
When running `npx create-remix@latest`, The CLI asks me 
"Where do you want to deploy? Choose **Remix** if you're unsure; it's easy to  change deployment targets."
But there is no option such as **Remix**, but **Remix App Server**. This PR is to make users not confused when first using `create-remix`
> fix(remix-dev): improve `appTemplate` message

- contributors.yml
- docs/other-api/react-router.md
"Other api" docs about React Router were pointing at the old urls (which do not redirect properly). Updated to point to the new ones
> docs(other-api/react-router): update links to `react-router` docs

- examples/basic/app/routes/index.tsx
- integration/link-test.ts
- packages/remix-react/components.tsx
- packages/remix-react/links.ts
- packages/remix-server-runtime/links.ts
This PR improves support for returned links that include an `imagesrcset` attribute to preload images when matched against a responsive set of URLs. This only works when `rel === 'preload'` and `as === 'image'`.  https://html.spec.whatwg.org/commit-snapshots/cb4f5ff75de5f4cbd7013c4abad02f21c77d4d1c/#attr-link-imagesrcset
Prior to this PR, a few problems with our implementation:
1. Our types for `HtmlLinkDescriptor` make `href` required. This is true *unless* a link includes `imagesrcset` and `imagesizes`, though `imagesrcset` and `href` will also work with or without `imagesizes` according to the spec. This PR uses an intersection type to account for these cases.
2. React 17 was released prior to these attributes being accepted into the spec and implemented by browsers, so passing the …
> fix: Better support for `imageSrcSet` + `imageSizes` in route `links` (#184)

- templates/deno/.vscode/resolve_npm_imports.json
`@remix-run/deno` code is already an ESM Deno module, so it should not be processed
by a Deno-friendly CDN expecting a CJS Node package.
> fix(templates/deno): get types for `@remix-run/deno` directly from `node_modules/`

- templates/arc/README.md
- templates/arc/package.json
as of arc v10, they recommend a local install of the arc cli https://arc.codes/docs/en/get-started/detailed-aws-setup#install-architect – a global install is still supported, but having it locally ensures that it's installed
Closes: #
> chore(templates/arc): move arc to devDependencies

- .github/workflows/deployments.yml
- scripts/deployment-test/deno-deploy.mjs
- templates/deno/.vscode/extensions.json
- templates/deno/README.md
- templates/deno/package.json
Deployment test for Deno Deploy.
Tried the test locally by using my own Deno Deploy project name, and that deployed successfully. (https://salty-bee-35.deno.dev/)
> feat(templates/deno): deploying to Deno Deploy

- templates/arc/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers/package.json
- templates/deno/package.json
- templates/express/package.json
- templates/fly/package.json
- templates/netlify/package.json
- templates/remix/package.json
- templates/vercel/package.json
As mentioned by @pcattori in https://github.com/remix-run/remix/pull/3221#discussion_r876255891, these fields aren't necessary for apps.
> chore(templates): remove `description`, `license` & `name` keys from `package.json`

- docs/guides/typescript.md
> docs: remove `description` & `license` keys from `package.json`

- packages/remix-eslint-config/rules/core.js
Companion PR of #3284
I think we can enable these again, as:
> - The first release supporting separate packages was `1.3.3`, which was released on 23 Mar 2022
>   https://github.com/remix-run/remix/releases/tag/v1.3.3
> - The `replace-remix-imports` migration was added in `1.4.0`, which was released on 14 Apr 2022
>   https://github.com/remix-run/remix/releases/tag/v1.4.0
> - We now export functions/types that aren't available anymore through the `remix` package, as they're not included in the `magicExports` anymore (see both `@remix-run/cloudflare` & `@remix-run/node`) since `1.5.0`
> - We now have a runtime package (`@remix-run/deno`) that doesn't have *any* magic exports *at all* since `1.5.0`
> https://github.com/remix-run/remix/releases/tag/v1.5.0
> feat(remix-eslint-config): enable deprecated imports warnings

- packages/remix-react/components.tsx
- packages/remix-react/index.tsx
This PR exposes additional types that are helpful when passing values via context or props.
Complex return types from functions should be exposed directly IMO. Usage is a little simpler than relying on `ReturnType<typeof someFunc>`, and in the case of generics like `Fetcher` and `FetcherWithComponents` it is necessary.
```ts
// instead of this...
type Ctx = {
fetcher: ReturnType<typeof useFetcher>;
location: ReturnType<typeof useLocation>;
};
// ...I can do this
type Ctx = {
fetcher: FetcherWithComponents<SomeData>;
location: Location;
};
```
> enhancement: Export additional types from `@remix-run/react`

- templates/deno/package.json
`format` and `lint` scripts were checking build directories, which produced tons of nonsensical errors.
> fix(templates/deno): ignore `build` dirs from tooling

- contributors.yml
- examples/firebase-auth-firestore/.env.example
This is an update to `.env.example` for the Firebase Auth Example that makes it more clear what goes where and how to format.
> docs(examples): update `.env.example` of `firebase-auth-firestore` example

- contributors.yml
- examples/firebase-auth-firestore/app/server/firebase.server.ts
Apply fixes as per comment by @mocon at https://github.com/remix-run/remix/pull/1811#issuecomment-1090544230
Also:
- throw meaningul errors when environment variables are missing or can't be parsed.
- check for existence of environment variable rather than cast to string
Closes: issue reported in comment https://github.com/remix-run/remix/pull/1811#issuecomment-1090544230
```sh
cd examples/firebase-auth-firestore
yarn
yarn dev
cp .env.example .env
yarn dev
yarn dev
yarn dev
```
I plan to follow up with a few other PRs:
- [fallback to Firebase emulator](https://github.com/penx/remix/compare/fix-firebase-example...penx:firebase-emulator) on localhost when environment variables are not set
- use REST API for auth instead of client side SDK as detailed at …
> fix(examples/firebase-auth-firestore): Fix imports and throw meaningful errors when missing .env

- templates/vercel/package.json
- templates/vercel/vercel.json
Follow-up of #2057
`vercel.json` isn't necessary anymore: https://github.com/vercel/vercel/pull/7886
> chore(templates): update `vercel` template

- .github/workflows/no-response.yml
> ci: update needs-response workflow to use official stale action

- packages/remix-dev/cli/run.ts
I simply merged the default case with the dev case.
This allow to use the `--debug` CLI flag when using the `remix dev` shorthand. 
I've built and tested from one of my projects using `node ../remix/build/node_modules/\@remix-run/dev/cli.js --debug`
> fix(remix-dev): Allow debugging for the remix shorthand

- examples/firebase-auth-firestore/app/routes/index.tsx
Fix the Firebase example when JavaScript is disabled.
`method="delete"` is not a valid form action.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/form#attr-method
While this works when JavaScript is enabled, it does not fall back gracefully.
Instead, use specify form action using name + value on buttons, as shown in FAQs:
https://remix.run/docs/en/v1/pages/faq#how-do-i-handle-multiple-forms-in-one-route
Closes: a bug I encountered while working on the Firebase example - no open issue.
- is it possible to write integration tests for the examples?
In order to test this manually, I ran the Firebase example with JavaScript enabled and ensured:
- when submitting new TODO: entries with a blank input, the validation error shows
- when deleting TODO: entries, the …
> fix(examples): use `post` action in `firebase-auth-firestore` example

- contributors.yml
- docs/guides/envvars.md
When I recently spun up a project using the `@remix-run/cloudflare-pages` adapter, it was not clear how to set up and use env variables, both locally and when deployed to Cloudflare Pages.
Thankfully @jemjam figured it out in [this issue comment](https://github.com/remix-run/remix/issues/1285#issuecomment-1124463689)
This updates the Environment Variables docs with that information. This should hopefully save people a lot of pain when initially setting up a new project with the Cloudflare Pages adapter.
> docs(guides/envvars): clarify docs for local/production env variables

- examples/firebase-auth-firestore/.env.example
- examples/firebase-auth-firestore/README.md
- examples/firebase-auth-firestore/app/server/auth.server.ts
- examples/firebase-auth-firestore/app/server/firebase-rest.server.ts
- examples/firebase-auth-firestore/app/server/firebase.server.ts
- examples/firebase-auth-firestore/package.json
Use the [Firebase Auth REST API](https://firebase.google.com/docs/reference/rest/auth) for authenticating server side, instead of the [Firebase client SDK](https://github.com/firebase/firebase-js-sdk).
The [Firebase Client Auth SDK is stateful](https://firebase.google.com/docs/auth/web/auth-state-persistence). It seems to have been built for the purpose of using it within an application where only one user is logged in at a time (i.e. client applications). It _may_ not pose a security risk if it is _only_ used for authentication calls, but login state is persisted in the module and this could lead to security issues if other features such as `firebase/firestore` were used, as these would behave as the last user to log in.
The Firebase Auth REST API gives us the same functionality with no …
> feat(examples/firebase-auth-firestore): use rest api for server auth

- contributors.yml
- docs/guides/migrating-react-router-app.md
This fixes a typo in the "Migrating your React Router App to Remix" documentation: changes "wave" to "have".
> docs(guide): fix typo in Migrating React Router App

- integration/catch-boundary-test.ts
- integration/error-boundary-test.ts
- packages/remix-server-runtime/__tests__/server-test.ts
- packages/remix-server-runtime/server.ts
Closes: #599
Testing Strategy: I tested using the repo in #599 but the repro setup is basically:
* Parent route with loader data
* Child route that exports `ErrorBoundary` or `CatchBoundary`
* Child contains `form` or `<Form reloadDocument={true}>` submitting to child action that throws
* This error only happens in server-side form submissions 
* Proper boundary should be used and the parent loaderData should not be wiped away on submission
> fix(remix-server-runtime): use correct error/catch boundary on SSR action errors

- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli/create.ts
- packages/remix-dev/cli/run.ts
This PR improves the CLI by asking about using TypeScript or JavaScropt *before* running `npm install`. This is a better UX because:
- We ask all questions up front, so it just flows a bit better
- If we convert the template first, `npm install` won't include all of the TS-related modules previously in the `package.json`
---
> enhancement(cli): Ask about TypeScript before `npm install`

- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
This PR adds a `--port` flag to `remix dev` that takes precedence over `process.env.PORT`. This makes it easier to choose a new port on the fly.
Note, I updated the snapshot but didn't create any new tests yet. We don't currently have a test suite for `remix dev` commands and I need to follow up internally before adding a new process-intensive test that could further slow things down in CI. I did test it manually and things work as expected.
> enhancement(dev/cli): Add `--port` flag to `remix dev`

- templates/deno/.vscode/resolve_npm_imports.json
Seems like this went wrong when merging `main` into `release-v1.6.0` (1cd43bee)
This PR is making sure we keep what @pcattori did in #3278
> fix(templates/deno): fix `resolve_nom_imports`

- docs/pages/contributing.md
When you get a fresh clone of your fork and run through the setup for contributing you are likely to get an error asking you to install browsers with playwright - unless it was previously installed for another project.  Message comes from [here](https://github.com/microsoft/playwright/blob/3853014fa74033110bd032b195e4bde812fe3cc8/packages/playwright-core/src/server/registry/index.ts#L318-L335)  in from playwright.
This is just a quick update to make sure to run the browser install before testing to confirm your ready to contribute!
> docs(pages/contributing): add requirement to install `playwright`

- docs/tutorials/jokes.md
It seems that having a space breaks code highlighting
> docs(tutorials/jokes): fix code highlighting

- contributors.yml
- docs/api/remix.md
updated the docs for `fetcher.type` from `load` to `normalLoad`
> docs: update incorrect fetcher.type "load" to "normalLoad"

- package.json
use [playgrounds](https://remix.run/docs/en/v1/pages/contributing#playground) instead
> chore(scripts): remove obsoleted `dev` script

- contributors.yml
- docs/guides/data-writes.md
The issue here is that `<Form reloadDocument />` hasn't been mentioned yet, neither in text nor code. So the reader following along with the guide will have `<form />` implemented in their editor at this point.
Note that the next paragraph goes into why `Form` needs the `reloadDocument` prop to be equivalent to `form`, which makes sense, and then we can forget about `form` altogether.
> docs(guides/data-writes): fix `form`/`Form` explanation

- examples/firebase-auth-firestore/firebase-fixtures/auth/config.json
- examples/firebase-auth-firestore/firebase-fixtures/firestore.rules
- examples/firebase-auth-firestore/firebase.json
Add a firestore.rules file ([docs](https://firebase.google.com/docs/firestore/security/get-started)) that disables public access to all Firestore data.
All reads and writes are done via firebase-admin, which skips Firebase rules.
Also added a auth/config.json file to silence auth warning during emulator startup:
```sh
$ yarn emulators
...
⚠  auth: Skipped importing config because /remix/examples/firebase-auth-firestore/firebase-fixtures/auth/config.json does not exist.
```
> docs(examples): add firestore rules to `firebase-auth-firestore` example

- contributors.yml
- docs/api/remix.md
Adds caveat around use of the code verbatim, as using `expires` in the way shown, outside any kind of dynamic function, would result in a fixed expiry for all future cookies
> docs(api/remix): add note to sessions usage section

- integration/redirects-test.ts
- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/transition.ts
There is some stateful information driving whether or not we revalidate inside transition manager which was getting lost across a redirect boundaries in certain scenarios.  This PR fixes two potential flows:
1. action submission redirects, then loader redirects
1. We go `actionRedirect -> normalRedirect` and the second loader execution skips reused parent routes
2. This is fixed by keeping subsequent redirects marked as `actionRedirect`
2. loader redirects with a cookie
1. We go normalRedirect -> normalRedirect but we lose the `location.state.setCookie` flag on the second redirect
2. This is fixed by carrying forth the `setCookie` flag from the current navigation when kicking off a new `normalRedirect`
Closes: #3302 
* Tested locally with …
> fix: Handle revalidations across multi-redirects

- contributors.yml
- docs/tutorials/blog.md
Someone asked about this on Discord.
I believe it should be `npx prisma migrate dev`?
> docs(blog-tutorial): fix prisma migrate command

- contributors.yml
- docs/api/conventions.md
Adds clarifying context about how `meta` works under the hood (it can run on both client and server) so don't try to access server-side data directly in it.
As I found it via: https://github.com/remix-run/remix-website/pull/46#discussion_r905343443
Given that open graph tags like `og:image` are supposed to be absolute URLs, it seems pretty likely that somebody is going to need to do this at some point in time.
> docs(api/conventions): add note about how to access server-side data in `meta` function

- integration/helpers/create-fixture.ts
Display the actual contents of stderr when things fail. I preserved the commented-out debug stuff, as that can be useful for seeing what's happening when things **don't** fail.
* Ran all integration tests, they passed, and no output changed
* Made a test fail and confirmed I saw the new error message and useful output :)
> chore(integration): improve build failure output in tests

- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
This is important if people run `npx remix init` themselves, like suggested in https://github.com/remix-run/indie-stack/pull/112, https://github.com/remix-run/blues-stack/pull/89 & https://github.com/remix-run/grunge-stack/pull/76
> fix(remix-dev/cli/init): always remove `remix.init` folder

- .github/workflows/release-test.yml
we only want to test against the latest node on normal commits/PRs, but on releases we can test against 14, 16, and 18. follow up fix to https://github.com/remix-run/remix/pull/3561
> ci(release-test): remove pull_request trigger

- contributors.yml
- packages/remix-dev/compiler.ts
Closes: (no issue yet - can create one if you like)
There isn't currently an easy way for us to test yarn pnp / Remix compatibility, so this is just a local manual test.
Before this change (current dev branch, when running `remix build`, multiple errors (as below) appear, I guess because yarn cannot resolve the paths generated by the `NodeModulesPolyfills` plugin, unless the `esbuild-plugin-pnp` plugin runs first. I'm guessing the pnp plugin needs to set up some path transformation stuff before the polyfill plugin, but the docs for both are super light so I'm not 100% sure *why* it fixes the errors, but it does.
Thankfully when not using yarn pnp, `esbuild-plugin-pnp` is a no-op, so no risk to non-yarn users either way.
```
Build failed with 9 errors: …
```
> fix(remix-dev): fix Yarn PnP resolve issue

- .github/workflows/deployments.yml
- .github/workflows/format.yml
- .github/workflows/nightly.yml
- .github/workflows/release-comments.yml
- .github/workflows/release-private.yml
- .github/workflows/release.yml
- .github/workflows/reusable-test.yml
- .github/workflows/stacks.yml
We already use `actions/setup-node@v3` which has equivalent caching functionality that isn't broken for yarn+windows (or yarn 2+ across the board). So just use that wherever possible. In addition to fixing builds, this has the added benefit of slightly speeding them up, since we won't double-cache things (in some cases we had both caches enabled).
Making this PR against `main` instead `dev`, since the jobs explicitly use `remix-run/remix/.github/workflows/reusable-test.yml@main`, but I can switch it up if y'all like. Just trying to get my 4-month-old PR unblocked yet again 😆😭
For context, see https://github.com/bahmutov/npm-install/issues/146, in particular [this comment](https://github.com/bahmutov/npm-install/issues/146#issuecomment-1169226551) and linked test output.
This is an …
> fix: remove bahmutov/npm-install to fix windows builds

- packages/remix-dev/.gitignore
- packages/remix-dev/package.json
- packages/remix-node/.gitignore
- packages/remix-node/package.json
- rollup.config.js
- scripts/copy-build-to-dist.mjs
Fix deep imports for globals/server-build
* `@remix-run/dev/server-build`
* JS file written outside of `dist/` by `rollup`, then copied from `build -> packages` in postbuild
* Types file written into `dist/` by `tsc` - copied outside of `dist/` in both build and `packages/` dir by `postbuild` 
* `@remix-run/node/globals.d.ts`
* Shim to do the re-export written out in `postbuild` and copied to `packages/` dir
> fix: fix deep imports

- contributors.yml
- packages/remix-dev/cli/commands.ts
- packages/remix-serve/cli.ts
Closes: #3600
This patch addresses a specific regression in Node v18.3 by making the detection of IPv4 addresses more durable.
**References:** 
- [Broken network `family` detection](https://github.com/nodejs/node/blob/49362efd5b39f31a14260612422109e130068d08/lib/os.js#L251)
- [v18.4 patch from 1-2 weeks ago](https://github.com/nodejs/node/commit/70b516e4dbdfdfea2183995ec3b368dacaa38183#diff-f52f7c022afbe0147ec297ea168db37d7e5aa3a611f18d952c5ddb85ae689059R131)
See reproduction steps in #3600
> fix(remix-dev,remix-serve): fix network `family` detection

- contributors.yml
- docs/api/conventions.md
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/compiler.ts
- packages/remix-dev/config.ts
Support to watch directories other then remixes default directories. Will help integration with mono repos like NX/TurboRepo.
Closes: #2983
Agreed upon replacement of: https://github.com/remix-run/remix/pull/2985
- [ x ] Docs
- [ x ] Tests
> feat(remix-dev): add `watchPaths` config option

- packages/remix-dev/cli/create.ts
i'm quite interested in why our tests all passed without this...
Closes: #3618
> fix(remix-dev/create): check for undefined `--token`

- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
> feat(remix-dev/cli/init): add `--no-delete` flag

- contributors.yml
- scripts/playground/new.js
- scripts/playground/template/package.json
Creating an application from the `yarn playground:new` command is currently not working, it is failing due to this error:
```
Running Remix Init...
node:internal/modules/cjs/loader:936
throw err;
^
Error: Cannot find module '/workspaces/remix/playground/playground-1656781242957/node_modules/@remix-run/dev/cli'
at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
at Function.Module._load (node:internal/modules/cjs/loader:778:27)
at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12)
at node:internal/main/run_main_module:17:47 {
code: 'MODULE_NOT_FOUND',
requireStack: []
}
Node.js v17.6.0
node:internal/errors:844
const err = new Error(message);
^
Error: Command failed: node ./node_modules/@remix-run/dev/cli init
at checkExecSyncError …
```
> fix: fix `playground` creation

- integration/esm-only-warning-test.ts
- integration/helpers/playwright-fixture.ts
- integration/prefetch-test.ts
- integration/tsconfig-test.ts
- integration/tsconfig.json
- packages/remix-express/tsconfig.json
- packages/remix-react/tsconfig.json
- packages/remix-server-runtime/tsconfig.json
- tsconfig.json
Fix errors that currently show up in VSCode with typescript 4.5.5 (the current version Remix uses). Playwright only transpiles typescript, it doesn't do any type checking. In addition to fixing the errors, start type checking `integration` when we build.
> chore(integration): fix type errors and start enforcing type checks

- contributors.yml
- docs/tutorials/jokes.md
at point where reader is only done with building types for `Joke`, the example shows to import `type User` from `@prisma/client` where it is not there yet.
the succeeding code continuation also didn't use the built type from `@prisma/client`
> docs: jokes app tutorial in fetching jokes part

- scripts/deployment-test/vercel.mjs
i don't think vercel deploy allows for the environment variable, instead requiring the flag to be passed, but other vercel commands allow it 🤷‍♂️ https://github.com/vercel/vercel/blob/695bfbdd60a97030457ea1861c5bb89bcfe92353/packages/cli/src/index.ts#L439, so I'll keep in spawn's `env`.
Closes: #
> ci(deploy/vercel): pass token via `--token`

- packages/remix-dev/compiler.ts
- packages/remix-dev/package.json
- yarn.lock
Closes: (No issue yet)
Still no testing strategy for yarn pnp compatibility (though sounding like we might need to work out how to integration test this, given the complexity)
This is another fix for yarn pnp, in the same realm as #3594, and related to [this fix](https://github.com/yarnpkg/berry/pull/4569) in `@yarnpkg/esbuild-plugin-pnp` by @jenseng, with the `resolveDir` esbuild property. However, this may not solve the issues with Deno that @lensbart is having.
This also un-does #3579 because that didn't actually work at all, just hid some errors (I was lazy there). After looking in much more detail I think I have solved a related problem.
I've noticed that all imports in the `pnp` namespace being resolved (in the `onResolve` esbuild callback) have an *empty* `resolveDir` value by …
> fix(remix-dev/compiler): fix Yarn PnP resolution for empty modules

- docs/tutorials/blog.md
- docs/tutorials/jokes.md
- update pre-requisite node version requirements for docs.
- `eslint` version 8 requires the following node version (^12.22.0, ^14.17.0, or >=16.0.0)
Closes: #3652
- `npm install / yarn install` failure 
- `eslint` v8 requires the 3 versions specified above
- N/A docs changes only
> fix(docs/tutorials): update pre-requisite Node version

- packages/remix-server-runtime/responses.ts
In the original loader type inference PR #3276 I made an attempt to constrain the generic parameter of the `json` function to exclusively JSON-compatible types. This caused [typechecking errors](https://github.com/remix-run/remix/runs/7240224157?check_suite_focus=true) when attempting to assign an interface to the generic due to https://github.com/microsoft/TypeScript/issues/15300
```ts
interface MyInterface { arg: string };
json<MyInterface>();
// Index signature is missing in type
```
This PR implements the most straightforward solution: loosening the generic parameter of `json` to allow any type `<T extends unknown>`. This was the type signature before my PR landed so it will certainly be backwards compatible. Enforcing JSON serializability statically would have been nice but I don't …
> fix(remix-server-runtime): support interfaces in `JsonFunction`

- templates/deno/.vscode/resolve_npm_imports.json
See the existing comment in `.vscode/resolve_npm_imports.json`
> fix(templates/deno): grab `@remix-run/deno` types directly from `node_modules/`

- packages/remix-dev/cli/run.ts
It seems that we forgot to declare it in #3447
Closes #3693
> fix(remix-dev): declare `--port` & `-p` flags

- packages/remix-architect/rollup.config.js
- rollup.utils.js
> refactor(rollup): cleanup `magicExports` remains

- contributors.yml
- docs/guides/typescript.md
I noticed that the line highlight in the Typescript guide is misplaced:
The `package.json` template was updated in e9692e11, but the hightlight stayed on the old line number, this PR fixes that.
Other snippets of `package.json` and `tsconfig.json` in the docs are correct,
> docs(guides/typescript): fix code highlighting

- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
- packages/remix-dev/config.ts
- packages/remix-serve/cli.ts
- packages/remix-serve/index.ts
- packages/remix-server-runtime/build.ts
this allows `remix dev` and `remix-serve [build-dir]` to use your customized `assetsBuildDirectory` and `publicPath`.
in `remix dev` we already read the config, so we can just pass `config.publicPath` and `config.assetsBuildDirectory` along to `remix-serve`'s `createApp` function to use, but in `remix-serve [build-dir]` we'll require the passed `buildPath` in `remix-serve/cli.ts` and pass those from the build itself to `createApp`
> feat(remix-dev,remix-serve): include publicPath in server build manifest

- decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
- decisions/0002-do-not-clone-request.md
- decisions/index.md
already done in https://github.com/remix-run/remix/pull/3259, but these
deletions probably came back when merging `dev` back into `main` at some
point
> docs(decisions): remove unused index and frontmatter

- .changeset/yellow-flowers-trade.md
- integration/compiler-test.ts
- integration/helpers/create-fixture.ts
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
> fix(serverBareModulesPlugin): update require.resolve to use full import, update warning

- templates/vercel/package.json
Follow-up of #3420
---
Base branch is `dev`, because we need #3420 to be merged in order for this to work
> templates(vercel): update `@vercel/node` dependency

- .changeset/blue-starfishes-study.md
- contributors.yml
- packages/remix-eslint-config/index.js
Closes: #3715
1. In a new directory run `yarn init -2`.
2. Then run `yarn add -D eslint @remix-run/eslint-config`.
3. Create a file called `.eslintrc` with the following:
```json
{
"extends": [ "@remix-run/eslint-config" ]
}
```
4. Create a file called `test.js` with the following:
```js
eslint_Wont_like_This = true
```
5. Run `yarn eslint test.js`.
6. Ensure that the output is an ESlint problem and not a Yarn error (as shown in #3715).
I attempted to write an automated test, however, I couldn't find any preexisting ones for this package, so I didn't have anything to go off.
> fix(remix-eslint-config): use `require.resolve` when importing `@babel/preset-react`

- .changeset/weak-icons-matter.md
- packages/remix-dev/server-build.ts
closes https://github.com/remix-run/grunge-stack/issues/85
x-ref #3349
Closes: #
> fix(remix-dev): update type for ServerBuild virtual module

- .changeset/tender-impalas-invite.md
- contributors.yml
- docs/guides/mdx.md
- integration/mdx-test.ts
- packages/remix-dev/compiler/plugins/mdx.ts
This adds a handle export, links export, and loader export to MDX routes, much like the existing meta and headers exports.
Closes: #2592, #2858
I added a new integration test for mdx routes which covers the existing functionality (I believe this was uncovered before) as well as the newly added functionality.
I can see a couple different approaches for doing this. One option would be to just make the handle the frontmatter and omit the loader altogether. We could also structure the loader as:
```js
{
frontmatter: {/* ... */}
}
```
>  feat(remix-dev): add support for `handle`, `links` & `loader` to mdx 

- contributors.yml
- templates/netlify/README.md
- templates/netlify/package.json
- templates/netlify/remix.config.js
This PR improves the DX when using the Netlify template to build out your Remix application. cc: @ascorbic. I've based this PR off of `main` because I believe @mcansh mentioned that if it's just template changes, there's no need to branch off of the `dev` branch.
Closes: #3753
1. Create a new Remix application and select Netlify for the deployment target.
2. You can install whatever you'd like in the Remix CLI steps. It also doesn't matter if you select TypeScript or JavaScript
3. Once your application has been created, from a shell, change to the root directory of your new application.
4. Run `npm run dev`
5. The Remix dev server starts and renders the main page when navigating to http://localhost:3000
6. Stop the Remix dev server.
7. Run `netlify dev`. The server …
> templates(netlify): improve DX for Netlify serverless template

- docs/api/remix.md
Updated `unstable_createFileUploadHandler` callbacks signature according to the changes that happened in #2736 
Closes #3756
> docs(uploads): Update unstable_createFileUploadHandler callbacks signature

- docs/tutorials/blog.md
- docs/tutorials/jokes.md
Remix doesn't support Node v12
> docs(tutorials): update Node requirement

- .github/workflows/release-experimental.yml
We won't be triggering any releases from GitHub moving forward. For experimentals, we can trigger the workflow simply by pushing the version tag created after running `yarn run version experimental`.
> chore(ci): Trigger experimental release from tag instead of GitHub

- .github/workflows/nightly.yml
- .github/workflows/reusable-test.yml
- package.json
- scripts/build.mjs
This is a simple script that makes builds faster by default, making `tsc` and copying build artifacts to package `dist` directories opt-in via either `process.env.CI` or command line args.
> chore: Add script for faster builds

- .changeset/long-taxis-drop.md
- contributors.yml
- packages/remix-node/index.ts
Closes: #3758
The explanation is in this comment:
https://github.com/remix-run/remix/issues/3758#issuecomment-1188882909
Manual. This fixes a bug that only appears with build packages as it is basically a packaging issue.
> Fix `json()` when inferring the return type

- contributors.yml
- docs/guides/not-found.md
When discussing this topic with colleagues the wording 'you don't have to do anything' was interpreted in an ambiguous way.
This re-phrasing link's back to splat routes as a good option for handling 404s
> docs(guide): Clarify how to handle 404s

- .github/workflows/postrelease.yml
- .github/workflows/release-comments.yml
- .github/workflows/release.yml
- .github/workflows/reusable-test.yml
- scripts/release/comment.ts
- scripts/release/constants.ts
- scripts/release/github.ts
- scripts/release/utils.ts
Same as https://github.com/remix-run/remix/pull/3744. I cherry-picked the squashed commit to `dev` because we should keep workflow changes in sync between releases as much as possible.
> ci: move comments, deploy and stacks test to different action (#3744, #3803)

- .changeset/loud-emus-cross.md
- packages/remix-react/index.tsx
- rollup.utils.js
We moved a bit hastily on exposing this type. We need to bikeshed the name a bit and possibly expose it from the runtime instead of `@remix-run/react`
> chore(revert): Remove `UseDataFunctionReturn` type export

- templates/cloudflare-pages/package.json
- templates/cloudflare-workers/README.md
- templates/cloudflare-workers/package.json
- templates/cloudflare-workers/wrangler.toml
Update template for cloudflare workers. (https://github.com/remix-run/remix/discussions/3158)
- `wrangler.toml`: Changed to wrangler v2 style.
- `package.json`: Added wrangler to dependecncies. Updated @cloudflare/workers-types latest. (also pages template)
- `remix.env.d.ts`: Fixed dead link. (also pages template)
- `README`: Removed the sentence about installation of wrangler.
I have confirmed that it is deployable. (https://github.com/aiji42/remix-cf-wrangler-2)
```
uejima.aiji$ yarn deploy                                                                                             [~/git/remix-cf-wrangler-2]
yarn run v1.22.18
$ npm run build && wrangler publish
> build
> remix build
Building Remix app in production mode...
Built in 385ms
⛅️ wrangler 2.0.2
-------------------
Running …
```
> feat(templates): update Cloudflare templates to use `wrangler` v2

- contributors.yml
- integration/bug-report-test.ts
Closes: NA
I found this unnecessary `async` in the bug report template. There are some linting rules against this, like [no-async-without-await](https://palantir.github.io/tslint/rules/no-async-without-await/). If this is a team preference please feel free to close it :D.
> chore(bug-report-template): Remove unnecessary async

- .changeset/olive-pumpkins-kick.md
- contributors.yml
- packages/remix-react/__tests__/hook-types-test.tsx
- packages/remix-react/components.tsx
- packages/remix-react/package.json
- yarn.lock
Previously, objects with possibly undefined values became required. This PR makes it so they become optional instead, and preserves other behavior around undefined.
- Old: `{ a: number | undefined }` -> `{ a: number }`
- New: `{ a: number | undefined }` -> `{ a?: number }`
Added a new test to `packages/remix-react/__tests__/hook-types-test.tsx`, and ensured present type tests still pass.
> fix(remix-react): support undefined unions as optional keys in `UseDataFunctionReturn` type

- .changeset/silent-trains-build.md
- integration/esm-only-warning-test.ts
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
Closes: #
Added integration test that checks console output for warnings.
> Calm esm warnings

- .changeset/nervous-walls-sing.md
- packages/remix-react/components.tsx
> fix(@remix-run/react): preserve `null` properties for `useLoaderData` and `useActionData` inference

- .changeset/great-pumas-act.md
- contributors.yml
- packages/remix-netlify/server.ts
- packages/remix-server-runtime/data.ts
- packages/remix-server-runtime/routeModules.ts
- packages/remix-server-runtime/server.ts
this allows users to override the `context` with their own definitions using ambient modules.
as an example:
```js
declare module "remix" {
interface AppLoadContext {
graphql: <Result, Variables>(operation: {
query: TypedDocumentNode<Result, Variables>
variables: Variables
}) => Promise<ExecutionResult<Result>>
}
}
```
> types(remix-server-runtime): make `AppLoadContext` an empty interface instead of `any`

- packages/create-remix/tsconfig.json
- packages/remix-architect/tsconfig.json
- packages/remix-cloudflare-pages/tsconfig.json
- packages/remix-cloudflare-workers/tsconfig.json
- packages/remix-cloudflare/tsconfig.json
- packages/remix-dev/tsconfig.json
- packages/remix-express/tsconfig.json
- packages/remix-netlify/tsconfig.json
- packages/remix-node/tsconfig.json
- packages/remix-react/tsconfig.json
- packages/remix-serve/tsconfig.json
- packages/remix-server-runtime/tsconfig.json
- packages/remix-vercel/tsconfig.json
- packages/remix/tsconfig.json
This speeds up the build by telling TSC exactly what to check and what to skip reducing discovery time. It also is needed for our upgrade to react 18 otherwise types start loosing their s.
Closes: #
> chore: update tsconfigs to exclude node_modules and skip lib checks

- packages/remix-dev/cli/run.ts
Found an issue with the CLI when on the stack selection. The link includes ) in the link when clicking the link from the terminal. This resulted in a 404 page.
> chore(remix-dev/cli): fix broken stacks link

- examples/blog-tutorial/package.json
This shouldn't have been done in #3917, as that example is still using React v17
> chore(examples/blog-tutorial): revert update of `@testing-library/react` dependency

- .github/workflows/reusable-test.yml
- .github/workflows/stacks.yml
- integration/playwright.config.ts
- integration/upload-test.ts
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
- packages/remix-dev/__tests__/replace-remix-imports-test.ts
- packages/remix-dev/__tests__/setupAfterEnv.ts
this PR does the following:
- increase jest timeout on windows
- fixes a cache issue where we'd always use the latest playwright version as the cache key
- allows stacks + deployment tests to continue if one of them fails
- enable playwright test retries locally so we can check for flakey tests
- uses default workers based on machine config
- mark upload test as slow
- update playwright timeout on windows
- enable fullyParallel
Closes: #
CI and locally using Git Bash and PowerShell in windows terminal
> test: windows testing updates

- contributors.yml
- docs/tutorials/blog.md
mdn.io/request goes to https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
which isn't what we want.
mdn.io/Request goes to https://developer.mozilla.org/en-US/docs/Web/API/Request
which is what we actually want here.
mdn.io/request.formData and mdn.io/Request.formData both redirect to the same place,
but I updated this link to match the other fix.
> docs(tutorials/blog): fix links to MDN

- .changeset/slow-apples-pretend.md
- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/components.tsx
- packages/remix-react/transition.ts
chore: update RemixEntry to use new subscribe method
Closes: #
> chore(remix-react): add `subscribe` method to `transitionManager`

- .changeset/purple-ligers-drive.md
- integration/deterministic-build-output-test.ts
- packages/remix-dev/compiler/plugins/mdx.ts
This is a fix along the lines of #2027; because the MDX virtual modules resolve to absolute paths, the manifest/hashes/etc. differ based on the parent directory structure.
Refs: #2024
1. Expanded existing integration test to cover this scenario (fails without the fix). Also add other virtual module scenarios that weren't already covered
2. Validated in a real MDX Remix app that has split client / server builds (applied fix via patch-package)
> fix(remix-dev): make MDX builds deterministic

- integration/helpers/node-template/app/entry.client.tsx
- integration/helpers/node-template/app/entry.server.tsx
- packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/entry.client.tsx
- packages/remix-dev/__tests__/fixtures/replace-remix-imports/app/entry.server.tsx
- packages/remix-dev/__tests__/migrations/fixtures/indie-stack/app/entry.client.tsx
- packages/remix-dev/__tests__/migrations/fixtures/indie-stack/app/entry.server.tsx
This shouldn't have been done in #3917, as `package.json` is updated to React v18
> tests(remix-dev): update to React v18

- contributors.yml
- packages/remix-dev/cli/run.ts
Closes: #
I noticed from [blues-stack](https://github.com/remix-run/blues-stack/blob/f006c2f7d7cf546496240874b1dbf3f761b7f888/package.json#L13) that there is a `watch` option for the `remix` CLI, but it was not present in the `--help`, so I've added it.
> docs: add remix watch example to cli

- templates/arc/app/entry.client.tsx
- templates/arc/app/entry.server.tsx
- templates/arc/package.json
- templates/express/app/entry.client.tsx
- templates/express/app/entry.server.tsx
- templates/express/package.json
- templates/fly/app/entry.client.tsx
- templates/fly/app/entry.server.tsx
- templates/fly/package.json
- templates/netlify/app/entry.client.tsx
- templates/netlify/app/entry.server.tsx
- templates/netlify/package.json
- templates/remix/app/entry.client.tsx
- templates/remix/app/entry.server.tsx
- templates/remix/package.json
- templates/vercel/app/entry.client.tsx
- templates/vercel/app/entry.server.tsx
- templates/vercel/package.json
Follow-up of #3917 
I didn't update Cloudflare & Deno templates as those weren't updated in #3917 by @jacob-ebey as well (see https://github.com/remix-run/remix/pull/3917#issuecomment-1206331413 for more questions about the reasoning behind this)
> feat(templates): update to React v18

- contributors.yml
- integration/bug-report-test.ts
- integration/form-test.ts
- integration/hook-useSubmit-test.ts
- packages/remix-react/components.tsx
Closes:  (the following issue)
> Currently, remix-react's `<Form>` through `useSubmit` (`useSubmitImpl`) 
implementation, includes the submitter value by setting it on the
`formData`. Unfortunetly, this may override any existing inputs having the
same name than the submitter; resulting in data loss.
```jsx
<Form>
<input name="tasks" value="first" />
<button name="tasks value="" type="submit">Add Task</button>
</Form>
// should submit `?tasks=first&tasks=` but submit `?tasks=`
```
See integration [Bug-Report-Test](https://github.com/remix-run/remix/blob/41870303f049c1fd8b7eec6d14777e31b44587b6/integration/bug-report-test.ts) via commit: https://github.com/remix-run/remix/commit/41870303f049c1fd8b7eec6d14777e31b44587b6
---
**test: failing test with submitter value not …
> fix(remix-react): prevent form data loss by appending submitter's value in `useSubmit` (`<Form>`)

- contributors.yml
- packages/remix-react/components.tsx
When we visualize the html meta tags on a browswer inspector, I think it's better to see
```html
<meta name="twitter:card" content="summary">
```
than
```html
<meta content="summary" name="twitter:card">
```
Closes: #
> fix(remix-react): switch `name` & `content` position in `meta` tags

- contributors.yml
- examples/theme-ui/app/entry.client.tsx
- examples/theme-ui/app/root.tsx
- examples/theme-ui/app/routes/index.tsx
- examples/theme-ui/app/routes/jokes.tsx
We expect the [theme-ui example](https://github.com/remix-run/remix/tree/main/examples/theme-ui)'s pages to have a stark blue background, to demonstrate that the theme-ui theme is being applied.
Instead, it has no styling at all.
The cause is [this PR](https://github.com/remix-run/remix/pull/3664), which removes some lines which are fundamental to [how theme-ui works](https://theme-ui.com/getting-started#classic-jsx-runtime).
I have also removed 2 entries from a `useEffect` dependency array which were also added in the mentioned PR, which were causing repeated `Maximum update depth exceeded` to appear in the browser console. This does not seem to affect this example, but can cause UI hangs on apps with state.
I've been unsuccessful in running linting against this example, so I can't …
> chore(examples/theme-ui): fix styling

- .changeset/wild-meals-beg.md
- packages/remix-react/components.tsx
> feat(remix-react): unblock hydration via async module scripts

- .changeset/four-poets-stare.md
- packages/remix-dev/compiler/loaders.ts
- packages/remix-dev/modules.ts
Follow-up of https://github.com/remix-run/remix/pull/3190#discussion_r873095942
> feat(remix-dev): import `.gql` & `.graphql` files as text

- packages/remix-architect/binaryTypes.ts
- packages/remix-dev/compiler/loaders.ts
- packages/remix-dev/modules.ts
- packages/remix-netlify/binaryTypes.ts
While looking at #3771 I noticed that we were missing the avif file type declaration.
> feat(remix-dev): allow importing `.avif` files

- packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createExportExpressionStatementFromExportDefaultDeclaration.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createExportExpressionStatementFromExportNamedDeclaration.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createImportExpressionStatement.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationIdentifier.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationObjectPattern.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/index.ts
This will partially resolve https://github.com/remix-run/indie-stack/issues/134
> fix(remix-dev/cli/migrate): fix `convert-to-javascript` migration

- contributors.yml
- examples/infinite-scrolling/app/routes/offset/simple.tsx
- examples/infinite-scrolling/app/routes/page/simple.tsx
In order to prevent bugs related to scrolling with scroll bar use fetched items count instead of all available.
> Use fetched item count for simple examples

- .changeset/thirty-pots-lay.md
- contributors.yml
- packages/remix-server-runtime/data.ts
- packages/remix-server-runtime/routeModules.ts
- packages/remix-server-runtime/server.ts
Closes: #3988
My strategy for addressing this issue is to always pass an empty object for the context, rather than passing nothing (or undefined). Since we've already declared the AppLoadContext interface to be `{[key: string]: unknown}`, I feel like this would be a reasonable approach. 
I created an app in the playground and (manually had to) copy over the built remix-server-runtime directory into it. I then augmented the AppLoadContext interface with a property called `notes`. I then tried to access both a known and unknown property to make sure that typescript knew the difference.
```typescript
declare module '@remix-run/server-runtime' {
export interface AppLoadContext {
notes: string[]
}
}
export const loader: LoaderFunction = async ({ request, context }) => { …
```
> types(remix-server-runtime): make `context` mandatory in `DataFunctionArgs`

- .changeset/stupid-houses-sing.md
- docs/api/conventions.md
- packages/remix-server-runtime/routeModules.ts
Supercedes #928
See usage example in new jsdoc for `MetaFunction` or in the changeset
Testing Strategy: I tried out the example shown in the jsdoc locally
> feat: `MetaFunction` type infers `data` and `parentsData` types from loaders

- .github/workflows/release-test.yml
- .github/workflows/reusable-test.yml
- .github/workflows/test.yml
- integration/form-test.ts
- integration/playwright.config.ts
to limit testing to chrome or webkit you can use 
- `yarn test:integration --project=webkit`
- `yarn test:integration --project=chromium`
currently the only failing test is due to a bug in Safari, so i've added browser check for the bugged behavior https://github.com/remix-run/remix/pull/4049/files#diff-6ba8f3349b2b29f4668d3cdbcc4df75c8182edad8eaea07c5a6d7f227309acf7R794-R803
related: #4023 / #4024 
edit: looks like `@playwright/test@next` is shipping with webkit 16 👀 
Closes: #
> test: enable webkit testing for playwright

- contributors.yml
- templates/cloudflare-pages/package.json
- templates/cloudflare-pages/public/_routes.json
John here from the Cloudflare Pages team.
`_routes.json` is a new optional file from Cloudflare Pages. It describes how [Pages Functions](https://developers.cloudflare.com/pages/platform/functions/) are routed through the Cloudflare Workers runtime. Via inclusion and exclusion rules, we route traffic to your Pages Functions or to static assets.
_As noted in the [contributing doc](https://github.com/remix-run/remix/blob/main/docs/pages/contributing.md#setup), I've branched off of main instead of dev since this only changes a template._
> feat(templates/cloudflare-pages): add `_routes.json`

- decisions/0003-streaming-apis.md
Design doc for the upcoming `defer()` + `<Await>` APIs
[Preview link](https://github.com/remix-run/remix/blob/brophdawg11/deferred-design-doc/decisions/0003-streaming-apis.md)
[🔥 Preview link using github-md.com](https://github-md.com/remix-run/remix/blob/brophdawg11/deferred-design-doc/decisions/0003-streaming-apis.md)
> docs: First pass at defer API design doc

- .changeset/red-apples-stew.md
- packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createExportExpressionStatementFromExportDefaultDeclaration.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createImportExpressionStatement.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationIdentifier.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/createVariableDeclarationObjectPattern.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/transform/index.ts
Re-submission of #3987, now without the named exports conversion
> This will partially resolve https://github.com/remix-run/indie-stack/issues/134
@kentcdodds Once told me that he's more familiar with `babel`'s own codemod instead of using `jscodeshift`.
Don't know if it's preferred to continue with `jscodeshift` or if we should look into `babel` instead? 🤔
> fix(remix-dev/cli/migrate): process default exports in `convert-to-javascript` migration

- .changeset/late-jars-wonder.md
- integration/form-test.ts
- packages/remix-react/components.tsx
The recent work done in #3697 uncovered a previously unknown bug where we do not match default browser behavior.  By default, non-JS `<form method="get">` will replace any existing search parameters in the URL, but our behavior has been to append (without first resetting the params) since #814.  
Default browser behavior is shown in [this code sandbox](https://codesandbox.io/s/form-get-params-e26g6e).  You may have to open it in a new window and load it with some existing query params, and then submit the form.  I.e., https://e26g6e.sse.codesandbox.io/?junk=value
This new Remix behavior also has the side effect of no longer including the `?index` in the destination URL (even though it _is_ included in the form action).  This should have no impact since GET submissions run all relevant …
> fix(remix-react): GET form submissions should replace current search params

- packages/remix-server-runtime/server.ts
Use `some` vs. an explicit loop with an early return. This is a classic example of why `some` was added to the language. :)
> refactor(remix-server-runtime): simplify `isIndexRequestUrl`

- packages/remix-architect/__tests__/server-test.ts
- packages/remix-netlify/__tests__/server-test.ts
```
'AbortController' is defined but never used
```
> chore(remix-architect,remix-netlify): fix ESLint warnings

- contributors.yml
- docs/api/remix.md
Hey there! 👋
Micro adjustment to the `useFetchers` docs.
Appreciate all the stellar work on Remix!! 🙌
> docs(api/useFetchers): typo fix

- .changeset/lazy-lions-invent.md
- packages/remix-server-runtime/server.ts
Don’t lie to TypeScript or it will lie to you
> fix(remix-server-runtime): don't automatically cast `error` without check

- docs/guides/styling.md
Fix inconsistency with missing `app/` before `routes/`.
Note code examples on proceeding lines start with `app/`:
https://github.com/remix-run/remix/blob/dc417f6876620ce2fd23977145efd16f4fe02413/docs/guides/styling.md?plain=1#L91-L117
> docs(styling.md): fix filename path in code block

- contributors.yml
- examples/usematches-loader-data/README.md
This change fixes the link from Readme to the `useUser` file in the example project
> docs(examples/usematches): Fix incorrect link in README

- packages/remix-architect/__tests__/server-test.ts
- packages/remix-architect/server.ts
- packages/remix-express/server.ts
- packages/remix-netlify/__tests__/server-test.ts
- packages/remix-netlify/server.ts
- packages/remix-vercel/server.ts
Fix node 14 netlify/architect tests by leveraging the remix`@remix-run/node` `AbortController`.  Follow up to https://github.com/remix-run/remix/pull/3626.
> ci: Fix netlify/architect node 14 tests with AbortController polyfill

- contributors.yml
- docs/api/remix.md
Closes: #3789
Fixed the heading `unstable_parseMultipartFormData` overflowing its container due to its heading level.
> docs(api/remix): fix heading level (#3789)

- contributors.yml
- docs/tutorials/jokes.md
- Fix a typo.
- Fix the wrong highlighted lines for one codeblock.
> docs(tutorials/jokes): fix typo + code highlighting

- .changeset/seven-bears-listen.md
- packages/remix-node/stream.ts
> chore: flush node streams

- .changeset/sour-roses-heal.md
- integration/fetcher-test.ts
- packages/remix-react/components.tsx
Closes: #4221
* Integration tests in `fetcher-test`
> fix: preserve ?index for fetcher get submissions

- .changeset/hot-pugs-tie.md
- packages/remix-react/package.json
- yarn.lock
should have been removed when serialize type helpers were moved into server-runtime pkg
> fix(@remix-run/react): remove unused `type-fest` dependency

- packages/remix-server-runtime/serialize.ts
to remove dependency on `type-fest` since we are planning to replace `Merge` with `&` anyway
> fix(@remix-run/server-runtime): inline `Merge` type utility from `type-fest`

- contributors.yml
- docs/api/remix.md
Assuming the code block [here](https://remix.run/docs/en/v1/api/remix#createsessionstorage) is accurate, this fixes the reference in the note, as `readData` does not take an `expires` arg, but `createData` does! :)
> docs(api/remix): fix typo

- .gitignore
- integration/tsconfig.json
- packages/create-remix/tsconfig.json
- packages/remix-architect/tsconfig.json
- packages/remix-cloudflare-pages/tsconfig.json
- packages/remix-cloudflare-workers/tsconfig.json
- packages/remix-cloudflare/tsconfig.json
- packages/remix-dev/tsconfig.json
- packages/remix-express/tsconfig.json
- packages/remix-netlify/tsconfig.json
- packages/remix-node/tsconfig.json
- packages/remix-react/tsconfig.json
- packages/remix-serve/tsconfig.json
- packages/remix-server-runtime/tsconfig.json
- packages/remix-vercel/tsconfig.json
- packages/remix/tsconfig.json
- tsconfig.json
Speeds up build a bit by allowing tsc to quickly find references: https://www.typescriptlang.org/docs/handbook/project-references.html#composite
Allows projects to build in more isolation and avoids wired x-project types to leak. For example I have a PR open right now that does not recognize `headers.entries()` as a method in the server-runtime, but with these changes it works fine.
Closes: #
> chore: update tsconfigs to use composite

- .github/workflows/format.yml
Just like we do in https://github.com/remix-run/examples
https://github.com/remix-run/examples/blob/8c122f535a345c35400e06b77de0628b53342200/.github/workflows/format.yml#L42-L43
> ci: use GitHub Actions account to commit format changes

- packages/remix-react/components.tsx
Fixes a regression where the manifest was not preloaded. This is omre of an issue now than before as we now dynamically import the manifest to avoid race contitions of async script tags
Closes: #
> fix: preload manifest

- templates/arc/app/entry.client.tsx
- templates/arc/app/entry.server.tsx
- templates/express/app/entry.client.tsx
- templates/express/app/entry.server.tsx
- templates/express/package.json
- templates/fly/app/entry.client.tsx
- templates/fly/app/entry.server.tsx
- templates/fly/package.json
- templates/netlify/app/entry.client.tsx
- templates/netlify/app/entry.server.tsx
- templates/remix/app/entry.client.tsx
- templates/remix/app/entry.server.tsx
- templates/remix/package.json
- templates/vercel/app/entry.client.tsx
- templates/vercel/app/entry.server.tsx
Mainly includes https://github.com/remix-run/indie-stack/commit/e8d39cf00d92d2d16abab93025e4b4e47f8c808c, https://github.com/remix-run/indie-stack/commit/a1a1c05dcc2612e20fe35bdff2567df82719b85b & https://github.com/remix-run/indie-stack/pull/125
> feat(templates): bring React 18 templates in line with `indie-stack` updates

- .changeset/tame-hotels-attack.md
- contributors.yml
- docs/other-api/dev.md
- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/cli/create.ts
Closes: #4328
My main mode of testing was to try this out against a private repo with a stack tarball by running these three permutations:
```sh
npx create-remix ./my-project --template https://github.com/<owner>/<repo>/releases/download/v.1.1/stack.tar.gz --token <my-token>
npx create-remix ./my-project --template https://github.com/<owner>/<repo>/releases/download/<version>/stack.tar.gz --token <my-token>
npx create-remix ./my-project --template https://github.com/<owner>/<repo>/releases/download/<bad version>/stack.tar.gz --token <my-token>
yarn test
```
I attempted unsuccessfully to unit test this, but without spending much more time mocking out github api calls, I wasn't able to write anything worthwhile... happy to revisit if you disagree! I also cleaned up a …
> fix(create-remix): Allow private GitHub repos to use the latest release url for tarballs

- packages/remix-server-runtime/__tests__/.eslintrc
- packages/remix-server-runtime/__tests__/.eslintrc.js
- templates/arc/.eslintrc
- templates/arc/.eslintrc.js
- templates/cloudflare-pages/.eslintrc
- templates/cloudflare-pages/.eslintrc.js
- templates/cloudflare-workers/.eslintrc
- templates/cloudflare-workers/.eslintrc.js
- templates/express/.eslintrc
- templates/express/.eslintrc.js
- templates/fly/.eslintrc
- templates/fly/.eslintrc.js
- templates/netlify/.eslintrc
- templates/netlify/.eslintrc.js
- templates/remix/.eslintrc
- templates/remix/.eslintrc.js
- templates/vercel/.eslintrc
- templates/vercel/.eslintrc.js
ESLint has a new flat config feature (which is going to be the default in v9 or v10), which [requires a JS config file](https://eslint.org/blog/2022/08/new-config-system-part-2/#the-new-config-file%3A-eslint.config.js)
https://eslint.org/blog/2022/08/new-config-system-part-1
https://eslint.org/blog/2022/08/new-config-system-part-2
https://eslint.org/blog/2022/08/new-config-system-part-3
> chore(templates): convert all `.eslintrc` files to JS

- .github/workflows/reusable-test.yml
- integration/abort-signal-test.ts
- integration/action-test.ts
- integration/helpers/cleanup.mjs
- integration/playwright.config.ts
- package.json
an alternate approach to this is conditionally setting projects in `integration/playwright.config.ts`, but you lose out on quickly knowing which browser/os failed in the GitHub Actions UI
Closes: #
> ci: run integration tests on appropriate platforms

- .changeset/stupid-games-build.md
- integration/abort-signal-test.ts
- integration/form-test.ts
- packages/remix-react/transition.ts
- packages/remix-server-runtime/server.ts
Same fix as https://github.com/remix-run/react-router/pull/9455 in react router
If you have a route tree of:
```jsx
<Route path="parent" action={...} element={<Parent />}>
<Route element={<Pathless />}>
<Route index element={<Index />} />
</Route>
</Route>
```
And a `<Form method="post">` in `<Parent />` submits, then it should ignore the pathless layout route in the middle and walk upwards to the last path-contributing matches action.
Closes: #2498
Testing Strategy: Added integration tests
> fix: Ignore pathless layout routes when matching actions

- packages/remix-node/globals.ts
Make sure AbortController is installed globally for node version less than 15.
Closes: #
Existing deployment tests will validate the change.
> chore: ensure AbortController installed globally

- .changeset/witty-kiwis-flow.md
- contributors.yml
- packages/remix-react/components.tsx
**Closes Issue #**: no official issue that I can find, but Kent mentioned in Discord that this would be a good contribution opportunity: https://discord.com/channels/770287896669978684/770287896669978687/1032333166402351154
This PR adds support for inferring the type of the `.data` property of `useFetcher` from loader and action functions, similarly to how you can write `useLoaderData<typeof loader>`.  e.g. you can now write `useFetcher<typeof action>`, and `fetcher.data` will be inferred correctly.  Previously, you had to write `useFetcher<SerializeFrom<typeof action>>`.
**Docs**:
How should this change best be documented?  I struggled to find documentation for the matching changes to `useActionData` and `useLoaderData` outside of the changelog and the `decisions` documentation. …
> feat(remix-react): add `typeof action` inference to `useFetcher`

- .changeset/stale-spoons-tie.md
- integration/conventional-routes-test.ts
- packages/remix-dev/config/routesConvention.ts
This is a drastically simpler approach to fix #3014 than the one I originally proposed in #3986, since it turns out `index` routes with `path`'s _are_ valid in react-router's matching algorithm (see https://github.com/remix-run/react-router/pull/8151).  They effectively serve as a shorthand to avoid adding the nested `index` under the `path` route.
Therefore, it turns out that the underlying issue here was just the inadvertent trailing slash generated by `defineConventionalRoutes`.
For the following `routes/` folder:
```
routes/
nested/
__pathless/
foo.jsx
__pathless.jsx
index.jsx
```
We were generating a route tree of:
```jsx
<Routes>
<Route file="root.jsx">
<Route path="nested/" file="routes/nested/__pathless.jsx">
<Route path="foo" file="routes/nested/__pathless/foo.jsx" />
</Route> …
```
> fix: avoid collisions on pathless routes with indices

- decisions/0006-linear-workflow.md
Initial decision doc for linear workflow
[Preview link](https://github.com/remix-run/remix/blob/brophdawg11/linear-decision-doc/decisions/0006-linear-workflow.md)
> docs: add linear workflow decision doc

- integration/form-test.ts
- integration/helpers/playwright-fixture.ts
Expand test coverage around forms:
* Rework all form tests to run both with and without JavaScript. This way we can better detect/prevent regressions or inconsistencies between how `<form>` and `<Form>` work.
* Dedup and expand form method tests to ensure we cover all supported Form `method`s and submitter `formMethod`s
* Expand coverage around form serialization (tree order, image submit buttons, files in URL-encoded payloads)
* Conditionally mark tests as failing (via [`test.fail`](https://playwright.dev/docs/api/class-test#test-fail-1)):
* Non-get/post `<Form>` methods with JavaScript disabled (#4420)
* Form serialization problems with JavaScript enabled (#4342)
References: #4342
> test: expand test coverage around forms

- .changeset/khaki-hornets-destroy.md
- integration/meta-test.ts
- packages/remix-react/components.tsx
`meta` misses a few cases when checking for OG meta, rendering `<meta name>` instead of `<meta property>` for those tags. This PR fixes that.
I also added semi-related tests for nested route cases just to make the `meta` tests cover a bit more ground.
> Fix attributes for namespaced Open Graph and Facebook meta tags

- packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
- packages/remix-dev/__tests__/replace-remix-imports-test.ts
- packages/remix-dev/cli.ts
- packages/remix-dev/cli/error.ts
- packages/remix-dev/cli/migrate/jscodeshift.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/index.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/resolveTransformOptions.ts
- packages/remix-dev/index.ts
Rather than `process.exit(1)`, throw an error so we don't kill the jest worker. Also increase the timeout for two tests that often go more than 10 seconds (especially on Windows). The CLI entrypoint already exits appropriately if there's an error, it just needs a little tweak to better handle "expected" errors.
Because these tests are slow (running yarn, etc.), they would often time out while jscodeshift was still running, causing the afterEach callbacks to delete things underneath it and transforms to fail. `failOnError: true` would then cause jscodeshift to call `process.exit(1)`, which would then kill the current process (the jest worker). Depending on the exact timing, you'd see one or more of the following in the test output:
* A bunch of lines like:
```
ERR …
```
> chore(remix-dev): fix flaky tests, make CLI more testable

- integration/helpers/cleanup.mjs
Running `rimraf` after integration tests is really slow. Executing a shell command to remove the temporary directory instead is significantly faster, and I don't believe it should be an issue for this case (though if there's anything I'm missing here, particularly on the Windows side, someone feel free to push back).
> tests(integration): replace `rimraf` in cleanup

- contributors.yml
- docs/pages/technical-explanation.md
Fix typos in the Technical Explanation documentation.
> docs(technical-explanation): fix typos

- .github/workflows/nightly.yml
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands
Closes: #
> ci(nightly): update output command

- integration/form-test.ts
- integration/transition-test.ts
@kentcdodds switched to `intent` in his learning materials now, as this reduces overloading of the term `action`
> chore(tests): use `intent` instead of `action`

- docs/pages/faq.md
@kentcdodds switched to `intent` in his learning materials now, as this reduces overloading of the term `action`
> docs: use `intent` instead of `action` or hidden input

- .github/workflows/format.yml
we have branch protection on for the dev branch which requires all changes to be made through a PR, this changes the commit to be made from the `remix-run-bot` account which is allowed. 
Reverts remix-run/remix#4285
> Revert "ci: use GitHub Actions account to commit format changes"

- integration/error-boundary-test.ts
- integration/error-data-request-test.ts
- integration/transition-test.ts
- packages/remix-server-runtime/__tests__/server-test.ts
- packages/remix-server-runtime/server.ts
chore: update tests to handle no assert flow
Closes: #
> chore: remove assert flow

- .changeset/curvy-countries-boil.md
- packages/remix-react/components.tsx
Closes: #
I was testing my app with an iPhone 6, and found out the client side was totally broken.
We had a [discussion](https://github.com/remix-run/remix/discussions/3240#discussioncomment-4086437) with @sergiodxa a few days ago where we uncovered that we re-introduced a nullish coalescing operator `??` in https://github.com/remix-run/remix/pull/3697 that could be problematic for old browsers.
I can now confirm that it is indeed problematic. 🙃 
This PR gets rid of it.
> fix(remix-react): Remove nullish coalescing operator

- docs/pages/contributing.md
- Examples are not in this repo anymore.
- Fixed a couple of typos
- Fixed the contributors.yaml file url
> docs(pages/contributing): Fix typos

- packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/tsconfig.json
For the reasons mentioned in https://github.com/remix-run/remix/pull/4572#discussion_r1022007355
> test(remix-dev): bring `replace-remix-magic-imports` fixture in line with template

- .changeset/beige-planes-type.md
- packages/remix-server-runtime/__tests__/data-test.ts
- packages/remix-server-runtime/data.ts
- packages/remix-server-runtime/headers.ts
- packages/remix-server-runtime/responses.ts
- packages/remix-server-runtime/server.ts
[decision doc](https://github-md.com/remix-run/remix/blob/dev/decisions/0007-remix-on-react-router-6-4-0.md#decision)
Step 2 in layering Remix back on top of React Router now that we have released `@remix-run/router`.
Changes:
- Deploy `@remix-run/server-runtime` on-top of a local copy of `@remix-run/router`.
Closes: #
Assert that existing tests pass and manually check new code is not in non-experimental production builds.
> feat(remix-server-runtime): RRR 2 - Deploy `@remix-run/server-runtime` changes

- integration/playwright.config.ts
This will prevent tests from running multiple times locally when failing. This makes error stack traces easier to follow and reduces overall output noise in the terminal (plus it's just unnecessary for local dev).
> chore(tests): Only retry on failed tests in CI

- contributors.yml
- docs/guides/data-writes.md
> docs(guides/data-writes): Fix a couple typos

- .changeset/khaki-meals-prove.md
- rollup.utils.js
I wanted to re-submit #2735 again, as:
- The first release supporting separate packages was `1.3.3`, which was released on 23 Mar 2022
https://github.com/remix-run/remix/releases/tag/v1.3.3
- The `replace-remix-imports` migration was added in `1.4.0`, which was released on 14 Apr 2022
https://github.com/remix-run/remix/releases/tag/v1.4.0
- We now export functions/types that aren't available anymore through the `remix` package, as they're not included in the `magicExports` anymore (see both `@remix-run/cloudflare` & `@remix-run/node`) since `1.5.0`
- We now have a runtime package (`@remix-run/deno`) that doesn't have *any* magic exports *at all* since `1.5.0`
https://github.com/remix-run/remix/releases/tag/v1.5.0
- Our ESLint config is warning with a deprecated message when importing from …
> feat: deprecate all functions & types exported from `magicExports`

- .github/workflows/postrelease.yml
The workflow apparently never ran: https://github.com/remix-run/remix/actions/workflows/postrelease.yml
Found that we had a small bug: https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-only-when-a-push-of-specific-tags-occurs
> chore: fix `postrelease` workflow

- .changeset/itchy-paws-remain.md
- packages/remix-dev/cli/commands.ts
Fixes `remix dev` in `1.8.0-pre.0`
To reproduce:
```sh
> npx create-remix@1.8.0-pre.0
> cd my-remix-app/
> npm run dev
```
> fix: add missing return to Fix remix dev command

- .changeset/early-camels-guess.md
- packages/remix-react/components.tsx
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-server-runtime/routeMatching.ts
- packages/remix-server-runtime/routeModules.ts
- yarn.lock
* Remove the `react-router-dom` dependency from `@remix-run/server-runtime` since it can pull everything from `./router` now
* Upgrade `@remix-run/react` to use `react-router-dom@~6.4.3`.  Went with a `~` here so we inherit bug fixes automatically but have to manually perform minor version upgrades so we have a chance to ensure full compatibility
Note this is not using `StaticRouterProvider`/`RouterRrovider` yet, still using the old approach (direct `Router` usage), just from the latest deployed version.
> Bump remix to react-router-dom@6.4.3

- contributors.yml
- integration/redirects-test.ts
- packages/remix-server-runtime/router/utils.ts
Cherry-picked the integration test from https://github.com/remix-run/remix/pull/4579
> fix: Integration test for external redirects

- packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
- packages/remix-dev/cli/migrate/migrations/convert-to-javascript/index.ts
first off, shout out to the lovely discord folks for uncovering this one https://canary.discord.com/channels/770287896669978684/1046094365426208818/1046094365426208818
fast-glob requires unix style paths
Closes: #
> fix(remix-dev): convert `config.appDirectory` to relative unix path

- .changeset/clean-clocks-float.md
- .github/workflows/reusable-test.yml
- .vscode/deno_resolve_npm_imports.json
- packages/remix-deno/server.ts
- scripts/build.mjs
Currently no typechecking is performed on the `remix-deno` package, because `tsc` cannot handle `.ts` file extension imports. This PR adds support for typechecking using the `deno check` command. 
Closes: #
Run `yarn build --deno`
> ci: add typechecking for deno

- docs/api/conventions.md
- docs/api/remix.md
- docs/guides/api-routes.md
- docs/guides/bff.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/guides/envvars.md
- docs/guides/mdx.md
- docs/guides/not-found.md
- docs/guides/optimistic-ui.md
- docs/guides/resource-routes.md
- docs/guides/routing.md
- docs/guides/styling.md
- docs/other-api/serve.md
- docs/pages/faq.md
- docs/pages/philosophy.md
- docs/pages/technical-explanation.md
- docs/tutorials/blog.md
- docs/tutorials/jokes.md
See https://github.com/remix-run/remix/releases/tag/remix@1.6.5
---
Closes #4110
Closes #4115
Closes #4609
Just like I did in https://github.com/remix-run/examples/pull/82, https://github.com/remix-run/examples/pull/83, https://github.com/remix-run/examples/pull/84 & https://github.com/remix-run/examples/pull/85
> docs: fix `useActionData`/`useLoaderData` usage

- .changeset/thin-oranges-boil.md
- packages/remix-react/components.tsx
Firefox infinitely reloads the page as long as `<LiveReload>` is rendering.
Closes #4692
> fix: Firefox LiveReload

- contributors.yml
- docs/tutorials/blog.md
Very small and simple docs edit (fixing a typo in the blog tutorial). Looks like the "new type for the error object" mentioned on this line was removed from the code snippet in the following commit ~8 months ago: https://github.com/remix-run/remix/commit/28ef6426861e6f6b670b6bd654272726b3c5c936
This PR will remove the mention of said missing code snippet.
> docs(tutorials/blog): Don't mention removed errors typecheck

- package.json
- yarn.lock
GitHub bumped `ubuntu@latest` to 22.04 - https://github.blog/changelog/2022-11-09-github-actions-ubuntu-latest-workflows-will-use-ubuntu-22-04/
which broke playwright `< 1.23`
example: https://github.com/remix-run/remix/actions/runs/3603174194/jobs/6071045976
which they fixed here: https://github.com/microsoft/playwright/issues/13738
Closes: #
> chore: bump @playwright/test to latest

- .changeset/light-sheep-give.md
- contributors.yml
- packages/remix-server-runtime/__tests__/responses-test.ts
- packages/remix-server-runtime/responses.ts
Closes: #4199: TypedResponse allows incompatible types
NOTE: I believe there's a _small_ chance this can be a breaking change for some people who may have been counting on the previous TypedResponse behavior. To be more explicit, something like this would fail now, as the actual return type is different than the declared return type (which was not enforced prior to this patch):
```typescript
export const action = async (args: ActionArgs): Promise<TypedResponse<string>> => {
return json(42);
};
```
This should have been the desired behavior though, and would be a benefit as users would either have to update their method declarations or fix their code as we're uncovering errors that were previously hidden.
[Playground link demonstrating the …
> Fix 4199: TypedResponse allows incompatible types

- packages/remix-testing/package.json
Without this, an older version (`1.7.6`) of `@remix-run/node`, `@remix-run/react` & `@remix-run/server-runtime` would be added to `yarn.lock` when running `yarn install`
> chore(remix-testing): update dependencies

- packages/remix-server-runtime/index.ts
- packages/remix-testing/create-remix-stub.tsx
- packages/remix-testing/package.json
The feature branch for the `remix-testing` got a bit stale once we released 1.8.0 and deleted the dup router code
> fix(remix-testing): fix deps

- docs/other-api/react-router.md
Fixes the broken URLs in [React Router v6 api page](https://remix.run/docs/en/v1/other-api/react-router) while I was reading the documentation. I assume those are the correct links, but pls correct me if I'm wrong.
> docs(other-api/react-router): fix `react-router` links

- .changeset/blue-tigers-look.md
- packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
- packages/remix-dev/server-build.ts
This should fix https://github.com/remix-run/remix/issues/4766. Unrelated to https://github.com/remix-run/remix/issues/4759.
Changeset will be added to the release branch @brophdawg11 started. Aiming to cut a hotfix shortly.
> fix(types): Add missing type def for `future` value in `@remix-run/dev/server-build`

- .github/workflows/reusable-test.yml
- .github/workflows/test.yml
- package.json
- packages/remix-server-runtime/rollup.config.js
- yarn.lock
Removes the no-longer used `ENABLE_REMIX_ROUTER` flag
> Remove ENABLE_REMIX_ROUTER flags

- .changeset/rare-bikes-report.md
- integration/loader-test.ts
- packages/remix-server-runtime/package.json
- packages/remix-server-runtime/server.ts
- yarn.lock
Fixes https://github.com/remix-run/remix/issues/4741 by using `isResponse` instead of `instanceof Response`
Note: integration tests will fail until we get `@remix-run/server-runtime` onto the latest `@remix-run/router`
> Remove instanceof Response checks in favor of isResponse

- .changeset/early-camels-guess.md
- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/browser.tsx
- packages/remix-react/components.tsx
- packages/remix-react/errorBoundaries.tsx
- packages/remix-react/links.ts
- packages/remix-react/package.json
- packages/remix-react/routeMatching.ts
- packages/remix-react/routeModules.ts
- packages/remix-react/server.tsx
- packages/remix-react/transition.ts
- packages/remix-server-runtime/package.json
- packages/remix-server-runtime/routeMatching.ts
- packages/remix-server-runtime/routeModules.ts
- yarn.lock
This upgrades Remix to use the latest `react-router-dom@6.4.4` release for rendering _without yet using the new `RouterProvider`_.  This still renders with `StaticRouter` on the server and and a raw `Router` on the client.  The difference is that we're now using the new `createBrowserHistory` + `v5Compat` flag from `@remix-run/router` and we drop the `history@5` dependency.
Subsequent releases will switch from `StaticRouter`/`createBrowserHistory`/`Router` to `StaticRouterProvider`/`createBrowserRouter`/`RouterProvider`
> refactor(remix-react): upgrade Remix to `react-router-dom@6.4` (non-data-router) and drop `history`

- .github/workflows/nightly.yml
when adding deno typechecking (#4715), `nightly` now refers to the version we just calculated which hasnt been published when trying to build and typecheck https://github.com/remix-run/remix/actions/runs/3636615016/jobs/6136755201
Closes: #
> ci(nightly): move git operations after build

- contributors.yml
- packages/remix-dev/__tests__/routesConvention-test.ts
- packages/remix-dev/config/routesConvention.ts
Closes: #4480. `defineConventionalRoutes` was repeatedly running `.filter` and `.find` against the list of routeIds to find parents, which was causing an exponential slowdown in larger projects. This update first generates a `parentRouteIds` object and then filters against that instead.
Testing Strategy: There weren't any direct tests for `defineConventionalRoutes` as far as I could tell, so I added one to make sure the necessary number of routes (including parent route ids) are generated. I used an existing fixture for the routes folders (`remix-dev/__tests__/fixtures/replace-remix-imports`) but I can add one specific to the `routesConventions` tests if you prefer this test remain uncoupled from the replace imports test.
I ran this against my production app with nearly 700 routes and the …
> perf(remix-dev): Optimize `parentRouteId` lookup in `defineConventionalRoutes`

- .changeset/metal-impalas-brake.md
> chore(dev): add changeset for PR #4538

- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/routes.tsx
Follow-up of https://github.com/remix-run/remix/pull/4731
> refactor(remix-react): use `react-router-dom` import instead of `react-router`

- integration/fetcher-state-test.ts
- integration/transition-state-test.ts
- packages/remix-react/package.json
- yarn.lock
Added fine-grained tests around `fetcher.type` that we can use to ensure we get the "Remix on Router 6.4" back-compat layer implemented correctly
> Add fetcher state/type tests

- .changeset/fresh-shrimps-join.md
- packages/remix-dev/compiler/compileBrowser.ts
- packages/remix-dev/package.json
- scripts/release/package-lock.json
- scripts/release/package.json
- yarn.lock
> chore(deps): bump esbuild to latest

- integration/abort-signal-test.ts
- integration/action-test.ts
- integration/bug-report-test.ts
- integration/catch-boundary-data-test.ts
- integration/catch-boundary-test.ts
- integration/compiler-test.ts
- integration/error-boundary-test.ts
- integration/error-data-request-test.ts
- integration/fetcher-layout-test.ts
- integration/fetcher-test.ts
- integration/file-uploads-test.ts
- integration/form-test.ts
- integration/helpers/create-fixture.ts
- integration/hook-useSubmit-test.ts
- integration/js-routes-test.ts
- integration/layout-route-test.ts
- integration/link-test.ts
- integration/loader-test.ts
- integration/mdx-test.ts
- integration/meta-test.ts
- integration/multiple-cookies-test.ts
- integration/prefetch-test.ts
- integration/redirects-test.ts
- integration/rendering-test.ts
- integration/resource-routes-test.ts
- integration/server-code-in-browser-message-test.ts
- integration/set-cookie-revalidation-test.ts
- integration/transition-state-test.ts
- integration/transition-test.ts
- integration/upload-test.ts
- [chore: normalize afterAll](https://github.com/remix-run/remix/pull/4785/commits/d70a7dc813fabac2980140de10ab829f8bcb2acc)
- [test: close server synchronously](https://github.com/remix-run/remix/pull/4785/commits/b3f50205508151f5a0a611650b1b4e361236c969)
closing asynchronously would intermittently result in the `test.afterAll` hook to timeout
Closes: #
> test(integration): close server synchronously 

- .changeset/moody-pants-own.md
...to make it clear that Remix won't support optional segments until integrated with React Router 6.5
> chore: edit the optional segments changeset

- contributors.yml
- docs/file-conventions/remix-config.md
* Update code example to reflect that watchPaths can be a string, array, or async function
* Clarify that watchPaths directories are relative to the project root
Updated from #4578 after documentation was moved, and closes [#4530](https://github.com/remix-run/remix/issues/4530).
> docs(file-conventions/remix-config): update `watchPaths`' description

- .changeset/mighty-grapes-laugh.md
- .changeset/sharp-paws-nail.md
- integration/catch-boundary-test.ts
- integration/request-test.ts
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- yarn.lock
Adds additional tests to the bug report in #4826.  I went back and made sure all these tests pass on `1.7.6` and then with the sibling PR in `react-router` they all pass on 1.8.x Remix now as well.
_Note: CI will fail until we release RR and update `server-runtime`'s `package.json` in this branch_
React Router PR: https://github.com/remix-run/react-router/pull/9721
Can test via:
* Check out this branch in remix
* Check out the corresponding branch in react-router
* In `react-router`, 
* `LOCAL_BUILD_DIRECTORY=../remix yarn build`
* Assumes your `remix` and `react-router` repo clones are sibling directories
* In `remix`:
* `yarn test:integration request-test --project chromium` 
Also, since this PR will update the `@remix-run/router` dependency I also added an integration tests for …
> Add integration tests for request structures

- .changeset/mighty-rules-drum.md
- packages/remix-dev/compiler/compileBrowser.ts
- packages/remix-dev/compiler/compilerServer.ts
- packages/remix-dev/compiler/plugins/cssFilePlugin.ts
> fix(remix-dev): resolve asset entry full path to support mono-repo import of styles

- contributors.yml
- docs/route/handle.md
I noticed a minor issue while reading the docs for `handle`.
> docs(route/handle): fix typo

- contributors.yml
- templates/cloudflare-pages/package.json
`NODE_ENV` in `start` script was set to `development` instead of `production` because `dev:wrangler` script overwrites `NODE_ENV` with `development`.
```
$ cd ~/path/to/remix-run/remix
$ yarn install
$ yarn build
$ node ./build/node_modules/create-remix/cli.js --template ./templates/cloudflare-pages my-app
$ cd my-app
$ echo 'console.log("NODE_ENV:", process.env.NODE_ENV);' >> ./node_modules/.bin/wrangler
$ npm run start | grep NODE_ENV:
NODE_ENV: production
```
> fix(templates/cloudflare-pages): fix start script

- .changeset/many-zebras-arrive.md
- packages/remix-dev/cli/migrate/migrations/transforms.ts
- packages/remix-dev/rollup.config.js
> fix(dev): build modules for ts->js conversion

- package.json
- scripts/remove-prerelease-changelogs.mjs
- scripts/unist.d.ts
- yarn.lock
This creates a script that can be used after existing Changesets' pre-release mode to remove all of the generated pre-release changelogs.
> chore: Add script to remove pre-release notes from changelogs

- contributors.yml
- docs/route/headers.md
`handledatarequest` link was a 404 as it has a the trailing `.tsx` on the URL
> docs(route/headers): Fix incorrect link on headers

- integration/error-boundary-test.ts
- integration/fetcher-layout-test.ts
- integration/file-uploads-test.ts
- integration/upload-test.ts
Fix some flakey tests in the `feat/rrr-rendering` branch before merging to `dev`
> Fix flakey firefox tests

- packages/remix-dev/codemod/index.ts
- packages/remix-dev/codemod/replace-remix-magic-imports/transform.ts
- packages/remix-dev/codemod/replace-remix-magic-imports/utils/detect.ts
- packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
- packages/remix-dev/codemod/replace-remix-magic-imports/utils/postinstall.ts
- packages/remix-dev/compiler/build.ts
- packages/remix-dev/compiler/compileBrowser.ts
- packages/remix-dev/compiler/compilerServer.ts
- packages/remix-dev/compiler/plugins/cssFilePlugin.ts
- packages/remix-dev/compiler/remixCompiler.ts
- packages/remix-dev/compiler/watch.ts
This way we use type imports consistently throughout the codebase
> refactor: use type imports instead of type modifiers

- .changeset/silver-ducks-protect.md
- packages/remix-react/index.tsx
- packages/remix-testing/create-remix-stub.tsx
- packages/remix-testing/package.json
- yarn.lock
supersedes #4899 
Closes: #
Testing Strategy: https://github.com/mcansh/stubbbbbs
> chore(remix-testing): utilize react-router 6.5+

- docs/route/index.md
The link on https://remix.run/docs/en/v1/route to `Route Module Constraints` 404s, as it goes to
```
https://remix.run/docs/en/guides/constraints
```
instead of 
```
https://remix.run/docs/en/v1/guides/constraints
```
`Route Modules API` is the only nav section with a linked index page; seems like even though the index is literally a directory deeper, it's not being treated that way. 🤷
> docs(route/index): fix broken link

- contributors.yml
- docs/tutorials/jokes.md
Added markdown link shortcut for the scripts component and changed the Javascript sections `scripts` component link to use said shortcut.
> docs(tutorials/jokes): Fix link to the scripts component

- .github/workflows/nightly.yml
TODO: cherry pick merged commit to dev
changed to check against changes to dev here https://github.com/remix-run/remix/pull/4072/files#diff-0d5658b415099a82c11c03a06ca4ec765b4003a1f4b2f3f1943980a882cf8aa6, but that causes a new nightly every day as we dont ever compare against the previous nightly 😅
closes #4965
Closes: #
> ci(nightly): revert to comparing sha instead of checking for changes against dev

- .changeset/modern-pumas-hide.md
- packages/remix-architect/package.json
- packages/remix-architect/sessions/arcTableSessionStorage.ts
- yarn.lock
As of @architect/functions@5.2.0, types are included in the package itself and there is no longer a need for
@types/architect__functions.
> refactor(remix-architect): use `@architect/functions`' built-in types

- integration/helpers/node-template/app/entry.client.tsx
- scripts/playground/template/app/entry.client.tsx
- templates/arc/app/entry.client.tsx
- templates/cloudflare-pages/app/entry.client.tsx
- templates/cloudflare-workers/app/entry.client.tsx
- templates/deno/app/entry.client.tsx
- templates/express/app/entry.client.tsx
- templates/fly/app/entry.client.tsx
- templates/netlify/app/entry.client.tsx
- templates/remix/app/entry.client.tsx
- templates/vercel/app/entry.client.tsx
This fixes the problem we have on `main` in `templates/deno` + it also complies with our gotcha
- https://github.com/remix-run/remix/actions/runs/3834895046/jobs/6527706087#step:8:11
- https://lint.deno.land/#no-window-prefix
- https://remix.run/docs/en/v1/pages/gotchas#typeof-window-checks
---
Tagging @kentcdodds as he implemented this initially in our stacks, so maybe there was a reason to call these methods on `window` instead of using the global ones
> templates: don't use `window` in `entry.client.tsx`

- .changeset/cool-crews-kneel.md
- packages/remix-react/data.ts
> fix(remix-react): fix `content-type` on proxied action request

- integration/helpers/node-template/app/entry.client.tsx
- scripts/playground/template/app/entry.client.tsx
- templates/arc/app/entry.client.tsx
- templates/cloudflare-pages/app/entry.client.tsx
- templates/cloudflare-workers/app/entry.client.tsx
- templates/deno/app/entry.client.tsx
- templates/express/app/entry.client.tsx
- templates/fly/app/entry.client.tsx
- templates/netlify/app/entry.client.tsx
- templates/remix/app/entry.client.tsx
- templates/vercel/app/entry.client.tsx
safari doesn't have `requestIdleCallback` thus logging errors to the console
```log
Unhandled Promise Rejection: ReferenceError: Can't find variable: requestIdleCallback
(anonymous function)
rejectPromise
promiseReactionJob
```
Closes: #
> chore(templates): use typeof check for `requestIdleCallback`

- .changeset/curvy-mangos-heal.md
- packages/remix-dev/config/flat-routes.ts
> chore(remix-dev): update flat-routes invalid character error message to include link to RR proposal

- .changeset/little-lobsters-decide.md
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
> chore(remix-dev): don't allow `*` to be anywhere in segment

- .changeset/eighty-hounds-mix.md
- integration/error-boundary-test.ts
- package.json
- packages/remix-react/browser.tsx
- packages/remix-react/package.json
- packages/remix-react/server.tsx
- packages/remix-server-runtime/server.ts
- yarn.lock
Needed to add back in a global `RemixErrorBoundary` wrapper around the full application in case the root route threw from it's own boundary.
> Add outer RemixErrorBoundary to catch root boundary-thrown errors

- .changeset/purple-ads-itch.md
- babel.config.js
Closes #5043 
To test, run `yarn build` and look at `build/node_modules/@remix-run/react/dist/components.js` and confirm that around line 108 you don't see any `||=` operators.
Here's the diff between a `1.10.0` build and a build on this branch:
```bash
~/me/shopify/repos/remix (brophdawg11/node-14-build)> diff -r build-current build
diff -r build-current/node_modules/@remix-run/react/dist/components.js build/node_modules/@remix-run/react/dist/components.js
109,110c109,110
<     CatchBoundary ||= errorBoundaries.RemixRootDefaultCatchBoundary;
<     ErrorBoundary ||= errorBoundaries.RemixRootDefaultErrorBoundary;
---
>     CatchBoundary || (CatchBoundary = errorBoundaries.RemixRootDefaultCatchBoundary);
>     ErrorBoundary || (ErrorBoundary = errorBoundaries.RemixRootDefaultErrorBoundary); …
```
> Update babel config to transpile down to node 14

- .changeset/funny-numbers-type.md
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
closes #5028
before:
```jsx
<Routes>
<Route file="root.tsx">
<Route index file="routes/_index.tsx" />
<Route path="help" file="routes/help.tsx">
<Route index file="routes/help._index.tsx" />
<Route path="bam" file="routes/help.bam.tsx" />
</Route>
<Route path="app" index file="routes/app/_index.tsx" />
<Route path="app/footer" file="routes/app/footer.tsx" />
<Route path="app/primary-nav" file="routes/app/primary-nav.tsx" />
<Route path="something" index file="routes/something/_index.tsx" />
</Route>
</Routes>
```
after:
```jsx
<Routes>
<Route file="root.tsx">
<Route index file="routes/_index.tsx" />
<Route path="help" file="routes/help.tsx">
<Route index file="routes/help._index.tsx" />
<Route path="bam" file="routes/help.bam.tsx" />
</Route>
<Route path="app" index …
```
> fix: update flat-route module check for file colocation

- integration/css-modules-test.ts
- integration/css-side-effect-imports-test.ts
- packages/remix-dev/compiler/compileBrowser.ts
This fixes an issue where assets that are _only_ referenced in the CSS bundle build aren't written to disk, which impacts images referenced in CSS Modules files. This wasn't picked up in the test suite because we weren't asserting that requests for the image were successful, so I've updated all CSS bundle tests to catch this. I've confirmed that these updated tests fail against the latest code in dev.
This slipped through during development because the test image I was using was also referenced in the browser app build (via a regular style sheet) which _does_ write files to disk. I was able to reproduce this issue when I updated my test app to only use CSS Modules.
> fix: write assets from CSS bundle build

- docs/utils/cookies.md
The code example is missing imports for `Link` and `Form`
> docs(utils/cookies): Fix missing imports

- docs/guides/styling.md
The formatting was automatically updated, causing a ternary to wrap over three lines, but the highlighted lines weren't updated to reflect this.
> docs(guides/styling): fix highlighted lines for CSS bundle setup

- .changeset/lovely-seals-sin.md
- packages/remix-react/CHANGELOG.md
- packages/remix-react/components.tsx
- packages/remix-server-runtime/CHANGELOG.md
- yarn.lock
> Ensure useFetcher is stable across re-renders in back-compat layer

- packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
- packages/remix-dev/__tests__/migrations/fixtures/indie-stack/package.json
Apparently we need to add the `-p` flag when running `tsc` on the `cypress` folder
- https://github.com/remix-run/indie-stack/actions/runs/3951228293/jobs/6764810424
- https://github.com/remix-run/blues-stack/actions/runs/3951125579/jobs/6764576532
- https://github.com/remix-run/grunge-stack/actions/runs/3951229138/jobs/6764812112
> fix(tests): fix `typecheck` script in fixtures

- scripts/release/github.ts
this isnt an issue with remix due to no other packages starting with `remix`, but PRing to be consistent with RR https://github.com/remix-run/react-router/pull/9935
Closes: #
> ci(comment): update package check

- .changeset/mean-clocks-bow.md
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
- packages/remix-dev/compiler/compilerServer.ts
- packages/remix-dev/compiler/options.ts
- packages/remix-dev/compiler/plugins/serverEntryModulePlugin.ts
- packages/remix-dev/compiler/remixCompiler.ts
- packages/remix-dev/compiler/watch.ts
- packages/remix-dev/config.ts
- packages/remix-dev/devServer2.ts
- packages/remix-dev/liveReload.ts
- packages/remix-dev/server-build.ts
- packages/remix-react/__tests__/components-test.tsx
- packages/remix-react/components.tsx
- packages/remix-react/entry.ts
- packages/remix-server-runtime/__tests__/server-test.ts
- packages/remix-server-runtime/__tests__/utils.ts
- packages/remix-server-runtime/build.ts
- packages/remix-server-runtime/entry.ts
- packages/remix-server-runtime/server.ts
- packages/remix-server-runtime/serverHandoff.ts
Running the new dev server does the following:
1. Builds an initial build
2. Watches for changes to app source code and rebuilds when changes occur
3. Waits for the app server (i.e. `server.js`) to be ready
4. Sends a `RELOAD` message over the websocket
For step (3), the dev server polls `GET <app server>/__REMIX_ASSETS_MANIFEST` and compares the build hash received from the app server with the latest build hash produced by the compiler run within the dev server.
App server is now only restarted when a rebuild happens, not on every request.
That means that in-memory persistence is fixed. So no need to use the `global` trick anymore when dealing with DB connections, in-memory caches, etc..
In fact app server might not need to restart _at all_ if the app server supports some sort of …
> The new dev server

- .changeset/fresh-needles-join.md
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
before:
```
app_.projects.$id.roadmap/
_index.tsx
chart.tsx
update-timeline.server.tsx
```
after:
```
app_.projects.$id.roadmap/
index.tsx
chart.tsx
update-timeline.server.tsx
```
Closes: #
> fix(remix-dev/flat-routes): use `index` without leading underscore for colocation

- docs/components/form.md
- docs/components/outlet.md
- docs/hooks/use-async-error.md
- docs/hooks/use-async-value.md
- docs/hooks/use-before-unload.md
- docs/hooks/use-fetcher.md
- docs/hooks/use-form-action.md
- docs/hooks/use-href.md
- docs/hooks/use-location.md
- docs/hooks/use-navigate.md
- docs/hooks/use-navigation-type.md
- docs/hooks/use-navigation.md
- docs/hooks/use-outlet-context.md
- docs/hooks/use-outlet.md
- docs/hooks/use-params.md
- docs/hooks/use-resolved-path.md
- docs/hooks/use-revalidator.md
- docs/hooks/use-route-error.md
- docs/hooks/use-route-loader-data.md
- docs/hooks/use-search-params.md
- docs/hooks/use-submit.md
We already have docs for `Outlet` that point to the RR docs: https://remix.run/components/outlet
> docs: add pages for React Router components/hooks

- .changeset/flat-cobras-beam.md
- contributors.yml
- packages/remix-node/__tests__/fileUploadHandler-test.ts
- packages/remix-node/upload/fileUploadHandler.ts
Closes: #3021
One unit test for each new function, added in the remix-node package.
This is basically the same PR as #3034, but it got closed by its author before being merged. I believe this is a useful feature and would very much like to see it added.
> feat(remix-node): add `getFilePath`& `remove` methods to `NodeOnDiskFile`

- scripts/utils.js
> chore: fix `version` script

- .github/ISSUE_TEMPLATE/bug_report.yml
We often receive regressions reports where it turns out that the OP only updated a single package, leading to unexpected behaviors.
Example: #5073
> chore(bug-report): Make sure the reporter have aligned remix dependencies

- .changeset/short-bobcats-switch.md
- packages/remix-server-runtime/package.json
- packages/remix-server-runtime/routeModules.ts
> refactor(remix-server-runtime): remove `react` & `react-dom` from `peerDependencies`

- packages/remix-react/index.tsx
accidentally removed when we cleaned up non public exports https://github.com/remix-run/remix/pull/4915/files#diff-95ce3997ccff84362b71981aafc7cf2e4f5bac7285637badde43de2196445bacL64
Closes: #
> fix(remix-react): export `CatchBoundaryComponent` type

- .changeset/breezy-dancers-lie.md
- docs/api/remix.md
- docs/utils/sessions.md
- integration/cf-compiler-test.ts
- packages/remix-cloudflare/index.ts
- packages/remix-cloudflare/sessions/workersKVStorage.ts
- packages/remix-dev/__tests__/transform-replaceRemixMagicImports-test.ts
- packages/remix-dev/codemod/replace-remix-magic-imports/utils/export.ts
- packages/remix-eslint-config/rules/packageExports.js
- rollup.utils.js
Rename to `createWorkersKVSessionStorage` for consistency with the "Workers KV" product name.
> feat(remix-cloudflare): rename `createCloudflareKVSessionStorage` to `createWorkersKVSessionStorage`

- packages/remix-dev/package.json
- yarn.lock
Upgrade vanilla extract from `6.0.1` to `6.0.2`
Version `6.0.1` of vanilla-extract uses `esbuild` version `0.11.16`.
Version `6.0.2` of vanilla-extract uses `esbuild` version `0.16.3`, which also happens to be [the same version of `esbuild` that the remix repo currently uses](https://github.com/search?q=repo%3Aremix-run%2Fremix+%22esbuild%22+language%3AJSON&type=code&l=JSON).
- https://github.com/vanilla-extract-css/vanilla-extract/pull/973
> chore(remix-dev): update `@vanilla-extract/integration`

- contributors.yml
- packages/remix-dev/modules.ts
This MR changes the type of imported Markdown or MDX files so we get type check and auto-completion for the `components` property of [@mdx-js/mdx](https://npm.im/@mdx-js/mdx). This way if users want to customize classNames or whatever in their imported Markdown or MDX, they can:
```tsx
import Example from "./example.md";
import { Link } from "remix";
// ...
<Example components={{ a: Link }}/>
```
You can also pass a `wrapper` component to wrap the entire imported Markdown or MDX, and also pass extra properties that will be passed to said wrapper:
```tsx
import Example from "./example.md";
import { Link } from "remix";
import { FancyWrapper } from "../components/FancyWrapper";
// ...
<Example components={{ a: Link, wrapper: FancyWrapper }} theme="dark" />
```
Currently both snippets above …
> feat(remix-dev): improve types for imported MD & MDX files

- docs/route/loader.md
- docs/utils/redirect.md
The current docs don't highlight that you can throw a redirect response. Also, it's not mentioned that throwing a `redirect` is different from throwing any other response (does not trigger `CatchBoundary`). The goal is to emphasize that throwing a redirect is kind of a special case.
> docs: add information about throwing `redirect`s

- packages/remix-node/upload/fileUploadHandler.ts
> chore(remix-node): update jsdoc for `FileUploadHandlerOptions`' `filter`

- .changeset/silent-cups-double.md
- integration/form-test.ts
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Bump router versions for 1.12 prerelease
> Bump react router versions

- .changeset/healthy-beers-nail.md
- integration/vanilla-extract-test.ts
- packages/remix-dev/compiler/plugins/cssSideEffectImportsPlugin.ts
- packages/remix-dev/compiler/plugins/vanillaExtractPlugin.ts
Fixes: #5238
I added integration tests for side-effect imports of Vanilla Extract files, both within the app context and within the Vanilla Extract child compilation since it's a separate esbuild pass. I've confirmed that these tests fail when the fix hasn't been applied.
> fix: mark Vanilla Extract files as side effects

- contributors.yml
- packages/remix-dev/devServer/liveReload.ts
- packages/remix-dev/devServer2.ts
Closes: #5248
- Setup cloudflare pages template playground
- use npm run dev command with remix watch, then make change
- see if there is any wrangler error in console
- use npm run dev command with remix dev (new dev server), then make change
- see if there is any wrangler error in console
> fix(remix-dev): Server build should not be removed in `remix watch` and `remix dev` 

- .changeset/odd-plants-doubt.md
- integration/prefetch-test.ts
- packages/remix-react/components.tsx
external "to" detection should be brought over to React Router (pr: https://github.com/remix-run/react-router/pull/9900)
Closes: #5016
our current testing for Link should be enough, both here and in RR
> feat(remix-react): allow `<Link>`'s "to" prop to accept absolute urls

- .changeset/hip-cats-warn.md
- packages/remix-dev/config/flat-routes.ts
however that causes remix dev to not pick up new files or file renames. 
Closes: #
> fix(remix-dev): fast glob will return posix style paths even on windows

- .github/workflows/nightly.yml
nightlies with no changes from the previous day were still being created due to the old sort returning a tag from may
Closes: #
> ci(nightly): update sorting

- docs/other-api/adapter.md
- docs/pages/community.md
After discussion with @machour on Discord, I have added remix-google-cloud-functions to a new "community adapters" list in the docs.
> docs(other-api/adapter): add community adapters

- contributors.yml
- docs/guides/data-writes.md
This PR fixes missing `json` in `data-writes.md` document. At certain point in the guide we return the validation errors and form values with `json`, but it isn't actually imported anywhere. This PR makes it so that `json` is always imported too wherever the other used action `redirect` is mentioned.
> docs(guide/data-writes): add missing json imports

- docs/tutorials/jokes.md
> docs(tutorials/jokes): remove `ActionData` references

- contributors.yml
- docs/route/should-revalidate.md
The type for the shouldRevalidate function is ShouldRevalidateFunction and not ShouldReloadFunction.
> docs(route/should-revalidate): Fix shouldRevalidate typing

- .changeset/honest-crabs-sort.md
- packages/remix-dev/__tests__/cssSideEffectsPlugin-test.ts
- packages/remix-dev/compiler/plugins/cssSideEffectImportsPlugin.ts
Closes: #5287
I've added snapshot tests that exercise a bunch of language features for all combinations of JS/TS with and without JSX. I wanted to make sure there weren't other obvious cases we weren't handling, but I also wanted to provide a place to add further test cases in the future.
> fix: support decorators with CSS side-effects

- contributors.yml
- docs/pages/community.md
- docs/pages/contributing.md
- docs/pages/faq.md
- docs/pages/gotchas.md
- docs/pages/philosophy.md
- docs/pages/stacks.md
- docs/pages/technical-explanation.md
Simple docs changes.
PR on main, let me know if that is wrong. ([ref](https://remix.run/docs/en/v1/pages/contributing#branches))
Sorry for being nitpicky, having a copy-editor mindset makes me read more attentively 😂 
(If there is linting on the markdown files, CI might fail. I normally use Deno for formatting, and I turn it off when I'm contributing to other codebases. I'll set up the dev environment properly and fix it if that ends up being the case.)
> docs(pages/*): punctuation

- contributors.yml
- docs/tutorials/jokes.md
This is a simple change. [!4684](https://github.com/remix-run/remix/pull/4684) moved the `badRequest` function from the `/jokes/new.tsx` file to the `/utils/requests.server.ts` file, but left the `json` import unused.
This PR removes the `json` import from the `/jokes/new.tsx` file as it's not needed somewhere in the file.
> docs(tutorials/jokes): Remove unused json import

- docs/guides/styling.md
- docs/pages/gotchas.md
We've already had a couple of consumers trip over this, so I'm adding some warnings to the docs while the esbuild issue still exists.
> docs: add CSS bundle tree-shaking issue warnings

- .changeset/nine-apricots-breathe.md
- packages/remix-architect/__tests__/server-test.ts
- packages/remix-architect/server.ts
- packages/remix-express/__tests__/server-test.ts
- packages/remix-express/server.ts
- packages/remix-netlify/__tests__/server-test.ts
- packages/remix-netlify/server.ts
- packages/remix-vercel/__tests__/server-test.ts
- packages/remix-vercel/server.ts
The root cause of this came down to us passing the origin in the optional second `base` param for the `new URL()` constructor.  When we did this, an incoming pathname of `//` got incorrectly identified as a protocol-less absolute URL.  Since we know the origin, we can just pass an absolute URL directly into the first param to avoid this:
```js
let origin = 'http://localhost';
let path = '//';
// ❌ Throws `Invalid URL` error
new URL(path, origin);
// ✅ All good in the hood
new URL(`${origin}${path}`);
```
Closes: #4422
Replace #4622
**Testing Strategy**:
* Unit tests for each of the adapters
* Manual testing for express
⚠️ Note this does not change anything about our route matching logic, it just lets the request make it through to matching.  Current behavior is as follows:
* `//` will …
> Fix adapter request creation when double slashes exist

- .github/workflows/nightly.yml
- .github/workflows/release-comments.yml
- .github/workflows/release.yml
- scripts/release/comment.ts
- scripts/release/constants.ts
- scripts/release/find-release-from-changeset.js
- scripts/release/github.ts
https://twitter.com/rossipedia/status/1620562196303613953
before it would get PRs merged to dev and compare dates, now it will get PRs for the current release branch
Closes: #
> ci(comment) use current branch when gathering PRs for stable release

- contributors.yml
- docs/file-conventions/route-files-v2.md
Fixed incorrect route path in file conventions > route files v2 > folders for organization section
>  docs(file-conventions/route-files-v2): Fix incorrect routes path

- .changeset/tame-swans-burn.md
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
Closes: #5170
Closes: #5261
Closes: #5303
Closes: #5322
Closes: #5324
Closes: #5327
updated current tests
> fix(remix-dev): flat route fixes and enhancements

- contributors.yml
- docs/utils/defer.md
This change fixes the line highlight for the [defer](https://remix.run/docs/en/v1/utils/defer) example.
> docs(utils/defer): fix code highlighting

- .changeset/fresh-toes-shout.md
- packages/remix-dev/compiler/utils/postcss.ts
- packages/remix-dev/config.ts
when using `type: "module"` in package.json you need to make any commonjs files have the `.cjs` extension however `require.resolve` won't look for them 🙈
note: tailwindcss doesn't currently support mjs so that extension is intentionally missing.
Closes: #
> fix(remix-dev): update tailwind config detection to also look for cjs

- contributors.yml
- packages/remix-react/components.tsx
This merge request uses the same improved detection as in remix-run/react-router#9994.
> Added better detection for absolute urls in link component

- contributors.yml
- packages/remix-dev/compiler/loaders.ts
- packages/remix-dev/modules.ts
Adds support for importing photoshop image files as assets.
Not sure if there's any need to add the MIME type to the `binaryTypes.ts` files in remix-architect and remix-netlify, but fwiw the MIME is `image/vnd.adobe.photoshop`
I was able to import a `.psd` file as an asset as expected:
```typescript
import sourceArt from "./assets/art.psd"
export default function PsdLink() {
return (
<a href={sourceArt}>Download PSD</a>
)
}
```
> feat(remix-dev): allow importing `.psd` files

- docs/utils/sessions.md
- packages/remix-architect/sessions/arcTableSessionStorage.ts
- packages/remix-cloudflare/sessions/workersKVStorage.ts
- packages/remix-deno/sessions/fileStorage.ts
- packages/remix-node/sessions/fileStorage.ts
- packages/remix-server-runtime/index.ts
- packages/remix-server-runtime/reexport.ts
- packages/remix-server-runtime/sessions.ts
- packages/remix-server-runtime/sessions/cookieStorage.ts
- packages/remix-server-runtime/sessions/memoryStorage.ts
Currently, all session-related functions use the default `SessionData` interface that is defined as `{ [key: string]: any }`.
This works fine, but doesn't provide any type information for TypeScript when using e.g. `session.get(...)`.
This PR adds generic types to
- the `Session` interface
- the `createSession(...)` function
- all built-in session stores
You can now create a session storage like this:
```ts
// app/sessions.ts
interface CustomSessionData {
userId: number;
error: string;
}
export const {
getSession,
commitSession,
destroySession
} = createCookieSessionStorage<CustomSessionData>();
```
and use it like usual, but you will now get type information and auto-completion when using any of the `session.(has|get|set|flash|unset)` functions.
Using the generic session data type is …
> feat(remix-server-runtime): allow generic types for `SessionData`

- contributors.yml
- docs/guides/data-loading.md
> docs(guides/data-loading): replace `unstabel_shouldReload` references with `shouldRevalidate`

- .changeset/tidy-doors-judge.md
- packages/remix-dev/compiler/watch.ts
The `onCompileFailure` was not passed to the `compile` function so errors were not logged during initial build in dev.
It is passed to `createRemixCompiler` instead but it doesn't seem to be used there, so perhaps you want to remove it.
> Fix: log errors during initial build in development

- .changeset/twelve-seahorses-arrive.md
- packages/remix-react/entry.ts
- packages/remix-server-runtime/entry.ts
- packages/remix-server-runtime/server.ts
- packages/remix-testing/create-remix-stub.tsx
(cherry picked from commit 2d28768b17a0767c2723625c5acec51a02ec0d22)
Closes: #
> chore: sync `FutureConfig` interface

- .changeset/tidy-singers-battle.md
- packages/remix-react/components.tsx
- packages/remix-react/transition.ts
Fix `Fetcher` types in the back-compat layer to reflect undefined form* fields on `Idle`/`Loading`/`Done` states so TS doesn't complain on `fetcher.formMethod` accesses in those states.
> Ensure types for fetchers always include form* submission fields

- contributors.yml
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
This a typo PR fix the ESM only warning in the console: the missing closing quote around `serverDependenciesToBundle`.
> fix(remix-dev/compiler): fix typo in `serverBareModulesPlugin` message

- packages/remix-dev/config.ts
removes a duplicate console.log about installing `isbot`
Closes: #
> chore(remix-dev): remove duplicate console.log

- .changeset/flat-routes-route-fixes.md
- integration/flat-routes-test.ts
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
- packages/remix-server-runtime/entry.ts
updates some missed logic so `<dir>/route` no longer conflicts in some cases.
updates conflict logic so it no longer throws errors and instead displays a nice error message about your conflicts
```log
⚠️ Route Path Collision: "/products/:pid"
The following routes all define the same URL, only the first one will be used
🟢️️ routes/products.$pid.tsx
⭕️️ routes/products.$productId.tsx
```
```log
⚠️ Route Path Collision: "/dashboard"
The following routes all define the same URL, only the first one will be used
🟢️️ routes/dashboard/route.tsx
⭕️️ routes/dashboard.tsx
```
```log
⚠️ Route Path Collision: "/"
The following routes all define the same URL, only the first one will be used
🟢️️ routes/_landing._index.tsx
⭕️️ routes/_dashboard._index.tsx
⭕️ routes/_index.tsx
```
Closes: #5470
Closes: …
> fix(remix-dev): normalize `/route` routeId, update route collision warnings

- .changeset/new-bulldogs-allow.md
- integration/link-test.ts
- packages/remix-react/components.tsx
test: add test to assert generated scripts
Closes: https://github.com/remix-run/remix/issues/5531
Check known imports are there and the appropriate number exist.
> fix: remove duplicate manifest imports introduced by defer work

- packages/remix-react/data.ts
Fixes error message when a deferred value can never be resolved to read more fluently.
I checked other usages in this file and found no other obvious violations, so this is unfortunately One Of Those:tm: prs.
N/A
> fix(*): fix error message

- .changeset/afraid-tigers-occur.md
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
hit a snag in a demo app as it complained there was a conflict when there wasn't.
```log
⚠️ Route Path Collision: "/:username"
The following routes all define the same URL, only the first one will be used
🟢 routes/_user.$username.tsx
⭕️️ routes/sneakers.$sneakerId.tsx
```
Closes: #
> chore(remix-dev): remove broken param collision check

- .changeset/red-kids-look.md
- contributors.yml
- integration/bug-report-test.ts
- integration/scroll-test.ts
Reverts an unintentional change to `bug-report-test.ts` (#3171) and moves the passing test to it's own `scroll-test.ts` file
> Move scroll test to it's own file

- .changeset/dirty-wolves-knock.md
- contributors.yml
- integration/matches-test.ts
- packages/remix-react/components.tsx
**Problem:** `useMatches` returning different route match data on sub navigation. This problem isn't obvious because the last `useMatches` hook call always returns the correct route's loader data
https://stackblitz.com/edit/remix-run-remix-askr4f?file=app/root.tsx
Navigate between home, test and test 2 page.
1. On full page reload, you will see multiple logs from `useMatches` of the same route (This is fine and it is due to React re-renders)
2. On sub navigation, you will see multiple logs from `useMatches` but of different route loader data. It is always the current route and the previous route
Notice that the server side console only logs loader data for the correct route
> Fix useMatches returning different loader data on sub navigation on client side

- .changeset/four-feet-grab.md
- docs/file-conventions/remix-config.md
- packages/remix-dev/__tests__/fixtures/stack/remix.config.js
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/config.ts
docs: add serverBuildTarget migration table
Closes: #
No functional changes, just a warning and docs.
> feat(remix-dev): serverBuildTarget deprecation warning

- .changeset/cool-planets-perform.md
- contributors.yml
- integration/tsconfig-test.ts
- packages/remix-dev/compiler/utils/tsconfig/write-config-defaults.ts
See https://devblogs.microsoft.com/typescript/announcing-typescript-5-0-beta/#moduleresolution-bundler for more info.
I've been patching this since I moved to TypeScript v5 beta. I also added a unit test.
> Allow TypeScript v5 moduleResolution: "bundler"

- .changeset/lazy-dots-sip.md
- integration/flat-routes-test.ts
- integration/hmr-test.ts
- integration/tsconfig.json
- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/config.ts
~~for some reason adding the warning is causing the HMR tests to fail 🤔 https://github.com/remix-run/remix/actions/runs/4317024896/jobs/7533572210~~
edit: it was checking stderr length and the warning goes to stderr 🤦‍♂️
Closes: #
> feat(remix-dev): add warning when `future.v2_routeConvention` is not enabled

- .changeset/deprecate-use-transition.md
- docs/hooks/use-transition.md
- packages/remix-react/components.tsx
- packages/remix-react/warnings.ts
Officially deprecates `useTransition` in favor of `useNavigation` for v1
> Deprecate useTransition in favor of useNavigation

- docs/file-conventions/route-files-v2.md
The intro paragraph on the Folders for Organization section wasn't updated to use the new convention of `route.tsx` added in 1.13.0.
> docs(file-conventions/route-files-v2): use new `route.tsx` convention

- .changeset/fix-x-route-imports.md
- integration/shared-route-imports-test.ts
- packages/remix-dev/compiler/compileBrowser.ts
- packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
- packages/remix-dev/compiler/plugins/browserRouteModulesPlugin_v2.ts
fix: put new browserRouteModulesPlugin behind `config.future.unstable_dev`
This fixes an issue that arose because of using AST parsing to strip route module exports. Reverting to previous way for now and will work on a fix behind the unstable_dev flag.
Closes: #
New integration tests.
> fix: revert browserRouteModulesPlugin

- contributors.yml
- packages/remix-dev/compiler/loaders.ts
This PR enables support for users to include "native" (`.node`) modules into their server bundles (when using NodeJS). 
Libraries like `sharp` (awesome for for image processing) are written in a lower-level language than NodeJS and then are compiled as a "native" module to be used in a Node environment.
Discussion: #2560
> feat(remix-dev/compiler): support native `.node` files

- .changeset/three-cheetahs-lick.md
- docs/route/catch-boundary.md
- docs/route/error-boundary-v2.md
- docs/route/error-boundary.md
- integration/action-test.ts
- integration/defer-test.ts
- integration/hmr-test.ts
- packages/remix-dev/__tests__/create-test.ts
- packages/remix-dev/config.ts
- packages/remix-react/browser.tsx
- packages/remix-react/errorBoundaries.tsx
- packages/remix-react/routeModules.ts
- packages/remix-server-runtime/routeModules.ts
Deprecates `CatchBoundary` in favor of the new `future.v2_errorBoundary` behavior
> Deprecate CatchBoundary in favor of future.v2_errorBoundary

- .changeset/deprecate-fetcher-type-submission.md
- docs/guides/optimistic-ui.md
- docs/hooks/use-fetcher.md
- docs/hooks/use-fetchers.md
- packages/remix-react/components.tsx
Deprecate `fetcher.type` and `fetcher.submission`
> Deprecate fetcher.type and fetcher.submission

- .changeset/no-log-on-aborted-request.md
- packages/remix-server-runtime/server.ts
Since aborted requests is an ecpedted flow, we should not log the error from the router (i.e., `new Error("queryRoute() call aborted")`).  We had this check for some flows but not all.
> chore: don't log server errors for aborted requests

- .changeset/css-bundle-monorepo-fix.md
- packages/remix-dev/compiler/plugins/cssBundleEntryModulePlugin.ts
fixes an issue when using `@remix-run/css-bundle` in a monorepo.
no integration tests as i don't think we can do that with our current test infra
Closes: #5659
> fix(remix-dev): use path.resolve when re-exporting entry.client

- integration/catch-boundary-data-test.ts
- integration/catch-boundary-test.ts
- integration/error-boundary-test.ts
- integration/link-test.ts
Prepping for v2 by copying all current `ErrorBoundary`/`CatchBoundary` integration tests and running them with `v2_errorBoundary` enabled.  Then in v2 we can just delete the v1 versions of the tests and keep the copy/pasted versions.
> Add v2_errorBoundary tests

- contributors.yml
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
Fixes #5672.
I've added a test in remix-dev for the functionality as well. Before this change, this test failed on Windows and passed on MacOS.
> fix(remix-dev): Use normalized file path when analyzing flat routes

- .changeset/remove-fetcher-back-compat.md
- integration/fetcher-state-test.ts
- packages/remix-react/components.tsx
- packages/remix-react/transition.ts
Removes `fetcher.type` and `fetcher.submission` for v2.  We still keep a small back-compat layer for now since there's an unintentional mismatch in casing between `formMethod` on Remix `useFetcher`/`useTransition` versus react Router `useFetcher`/`useNavigation`
> Remove fetcher.type/fetcher.submission

- .changeset/proud-nails-hunt.md
- packages/remix-dev/config.ts
This will warn people about #5701
> feat(remix-dev): show deprecation warning when `browserBuildDirectory` config is used

- packages/remix-testing/package.json
This fixes an issue with mismatched types between different versions of react-router-dom.
> Fix v2 type error by bumping react-router-dom to experimental release

- .github/workflows/test.yml
19.8 is no good
related https://github.com/nodejs/node/issues/47096
```log
Building Remix app in production mode...
node[78803]: ../src/module_wrap.cc:599:MaybeLocal<v8::Promise> node::loader::ImportModuleDynamically(Local<v8::Context>, Local<v8::Data>, Local<v8::Value>, Local<v8::String>, Local<v8::FixedArray>): Assertion `(it) != (env->id_to_function_map.end())' failed.
1: 0x104488e00 node::Abort() [/Users/logan/.n/bin/node]
2: 0x104488bcc node::PrintCaughtException(v8::Isolate*, v8::Local<v8::Context>, v8::TryCatch const&) [/Users/logan/.n/bin/node]
3: 0x10445132c node::loader::ImportModuleDynamically(v8::Local<v8::Context>, v8::Local<v8::Data>, v8::Local<v8::Value>, v8::Local<v8::String>, v8::Local<v8::FixedArray>) [/Users/logan/.n/bin/node]
4: 0x10473892c …
```
> ci: run tests with node 19.7

- .changeset/fluffy-dragons-reflect.md
- packages/remix-dev/compiler/compileBrowser.ts
- packages/remix-dev/compiler/plugins/hmrPlugin.ts
`react-refresh` is a dependency of `@remix-run/dev`, not of your app so it's not "hoisted" to node_modules.
so we can use require.resolve to find it. This fixes an issue where remix-dev would not work with pnpm.
see https://github.com/pnpm/pnpm/issues/2957#issuecomment-719832332 for a similar issue in CRAv4 and how they fixed it there https://github.com/pmmmwh/react-refresh-webpack-plugin/pull/230/files
confirmed working: https://twitter.com/jplhomer/status/1631375544263516180
closes #5811
Closes: #
> fix(remix-dev): `require.resolve` isolateChunks for pnpm

- packages/remix-react/components.tsx
It was necessary for CSPs before, then it was no longer necessary thanks to https://github.com/remix-run/remix/pull/2783, but then it became necessary again when this PR was merged: https://github.com/remix-run/remix/pull/2874 but the deprecation warning was never removed.
Until this is released, people will get this in their editors:
> fix(remix-react): undeprecate `LiveReload`'s `nonce` prop

- .github/workflows/test.yml
Node release 19.8.1 which should fix the bugs that previously caused our CI builds to fail.
Closes: #
> Revert testing Node 19.7 -> latest

- .changeset/remove-unstable-css-modules.md
- docs/guides/styling.md
- integration/css-modules-test.ts
- integration/css-side-effect-imports-test.ts
- integration/deterministic-build-output-test.ts
- integration/postcss-test.ts
- integration/tailwind-test.ts
- integration/vanilla-extract-test.ts
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/compiler/compileBrowser.ts
- packages/remix-dev/compiler/compilerServer.ts
- packages/remix-dev/config.ts
- packages/remix-react/entry.ts
- packages/remix-server-runtime/entry.ts
- packages/remix-testing/create-remix-stub.tsx
Removes the `unstable_cssModules` future flag and automatically enables CSS Modules. This means that CSS bundling is no longer conditional within the Remix compiler.
> feat!(remix-dev): remove `unstable_cssModules`

- docs/pages/api-development-strategy.md
Initial pass at future flags docs
[Rendered](https://github.com/remix-run/remix/blob/brophdawg11/future-flags-docs/docs/pages/api-development-strategy.md)
> Add docs on API Development Strategy

- .changeset/flat-routes-perf.md
- integration/flat-routes-test.ts
- packages/remix-dev/__tests__/flat-routes-test.ts
- packages/remix-dev/config/flat-routes.ts
- packages/remix-dev/package.json
- yarn.lock
- Stop glob matching for routes, instead fs.readdirSync() just the routes directory, and if (isDir) look for a index or route module.
- Move away from define routes helper for something like this with a single iteration over routes sorted by reverse ID length
this is available as `v0.0.0-experimental-699baf49c`
Closes: #
> refactor(remix-dev): flat routes perf improvements

- .changeset/thick-actors-juggle.md
- integration/action-test.ts
- integration/defer-test.ts
- packages/remix-react/components.tsx
This will warn people about #5705
> feat(remix-react): show deprecation warning when `imagesizes` & `imagesizes` properties are returned from `links` function

- .changeset/mean-deers-wink.md
- packages/remix-react/browser.tsx
- packages/remix-react/components.tsx
- packages/remix-react/warnings.ts
> fix(remix-react): don't warn about runtime deprecation warnings in production

- .changeset/bump-router-dependency.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Updates to include the fix from https://github.com/remix-run/react-router/pull/10247 which fixes `defer` in the Blues Stack (https://github.com/remix-run/blues-stack/issues/151) when bundling the express server
> Bump router 6.10.0-pre.1

- packages/remix-dev/compiler/browserjs/compiler.ts
- packages/remix-dev/compiler/build.ts
- packages/remix-dev/compiler/compiler.ts
- packages/remix-dev/compiler/css/compiler.ts
- packages/remix-dev/compiler/plugins/cssImports.ts
- packages/remix-dev/compiler/serverjs/compiler.ts
- packages/remix-dev/compiler/watch.ts
- packages/remix-dev/package.json
- yarn.lock
Esbuild 0.17 introduces the `context` API which mirrors our `{ compile, dispose }` API for compilers, making our usage much simpler. Plus TS types were improved so we don't need to do `invariant` checks just to make TS happy anymore.
Testing Strategy: existing compiler tests
> chore(dev): upgrade to esbuild 0.17
