remix-run/remix

integration/css-modules-test.ts
packages/remix-dev/package.json
yarn.lock

As a follow-up to #5922, this PR pins to an exact version of esbuild. This is important for us since esbuild often ships major changes in patch releases.
The reason for pinning to this specific version is to ensure we don't inherit the CSS tree shaking changes introduced in [esbuild v0.17.7](https://github.com/evanw/esbuild/releases/tag/v0.17.7). To confirm this is the case and to catch future regressions, I've also added a tree-shaking test to the CSS Modules test suite. I've validated that this test fails against esbuild v0.17.14 introduced in #5922.

chore(dev): pin esbuild to v0.17.6

---

contributors.yml
docs/pages/v2.md

serverBuildDirectory is duplicated in the new example and should be serverBuildPath

docs(pages/v2): fix typo in `serverBuildDirectory` section

---

docs/route/meta-v2.md

Links were missing causing tags to show on the page and tag formatting looked incorrect.
I've made some educated guesses about what the links should be, if any are wrong then let me know and I'll update them

docs(meta-v2): fix links

---

contributors.yml
docs/pages/v2.md

Also see #5968 but this PR is more complete as the import on the second example is also incorrect :-)

docs(pages/v2): fix typo in `useFetcher` section

---

integration/postcss-test.ts

I noticed these tests failing in the `release-test` workflow since it runs the tests against Node v14 which doesn't have `String.prototype.replaceAll`, so this PR updates the code to use `replace` instead.

test(dev): fix PostCSS tests in Node 14

---

docs/tutorials/blog.md

Deep pass over the Blog tutorial to update it to v2 route conventions, and fix up a couple typos and minor errors

docs: update blog tutorial for v2 routes

---

docs/tutorials/blog.md

The tutorial starts with the current `indie-stack`, which has `v2_routeConvention` enabled

docs(tutorials/blog): use enabled `v2_routeConvention` flag

---

contributors.yml
templates/arc/app/routes/_index.tsx
templates/cloudflare-pages/app/routes/_index.tsx
templates/cloudflare-workers/app/routes/_index.tsx
templates/deno/app/routes/_index.tsx
templates/express/app/routes/_index.tsx
templates/fly/app/routes/_index.tsx
templates/netlify/app/routes/_index.tsx
templates/remix/app/routes/_index.tsx
templates/vercel/app/routes/_index.tsx

When I bootstrapped a new Remix project a few days ago, I noticed the type `V2_MetaFunction` was imported from the Node adapter `@remix-run/node`, which isn't installed because I chose to deploy to Cloudflare Pages. This is present in all templates. I also noticed that this type can be imported both from the adapter, and from `@remix-run/react`. I wasn't sure which is the correct one, maybe the adapter specific version is more correct, but I couldn't from a brief glance I didn't notice any difference in the types.

Fix `V2_MetaFunction` type import in templates

---

contributors.yml
scripts/playground/template/README.md

For non-native English-speaking developers like myself, it took some time to understand the meaning of the expression "`.gitignore` -d" when I first encountered it. 
To make it more accessible for developers who may not be fluent in English, I've updated the wording to a clearer English expression.

docs(playground): clarify README

---

.changeset/serialize-from-data-key.md
packages/remix-react/__tests__/hook-types-test.tsx
packages/remix-server-runtime/__tests__/serialize-test.ts
packages/remix-server-runtime/__tests__/utils.ts
packages/remix-server-runtime/responses.ts

Closes: #5211
Closes: #5938
- Fixes serialization type inference when returned data has a data key. The fix brands `TypedDeferredData` to make it explicitly nominal instead of structural. 
- Added tests to cover most of the serialization cases. 
Probably a different solution exists simplifying the current code and making use of  `@remix-run/router` types.

fix(server-runtime): fix SerializeFrom type inference

---

packages/remix-cloudflare-pages/worker.ts

Due to @mcansh's remark in https://github.com/remix-run/remix/pull/5822#discussion_r1163230868, I noticed that the CP adapter's `GetLoadContextFunction` was wrong
With this PR, we derive `context` from `@cloudflare/workers-types`' `PagesFunction`

fix(remix-cloudflare-pages): fix `GetLoadContextFunction` type

---

packages/remix-dev/config.ts

* Meta export notice does not match the format all the other V2 Future change notes
Prior to change the text doesn't properly terminate the sentence in the console notice

chore(remix-dev): fix `v2_meta` warning

---

packages/remix-architect/package.json
packages/remix-server-runtime/package.json

https://canary.discord.com/channels/770287896669978684/940264701785423992/1095463978722918460
https://canary.discord.com/channels/770287896669978684/940264701785423992/1095464105680322560
Closes: #

fix: move `@types/*` to devDependencies

---

.changeset/postcss-enabled-by-default.md
.changeset/remove-unstable-css-modules.md
.changeset/remove-unstable-css-side-effect-imports.md
.changeset/remove-unstable-postcss.md
.changeset/remove-unstable-tailwind.md
.changeset/remove-unstable-vanilla-extract.md
.changeset/tailwind-enabled-by-default.md

This PR updates the v2 changests to reflect changes made in v1 — namely that the `postcss` and `tailwind` options are being added (disabled by default) and that CSS bundling features are being enabled.

chore: update CSS bundling changesets

---

.changeset/testing-helper-context-and-types.md
packages/remix-testing/__tests__/stub-test.tsx
packages/remix-testing/create-remix-stub.tsx

before if you tried to pass a loader/action directly to the route object it would fail as `context` is optional in RR, but required in Remix (types for each are also different, bug would remain if required), so you would have to manually pass `context: {}`
```ts
import { json, type DataFunctionArgs } from "@remix-run/node";
import { unstable_createRemixStub as createRemixStub } from "@remix-run/testing";
export async function loader(args: DataFunctionArgs) {
return json({ hi: "there" });
}
createRemixStub([
{
path: "/example",
loader: args => loader({ ...args, context: {} }),
},
]);
```
now we're using the Remix types for loader/action, but we need to cast them on the way out back to RR for use with `createMemoryRouter`
```ts
import { json, type DataFunctionArgs } from "@remix-run/node"; …
```

feat(remix-testing): cast types to use Remix type definitions + allow passing context

---

docs/guides/migrating-react-router-app.md
docs/guides/styling.md

This PR removes all references to the _lack_ of CSS bundling and adds CSS bundling docs to the React Router migration guide now that these features have been stabilized.

docs: update references to CSS bundling

---

contributors.yml
docs/guides/typescript.md

Please pardon the lack of corresponding issue; I didn't see anything in https://github.com/remix-run/remix/blob/b30a61157d89f21eef1063d4dd8fca2326f9210e/docs/pages/contributing.md about it. 🙂

docs(guides/typescript): add punctuation

---

packages/remix-vercel/package.json
yarn.lock

This should close https://github.com/remix-run/remix/security/dependabot/20 as now all versions are at `2.6.7` (which is a fixed version)

fix(deps): update `node-fetch`

---

docs/pages/v2.md

Follow-up of #5934
Since we're talking about replacement, I figured that we don't need to specify the default values in here in order to make it work as expected

docs(pages/v2): remove default values from `serverBuildTarget` section

---

contributors.yml
docs/guides/streaming.md

https://aws.amazon.com/blogs/compute/introducing-aws-lambda-response-streaming

docs(guides/streaming): remove text about AWS Lambda not supporting streaming

---

.changeset/dev-server.md
integration/hmr-test.ts
package.json
packages/remix-dev/channel.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/compiler.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer_unstable/env.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-dev/devServer_unstable/ping.ts
packages/remix-dev/devServer_unstable/socket.ts
packages/remix-dev/index.ts
packages/remix-dev/result.ts
packages/remix-server-runtime/server.ts
yarn.lock

Fixes #5834 #5663 #5348 #5492
- Fix for async error handling in compiler
- Push-based app server synchronization (instead of polling)
- App server as a managed subprocess

feat(dev): unstable dev server improvements

---

.changeset/cjs-esm-warning.md
docs/pages/v2.md
integration/hmr-test.ts
packages/remix-dev/__tests__/create-test.ts
packages/remix-dev/config.ts

feat(remix-dev): add warning for v2 "cjs"->"esm" defaults

---

packages/remix-dev/cli/commands.ts
packages/remix-dev/compiler/options.ts
packages/remix-dev/compiler/server/compiler.ts
packages/remix-dev/compiler/server/plugins/entry.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-react/__tests__/components-test.tsx
packages/remix-react/browser.tsx
packages/remix-react/components.tsx
packages/remix-react/entry.ts
packages/remix-server-runtime/build.ts
packages/remix-server-runtime/serverHandoff.ts

fix(dev): define `process.env.REMIX_DEV_HTTP_PORT` in server build

---

.changeset/hdr-revalidate-only-when-needed.md
integration/hmr-test.ts
packages/remix-react/browser.tsx
packages/remix-react/components.tsx
packages/remix-react/routes.tsx

Begin scoping loader revalidation, currently only all or none but lays the plumbing for further granularity. 
Closes: #
Update integration tests to add shouldRevalidate function to verify we

feat: revalidate loaders only when a change to one is detected

---

.github/workflows/test.yml
integration/error-data-request-test.ts
packages/remix-architect/__tests__/server-test.ts
packages/remix-express/__tests__/server-test.ts
packages/remix-netlify/__tests__/server-test.ts
packages/remix-node/package.json
packages/remix-vercel/__tests__/server-test.ts
yarn.lock

fixes `TypeError: Value of "this" must be of type URLSearchParams` on Node 20
looks like node 20 also changes how our Headers polyfill is rendered via jest's `toMatchInlineSnapshot` as this is the result of tests
```diff
- "headers": Headers {
-   Symbol(query): Array [
-     "cache-control",
-     "max-age=300, s-maxage=3600",
-     "x-forwarded-host",
-     "localhost:3000",
-     "x-forwarded-proto",
-     "http",
-   ],
-   Symbol(context): null,
- },
+ "headers": Headers {},
```
<details>
</details>
---
Closes #6118

chore(remix-node): bump `@remix-run/web-fetch` to latest

---

.changeset/dev-server.md
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/options.ts
packages/remix-dev/compiler/server/compiler.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-server-runtime/dev.ts

fix(dev): statically serve built assets from dev server

---

.changeset/express-template-esm.md
templates/express/.eslintrc.cjs
templates/express/.eslintrc.js
templates/express/package.json
templates/express/remix.config.js
templates/express/server.js

feat: express template server entry is now ESM
feat: express template uses new dev command
Closes: #

feat: express template outputs ESM for build

---

.changeset/two-pumpkins-roll.md
packages/remix-node/package.json

chore(remix-node): add missing files to published package

---

.changeset/async-load-context.md
packages/remix-architect/server.ts
packages/remix-cloudflare-pages/worker.ts
packages/remix-cloudflare-workers/worker.ts
packages/remix-express/server.ts
packages/remix-netlify/server.ts
packages/remix-vercel/server.ts

feat: support async `getLoadContext` in all adapters

---

contributors.yml
docs/pages/v2.md

Simple typo I noticed while reading the documentation for v2. This updates `heirarchy` to the correct spelling `hierarchy`.

docs(pages/v2): typo heirarchy -> hierarchy

---

contributors.yml
docs/file-conventions/routes-files.md

The link to `headers` in the Route File Naming was pointing to https://remix.run/docs/en/v1/routes/headers when it should have been point to https://remix.run/docs/en/v1/route/headers

docs(file-conventions/routes-files): Fix headers link

---

.changeset/empty-taxis-call.md
packages/remix-dev/compiler/server/plugins/bareImports.ts

this fixes the issue with misleading warnings for pnp mentioned in [this comment](https://github.com/remix-run/remix/issues/4106#issuecomment-1239133762) where the compiler in `@remix-run/dev` is attempting to resolve packages against it's own `package.json` rather than the application's `package.json`.
Closes: #
Adapted from https://github.com/remix-run/remix/pull/4156

fix(remix-dev): use correct require context in serverBareModulesPlugin

---

.changeset/dev-server.md
packages/remix-serve/cli.ts

feat(serve): call `devReady` for dev server compatibility

---

.changeset/pink-walls-hide.md
templates/remix/remix.config.js

template: enable unstable_dev by default in the remix template

---

packages/remix-dev/devServer_unstable/index.ts

fix(dev): tracking of prev build even when rebuilds are interrupted

---

.changeset/dev-server.md
.changeset/modern-ways-eat.md
integration/hmr-test.ts
packages/remix-cloudflare/index.ts
packages/remix-deno/index.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-node/index.ts
packages/remix-serve/cli.ts
packages/remix-server-runtime/dev.ts
packages/remix-server-runtime/index.ts
templates/express/server.ts

chore: rename devReady to broadcastDevReady

---

.changeset/thin-knives-try.md
packages/remix-dev/compiler/compiler.ts

fix(dev): show first compilation error when build fails

---

.changeset/splat-index-matching-revert.md
.changeset/splat-index-matching.md
docs/tutorials/jokes.md
integration/revalidate-test.ts
integration/root-route-test.ts
integration/splat-routes-test.ts
packages/remix-dev/CHANGELOG.md
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts
packages/remix-server-runtime/CHANGELOG.md

Reverts PR #6130 (issue #5841)
Before #6130, Remix was creating a route tree as follows:
```jsx
<Route path="" element={<Root />}>
{ /* routes/ directory */}
</Route>
```
#6130 removed `path=""` from the root route:
```jsx
<Route element={<Root />}>
{ /* routes/ directory */}
</Route>
```
This allowed a sole `routes/$.jsx` to match the `/` route because root is now a _true_ pathless route.  
However, it breaks the previous Remix behavior that that `root.jsx` alone no longer matches `/`, so while it's not a super-communicated feature, you could no longer create remix apps with simple `root.jsx` and no `routes/` directory.

Revert "Fix splat route index matching

---

.changeset/bump-router-pre-2.md
docs/tutorials/jokes.md
packages/remix-dev/CHANGELOG.md
packages/remix-react/package.json
packages/remix-server-runtime/CHANGELOG.md
packages/remix-testing/package.json
yarn.lock

Bump router version to pick up https://github.com/remix-run/react-router/pull/10409

Bump to latest router prerelease

---

docs/guides/streaming.md

- SerializedFrom => SerializeFrom
- useAsyncValue() is not (yet?) generic
Closes: #6040

docs(streaming): Fix useAsyncValue example

---

packages/remix-vercel/__tests__/server-test.ts
packages/remix-vercel/package.json
yarn.lock

As noted by @TooTallNate in https://github.com/vercel/vercel/pull/9745#issuecomment-1519196324, we can replace `@vercel/node-bridge` with `http`

tests(remix-vercel): remove `@vercel/node-bridge` usage

---

contributors.yml
docs/tutorials/blog.md

Avoids instances like [this](https://stackoverflow.com/questions/70592530/not-able-to-import-marked-js-from-types-marked-in-react-app) where users may have thought that they only needed to run the TypeScript line to install `marked`, but both are required for TypeScript users.
Closes:

docs(tutorials/blog): clarify `@types/marked` installation is additional for TS users

---

contributors.yml
docs/tutorials/jokes.md

Simple docs change
The jokes tutorial tells the reader to install ts-node to the project dependencies, but then to run the seed script as though it's installed globally. This just adds `npx` before the ts-node seed script command because that's needed for users (like me) who don't have ts-node installed globally. This will probably be especially helpful for those coming from a non-frontend background.

docs(tutorials/jokes): Use npx when calling ts-node

---

contributors.yml
docs/pages/v2.md

I corrected the method for obtaining the `pathname` from `useNavigation`

docs(pages/v2): Fix navigation formAction in v2 documentation page

---

contributors.yml
docs/guides/not-found.md

This is a fix to set `statusText` correctly in the [not-found](https://remix.run/docs/en/main/guides/not-found#how-to-send-a-404) guide example.
I assume the example is meant to set "statusText" and not the response body, because the following CatchBoundary displays it:
```jsx
...
<h1>
{caught.status} {caught.statusText}
</h1>
...
```

docs(guides/not-found): Set statusText correctly in not-found guide

---

.github/workflows/deployments.yml
.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/reusable-test.yml
.github/workflows/stacks.yml

Reverts remix-run/remix#6178
it's currently cancelling the comment, deploy tests, and stack tests for nightly and changeset releases https://github.com/remix-run/remix/actions/runs/4843033118, https://github.com/remix-run/remix/actions/runs/4833273314

Revert "chore: remove `styfle/cancel-workflow-action` usage"

---

.eslintrc.js
docs/guides/constraints.md
docs/guides/streaming.md
docs/guides/styling.md
docs/other-api/adapter.md
docs/pages/technical-explanation.md
packages/remix-dev/config/defaults/cloudflare/entry.server.react-string.tsx
packages/remix-dev/config/defaults/deno/entry.server.react-string.tsx
packages/remix-dev/config/defaults/node/entry.server.react-stream.tsx
packages/remix-dev/config/defaults/node/entry.server.react-string.tsx
templates/arc/app/entry.server.tsx
templates/arc/server.ts
templates/express/app/entry.server.tsx
templates/fly/app/entry.server.tsx
templates/netlify/app/entry.server.tsx
templates/netlify/server.ts
templates/remix/app/entry.server.tsx
templates/vercel/app/entry.server.tsx
templates/vercel/server.ts

Using the same rules as we do in the `examples` & stack repos
https://github.com/remix-run/examples/blob/main/.eslintrc.js
https://github.com/remix-run/indie-stack/blob/main/.eslintrc.repo.js
https://github.com/remix-run/blues-stack/blob/main/.eslintrc.repo.js
https://github.com/remix-run/grunge-stack/blob/main/.eslintrc.repo.js
---
Follow-up of https://github.com/remix-run/indie-stack/pull/223, https://github.com/remix-run/blues-stack/pull/176 & https://github.com/remix-run/grunge-stack/pull/142

chore(docs,templates): lint with same rules as examples/stacks

---

contributors.yml
templates/cloudflare-pages/public/_headers
templates/netlify/netlify.toml

This is a minor improvement to both the Netlify and Cloudflare Pages templates to include the `immutable` directive in the `Cache-Control` header for the hashed build assets. This removes the `s-maxage` for those as well since they are redundant to the `max-age` given they are equal. These now exactly match `Cache-Control` headers for hashes assets in the Deno, Express, and fly.io (via `remix-serve`) templates.
See `immutable` docs here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control#immutable

templates(cloudflare-pages,netlify): add `immutable` to `Cache-Control` header

---

.changeset/export-use-match.md
contributors.yml
packages/remix-react/index.tsx

This is useful if you need to give a component some added functionality if a specific path is "active" or not.

feat(remix-react): export `react-router-dom`'s `useMatch` hook

---

.changeset/better-opt-out-of-revalidations.md
integration/hmr-log-test.ts
integration/hmr-test.ts
packages/remix-react/routes.tsx

Closes: #
Updated existing tests to always try to revalidate and validates they opt out for HMR only changes.

fix: better opt out of loader revalidation on UI only changes

---

.changeset/good-laws-marry.md
packages/remix-dev/devServer_unstable/index.ts

Fixes #6283
Testing: Added a `setTimeout` locally to artificially delay `p.kill` to simulate a slow-to-kill process for the app server. Confirmed that this code was resilient and waited for process to be killed before proceeding to spin up new app server instance and that `EADDRINUSE` was not encountered.

fix(dev): wait until app server is killed before starting a new app server

---

.changeset/light-bikes-exercise.md
packages/remix-dev/compiler/watch.ts

before this, `entryPoints` were normalized to use unix path separators (`/`) where `file` and `appFile` were using windows path separators (`\\`)
commit was done in parallels on windows 11 where i don't have gpg set up, sue me
Closes: #5247 
Testing Strategy: local testing on windows

fix(remix-dev): normalize path before testing if it is a route entry

---

.github/workflows/merged-pr.yml
.github/workflows/release-comments.yml

re-adds the `merged-pr` workflow that applies the `awaiting release` and properly checks that it's being run on this repo.
also bumps `mcansh/release-comment-action` to 0.4 so we can remove the label when the comment workflow runs https://github.com/mcansh/release-comment-action/pull/8
✅ edit! need to check for stable over in `mcansh/release-comment-action` before we remove the label. one sec https://github.com/mcansh/release-comment-action/pull/9

ci: re-add merged pr workflow 

---

.changeset/poor-nails-warn.md
packages/remix-dev/compiler/compiler.ts
packages/remix-dev/compiler/watch.ts
packages/remix-dev/devServer_unstable/index.ts

previously there was a race where the app server could respond with the updated manifest version (aka build hash) _before_ the dev server was listening for that version.
Closes: #

fix(dev): dev server listens for updated build hash before writing server files

---

.changeset/twenty-toys-laugh.md
packages/remix-dev/compiler/cancel.ts
packages/remix-dev/compiler/js/plugins/cssBundleUpdate.ts
packages/remix-dev/compiler/server/plugins/manifest.ts
packages/remix-dev/compiler/utils/log.ts
packages/remix-dev/compiler/watch.ts

Fixes #6285
by canceling the previous build when a new rebuild is kicked off
Tested locally by hitting <kbd>Cmd</kbd> + <kbd>S</kbd> quickly and repeatedly with the Remix App Server template with `unstable_dev: true` set. Hangs in 1.16, but continues to rebuild correctly with these changes.

fix(dev): prevent rebuilds from hanging

---

.changeset/ninety-flies-allow.md
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/devServer_unstable/index.ts

When sending HMR updates, the assumption was that serving assets from dev server would allow those updates to be sent immediately, without waiting for the app server to restart. But this isn't the case (e.g. if you navigate to another page that has a loader and the app server is rebooting, that loader fetch will fail).
---
Idea moving forward is:
1) If you don't mind a bit of downtime from your app server during dev, then you can rely on Remix restarts. but you'll need to wait for app server to reboot before you hard refresh or click buttons that trigger actions, or navigate to different pages that need loaders.
2) if that amount of downtime is too much for you, using chokidar and purgeRequireCache w/ --no-restart and that will keep you zipping along with an always-up server.
Note: during …

refactor(dev): revert serving assets from dev server

---

contributors.yml
docs/tutorials/blog.md

Hi! 
This PR adds a whitespace character to the label of the Markdown input field in the create post form, in line with a similar change made in a later step of the tutorial.
The original code did not have a whitespace character after the colon, which caused a visual inconsistency with the other labels in a later step that was corrected by adding the whitespace character. This PR adds the whitespace character to the earlier step for consistency.

docs(tutorials/blog): Fix markdown label spacing

---

.changeset/afraid-coats-count.md
integration/hmr-log-test.ts
integration/hmr-test.ts
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/compiler.ts
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/js/plugins/routes_unstable.ts
packages/remix-dev/compiler/manifest.ts
packages/remix-dev/compiler/options.ts
packages/remix-dev/compiler/server/plugins/entry.ts
packages/remix-dev/compiler/watch.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer_unstable/hdr.ts
packages/remix-dev/devServer_unstable/hmr.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-dev/manifest.ts
packages/remix-react/browser.tsx
packages/remix-react/components.tsx
packages/remix-react/routes.tsx

feat(dev): cross-module loader change detection

---

.changeset/calm-falcons-boil.md
integration/css-side-effect-imports-test.ts
packages/remix-dev/compiler/plugins/cssSideEffectImports.ts

Closes: #5331
This fixes an issue where the CSS side-effect imports plugin mistakenly assumed that JS files don't contain JSX, but this is out of step with the rest of Remix.
I've validated that `.mjs` and `.cjs` files don't support JSX in Remix, so this issue only affects JS files.
I've added a test to catch this, ensuring that the test fails against the latest code in dev.

fix(dev): fix JSX in JS files with CSS imports

---

packages/remix-dev/devServer_unstable/index.ts

fix(dev): use `;` for joining PATHs in windows

---

contributors.yml
docs/guides/styling.md

Corrects the fragment for the tailwind css docs, from #tailwind to #tailwind-css

docs(guide/styles): Fix anchor for tailwind css

---

.changeset/slimy-snakes-do.md
packages/remix-dev/compiler/plugins/vanillaExtract.ts

Closes: #6314
This ensures that, in the rare case that someone is using a .css.js/ts file extension when _not_ using Vanilla Extract in their app, we don't inadvertently try to process it with the Vanilla Extract plugin.

fix(dev): skip Vanilla Extract plugin if not installed

---

docs/guides/styling.md

As a follow-up to #6315, I'm adding a warning to the Tailwind documentation to recommend avoiding Tailwind's `@import` syntax in favour of the Tailwind directives.

docs(guides/styling): add Tailwind import warning

---

contributors.yml
docs/guides/styling.md

When you first finish the Tailwind setup and start up the app, I was confused to see the following warning:
```
warn - No utility classes were detected in your source files. If this is unexpected, double-check the `content` option in your Tailwind CSS configuration.
warn - https://tailwindcss.com/docs/content-configuration
```
Turns out I just hadn't used Tailwind yet, so I added this note so others don't go around wondering what they did wrong.

docs(guides/styling): add note about Tailwind warning

---

.changeset/fix-css-bundle-server-client-mismatch.md
.changeset/include-css-bundle-in-manifest-hash.md
packages/remix-dev/compiler/manifest.ts

Fixes #6369
The `cssBundleHref` value wasn't being included in the hash in the manifest file name. This means that CSS bundle changes weren't busting the manifest cache. I've also refactored the code to try to avoid this issue coming back when further changes are made to the manifest structure.

fix(dev): include `cssBundleHref` in manifest hash

---

.changeset/polite-garlics-invite.md
contributors.yml
packages/remix-server-runtime/sessions.ts

This is just the relevant parts of the code changes from #6325 instead of also tackling eslint-config changes.
- Expose methods in the `SessionStorage` interface as arrow functions so destructuring is correctly part of the contract.
I attempted to add the typescript-eslint rules contained in ["plugin:@typescript-eslint/recommended-requiring-type-checking"](https://typescript-eslint.io/linting/configs#recommended-requiring-type-checking) to a Remix based project and came across two common code issues:
```js
const { pipe, abort } = renderToPipeableStream();
```
and then on:
```js
const { getSession, commitSession, destroySession } = createDatabaseSessionStorage();
```
Both of these cause an `unbound-method` error:
> error  Avoid referencing unbound methods which may cause unintentional …

refactor(remix-server-runtime): expose `SessionStorage`'s methods as arrow functions

---

contributors.yml
packages/remix-cloudflare-pages/worker.ts

As context.env type is defined in [@cloudfare/worker-types](https://github.com/cloudflare/workerd/blob/main/types/defines/pages.d.ts)
we can somehow remove the annotation as any in woker.ts. :)
menthioned in #6341 , As this change is touching package, move this to dev branch

chore(remix-cloudflare-pages): remove unnecessary typecast 

---

docs/tutorials/jokes.md

This reverts @machour's #6209 as `URLSearchParams.get` returns a value of type `string | null`.
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/get#return_value
The mentioned problem in #5843 was already fixed in #6050

docs(tutorials/jokes): remove unnecessary typecast

---

integration/helpers/node-template/package.json
package.json
packages/remix-dev/compiler/plugins/vanillaExtract.ts
yarn.lock

Closes #6314.
This fixes an issue with our (currently unreleased) Vanilla Extract detection logic which is intended to disable Vanilla Extract support for consumers who aren't using it.
Because we're using `require.resolve` to check for the presence of the `@vanilla-extract/css` package, in the case of a flattened node_modules directory, some consumers can get false positives. This is because Remix depends on `@vanilla-extract/integration` to manage the esbuild integration, but that package depends on `@vanilla-extract/css`. I've seen this myself where `npx create-remix@latest` using npm to install dependencies results in `@vanilla-extract/css` being requirable from my app.
Instead, we now check the app's package.json to ensure that they have a direct dependency on `@vanilla-extract/css`.

fix(dev): detect Vanilla Extract in package.json

---

.changeset/expose-error-headers.md
integration/headers-test.ts
packages/remix-server-runtime/headers.ts
packages/remix-server-runtime/routeModules.ts

We have a gap in the API currently where you cannot access headers from child-route-thrown-responses because we only run `headers()` from "renderable" matches (which means root down to the boundary).  So if you `throw new Response()` from `/parent/child` and catch it in `/parent` - you have no way to send any child headers back from the `/parent` `headers()` function.
This PR adds a new `errorHeaders` parameter to `headers()` that holds the headers from any thrown Response triggering the error boundary.
If the route that throws the response is also the boundary route, then `errorHeaders` will be the same as what's already passed as `loaderHeaders`/`actionHeaders`.
We also only expose the `errorHeaders` to the leaf renderable match `headers()` function to avoid duplicating the header value …

Surface thrown response headers to ancestor boundaries

---

scripts/playground/template/.gitignore
scripts/playground/template/app/root.tsx
scripts/playground/template/app/styles/tailwind.css
scripts/playground/template/package.json
scripts/playground/template/remix.config.js

When running `yarn playground:new`, the default template uses Tailwind but doesn't use the new built-in Tailwind support. It also doesn't include the `@remix-run/css-bundle` boilerplate which is a bit of a slowdown if you're wanting to iterate on CSS bundling features.

chore: update playground template CSS setup

---

contributors.yml
docs/file-conventions/route-files-v2.md

fix: change wrong code lines highlight
There is a wrong line highlighting in [Dot Delimiters](https://remix.run/docs/en/main/file-conventions/route-files-v2#dot-delimiters) section that this commit will fix it.

docs(file-conventions/route-files-v2): fix code highlighting

---

.changeset/lemon-beers-fetch.md
packages/remix-server-runtime/serialize.ts

feat: simplified types for useLoaderData, useActionData, useFetcher, SerializeFrom

---

contributors.yml
docs/tutorials/jokes.md

The session secrets are used to `sign` the cookie, not to `encrypt` it. This mistake can lead to dangerously wrong assumptions 🙂

fix typo in jokes app tutorial

---

.changeset/error-response-resource-route.md
integration/resource-routes-test.ts
packages/remix-server-runtime/server.ts

Properly handle ErrorResponse inside resource routes

---

.changeset/great-geese-compare.md
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/plugins/cssSideEffectImports.ts
packages/remix-react/components.tsx
packages/remix-server-runtime/serialize.ts

perf(dev): faster server export removal for routes

---

.changeset/strong-dolphins-tell.md
integration/hmr-log-test.ts
integration/hmr-test.ts
packages/remix-dev/devServer_unstable/hdr.ts
packages/remix-dev/devServer_unstable/index.ts

Fixes #6448
Introduces a step in the HMR/HDR integration test where invalid syntax is written to a route and then subsequently fixed. Dev server does not crash and correctly applies HMR/HDR when fix is written.

fix(dev): gracefully handle hdr errors

---

.changeset/wicked-pandas-give.md
integration/hmr-log-test.ts
integration/hmr-test.ts
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/options.ts
packages/remix-dev/compiler/server/compiler.ts
packages/remix-dev/compiler/server/plugins/entry.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-dev/devServer_unstable/socket.ts
packages/remix-react/__tests__/components-test.tsx
packages/remix-react/browser.tsx
packages/remix-react/components.tsx
packages/remix-react/entry.ts
packages/remix-server-runtime/build.ts
packages/remix-server-runtime/serverHandoff.ts

feat(dev): reuse dev server port for websocket

---

.changeset/rude-geese-remain.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/devServer_unstable/index.ts

fix(dev): better error message when `remix-serve` is not found

---

contributors.yml
docs/guides/not-found.md

I believe `CDNS` is meant to be `CDNs`, the plural of CDN. 🙂

docs(guides/not-found): fix typo

---

contributors.yml
docs/hooks/use-matches.md

Noticed that line 9 was missing in the highlighting whilst checking the docs.

docs(hooks/use-matches): fix code highlighting

---

docs/guides/migrating-react-router-app.md
docs/guides/streaming.md
docs/guides/styling.md
docs/route/headers.md
integration/defer-test.ts
packages/remix-dev/__tests__/fixtures/indie-stack/app/entry.server.tsx
packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/app/entry.server.tsx
packages/remix-dev/__tests__/fixtures/stack/app/entry.server.tsx
packages/remix-dev/config/defaults/cloudflare/entry.server.react-stream.tsx
packages/remix-dev/config/defaults/cloudflare/entry.server.react-string.tsx
packages/remix-dev/config/defaults/deno/entry.server.react-stream.tsx
packages/remix-dev/config/defaults/deno/entry.server.react-string.tsx
packages/remix-dev/config/defaults/node/entry.server.react-stream.tsx
packages/remix-dev/config/defaults/node/entry.server.react-string.tsx
scripts/playground/template/app/entry.server.tsx
templates/arc/app/entry.server.tsx
templates/cloudflare-pages/app/entry.server.tsx
templates/cloudflare-workers/app/entry.server.tsx
templates/deno/app/entry.server.tsx
templates/express/app/entry.server.tsx
templates/fly/app/entry.server.tsx
templates/netlify/app/entry.server.tsx
templates/remix/app/entry.server.tsx
templates/vercel/app/entry.server.tsx

templates: have `loadContext` available in `handleRequest`

---

packages/remix-react/components.tsx

Fix a missing space. Before this patch, the warnings print as:
```
⚠️ REMIX FUTURE CHANGE: `fetcher.type` will be removed in v2. Please use `fetcher.state`, `fetcher.formData`, and `fetcher.data` to achieve the same UX.For instructions on making this change see https://remix.run/docs/en/v1.15.0/pages/v2#usefetcher
```
Note the lack of space between "UX." and "For".

fix(remix-react): fix typos in V2 warnings

---

scripts/copy-build-to-dist.mjs

I ran into this issue while working on #6509 which resulted in tests failing on Windows in CI. Since that PR is now closed, I've pulled out this fix into its own PR.

chore: fix copy-build-to-dist script on Windows

---

.changeset/chilly-shoes-scream.md
contributors.yml
packages/remix-dev/cli/run.ts

Hi team, I'm a maintainer of SST. SST helps Remix users [deploy their Remix apps to AWS](https://docs.sst.dev/start/remix).
We've received feedback indicating that the `Architect (AWS Lambda)` option in the `create-remix` flow is causing some confusion. SST wraps around the default `Remix App Server` inside a Lambda handler, but we've noticed several users mistakenly selecting the `Architect (AWS Lambda)` deployment target. (please see the attached screenshot for reference)
This PR removed the `AWS Lambda` copy from the `Architect` deployment target to alleviate this confusion.

fix(remix-dev/cli): remove `AWS Lamba` copy

---

packages/remix-vercel/index.ts
templates/vercel/README.md

As @mcansh mentioned in https://github.com/remix-run/remix/pull/5734#issuecomment-1478469486

feat(remix-vercel): show deprecation warning on usage

---

integration/bug-report-test.ts
integration/catch-boundary-data-test.ts
integration/catch-boundary-test.ts
integration/defer-test.ts
integration/error-boundary-test.ts
integration/fetcher-state-test.ts
integration/form-test.ts
integration/hmr-log-test.ts
integration/hmr-test.ts
integration/navigation-state-v2-test.ts
integration/transition-state-test.ts

This addresses a couple of issues:
- HMR tests timing out.
- Flaky tests seemingly due to APIs responding faster and more often than the UI updates.
We still have some non-blocking flaky test issues, but the main thing is that the HMR tests are no longer blocking builds in CI due to persistent timeouts.

test: fix integration tests

---

.changeset/orange-beds-explode.md
integration/compiler-test.ts
integration/esm-only-warning-test.ts
integration/flat-routes-test.ts
packages/remix-dev/__tests__/create-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/compiler/context.ts
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/options.ts
packages/remix-dev/compiler/plugins/deprecatedRemixPackage.ts
packages/remix-dev/compiler/server/plugins/bareImports.ts
packages/remix-dev/compiler/watch.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer/liveReload.ts
packages/remix-dev/devServer_unstable/env.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-dev/devServer_unstable/socket.ts
packages/remix-dev/package.json
packages/remix-dev/tux/format.ts
packages/remix-dev/tux/index.ts
packages/remix-dev/tux/logger.ts

feat(dev): prettier logging for `remix build` and `remix dev`

---

.changeset/dual-forward-bug.md
integration/browser-entry-test.ts
packages/remix-react/browser.tsx
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/serverHandoff.ts

This can happen when entry.client.ts isn't fully loaded before a route change occurs.
The fix is to validate the route's module is loaded, and if not, simply reload the page. Credit to @brophdawg11 who suggested this approach here: https://github.com/remix-run/remix/issues/1757#issuecomment-1401023829
See https://github.com/remix-run/remix/issues/1757 for more info.
Closes: #1757
- added a new test (included in this PR) named browser-entry-test.ts

fix: reload page when routeModules doesn't contain module for current route

---

packages/remix-architect/package.json

The `@remix-run/architect` package exports types that depend upon `@types/aws-lambda`, so it needs to depend (not devDepend) on it.
This will fix the following error that occurs on a freshly bootstrapped Architect project generated with create-remix:
```
$ npm run typecheck
> typecheck
> tsc
node_modules/@remix-run/architect/dist/server.d.ts:3:135 - error TS2307: Cannot find module 'aws-lambda' or its corresponding type declarations.
3 import type { APIGatewayProxyEventHeaders, APIGatewayProxyEventV2, APIGatewayProxyHandlerV2, APIGatewayProxyStructuredResultV2 } from "aws-lambda";
~~~~~~~~~~~~
```
See https://stackoverflow.com/a/46011417/167694.
Addresses part of #6296.

Move `@types/aws-lambda` from devDependencies to dependencies

---

.github/workflows/merged-pr.yml

This approach was added in https://github.com/remix-run/remix/pull/6277, but I've gotten a few notifications that it failed on recently merged PRs of mine:  https://github.com/remix-run/remix/actions/workflows/merged-pr.yml.
```
Run actions/github-script@v6
...
TypeError: Cannot read properties of undefined (reading 'addLabels')
at eval (eval at callAsyncFunction (/home/runner/work/_actions/actions/github-script/v6/dist/index.js:1514[3](https://github.com/remix-run/remix/actions/runs/5060206394/jobs/9082772469#step:2:3):16), <anonymous>:3:21)
...
Error: Unhandled error: TypeError: Cannot read properties of undefined (reading 'addLabels')
```
It seems the last successful run was using a different workflow entirely.  I think we might just have a bad script based on what the docs show for …

Fix add labels workflow for merged PRs

---

.changeset/typescript-eslint-recommended.md
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/compiler/server/plugins/bareImports.ts
packages/remix-dev/server-build.ts
packages/remix-eslint-config/index.js
packages/remix-eslint-config/internal.js
packages/remix-eslint-config/rules/core.js
packages/remix-eslint-config/rules/import.js
packages/remix-eslint-config/rules/typescript.js
packages/remix-netlify/__tests__/server-test.ts
packages/remix-node/__tests__/fetch-test.ts
packages/remix-react/__tests__/deferred-scripts-test.tsx
packages/remix-server-runtime/__tests__/serialize-test.ts
packages/remix-server-runtime/responses.ts

Continuation of https://github.com/remix-run/remix/pull/6248 for the `dev` branch

feat(remix-eslint-config): extend from typescript-eslint/recommended

---

contributors.yml
docs/guides/routing.md

Routing guide seems to have a typo in it. URL `/sales/invoices` should only match to `routes/sales.invoices.tsx` or `routes/sales.invoices._index.tsx`. This is inline with the paragraph above the example as well.

docs(guides/routing): fix typo

---

contributors.yml
docs/tutorials/jokes.md

It was redirecting us for a older version `hydrate`, I just adapted to redirect to the right doc for `hydrateRoot`
Closes: #6626 
https://remix.run/docs/en/1.17.1/tutorials/jokes#explore-the-project-structure
At this part of the tutorial, it is showing us a link to go into the `hydrate` doc, but this is the old docs of this functions, we're now using `hydrateRoot`, I just adapted the URL using the new docs

docs(tutorials/jokes): update hydrate link

---

.changeset/clever-ways-love.md
docs/other-api/adapter.md
docs/other-api/dev-v2.md
docs/other-api/dev.md
docs/pages/api-development-strategy.md
docs/pages/v2.md
integration/hmr-log-test.ts
integration/hmr-test.ts
integration/shared-route-imports-test.ts
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/config.ts
packages/remix-react/entry.ts
packages/remix-serve/cli.ts
packages/remix-server-runtime/__tests__/utils.ts
packages/remix-server-runtime/entry.ts
packages/remix-testing/create-remix-stub.tsx

feat(dev): stabilize v2 dev server

---

.changeset/rude-meals-move.md
packages/remix-dev/compiler/compiler.ts
packages/remix-dev/compiler/js/plugins/routes.ts
packages/remix-dev/compiler/manifest.ts
packages/remix-dev/devServer_unstable/hdr.ts

~~Closes~~Helps with: #6630 #6560 (?)
Existing HMR tests cover removal / addition of exports across routes.

cache getRouteModuleExports calls

---

.changeset/css-bundle-skip-node-polyfills.md
packages/remix-dev/compiler/css/compiler.ts

Since the JavaScript from the CSS bundle build is never executed and we only use the bundled CSS, there's no need to inject Node polyfills.

fix(dev): skip unused Node polyfills in CSS build

---

.changeset/css-side-effect-imports-hmr-cache.md
packages/remix-dev/compiler/plugins/cssSideEffectImports.ts
packages/remix-dev/package.json
yarn.lock

This `addSuffixToCssSideEffectImports` function used internally within `cssSideEffectImportsPlugin` had its own cache, but this caching mechanism didn't factor in the newly added HMR work.
This PR replaces the custom caching mechanism with our new `fileWatchCache`, allowing us to more easily capture all plugin logic (including the HMR transform) in the cache.

fix(dev): cache CSS side-effects transform for HMR

---

.changeset/prefetch-viewport.md
.changeset/tidy-bears-turn.md
docs/components/link.md
docs/components/nav-link.md
integration/prefetch-test.ts
packages/remix-react/components.tsx

Closes: https://canary.discord.com/channels/770287896669978684/940264701785423992/1109137291974279239

feat: add `prefetch="viewport"` support to `<Link>`

---

.changeset/five-zoos-fix.md
packages/remix-dev/__tests__/flat-routes-test.ts
packages/remix-dev/config/flat-routes.ts

#4421 added a short circuit for checking for URL conflicts with pathless layout routes, but it is unintentionally also short circuiting the line that updates the route manifest to strip the parent path.  Need to lift that up before the short circuit.  Doesn't impact root pathless layout routes, only those that are nested underneath an existing path segment which we didn't have existing tests for.
Closes #6645

Fix bug with pathless layout routes beneath nested path segments

---

.changeset/update-polyfills-plugin.md
packages/remix-dev/package.json
yarn.lock

Since this is such a big perf win, I want to be sure that Remix consumers are guaranteed to get the latest version as part of our next release.

fix(dev): update polyfills plugin to use cache

---

.changeset/css-bundle-skip-packages.md
packages/remix-dev/compiler/css/compiler.ts
packages/remix-dev/compiler/plugins/emptyModules.ts

The CSS bundle build ultimately only cares CSS imports and these packages are known not to contain any, so this PR allows esbuild to skip compilation of these packages entirely. In my basic example app using CSS bundling, I've seen builds go from ~170ms to ~120ms.

perf(dev): skip Remix/React packages in CSS build

---

.changeset/cache-regular-stylesheets.md
packages/remix-dev/compiler/plugins/cssImports.ts

This PR uses our new `fileWatchCache` to cache compilation of regular CSS imports. This avoids the need to run them through an esbuild sub-compilation if the file contents haven't changed.
This change is covered by our existing HMR tests.

perf(dev): cache regular stylesheet compilation

---

packages/remix-dev/compiler/js/compiler.ts

perf(dev): ignore server runtimes indirectly imported by deps

---

.changeset/blue-dots-glow.md
packages/remix-dev/devServer_unstable/index.ts
packages/remix-dev/devServer_unstable/proc.ts
packages/remix-dev/package.json
yarn.lock

Previously, only the immediate child process run via `-c` was killed. When that child spawned its own subprocesses (e.g. using `binode` for MSW support), _those_ descendants stuck around, causing port conflicts and other errors.
Existing HMR tests cover this. Also tested locally with Indie Stack + MSW

fix(dev): wait until all app server descendants have been killed

---

.changeset/chatty-birds-sing.md
integration/helpers/playwright-fixture.ts
package.json
packages/remix-react/package.json
packages/remix-testing/package.json
yarn.lock

Bump to `react-router-dom@6.14.0-pre.1` to include https://github.com/remix-run/react-router/pull/10627 which was why we were originally failing E2E tests on playwright 1.28 (older version of Chrome)

Bump router

---

packages/remix-dev/__tests__/cli-test.ts

The `express` template in main now uses ESM which crashes this test. This is because the code in `@remix-run/dev` that reads the config makes a special case when `NODE_ENV` is `"test"` and attempts to `require` the config rather than importing it, so this is not an issue impacting consumers. As a quick fix, this PR switches to the CJS `remix` template which still passes this test suite since it only asserts the presence of a couple of key files.

test(dev): fix CLI test

---

.changeset/tasty-bats-turn.md
packages/remix-dev/cli/commands.ts

Fixes #6709
on some terminal emulators, "clearing" only scrolls the next line to the top. on others, it erases the scrollback.
instead, let users call `clear` themselves (`clear && remix dev`) if they want to clear
Closes: #

fix(dev): do not clear screen when dev server starts

---

.changeset/pretty-moose-flow.md
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/plugins/nodePolyfillsPlugin.ts
packages/remix-dev/compiler/server/compiler.ts
packages/remix-dev/package.json
yarn.lock

Fixes #6665.
Fixes #6644 since this PR forces an update that includes a bug fix.
This PR updates to the latest version of `esbuild-plugins-node-modules-polyfill` which now lets you opt in to polyfilling of Node globals, and also fixes a bug with polyfills that use `Object.freeze` on their default exports.

fix(dev): polyfill Node process and Buffer globals

---

.changeset/hydrate-error-type.md
integration/error-sanitization-test.ts
packages/remix-react/errors.ts
packages/remix-server-runtime/errors.ts

Support proper hydration of Error subclasses

---

.changeset/popular-beers-bake.md
packages/remix-server-runtime/serialize.ts

Fixes #6701 , #6693
Reverts "pretty" types for `useLoaderData`, `useActionData`, etc...
Pretty types relied on the ability to eagerly evaluate types, but this can cause infinite recursion or errors with circular referenced types.
Tested in [Typescript playground](https://www.typescriptlang.org/play?target=6&jsx=4&module=1&isolatedModules=true&pretty=false#code/JYWwDg9gTgLgBAbzgKwM4QHZwL5wGZQQhwDkAAlAKYjAAeAtFAK4YD0GEAJpSQFCiRYiOAGUYUYGEo58hYiVTjJPfuGjwkALxkEipTVxIBuXqcq1B8GAE8pcACq3KnAEqVUkDKkoAee3ABeOBYAaw4AdwwAPkC4AHkaGB83D0xvABo4ACI0TCyYgDJEXjgUdAwACgBKAC44AAU5YG8-KJNsE14bOwApcsbQYBhgADdpAJK4AB84RQkMAHNJmYwmEAAjSihluHWICAAbSgBDDB2xeaXSmYA5Nc3t67gAIX2j053Vg4OTbukbzB9TADRKjcbBDDcPDADDOaZwABiLAAxsNMPDUNYNodOqwAFQlPFwAAGp2sxLgzTgMAAFtJMAdrNSnNSacd4MjTnAjvBrBAmHBKABHJjs6TEgAMFPCQxpJIAjMTCaJK …

fix: avoid circular references and infinitely recursive types

---

contributors.yml
docs/other-api/dev-v2.md

Closes https://github.com/remix-run/remix/issues/6754

fix(docs): Avoid ghost value creation when using `app/utils/remember.ts`

---

.changeset/dry-items-deliver.md
docs/other-api/dev-v2.md
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/options.ts
packages/remix-dev/compiler/server/compiler.ts
packages/remix-dev/compiler/server/plugins/entry.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer_unstable/index.ts
packages/remix-dev/server-build.ts
packages/remix-react/__tests__/components-test.tsx
packages/remix-react/components.tsx
packages/remix-server-runtime/build.ts
packages/remix-server-runtime/dev.ts
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/serverHandoff.ts

Fixes #6718
Supercedes #5467
Tested my running creating TLS key/cert for `myhost` and running:
```sh
REMIX_DEV_ORIGIN=https://myhost remix dev --no-restart -c \"node server.js\" --tls-key=key.pem --tls-cert=cert.pem --port=443
```
👆 Note that origin can omit the port since the default HTTPS port of 443 is used. Also tested with `tlsKey` and `tlsCert` config options.
Also tried with the same command without `REMIX_DEV_ORIGIN` to ensure that TLS protocols (`https`/`wss`) are correctly inferred from TLS flags and config options.
Finally, also tested that `REMIX_DEV_SERVER_WS_PORT` works to set the ws port for the old dev server.

fix(dev): better networking options

---

contributors.yml
docs/tutorials/blog.md

Update Blog tutorial document by correct string syntax, remove template literals syntax for string without variable

docs(tutorials/blog): don't use unnecessary string literals

---

.changeset/nine-islands-mate.md
packages/remix-dev/compiler/js/plugins/hmr.ts

fix(dev): fix sourcemaps for v2_dev

---

.changeset/red-bananas-design.md
packages/remix-dev/compiler/analysis.ts
packages/remix-dev/compiler/css/compiler.ts
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/server/compiler.ts

feat(dev): output esbuild metafiles for bundle analysis

---

.changeset/kind-coins-attack.md
packages/remix-dev/devServer_unstable/proc.ts

fix(dev): ignore errors when killing already dead processes

---

contributors.yml
docs/tutorials/blog.md

Since the tutorial uses the V2 folder structure, the admin route is no longer created within the `posts` directory.
Closes: (not a reported issue)
Went through the tutorial 😄

docs(tutorials/blog): admin route no longer lives in the `posts` dir

---

templates/arc/plugin-remix.js

Fixes #198.
I ran `npx create-remix@latest`, created a new Architect project, and ran `npm run dev`. I opened a browser, turned on developer tools, and showed the JavaScript console. Here are screen shots before and after this patch, showing that the #198 is fixed.

fix: propagate NODE_ENV to application in arc sandbox mode

---

packages/remix-dev/compiler/analysis.ts

also avoids any race conditions when checking for existence of dirs/file
Closes: #

fix(dev): ensure build dir exists when writing metafiles

---

templates/arc/README.md

Thanks to #6757 and #6781, these are no longer needed.
See https://github.com/remix-run/grunge-stack/pull/154#issuecomment-1626080936.

templates(arc): remove `preferences.arc` instructions

---

docs/components/form.md
docs/guides/data-writes.md
docs/hooks/use-action-data.md
docs/hooks/use-fetcher.md
docs/hooks/use-submit.md
docs/pages/technical-explanation.md
integration/link-test.ts

Took over some extra docs changes @brophdawg11 did in #5689

docs: use `useNavigation` instead of `useTransition`

---

.changeset/chatty-pears-float.md
contributors.yml
packages/remix-react/transition.ts

I believe that there is a typing issue with fetchers where the encType is not typed correctly, I noticed this when using useNavigate where the hook was typed but the fetcher wasn't so I tracked it down and fixed it.
Import useFetcher or useFetchers
The type of formEncType should be FormEncType | undefined instead of string | undefined

fix(remix-react): fix `fetcher.formEncType`

---

.changeset/handle-network-errors.md
integration/error-boundary-v2-test.ts
packages/remix-react/data.ts
packages/remix-server-runtime/__tests__/data-test.ts
packages/remix-server-runtime/server.ts

If we make a `?_data` `fetch` and it never actually reaches the Remix server, and instead we get a 4xx/5xx response back from a CDN/Proxy/Load Balancer, etc., then we currently incorrectly think it's a returned response from a `loader`/`action` since it's perfectly valid to:
```js
export function loader() {
return json({ isTeapot: true }, { status: 418 });
}
```
This PR adds an `X-Remix-Response: yes` header to successful responses for `?_data` requests so we can differentiate responses that reached the Remix server from those that did not - and we can treat CDN/Proxy errors as real errors and surface them to the `ErrorBoundary`.
Closes #5418

Properly handle in-flight network errors on _data requests

---

.changeset/deferred-data-hang.md
integration/defer-test.ts
packages/remix-react/components.tsx
packages/remix-react/entry.ts
packages/remix-react/server.tsx
packages/remix-server-runtime/entry.ts
packages/remix-server-runtime/server.ts

fix: invalid deferred data hanging response

---

integration/scroll-test.ts
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
yarn.lock

Integration tests for https://github.com/remix-run/react-router/pull/10642.  These won't pass in CI until we do the next RR release and get Remix bumped.

Add tests for scroll hash decoding

---

.changeset/large-dodos-bathe.md
integration/form-test.ts
packages/remix-node/package.json
yarn.lock

Failing test until https://github.com/remix-run/web-std-io/pull/28 is merged

Add failing test for empty file input uploads

---

.changeset/shaggy-boats-explain.md
contributors.yml
packages/remix-server-runtime/__tests__/server-test.ts
packages/remix-server-runtime/server.ts

Closes https://github.com/remix-run/remix/pull/5738

Fix bug with ?_data request on non-matching route

---

.changeset/hot-ducks-march.md
docs/guides/dev-perf.md
docs/guides/manual-mode.md
docs/guides/performance.md
docs/other-api/dev-v2.md
docs/pages/v2.md
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/config.ts
packages/remix-dev/devServer_unstable/index.ts

chore(dev): warn if not using `v2_dev`

---

templates/cloudflare-pages/remix.config.js
templates/cloudflare-workers/remix.config.js

The change for the `serverConditions` of the templates of `cloudflare-pages` and `cloudflare-workers` was mentioned here by @huw:
- https://github.com/remix-run/remix/pull/6229#discussion_r1181993844
- https://github.com/remix-run/remix/pull/6650#discussion_r1240184974
Unfortunately, however, this was not addressed. Therefore I would like to have clarity whether it is recommended to adjust the `serverConditions` or to leave them at `worker`.
> I think this should be `["workerd", "worker", "browser"]`:
> 
> * `workerd` is the new standard for Cloudflare Workers and could have slightly different code, usually optimised for edge runtimes. This is being adopted by React [with a different bundle from their browser bundle](https://github.com/facebook/react/blob/559e83aebb2026035d47aa0ebf842f78d4 …

templates(cloudflare-pages,cloudflare-workers): adjust `serverConditions`

---

.changeset/nice-moons-kick.md
.changeset/server-node-builtins-polyfill.md
docs/file-conventions/remix-config.md
packages/remix-dev/compiler/server/compiler.ts
packages/remix-dev/config.ts
packages/remix-dev/package.json
yarn.lock

Closes #6665.
This modifies the API for the `serverNodeBuiltinsPolyfill` option so that you can also opt into empty polyfills. This is because our old polyfill setup provided empty polyfills by default for `fs`, `crypto`, `dns`, `dgram`, `cluster`, `repl` and `tls`.
Note that I've nested the modules config within an object (matching the API of esbuild-plugins-node-modules-polyfill) so that we can add more options in the future without it being a breaking change.

feat(dev): support empty server polyfills

---

docs/pages/v2.md
templates/arc/package.json
templates/cloudflare-pages/package.json
templates/cloudflare-workers/package.json
templates/express/package.json

The `--no-restart` flag is deprecated and replaced with `--manual`. We forgot to update it in one place in the docs and in several of the templates.

Rename --no-restart to --manual in docs and templates

---

.changeset/fuzzy-mugs-swim.md
integration/cf-compiler-test.ts
packages/remix-cloudflare/index.ts

feat(remix-cloudflare)!: remove `createCloudflareKVSessionStorage`

---

contributors.yml
templates/cloudflare-workers/server.ts

Fixes #6891 (discussed there)
This change removes the deprecated `build.dev` from the `cloudflare-workers` template, which was the only template that still used it, and replaces it with `process.env.NODE_ENV`. This brings it in line with the `cloudflare-pages` template.
This is arguably better than the previous solution as Remix uses an ESBuild `define` to replace `process.env.NODE_ENV` at compile-time, which means the whole code path will be tree-shaken out of production bundles. For the same reason, it’s better than using Cloudflare-specific methods for checking for the environment.

Remove `build.dev` in favour of `process.env.NODE_ENV` in the Cloudflare Workers template

---

packages/remix-dev/devServer/liveReload.ts

This prevents the WebSocket connection from being closed due to inactivity when using a proxy like Cloudflare.
Run a remix app in dev mode and load it via a [Cloudflare tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/):
```sh
npm run dev & cloudflared tunnel --url http://localhost:57763
```
Now open the tunnel URL and wait 100 seconds. The socket connection will be closed and the page will reload.

liveReload: add hearbeat for keepalive

---

packages/remix-dev/devServer/liveReload.ts
packages/remix-dev/devServer_unstable/socket.ts

This updates #6904 to apply the heartbeat to both version of the live-reload server.
Run a remix app in dev mode and load it via a [Cloudflare tunnel](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/do-more-with-tunnels/trycloudflare/):
```sh
npm run dev & cloudflared tunnel --url http://localhost:57763
```
Now open the tunnel URL and wait 100 seconds. The socket connection will be closed and the page will reload.

Heartbeat: implement in both live-reload servers

---

.changeset/seven-queens-try.md
packages/remix-cloudflare-pages/package.json
packages/remix-cloudflare-workers/package.json
packages/remix-cloudflare/package.json
templates/cloudflare-pages/package.json
templates/cloudflare-workers/package.json
yarn.lock

feat!: drop `@cloudflare/workers-types` v2 & v3 support

---

.changeset/fluffy-fishes-lay.md
contributors.yml
packages/remix-react/components.tsx

Discussed with @pcattori [on Discord](https://discord.com/channels/770287896669978684/940264701785423992/1131949671896584322).
For live reloading, we currently use the protocol and port from the `REMIX_DEV_ORIGIN` variable, but use the hostname from `window.location`. This PR also uses the hostname from `REMIX_DEV_ORIGIN` (when provided).
This also means that we can support use cases where the development server is on a different hostname from the static assets. This is the case, for example, with GitHub Codespaces, which proxies separate ports through HTTPS on different subdomains. For example:
- `https://<CODESPACE_NAME>-3000.app.github.dev` for the static assets
- `https://<CODESPACE_NAME>-3001.app.github.dev` for the websocket
(If for whatever reason you’re a Codespaces user seeing …

Use `REMIX_DEV_ORIGIN` for the live reload hostname

---

docs/other-api/create-remix.md

Yarn doesn't support specific versions for `yarn create`, and it's redundant for `pnpm create`.

docs: remove version from yarn/pnpm create

---

templates/arc/plugin-remix.js

Closes: #6933
Manually tested in a new application initialized with create-remix.

Pass REMIX_DEV_* env vars through to app in Architect template

---

.changeset/rich-months-search.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts

refactor!(dev): remove deprecated cli args and flags

---

.changeset/moody-pants-laugh.md
packages/remix-dev/compiler/js/compiler.ts
packages/remix-dev/compiler/server/compiler.ts
packages/remix-react/__tests__/components-test.tsx
packages/remix-react/components.tsx

refactor!(dev,react): remove deprecated REMIX_DEV_SERVER_WS_PORT env var

---

templates/remix-javascript/remix.config.js

These flags have already been removed but were still in the newly-added `remix-javascript` template introduced as part of the new `create-remix` CLI.

refactor: clean flags in remix-javascript template

---

packages/create-remix/package.json

Follow-up of @markdalgleish's #6887

chore(create-remix): add missing peerDependency of `esbuild-register`

---

.changeset/decouple-css-bundle-from-dev.md
packages/remix-css-bundle/index.ts
packages/remix-dev/compiler/plugins/cssBundlePlugin.ts

This PR makes it so that the contents of the `@remix-run/css-bundle` package are entirely managed by the Remix compiler rather than injecting `cssBundleHref` value into the package contents after reading them from disk—which we only did to support HMR when `cssBundleHref` used to be on the manifest but this is no longer the case. This ensures that there are no runtime errors when upgrading `@remix-run/dev` without upgrading `@remix-run/css-bundle`.
I wanted to get this change in for v2 so that this is the case for all v2.x releases.

fix: decouple css-bundle from dev

---

docs/pages/v2.md

Adds a note on the changing `state` behavior on GET submissions in v2

Add note on get submissions to v2 docs

---

docs/pages/api-development-strategy.md

This PR rewords the API Development Strategy guide to remove references to specific versions.

docs(pages/api-development-strategy): remove v1/v2 references

---

templates/arc/remix.config.js
templates/cloudflare-pages/remix.config.js
templates/cloudflare-workers/remix.config.js
templates/express/remix.config.js
templates/fly/remix.config.js
templates/netlify/remix.config.js
templates/remix/remix.config.js
templates/vercel/remix.config.js

Since all future flags have been removed, these templates can now be cleaned up to remove all future flag config.

chore(templates): remove future flags

---

docs/pages/v2.md
templates/arc/package.json
templates/arc/server.ts
templates/express/package.json
templates/express/server.js
templates/netlify/package.json
templates/netlify/server.ts
templates/vercel/package.json
templates/vercel/server.ts

@jacob-ebey's changes from #7009 against `main`, so new projects already have this + docs are already updated for people
We still need to release the changes Jacob made for `@remix-run/serve` in a patch release so all other Node-templates (Fly & Remix) have these changes as well

templates: install `source-map-support`

---

docs/guides/typescript.md
package.json
packages/remix-architect/package.json
packages/remix-cloudflare-pages/package.json
packages/remix-cloudflare-workers/package.json
packages/remix-cloudflare/package.json
packages/remix-deno/package.json
packages/remix-dev/__tests__/fixtures/cloudflare/package.json
packages/remix-dev/__tests__/fixtures/indie-stack/package.json
packages/remix-dev/__tests__/fixtures/node/package.json
packages/remix-dev/index.ts
packages/remix-dev/package.json
packages/remix-eslint-config/package.json
packages/remix-express/package.json
packages/remix-netlify/package.json
packages/remix-node/package.json
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
packages/remix-vercel/package.json
scripts/playground/template/package.json
templates/arc/package.json
templates/cloudflare-pages/package.json
templates/cloudflare-workers/package.json
templates/express/package.json
templates/fly/package.json
templates/netlify/package.json
templates/remix/package.json
templates/vercel/package.json
yarn.lock

Since we want to use latest version of `type-fest` for simplifying some of our own types, we need at least TS 5.1
https://github.com/sindresorhus/type-fest/releases/tag/v4.0.0

feat!: set minimum TS version to 5.1

---

.changeset/dirty-beers-sing.md
contributors.yml
packages/remix-dev/cli/create.ts
packages/remix-dev/package.json
yarn.lock

Replaces https://github.com/remix-run/remix/pull/6862 to include in 1.19.2
Closes https://github.com/remix-run/remix/issues/6833

Update proxy-agent dependency

---

.changeset/many-cars-jump.md
packages/remix-netlify/index.ts

Just like we did with the Vercel adapter
We should probably release this as `1.19.2` so people still get this warning before v2 🤔

feat(remix-netlify): show deprecation warning on usage

---

.changeset/lucky-kangaroos-develop.md
packages/remix-serve/cli.ts
packages/remix-serve/package.json
yarn.lock

Follow-up of ##7009 & #7010
This should be in a patch release

feat(remix-serve): install `source-map-support`

---

.changeset/brown-seals-look.md
packages/remix-dev/config.ts
packages/remix-dev/warnOnce.ts

Recreation of https://github.com/remix-run/remix/pull/6211 against `dev`
Run against my playground app which has all flags turned on + latest `nightly`:

Warn users about obsolete future flags in remix.config.js

---

docs/other-api/dev-v2.md

docs(dev): PORT env var for remix-serve, not --port flag

---

packages/remix-dev/config.ts

Apparently, ESLint sets the NODE_ENV to test and if you are using a eslint plugin that relies on this code you'll end up requiring when you should be importing.
Because this block is for Jest specifically, we'll instead use a known environment variable in a Jest environment.
- ~~[ ] Docs~~
- ~~[ ] Tests~~
Testing Strategy: Run CI. I also verified this solves my use case with a local patch.

fix(dev): switch to JEST_WORKER_ID environment variable

---

docs/guides/styling.md

Closes #5475
Now that Tailwind and PostCSS support are both enabled by default in v2, I've expanded the docs to more explicitly address the lack of vendor prefixing when using Tailwind in isolation.

docs(styling): document Tailwind + Autoprefixer

---

.changeset/moody-seals-fetch.md
docs/file-conventions/remix-config.md
packages/remix-dev/config.ts

This should be released in a patch release
Docs pointed to in the warnings will be implemented by #7023 & #7057

feat(remix-dev): add deprecation warning about `devServerBroadcastDelay` & `devServerPort`

---

packages/remix-node/upload/fileUploadHandler.ts
yarn.lock

This will make PRs like https://github.com/remix-run/remix/pull/6038 or https://github.com/remix-run/remix/pull/6044 less necessary
Did this by running `npx yarn-deduplicate && rm -rf ./node_modules && yarn`
- https://github.com/scinos/yarn-deduplicate
- https://npm.im/yarn-deduplicate

chore: dedupe `yarn.lock`

---

package.json
packages/remix-architect/package.json
packages/remix-architect/server.ts
packages/remix-express/package.json
packages/remix-express/server.ts
packages/remix-netlify/package.json
packages/remix-netlify/server.ts
packages/remix-node/globals.ts
packages/remix-node/index.ts
packages/remix-node/package.json
packages/remix-react/package.json
packages/remix-vercel/package.json
packages/remix-vercel/server.ts
yarn.lock

`AbortSignal` is stable as of Node v15.4
https://nodejs.org/api/globals.html#class-abortcontroller
---
This PR is relying on #6108, so that one needs to be merged first

chore: remove `abort-controller` dependency

---

packages/remix-server-runtime/package.json
packages/remix-server-runtime/serialize.ts

- Extracted `Jsonify` so that it's easier to switch to `type-fest` at a later stage
- Added cases for positive/negative infinity, `Boolean`, `Number`, `String`, `Map` & `Set`
- Added more deep grained type for objects that have a `toJSON` function
- Update `UndefinedToOptional` type
- Renamed some generics so they're more in line with the `type-fest` codebase
- `NonJsonPrimitive` -> `NotJsonable`
- Also replaced `Function` with `(...arguments_: any[]) => any`
- `SerializeTuple` -> `JsonifyList`
- Also updated this
- `SerializeObject` -> `JsonifyObject`
- Also updated this
This is mainly taking over @sachinraja's awesome work from https://github.com/sindresorhus/type-fest/pull/519, thanks for that! 🙏

feat(remix-server-runtime): use `type-fest`'s `Jsonify` type in `Serialize`

---

package.json
packages/remix-react/package.json
yarn.lock

This will remove the following install warning:
```sh
npm WARN deprecated source-map-resolve@0.6.0: See https://github.com/lydell/source-map-resolve#deprecated
```

chore: update `@testing-library/jest-dom`

---

packages/remix-express/package.json
packages/remix-vercel/package.json
yarn.lock

This will remove the following install warnings:
```sh
npm WARN deprecated formidable@1.2.2: Please upgrade to latest, formidable@v2 or formidable@v3! Check these notes: https://bit.ly/2ZEqIau
npm WARN deprecated superagent@6.1.0: Please upgrade to v7.0.2+ of superagent.  We have fixed numerous issues with streams, form-data, attach(), filesystem errors not bubbling up (ENOENT on attach()), and all tests are now passing.  See the releases tab for more information at <https://github.com/visionmedia/superagent/releases>.
```

chore: update `supertest`

---

.changeset/disabled-link-preload.md
packages/remix-react/links.ts

I'm not sure we _want_ this, but it's a POC for a potential fix for https://github.com/remix-run/remix/issues/2619
This adds some client-side detection of preload timeouts (after 3s) and once 3 stylesheet preloads timeout, we try to force a preload `link.onerror`.  If that also times out - we deduce that preload is not supported by the browser (or disabled by the user) and we stop trying to inject preloads for stylesheets on client side navigations.
Closes #2619

Handle disabled preload config in firefox

---

.github/workflows/deduplicate-yarn.yml

This is a re-submission of @mcansh's #6109, which should have gone to `main` I think #7035 (see a07ae176),
#7100 (see e6b4ab70), #7101 (see c6b70a61) & #7102 (see ef74be9e) didn't trigger the workflow while they should have and I think that's because the workflow should always be on `main` first before it can be triggered

chore: add `deduplicate-yarn` workflow

---

.changeset/global-fetch-instanceof.md
contributors.yml
integration/fetch-globals-test.ts
packages/remix-node/__tests__/fetch-test.ts
packages/remix-node/fetch.ts

Retarget to dev of https://github.com/remix-run/remix/pull/7069, credit to @jeeyoungk
Closes #3480
Closes #4148
Closes #4395
Closes #7059
This is a fix for the referenced issue; The fix is by
* Replace `NodeRequest` and `NodeResponse` classes with interfaces.
* However, class is still needed (as people may want to do `new NodeRequest` or `x instanceof NodeRequest`). For this purpose, `WebRequest` and `WebResponse` are exposed as classes.
This code is quite tricky as we're exporting types and values separately. The correct way of doing this is to define a type and value with the same identifier, `export` handles this correctly.
Testing Strategy: new integration and unit tests

feat(remix-node): replace extended classes for `NodeRequest` & `NodeResponse` with interface type casts

---

packages/remix-dev/__tests__/utils/withApp.ts
packages/remix-dev/cli/commands.ts
packages/remix-dev/compiler/compiler.ts
packages/remix-dev/compiler/fileWatchCache.ts
packages/remix-dev/compiler/watch.ts
packages/remix-react/components.tsx
packages/remix-react/data.ts
packages/remix-serve/cli.ts

This is just the relevant parts of the code changes from #6325 instead of also tackling eslint-config changes.
- Added [`void` operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/void) to Promises that are not being awaited. Used `await` on finally retry in test.
When enabling the typescript-eslint rules contained in ["plugin:@typescript-eslint/recommended-requiring-type-checking"](https://typescript-eslint.io/linting/configs#recommended-requiring-type-checking) I tried to improve code quality by addressing some of the issues raised when enabling the type checked linting rules.
This change specifically resolves issues raised with the typescript-eslint error: [`no-floating-promises`](https://typescript-eslint.io/rules/no-floating-promises).
> error …

chore: let `@typescript-eslint/no-floating-promises` ESLint rule pass

---

.changeset/wild-garlics-draw.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/compiler/options.ts

fix(dev): allow any mode (NODE_ENV)

---

.changeset/empty-cameras-walk.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/devServer/liveReload.ts

fix(dev): allow non-development modes for remix watch

---

.changeset/kind-grapes-clap.md
packages/create-remix/index.ts
packages/remix-dev/cli/commands.ts

Follow-up of @markdalgleish's #6887

feat!: stop passing `isTypeScript` to `remix.init` script

---

.github/workflows/deduplicate-yarn.yml

This should fix the workflow normally 🙏
https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs

chore: fix `deduplicate-yarn` workflow

---

contributors.yml
packages/remix-dev/package.json

Looks like preset env was added by accident or was not removed while refactoring. Now it is not referenced anywhere except root config and remix rely on esbuild for transpiling.
Preset env depends on many other packages which makes installing slower especially with bad internet connection.

chore(remix-dev): remove `@babel/preset-env` from dependencies

---

.changeset/friendly-fireants-report.md
.changeset/wicked-points-unite.md
docs/utils/redirectDocument.md
integration/navigation-state-test.ts
packages/remix-cloudflare/index.ts
packages/remix-deno/index.ts
packages/remix-node/index.ts
packages/remix-react/package.json
packages/remix-server-runtime/index.ts
packages/remix-server-runtime/package.json
packages/remix-server-runtime/responses.ts
packages/remix-testing/package.json
yarn.lock

Re-export `redirectDocument` from https://github.com/remix-run/react-router/pull/10705.
This will fail CI until we cut the next react router release and can point Remix to it.
Closes https://github.com/remix-run/react-router/discussions/9859

feat: re-export `redirectDocument` from RR

---

contributors.yml
docs/tutorials/blog.md

At present the diff highlighted in the blog docs is incorrect and confusing, I have updated the line number to show the correct highlighted diff:
page link: [second last code block in actions section](https://remix.run/docs/en/main/tutorials/blog#actions)
Closes: #

docs(tutorials/blog): fix code highlighting

---

.changeset/quiet-lemons-fold.md
packages/remix-react/index.tsx

The `Navigation` type is exported from react-router but wasn't re-exported from Remix. While it's possible for consumers to get the type via `ReturnType<typeof useNavigation>`, this is much more ergonomic and matches the expectation set elsewhere in Remix, e.g. both `useFetcher` and its `Fetcher` return type are exposed.
Fixes #3866

feat(react): export Navigation type

---

.changeset/disabled-link-preload.md
packages/remix-react/links.ts

Reverts #7106 and switches to use `relList.supports('preload')` to feature detect `<link rel="preload">` support
See also
* https://bugzilla.mozilla.org/show_bug.cgi?id=1847811
* https://developer.mozilla.org/en-US/docs/Web/API/HTMLLinkElement/relList
* https://html.spec.whatwg.org/multipage/semantics.html#dom-link-rellist
Closes #2619

refactor(remix-react): switch to use `relList` to feature detect link preload support

---

docs/utils/cookies.md

I'd recommend leaving the domain out of these examples
- it makes them less copy pastable, as it's one more thing folks have to read through and change
- domains are optional
When you don't specify a cookie domain, it automatically assigns itself to the host's domain plus any subdomains (such as www). This is expected behavior for most people.
If folks assume the domain is mandatory, it leads to complicated environment variable checks to work on localhost and staging and prod.
If the Domain field is set incorrectly, "restrict cookie to specific subdomain" is a much more googlable problem than "cookie returned in response but doesn't set", and for that reason I propose we default to the less restrictive empty value. 
This PR is prompted from a help thread in Discord on the issue …

docs(utils/cookies): remove `domain` cookie option

---

.changeset/fluffy-bananas-love.md
packages/remix-dev/compiler/watch.ts

fix(dev): stop remix dev when esbuild is not running

---

.changeset/useloaderdata-types-yarn-pnp.md
packages/remix-react/package.json

Fixes #6994
The `useLoaderData` return type depends on access to the `SerializeFrom` type exported by `@remix-run/server-runtime`. Since this package is listed as a dev dependency of `@remix-run/react` rather than a regular dependency, this type isn't currently available to consumers when running Yarn PnP.

fix(react): fix useLoaderData types in Yarn PnP

---

docs/guides/styling.md

Since the Styled Components example is now more complicated than the sample code that was in the docs, I've opted to replace the CSS-in-JS section of the styling docs with a link to the examples repo.

docs(styling): remove specific CSS-in-JS example

---

integration/cf-compiler-test.ts
integration/compiler-test.ts
integration/helpers/create-fixture.ts

Should have been removed in #6895

tests: remove `setup` step from fixture creation

---

packages/remix-dev/config/defaults/entry.dev.ts

This basically reverts @pcattori's #6725 now that we only support React 18
Should have been part of #7121

chore(remix-dev): stop ignoring missing `react-dom/client` for React 17

---

.changeset/orange-suits-nail.md
packages/remix-architect/__tests__/server-test.ts
packages/remix-architect/server.ts
packages/remix-express/__tests__/server-test.ts
packages/remix-express/server.ts
packages/remix-node/package.json
yarn.lock

fix: use `headers.entries()` instead of `headers.raw()`

---

.changeset/improve-minified-css-compatibility.md
packages/remix-dev/compiler/css/bundle.ts
packages/remix-dev/compiler/css/compiler.ts
packages/remix-dev/compiler/plugins/cssImports.ts
packages/remix-dev/compiler/utils/cssTarget.ts

Fixes #6114
As the changeset says, we now minify CSS targeting the Remix browser support baseline (i.e. anything that supports [ES module scripts](https://caniuse.com/es6-module)), whereas previously CSS was minified using esbuild's default "esnext" target. This meant that CSS in the production build could be using properties that are unsupported in some browsers.
This change also means you now have more control over CSS transformations using the built-in PostCSS support since they won't be reversed by esbuild's minification.

fix(dev): improve minified CSS compatibility

---

packages/create-remix/copy-template.ts

```
npx create-remix@nightly --template https://github.com/remix-run/remix/tree/dev/templates/remix
```
this was inadvertently extracting stuff from `templates/remix-javascript` into a `-javascript/` folder due to the `startsWith` check passing

Fix bug in create-remix git repo path collisions

---

packages/remix-deno/sessions/fileStorage.ts

There seems to be a recently introduced bug in Deno's lint command where async method definitions aren't detected when validating usage of `await`. This works around the issue.

refactor(deno): fix Deno lint errors

---

contributors.yml
docs/utils/sessions.md

Better clarify that it's only when using `cookieSessionStorage` that you need to commit a session after reading a flash value or unsetting a value.

Improve Session API docs

---

.changeset/remove-fetch-polyfill-references-in-adapters.md
packages/remix-architect/server.ts
packages/remix-express/server.ts

feat: remove references to fetch polyfills

---

.changeset/use-fetch-duplex.md
packages/remix-server-runtime/data.ts

Closes: https://github.com/remix-run/remix/issues/6940
Covered by existing tests

fix(remix-server-runtime): construct requests with duplex option

---

packages/remix-dev/compiler/plugins/cssBundlePlugin.ts

The resolved path for `@remix-run/css-bundle` became redundant due to https://github.com/remix-run/remix/pull/6982 since we don't read the package contents anymore.

fix(dev): remove unused css-bundle path resolution

---

integration/redirects-test.ts

Removed a few flakey tests that relied on global in-memory state which could conflict with one another during CI runs.  These are really testing router logic so I added tests for these flows in https://github.com/remix-run/react-router/pull/10810.

Adjust flaky tests

---

templates/arc/.gitignore
templates/arc/app.arc
templates/arc/server/config.arc
templates/cloudflare-pages/.gitignore
templates/express/.gitignore
templates/netlify/.gitignore
templates/vercel/.gitignore

I originally just wanted to ignore the `metafile.*` files, but since the entire build directory is generated I figured it would be better to ignore it entirely 🤷‍♂️
---
Supersedes #7090

templates: ignore `metafile.*` files

---

contributors.yml
docs/other-api/adapter.md

Like the title says! You can now deploy full remix applications to PartyKit. Additionally, there's a new starter template at https://github.com/partykit/remix-starter/ powered by partymix

docs(other-api/adapter): add PartyMix to community adapters

---

packages/remix-server-runtime/__tests__/formData-test.ts
packages/remix-server-runtime/__tests__/setup.ts
packages/remix-server-runtime/package.json

Just like we did in @jacob-ebey's #7230
We can do this because we call `installGlobals` for our tests
https://github.com/remix-run/remix/blob/6b6bb39185b6be73eaf8d0aa7ddd0fd39a17e3cf/packages/remix-server-runtime/__tests__/setup.ts#L2

test(remix-server-runtime): remove polyfill references

---

jest.config.js
jest/jest.config.shared.js
package.json
packages/create-remix/__tests__/create-remix-test.ts
packages/create-remix/jest.config.js
packages/remix-architect/__tests__/server-test.ts
packages/remix-architect/jest.config.js
packages/remix-dev/__tests__/cli-test.ts
packages/remix-dev/__tests__/cssSideEffectImports-test.ts
packages/remix-dev/__tests__/defineRoutes-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/jest.config.js
packages/remix-dev/package.json
packages/remix-eslint-config/README.md
packages/remix-eslint-config/package.json
packages/remix-express/__tests__/server-test.ts
packages/remix-express/jest.config.js
packages/remix-node/jest.config.js
packages/remix-react/__tests__/integration/meta-test.tsx
packages/remix-react/jest.config.js
packages/remix-react/package.json
packages/remix-server-runtime/__tests__/cookies-test.ts
packages/remix-server-runtime/jest.config.js
packages/remix-testing/jest.config.js
packages/remix-testing/package.json
yarn.lock

Without this update #7217 & #7219 will keep failing
---
CC/ @SimenB to make sure we're doing what we're supposed to do

chore: update Jest

---

.changeset/olive-chefs-jam.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/devServer_unstable/index.ts

fix(dev): kill app server when `remix dev` terminates

---

integration/helpers/create-fixture.ts

We don't include any `jsconfig.json` files in our fixtures anymore

chore: cleanup `createFixtureProject` in integration test helpers

---

.changeset/pretty-ears-vanish.md
packages/remix-dev/compiler/compiler.ts

Write the version to a sentinel file _after_ the server has been written.
This allows the app server to watch for changes to `version.txt`, avoiding race conditions when the app server would attempt to reload a partially written server build.

write build version to `version.txt` alongside the server build

---

packages/remix-architect/__tests__/server-test.ts
packages/remix-express/__tests__/server-test.ts

Follow-up of #7205 & especially @jacob-ebey's #7230
It's remove from the codebase, so why keep it in the tests? 🤷‍♂️

test: remove polyfill references from Node adapters

---

docs/guides/templates.md
docs/other-api/create-remix.md

I've seen some confusion with the removal of the `create-remix` dropdown (i.e., how do I create an express app).  Tried to clarify some of the new usage in the docs.

Add some clarity to the new create-remix CLI + templates option

---

.github/workflows/deployments.yml
.github/workflows/format.yml
.github/workflows/lint.yml
.github/workflows/nightly.yml
.github/workflows/release.yml
.github/workflows/stacks.yml

Switch to built-in CI job cancellation as recommended in https://github.com/styfle/cancel-workflow-action

Update CI workflows to cancel based on built-in concurrency setting

---

.changeset/node-web-crypto.md
packages/remix-node/sessions/fileStorage.ts

https://nodejs.org/docs/latest-v20.x/api/crypto.html#cryptogetrandomvaluestypedarray
https://nodejs.org/docs/latest-v20.x/api/crypto.html#cryptowebcrypto
https://nodejs.org/docs/latest-v20.x/api/webcrypto.html#cryptogetrandomvaluestypedarray

feat(remix-node): use Web Crypto API in `createFileSessionStorage`

---

.changeset/use-native-blob.md
packages/remix-node/fetch.ts
packages/remix-node/globals.ts

https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#class-blob
Unfortunately I couldn't get rid of `File` usage as that's only added in Node v20: https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#class-file

refactor: use native `Blob` class

---

.changeset/gorgeous-carrots-dance.md
packages/remix-dev/compiler/js/plugins/hmr.ts

do not interpret JSX in .ts files

---

docs/guides/migrating-react-router-app.md
integration/defer-test.ts
packages/remix-dev/config/defaults/entry.server.node.tsx
scripts/playground/template/app/entry.server.tsx
templates/arc/app/entry.server.tsx
templates/express/app/entry.server.tsx
templates/fly/app/entry.server.tsx
templates/remix-javascript/app/entry.server.jsx
templates/remix/app/entry.server.tsx

Follow-up of #7205 & @jacob-ebey's #7230
Templates are either calling `installGlobals` themselves _or_ if they're using `@remix-run/serve` (`fly`, `remix` & `remix-javascript`), that already called `installGlobals` as well
https://github.com/remix-run/remix/blob/c28c3cc6a577653a857f3f38a3d93eefa091f102/templates/arc/server.ts#L7
https://github.com/remix-run/remix/blob/c28c3cc6a577653a857f3f38a3d93eefa091f102/templates/express/server.js#L14
https://github.com/remix-run/remix/blob/c28c3cc6a577653a857f3f38a3d93eefa091f102/packages/remix-serve/cli.ts#L21

templates: remove polyfill references

---

.changeset/metal-horses-camp.md
package.json
packages/remix-dev/package.json

When running `npx run typecheck` on a newly installed project, I get the following errors
```sh
node_modules/@types/glob/index.d.ts:29:42 - error TS2694: Namespace '"/Users/michaeldeboey/Downloads/my-remix-app/node_modules/minimatch/dist/mjs/index"' has no exported member 'IOptions'.
29     interface IOptions extends minimatch.IOptions {
~~~~~~~~
node_modules/@types/glob/index.d.ts:74:30 - error TS2724: '"/Users/michaeldeboey/Downloads/my-remix-app/node_modules/minimatch/dist/mjs/index"' has no exported member named 'IMinimatch'. Did you mean 'Minimatch'?
74         minimatch: minimatch.IMinimatch;
~~~~~~~~~~
```
Running `npm ls @types/glob` to figure out where the dependency comes from, show us that it's a dependency of `sort-package-json`, which is a dependency of `@remix-run/dev`
```sh …
```

fix(remix-dev): remove `sort-package-json`

---

.changeset/early-trains-fold.md
packages/remix-node/base64.ts
packages/remix-node/globals.ts

- https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#atobdata
- https://nodejs.org/dist/latest-v20.x/docs/api/globals.html#btoadata

feat(remix-node): use built-in `atob` & `btoa`

---

.changeset/chilled-horses-look.md
packages/remix-cloudflare/index.ts
packages/remix-deno/index.ts
packages/remix-node/index.ts
packages/remix-server-runtime/index.ts
packages/remix-server-runtime/reexport.ts

Removing types which are just aliases for unknown.
I left `AppLoadContext` in for now since it's used in the adapters but I could be convinced to just hardcode `unknown` in those and remove that as well.
Follow up of https://github.com/remix-run/remix/pull/7319#discussion_r1316373471

Remove AppData/RouteHandle types

---

.changeset/tidy-paws-promise.md
packages/remix-react/__tests__/components-test.tsx
packages/remix-react/components.tsx

Previously, `${port} || REMIX_DEV_ORIGIN` was interpreted as the condition for the ternary, which caused `REMIX_DEV_ORIGIN`'s port to be used whenever `port` was defined, even if `REMIX_DEV_ORIGIN` was `undefined`.

fix live reload port when explicitly set as a prop

---

packages/remix-deno/.gitignore
packages/remix-deno/rollup.config.js

On my machine the Rollup build can be quite slow with initial builds taking 30s, but it was more of a papercut since rebuilds were fast. I was able to narrow it down to the usage of the `gitignore: true` option for `rollup-plugin-copy` on the `@remix-run/deno` package which no other package uses. I was able to achieve the same build output while avoiding this option.
Note that the removed `.gitignore` file was only present for `rollup-plugin-copy` to pick up, so with this config change it became redundant.

build(deno): speed up Rollup copy step

---

.changeset/small-impalas-invent.md
packages/remix-server-runtime/routeModules.ts

Follow-up of @brophdawg11's #7360
I don't think we want people to override `DataFunctionArgs` as they can already override `AppLoadContext`

fix(remix-server-runtime): make `DataFunctionArgs` a type alias

---

.github/workflows/test-full.yml
.github/workflows/test-pr-ubuntu.yml
.github/workflows/test-pr-windows-macos.yml

Node 20.6.1 is released which should fix https://github.com/shelljs/shelljs/issues/1133, so we should be bable to go back to `latest` versions of node in CI

Revert back to latest versions of node in CI

---

.changeset/postcss-surface-errors.md
packages/remix-dev/compiler/plugins/cssImports.ts
packages/remix-dev/compiler/plugins/cssModuleImports.ts
packages/remix-dev/compiler/plugins/cssSideEffectImports.ts
packages/remix-dev/compiler/plugins/vanillaExtract.ts
packages/remix-dev/compiler/utils/postcss.ts

We were swallowing errors when loading PostCSS config so that it didn't break the build for those without a PostCSS config, but this suppresses real errors for PostCSS consumers when there's a problem with their config.
This PR updates the logic so that we only swallow the missing config error and ensure that all other errors are thrown.
I've also refactored all CSS plugins so that the PostCSS config is loaded lazily rather than up-front in the `setup` hook. Without this change, consumers see the error coming from the first plugin that happens to be instantiated which is confusing if they're not using the feature, e.g. the error comes from the CSS Modules plugin when they're not using CSS Modules.

fix(dev): surface PostCSS config errors

---

.changeset/lovely-suits-appear.md
docs/guides/migrating-react-router-app.md
integration/defer-test.ts
packages/remix-dev/config/defaults/entry.server.node.tsx
packages/remix-express/__tests__/server-test.ts
scripts/playground/template/app/entry.server.tsx
templates/arc/app/entry.server.tsx
templates/express/app/entry.server.tsx
templates/fly/app/entry.server.tsx
templates/remix-javascript/app/entry.server.jsx
templates/remix/app/entry.server.tsx

Now that we're strictly using web fetch/streams and we no longer export the `fetch` API out through `@remix-run/node` (https://github.com/remix-run/remix/pull/7293), we are also using the globally available `Response` constructor in `entry.server.tsx` (https://github.com/remix-run/remix/pull/7271).  TS doesn't allow a node `PassThrough` stream to be passed directly, so we need to convert it to a web stream using node's `Readable.toWeb()` utility.
Closes: #7357

Fix TS error in entry-server - make Passthrough a ReadableStream

---

.changeset/remix-serve-esm-usage-error.md
docs/file-conventions/remix-config.md
docs/guides/migrating-react-router-app.md
docs/guides/typescript.md
docs/other-api/dev.md
docs/other-api/serve.md
packages/create-remix/__tests__/fixtures/stack/package.json
packages/remix-dev/__tests__/fixtures/node/package.json
packages/remix-dev/__tests__/fixtures/stack/package.json
packages/remix-serve/cli.ts

Since `remix-serve build` doesn't work in ESM projects (it needs to be the file path, e.g. `remix-serve build/index.js`), I've updated all `remix-serve` usage docs to use the `serverBuildPath` format instead.
This notably includes a code change in `remix-serve` in one of its error messages which was incorrectly telling consumers to provide the server build directory rather than the server build path.
This also cleans up references in the docs to the now-removed `serverBuildDirectory` option since it was referenced in the remix-serve docs.

fix(serve): update usage error to support ESM

---

.changeset/cyan-cameras-invite.md
packages/remix-server-runtime/routeModules.ts

`context` was inadvertently reverted to optional in https://github.com/remix-run/remix/pull/7362

Add back in required AppLoadContext to DataFunctionArgs

---

docs/guides/templates.md

Updated the Templates docs page to explicitly list out our in-repo templates so folks can easily find keywords such as cloudflare, deno, etc. with CMD-F.
[Preview](https://github.com/remix-run/remix/blob/brophdawg11/update-docs/docs/guides/templates.md)

Update Templates docs

---

docs/file-conventions/entry.server.md

Added some clarity for a scenario that comes up a lot with `handleError` and aborted requests

docs(file-conventions/entry.server): add note about aborted requests in `handleError` section

---

contributors.yml
docs/start/quickstart.md

Some really minor changes to the [quickstart docs on dev](https://remix.run/docs/en/dev/start/quickstart)
Two issues not addressed in the code:
1. There is no `tsconfig.json` file, yet we're using `.tsx` files. Should we include a step to add a `tsconfig.json` file such as [this one](https://github.com/remix-run/remix/blob/30bcd9e9dfbeda1707329da017f9ceccfac21521/docs/guides/typescript.md?plain=1#L49-L70). If so, I can add that instruction
2. When running `remix-serve build/index.js` (or rather `npx remix-serve build/index.js`) I get a syntax error due to the `import` statements. A simple `"type": "module"` in the `package.json` fixes this, but I wasn't sure if there's a more preferred recommendation for the quick start

docs(quickstart): Minor fixes to commands

---

.changeset/odd-bananas-teach.md
packages/remix-dev/config.ts

warn that `future.v2_dev` should be moved to `dev` in v2

---

docs/start/v2.md

Couple of broken links in the upgrade docs, 2 right at the top 😬

docs: fix links in v2 upgrade doc

---

.changeset/four-spies-draw.md
packages/remix-serve/cli.ts

to avoid race conditions caused by partially written server build
Tried HMR updates on a fresh install w/ these changes added in via `LOCAL_BUILD_DIRECTORY`

in manual mode, watch for changes to version.txt instead of server build

---

.changeset/add-uimatch-handle.md
packages/remix-react/components.tsx

Add second `handle` generic to `UIMatch` to match the React Router version
Closes: https://github.com/remix-run/remix/issues/7438

Add second generic to UIMatch for handle field

---

templates/arc/.gitignore
templates/cloudflare-pages/.gitignore

Thank you for developing this wonderful framework, Remix.
I have updated to v2 and tried using it and noticed that v2 outputs a `version.txt` when I do a build. However, I believe this is what Remix outputs at build time and not a file that should be included in git.
So I added it to gitignore.

templates: add version.txt to .gitignore

---

.changeset/forty-needles-pretend.md
packages/remix-serve/cli.ts

Tested locally (via `LOCAL_BUILD_DIRECTORY`) with both ESM and CJS project using the `remix` template

fix(serve): explicitly bust `require` cache for cjs compatibility

---

.changeset/fix-mdx-types-for-pnpm.md
packages/remix-dev/modules.ts

Fixes #7448
This issue doesn't surface when `@types/mdx` is hoisted to the top-level in `node_modules`, which is the behaviour of the official npm client, but pnpm is stricter about transitive dependencies and ensures that packages aren't hoisted to the top-level by default. This means that Remix consumers don't automatically get the global `*.md`/`*.mdx` types from `@types/mdx` in their app code and only see our augmented `attributes` and `filename` exports. To fix this, we now explicitly import the global types as part of the augmentation.
I've tested this change against a real app running both npm and pnpm to ensure this works across both, and I've confirmed that this change fixed the repro shared in the linked issue.

fix(dev): fix MDX types when using pnpm

---

.changeset/wicked-avocados-fly.md
integration/action-test.ts
integration/resource-routes-test.ts
packages/remix-react/routes.tsx

Before the React Router 6.4 integration, when you tried to submit to a route with no `action`, we logged a warning but still made the HTTP request knowing it would fail.  We [decided](https://github.com/remix-run/remix/pull/4703/files#r1048960110) to stop making the request when we integrated 6.4, but in doing so we lost the semantic nature of the 405 in the `ErrorBoundary`.  
This PR brings back the 405 by throwing an `ErrorResponse` instead of an `Error`

Throw an ErrorResponse instead of just an Error for route with no action

---

templates/express/server.js

prior to this change if you built the remix app, pruned dev only dependencies and attempted to `npm start` the server would bail as it tried to import chokidar
Closes: #

fix(templates/express): dynamically import `chokidar` so it doesn't crash production

---

.changeset/route-lazy-resource-route.md
packages/remix-dev/compiler/js/plugins/routes.ts
packages/remix-react/routes.tsx

Resource routes are compiled with a default export of `{}`, so we need to ignore those empty objects when assigning `Component` via `route.lazy`
Closes #7497

Fix resource routes being loaded through route.lazy

---

templates/arc/app.arc

arc docs don't mention it, but node 18 is supported
https://github.com/mcansh/remix-arc-node-18
https://cl2vu5dvj5.execute-api.us-west-2.amazonaws.com
Closes: #

chore(templates/arc): node 18

---

contributors.yml
docs/start/tutorial.md

Filename in code-block is missing `trailing_` underscore.

docs(start/tutorial): fix filename

---

contributors.yml
docs/file-conventions/entry.server.md

Broken links for default entry.server files ◡̈

fix(docs): entry server defaults broken links

---

.changeset/use-matches-type.md
packages/remix-react/index.tsx

We're re-exporting the RR version, not the Remix wrapper, so types are messed up
Closes #7518

Export correct Remix useMatches wrapper

---

contributors.yml
docs/discussion/form-vs-fetcher.md

Update `docs/discussions/form-vs-fetcher.md` user avatar details popup example route filename to match the one referenced in the code.

docs(discussion/form-vs-fetcher): fix user avatar details popup example filename

---

templates/express/server.js

Closes: #7542
The template was re-importing the `initialBuild` on every request, so HMR would appear to work after changes, but any full request would not update. Actions would also not update.
The documentation for [Manual Mode](https://remix.run/docs/en/main/guides/manual-mode) is not affected because it wasn't trying to dynamically import `chokidar` (so it can be a dev dependency).
This is against the `main` branch because templates usage is pulled directly from the repo and not released as packages.
**Testing Strategy:**
I opened my windows machine and ran this script:
```
npx create-remix@latest --template remix-run/remix/templates/express
```
I updated the `server.js` with these changes and then ran:
```
cd my-test
npm run dev
```

Fix express template to use re-loaded build in requests

---

contributors.yml
docs/start/tutorial.md

- [ x ] Docs
Three changes to the `tutorial.md` doc:
1. Renamed `Root()` to `App()` to match the tutorial code created from `npx create-remix@latest --template ryanflorence/remix-tutorial-template`. 
2. Added more detail to the code example to help the reader determine where to place the `<div id="detail">`
3. Comment added to remind reader to delete/replace existing `const contact = { ... }` with `const contact = await getContact(params.contactId);` in `contacts.$contactId.tsx`

docs(start/tutorial): small updates

---

docs/start/v2.md

Since the default for `serverModuleFormat` is now `esm`, the comments in the v2 guide for the different configurations of `serverBuildTarget` were incorrect.

Fix comment on default for serverModuleFormat

---

.changeset/fix-cf-sourcemaps.md
packages/remix-dev/compiler/server/write.ts

Closes: https://github.com/remix-run/remix/issues/3768
Initialized a new CF Pages template and built Remix into it. Ran the project, connected a debugger, threw an error in a loader and sourcemaps brought me back to the correct line in the source `.ts` route.

fix: sourcemap takes into account special chars in output file

---

contributors.yml
docs/start/tutorial.md

fixes incorrect spelling of the word `trailing` in the tutorial

docs(start/tutorial): fix incorrect spelling of the word trailing

---

.changeset/route-lazy-fouc.md
packages/remix-react/routes.tsx

Fixes a regression from the switch to `route.lazy`.  `loadRouteModulesWithBlockingLinks` happens on the initial route to a `route.lazy` route, but then was not included in the subsequent `loader`/`action` executions once we remove `.lazy`.
[View with whitespace changes hidden](https://github.com/remix-run/remix/pull/7576/files?diff=unified&w=1)
Closes #7516

Fix FOUC on subsequent client-side navigations to route.lazy routes

---

.changeset/dont-mutate-meta.md
package.json
packages/remix-react/__tests__/integration/meta-test.tsx
packages/remix-react/components.tsx
yarn.lock

Avoid mutating meta object when tagName is specified

---

docs/future/vite.md

After testing against our nightly release and the latest version of Vite, it looks like MDX routes are working. I've updated the docs to reflect this. The `remark` link was also broken so I've fix that too.

docs(vite): update MDX route support

---

packages/remix-dev/vite/plugin.ts
packages/remix-dev/vite/static/refresh-utils.cjs
packages/remix-react/browser.tsx

This fixes an issue where stale critical CSS stays in the document after making CSS changes in dev. This issue is most noticeable when removing styles since the old styles will still be applied.

fix(vite): clear critical CSS on HMR

---

packages/remix-dev/vite/static/refresh-utils.cjs

fixes useloaderdata destructuring when adding a loader to a route during HMR
```
TypeError: Cannot destructure property 'blah' of `useLoaderData(...)` as it is null.
```
Closes: #

place route updates in manifest.routes, not manifest itself

---

templates/express/package.json

Add node --watch flag. 
Would trigger an experimental warning for using the Node 18 --watch flag, alternative is use nodemon again.

Express template wasn't restarting when server.js changes

---

contributors.yml
docs/guides/form-validation.md

The current example did not account for handling undefined returned from `useActionData` in addition to passing the correct type into the generic. This is a simple update to documentation
Closes: #

Correcting Form Validation Error Handling

---

contributors.yml
docs/file-conventions/remix-config.md

Small docs change to link to the v2 version of the interactive demo of remix's file conventions for routing rather than the v1 routing version in the File Conventions > remix.config.js page. The link is already updated on the Route File Naming page

Update remix file conventions demo to v2 link

---

integration/vite-css-dev-test.ts
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

Currently, we require [userland config](https://github.com/pcattori/remix-template-vite/blob/main/vite.config.ts#L6-L8) to do this. We should just do it for the user automatically when the Vite plugin for Remix is used. Then the userland vite config can be simplified by omitting the `optimizeDeps` and `resolve` entries.
See [vite-plugin-react](https://github.com/vitejs/vite-plugin-react/blob/main/packages/plugin-react/src/index.ts#L267-L275) for a reference implementation.

Unstable Vite: dedupe and optimize react deps

---

docs/future/vite.md
integration/helpers/dev.ts
integration/vite-dev-express-test.ts
packages/remix-dev/index.ts
packages/remix-dev/vite/index.ts
packages/remix-dev/vite/plugin.ts
packages/remix-express/server.ts
packages/remix-server-runtime/server.ts

Expanded `createRequestHandler` to accept a function for `build` that acts as a dynamic way to get the latest build during dev. Then added APIs for custom server to delegate asset handling and SSR to Vite in dev:
```ts
import { createViteServer, loadViteServerBuild } from "@remix-run/dev"
// util to setup a Vite dev server in middleware mode
let vite = createViteServer()
//  ^? import("vite").ViteDevServer
// serve assets via built-in Vite middleware
app.use(vite.middlewares)
// serve SSR via Remix's request handler
app.use('*', createRequestHandler(() => loadViteServerBuild(vite)))
```
Names prefixed with `unstable_` for now
```ts
// server.mjs
import {
unstable_createViteServer,
unstable_loadViteServerBuild,
} from "@remix-run/dev";
import { createRequestHandler } from …
```

Unstable Vite: support for custom servers

---

integration/vite-dev-express-test.ts
packages/remix-dev/vite/plugin.ts

to allow userland servers to handle SSR requests via createRequestHandler
Previously, `vite.middlewares` included the middleware within `configureServer` that handles SSR for minimal dev server, which prevented userland `createRequestHandler` from ever being used.

do not use built-in, minimal SSR in middleware mode

---

.changeset/fetcher-key-persist.md
.changeset/fetcher-persist.md
docs/components/form.md
docs/file-conventions/remix-config.md
docs/hooks/use-fetcher.md
docs/hooks/use-fetchers.md
docs/hooks/use-submit.md
integration/fetcher-layout-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts
packages/remix-dev/package.json
packages/remix-dev/vite/plugin.ts
packages/remix-react/browser.tsx
packages/remix-react/components.tsx
packages/remix-react/entry.ts
packages/remix-react/package.json
packages/remix-server-runtime/entry.ts
packages/remix-server-runtime/package.json
packages/remix-testing/create-remix-stub.tsx
packages/remix-testing/package.json
scripts/bump-router-versions.sh
yarn.lock

Add new fetcher key APIs and fix issues with persistence behavior
React Router PRs:
* https://github.com/remix-run/react-router/pull/10960
* https://github.com/remix-run/react-router/pull/10961
* https://github.com/remix-run/react-router/pull/10962
RFC: https://github.com/remix-run/remix/discussions/7698
Closes: #7710

Add fetcherKey APIs and update fetcher persistence architecture

---

contributors.yml
docs/hooks/use-fetcher.md

The url should be `https://remix.run/docs/en/main/components/form` instead of `https://remix.run/docs/en/main/components/Form` as the latter throws a 404

docs(hooks/use-fetcher): update link

---

docs/discussion/hot-module-replacement.md
docs/future/vite.md
docs/other-api/dev.md

includes react fast refresh limitations
also, link to `vite`-tagged issues within new troubleshooting section in vite docs
Closes: #

docs(hmr): dedicated discussion doc for hmr

---

.changeset/kind-pandas-think.md
packages/remix-react/components.tsx

We're seeing hydration errors when the CSS contains characters that get HTML encoded in the server render. This is a short term fix to unblock the release. This method works except for some extreme edge cases.

fix(react): fix Vite dev CSS hydration errors

---

packages/remix-dev/vite/node/adapter.ts
packages/remix-server-runtime/server.ts

Since this arg hasn't been designed with public usage in mind, we're marking it as private in case the API changes in the future.

fix(server-runtime): mark critical CSS arg private

---

docs/future/vite.md

Due to https://github.com/remix-run/remix/issues/7786. We'll update these docs if this is resolved in Vite.

docs(vite): de-emphasize CSS `?url` imports

---

docs/future/vite.md

docs(vite): put typescript and livereload steps before server scripts

---

.changeset/curvy-wasps-occur.md
integration/vite-build-test.ts
packages/remix-dev/vite/plugin.ts

Fixes #7795
Added integration cases to `vite build` test checking that server values get removed from client, and that build succeeds without errors referring to server code.
Test was failing before the change, and passes now

fix(vite): remove server exports from resource routes

---

.changeset/fifty-garlics-heal.md
integration/vite-dev-express-test.ts
packages/remix-dev/vite/static/refresh-utils.cjs

and all other non-component Remix exports like `links` too
Fixes #7787

fix(vite): fix behind-by-one-render bug for `meta` HMR

---

templates/unstable-vite-express/tsconfig.json
templates/unstable-vite/tsconfig.json

I ran into an issue where TypeScript complained about my use of `import.meta` features because `"module"` wasn't set correctly.

chore(templates/vite): set TS module to ESNext

---

docs/file-conventions/remix-config.md

Add a specific callout showing that `publicPath` can also be an absolute URL

Add note on publicPath being an absolute url

---

.changeset/nervous-fans-do.md
integration/vite-css-dev-test.ts
integration/vite-dev-express-test.ts
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

This fixes an issue raised by @dmarkow in https://github.com/remix-run/remix/issues/7868#issuecomment-1791470740.
In the Vite dev server, we use a Babel transform to replace usage of `@remix-run/react` with a proxy module so that we can replace the `LiveReload` component with a Vite-specific implementation. Since this transformation doesn't come for free, we first check whether the file contains references to `@remix-run/react` and `LiveReload`. This should mean that, even if the transformation could be faster, it's only applied to a single file in your app.
However, there was an error in the boolean logic for this check that meant we were processing any file containing `@remix-run/react`, even if it was missing a reference to `LiveReload`. This PR fixes the logic so that both strings …

perf(vite): fix LiveReload proxy bailout logic

---

.changeset/clever-months-swim.md
contributors.yml
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7885
It seems explicitly setting vite's esbuild option is necessarily to make jsx transpilation work for `.jsx` file.
This change also aligns with what vite-plugin-react does here
- https://github.com/vitejs/vite-plugin-react/blob/b255776f75ced38e9ae8d0ba2f9113e697159a73/packages/plugin-react/src/index.ts#L130-L131
--- 
(The rest of the comment is some extra note from my investigation. It might not be accurate...)
My guess was that JSX transpilation for server module (i.e. transform done via `ssrLoadModule`) is done by vite's esbuild, which reads local `tsconfig.json` to configure certain transform options.
These are relevant docs:
- https://vitejs.dev/guide/features.html#other-compiler-options-affecting-the-build-result
- …

fix(vite): support JSX in .jsx files without React import

---

contributors.yml
docs/other-api/node.md

The current link to https://nodejs.dev/en/about/releases 404s. Updates the link to the current nodejs.org page that documents which releases are currently LTS Active and LTS Maintenance.

docs(node): update link to node releases

---

.changeset/gentle-ghosts-wait.md
packages/remix-dev/vite/plugin.ts

Closes: #7868. This adds caching around `resolvePluginConfig()` to avoid recalculating routes hundreds of times on startup. There is one cache used for `remix-react-refresh-babel` and `remix-remove-server-exports`, and another used in the middleware to determine if the virtual modules need to be invalidated.
I was unable to get a single cache working, as the cache would get updated in one of the other plugin transforms so there was no way to tell if it was stale for the route request by the time the middleware ran.
Discussion with @pcattori, "we have pretty good tests for this sort of thing in integration/vite-dev-express-test so if those pass with your changes I'd be reasonably confident about it"
Also used this in developing our app the last couple of days, which …

Add caching around resolvePluginConfig() and only invalidate virtual modules when necessary

---

.changeset/two-boxes-dance.md
packages/remix-dev/config.ts

We added a fix in #7261 to disallow unknown/removed future flags but it turns out that fix only worked when `FutureConfig` was empty - which it was at that time since we were preparing to release v2.  Now that we added the first. v3 future flag we found out this isn't the right approach and need to use a conditional type instead.
https://www.typescriptlang.org/play?#code/JYOwLgpgTgZghgYwgAgGIFczqhAwgexBmAHNkBvAKAEgA3AZgH0o4ATVCOLHALmQCN8+ADacQlAL6VKoSLEQoAggAdlBIqQqVkO5DEzYIAfj4BtANYQAnvhhoDOdcRIBdZBAAekEKwDOyUxAIWmg3IwoLaz5fMChQVz4gkKgJZD4ABTgoMGA4YQAeDG48QmcAPklpUTBkBFLNAF4tan1ivipqOiYWdk425Fj0CAAaGjoAJkYAdzAACwgEcz5BkZoJUdTfLmBfYgh-FTV6kmkZcGh4JHtip1JxrSkzuUulVVuSe6pdPQdjM0sbHYioZ3m5PN4-AEkqFkOFyJErNFYvEXIlgtBUhksjk8oVfu8Ko9qrVjvcmh1WoZ2mMGMw2BwuFSBlAhqNOrRJjN5otlizVtR1pJkFscrtgPtkId3uN …

fix(remix-dev): fix `FutureConfig` type

---

templates/unstable-vite-express/app/root.tsx
templates/unstable-vite-express/package.json
templates/unstable-vite/app/root.tsx
templates/unstable-vite/package.json

The `css-bundle` boilerplate is redundant in the Vite templates because `cssBundleHref` will always resolve to `undefined`.

templates(vite): remove `css-bundle`

---

.changeset/afraid-suns-yawn.md
.changeset/early-trees-walk.md
docs/future/vite.md
integration/vite-css-dev-test.ts
integration/vite-dev-express-test.ts
integration/vite-dev-test.ts
packages/remix-dev/manifest.ts
packages/remix-dev/vite/plugin.ts
packages/remix-react/entry.ts
templates/unstable-vite-express/app/root.tsx
templates/unstable-vite/app/root.tsx

Closes #7863.
This PR fixes a couple issues:
- Resolves a race condition between the React Refresh preamble script and the app code by ensuring that the preamble is imported first in the same script tag as the app code.
- Allows the `LiveReload` component to behave the same as the existing Remix compiler from a consumer perspective. You can now choose _not_ to render it, forcing you to perform a full refresh to see changes, and you can also render it after `Scripts`. I've updated the ordering of `LiveReload` and `Scripts` in the Vite tests to show this is the case.

fix(vite): fix HMR preamble race condition

---

.changeset/nasty-waves-whisper.md
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7722
While looking at devtools network tab, I just spotted vite itself seems to be using `/@fs/` url to define globals (the url is something like `http://localhost:5173/@fs/home/hiroshi/code/tmp/remix-pnpm-workspace/node_modules/.pnpm/vite@4.5.0/node_modules/vite/dist/client/env.mjs` cf. https://github.com/vitejs/vite/pull/12471).
So, I came to this idea of doing something similar to support default entries outside of remix app root.
I created a simpler reproduction in https://github.com/hi-ogawa/demo-remix-vite-pnpm-workspace and verified this fix using `pnpm patch` https://github.com/hi-ogawa/demo-remix-vite-pnpm-workspace/commit/6d18e91ab1a242c3624d8b20d274b356fad6f848

fix(remix-dev/vite): use `/@fs/` path to support default server/client entry outside of app root

---

.changeset/ninety-boats-fail.md
integration/vite-css-dev-test.ts
integration/vite-dev-express-test.ts
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

Fixes #7914
Cloned [npm reproduction](https://github.com/hi-ogawa/test-remix-vite-hmr-runtime/tree/chore-npm-reproduction) and built Remix into repro locally via `LOCAL_BUILD_DIRECTORY` and ran with `vite dev --force`.
Also, removed `optimizeDeps.include` from integration tests since that's no longer needed.

fix(vite): deduplicate `@remix-run/react`

---

.changeset/brown-panthers-lay.md
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7905
I think this error is caused by the combination of:
- babel does its own resolution when `plugins` option is passed as a string (not sure what rule exactly...)
- when running custom server (by `node ./server.mjs`), the base of such resolution becomes user's root directory.
- `react-refresh` package (transitive dependency of `@remix-run/dev`) is not visible from root directory when using pnpm's non-flat `node_modules`, 
Looking at `vite-plugin-react`, they indeed resolve plugin library on its own then pass to `plugins` option of `babel.transformAsync` (see "additional notes" below).
So this PR align with it in  a similar way by directly calling `require("react-refresh/babel")` within `@remix-run/dev`.
I think the reason why this issue …

fix(remix-dev/vite): fix `react-refresh/babel` plugin resolution

---

.changeset/slow-eyes-joke.md
integration/vite-css-dev-express-test.ts
packages/remix-dev/vite/plugin.ts
packages/remix-express/server.ts

fix(vite): fix dev FOUC with custom Express server

---

.changeset/eight-jeans-float.md
integration/vite-build-test.ts
integration/vite-dev-test.ts
package.json
packages/remix-dev/vite/plugin.ts
yarn.lock

Closes: https://github.com/remix-run/remix/issues/7901
I wrote a longer explanation here while investigating it https://github.com/remix-run/remix/issues/7901#issuecomment-1793262909
This specific issue of mdx rollup plugin is due to that single plugin instance's hook `{ config(config, env) => .. }` is run twice with different `env.mode` and child compiler's `config` hook runs later and it overwrites plugin's internal state which then affects parent compiler's transform https://github.com/mdx-js/mdx/blob/efff74e48aec9286c62185bf04f7b8aa72e07bd6/packages/rollup/lib/index.js#L76-L82
Note that this change only tries to align `env.mode` between parent and child compilers.
`env.command` is still inconsistent during `vite build` where parent has `command = "build"` while child has `command = …

fix(remix-dev/vite): set same `config.mode` for child compiler

---

.changeset/itchy-rabbits-fly.md
integration/vite-build-test.ts
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7941
I think the issue was due to asset resolution not taking account for code-split common assets.
I made a reproduction repo here https://github.com/hi-ogawa/test-remix-vite-css-split and this is my observation.
I attached vite manifest and remix manifest generated by `build ` currently.
In vite manifest, `_test-206a75ed.js` entry has reference to `assets/test-ef980167.css`, but there's no direct css dependency neither from `app/root.tsx` or `app/routes/_index.tsx`, so remix manifest ends up with no css.
<details><summary>build/manifest.json (vite manifest)</summary>
```js
{
"_components-be9f5b54.js": {
"file": "assets/components-be9f5b54.js",
"imports": [
"_jsx-runtime-26afeca0.js"
]
},
"_jsx-runtime-26afeca0.js": {
"file": …
```

fix(remix-dev/vite): attach CSS from shared chunks to routes

---

.changeset/tricky-news-thank.md
integration/vite-build-test.ts
integration/vite-dev-express-test.ts
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

fix(vite): load .env files into process.env in dev

---

docs/utils/defer.md

[Lee Robinson made a good point](https://twitter.com/leeerob/status/1723115296645361974) that we should probably link back to the Streaming Guide doc in the `defer` API doc
Closes: #

Add link to streaming guide in `defer` doc

---

.changeset/hungry-tables-hang.md
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7918
This can be achieved by
- set `skipEnvCheck: true` for `react-refresh/babel` plugin, and
- update `LiveReload` to check `viteCommand = "serve"` instead of `NODE_ENV = "development"`
I initially thought the error `"React Refresh Babel transform should only be enabled in development environment."` only manifests when remix plugin is (unintentionally) loaded on vitest, but I found that this can also happen, for example, when doing `NODE_ENV=test vite dev`.
So, I think it makes sense to disable this check (and also allow HMR) for other NODE_ENV as well since it looks like too-opinionated restriction. Also remix itself applies this transform only on `"serve"` command, so such warning is irrelevant.
Also note that this is yet-another …

fix(remix-dev/vite): allow custom `NODE_ENV` for `vite dev`

---

docs/future/vite.md

I'm still seeing usage of the `css-bundle` package in Remix + Vite repos in the wild. The docs suggest that removing the `css-bundle` package is optional, but this is leftover from when we placed more emphasis on allowing Vite-based Remix projects to be backwards compatible with the esbuild compiler. However, the docs are now written much more assertively in the direction of removing anything Vite doesn't use or support. This PR updates the `css-bundle` section to be more in line with the rest of the docs.

docs(vite): assert css-bundle removal

---

docs/guides/streaming.md

The `entry.server.ts` url is broken and there are a few more snippets that can be linked.

docs(streaming): Update broken links in streaming.md

---

contributors.yml
packages/remix-react/components.tsx

`LiveReload` component did not have a proper JSDoc, that might be confusing for new users when seeing this component in the `root.tsx`.

docs(remix-react): add JSDoc to LiveReload component

---

.changeset/green-buses-suffer.md
package.json
packages/remix-dev/package.json
packages/remix-dev/vite/plugin.ts
yarn.lock

Since Vite 5 is due to be released in the coming days, this PR bumps our peer dependency range to `^4.4.9 || ^5.0.0`, and also updates our dev dependency to `5.0.0-beta.18` so we can be confident that we're ready for the release.
The most notable change for us is that the CJS build of Vite is deprecated and due to be removed in v6. Our use of the CJS build still works in v5 but leaving it in would mean that the consumer sees a deprecation warning in the terminal. To avoid this deprecation warning without forcing us to migrate to ESM right now, we're now dynamically importing the `vite` package up-front in our plugin's `config` hook.

fix(vite): support Vite 5

---

packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7989
The same issue is already indicated in https://github.com/remix-run/remix/pull/7911#issue-1977584283 but this time, `@vanilla-extract/vite-plugin` is affected by the issue since it makes use of `config.command = "server" or "build"` to switch plugin behavior.
Specifically, the plugin uses this pattern:
```tsx
export function vanillaExtractPlugin({
...
}: Options = {}): Plugin {
let config: ResolvedConfig;
...
return {
name: 'vanilla-extract',
...
async configResolved(resolvedConfig) {
config = resolvedConfig;
...
}
// ... in later hooks (e.g. transform), it uses `config.command === 'build'` check to switch behavior ...
```
During `vite build`, child compiler calls `configResolved` 2nd time with `config.command: "serve"`, so it forces …

fix(remix-dev/vite): instantiate plugins independently for child vite compiler

---

contributors.yml
docs/route/links.md

Valid values are "anonymous" | "use-credentials". https://github.com/remix-run/remix/blob/43387828b3079d7f1f839b6bafa02e911f2be421/packages/remix-server-runtime/links.ts#L16

Update crossOrigin value used in links documentation

---

.changeset/tricky-frogs-film.md
integration/vite-build-test.ts
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7847 
I'm not so sure how robust this change is (especially `writeBundle` plugin hook), but it think it should achieve mostly same thing as what sveltekit did in https://github.com/sveltejs/kit/pull/9073. 
See this comment https://github.com/remix-run/remix/issues/7847#issuecomment-1792110139 for more references (especially vite's "stabilizing" discussion https://github.com/vitejs/vite/discussions/13808).
I added a test only for `build` case. I think this is not relevant for `dev` since vite serves assets files directly without moving or renaming file name with content hash etc..., so I didn't add a test.
Please let me know if there are others cases to be covered by tests.

fix(remix-dev/vite): use `ssrEmitAssets` to support assets referenced by server-only code

---

contributors.yml
docs/hooks/use-resolved-path.md

This fixes a broken link in the docs:
```diff
-https://remix.run/docs/utils/resolve-path
+https://reactrouter.com/utils/resolve-path
```

Fix broken `resolvePath` link in `use-resolved-path` docs

---

.changeset/proud-otters-cheat.md
packages/remix-dev/vite/plugin.ts

Fixes #8023
From the changeset:
> Fix redundant copying of assets from `public` directory in Vite build. This ensures that static assets aren't duplicated in the server build directory. This also fixes an issue where the build would break if `assetsBuildDirectory` was deeply nested within the `public` directory.

fix(vite): disable redundant copyPublicDir option

---

.changeset/modern-pans-happen.md
integration/vite-build-test.ts
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/8041
Follow up for https://github.com/remix-run/remix/pull/7892
EDIT: following comment is for initial approach. Now it's written to remove only unnecessary files based on the suggestion in  https://github.com/remix-run/remix/pull/8042#issuecomment-1817261780
---
Instead of keeping whole `assets` directory, maybe we could probe vite manifest and keep only `isDynamicEntry`.
(EDIT: I further extended reproduction https://github.com/hi-ogawa/remix-reproduction-8041 and I found that `isDynamicEntry` is not a right way to detect this)
For example, vite manifest from ssr build for `vite-build-test.ts` looks like this:
<details><summary>reveal build/.vite/manifest.json</summary>
(here `assets/test2-LxNzCzR4.txt` is server-only assets, so it's …

fix(remix-dev/vite): keep code-split JS files in SSR build

---

integration/package.json
integration/vite-css-build-test.ts
integration/vite-css-dev-express-test.ts
integration/vite-css-dev-test.ts
yarn.lock

Follow-up to #8000.
As of v3.9.2 of the Vanilla Extract Vite plugin, you no longer need to set `emitCssInSsr: true` when using the Remix Vite plugin (fixed in https://github.com/vanilla-extract-css/vanilla-extract/pull/1239). This PR upgrades our version of the Vanilla Extract Vite plugin and updates the tests to remove `emitCssInSsr: true`.

test(vite): upgrade Vanilla Extract Vite plugin

---

contributors.yml
docs/other-api/dev.md

I've updated the msw example based on the breaking changes they introduced in v2. Also, considering that Kent's epic-stack uses ESM by default I've added a few details regarding ESM modules to the msw example (might be useful for people using epic-stack as a reference).

docs: update msw example to msw@2.x version + add ESM related details

---

contributors.yml
docs/guides/templates.md

Fixed typo in template docs

---

.changeset/tricky-frogs-film.md
CHANGELOG.md
packages/remix-dev/CHANGELOG.md

This patch went out in v2.3.0 but the changeset didn't get picked up, probably due to the way the commit was cherry-picked into the `release-next` branch. This PR deletes the changeset and adds the missing line to the relevant changelogs. After merging, I'll update the GitHub release too.

chore: move missed changeset to changelog

---

CHANGELOG.md
packages/remix-dev/CHANGELOG.md

Follow-up to #8072. I missed that the item was already in one of the changelogs. This PR removes the duplicate item and updates the other changelog for consistency.

chore: dedupe changelog

---

integration/vite-hmr-hdr-test.ts

Ran this locally with:
```sh
yarn test:integration --project=firefox -g "vite-hmr"
```

test(vite): fix firefox expected error detection

---

.changeset/green-balloons-promise.md
packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/7722#issuecomment-1810263774 (follow up of https://github.com/remix-run/remix/pull/7913)
I think this issue is because of the lack of `normalizePath`.
---
In https://github.com/hi-ogawa/remix/pull/1/files, I'm trying to verify this works on Windows, but it seems there is still something wrong.
I see `SyntaxError: Unexpected token '<'` in https://github.com/hi-ogawa/remix/actions/runs/6919035654/job/18821929935#step:7:328 which indicates transform not being run for client entry.

fix(vite): apply `normalizePath` to default entry file outside of project directory

---

package.json

I was wondering if there is a specific reason to not enable caching for prettier https://prettier.io/docs/en/cli.html#--cache.
It might not matter if people use some IDE plugins to run linter on file save, but for some reason, I prefer running `yarn format` manually, so this caching would help me a little bit.
Here are quick stats on my PC:
```sh
$ time yarn format
...
real    0m13.486s
user    0m22.333s
sys     0m1.202s
$ time yarn format
...
real    0m3.397s
user    0m3.647s
sys     0m0.610s
```

chore: enable prettier cache

---

.changeset/chatty-shrimps-sell.md
integration/helpers/vite-template/tsconfig.json
integration/helpers/vite.ts
integration/package.json
integration/vite-dot-server-test.ts
packages/remix-dev/vite/plugin.ts
yarn.lock

Previously, only files with a `.server` extension were excluded. Now, files (recursively) within a directory named `.server` are also excluded.

Vite: exclude modules within `.server` directories from client build

---

.changeset/brown-hotels-rush.md
integration/vite-css-build-test.ts
integration/vite-css-dev-test.ts
packages/remix-dev/vite/import-vite-esm-sync.ts
packages/remix-dev/vite/plugin.ts
packages/remix-dev/vite/resolve-file-url.ts
packages/remix-dev/vite/styles.ts

Without this fix, CSS from the client entry appears to work in dev (after a flash of unstyled content), but the styles are then missing in the production build.
This PR ensures that:
- In dev, CSS from the client entry is included in the string of critical CSS to avoid FOUC.
- In production, any bundled CSS from the client entry is included with the root route.
To test this, CSS imported from the client entry has been added to Vite CSS tests for both dev and build.

fix(remix-dev/vite): bundle CSS from client entry

---

docs/start/quickstart.md

There was [a discussion in the Discord](https://discord.com/channels/770287896669978684/770287896669978687/1177977705514414191) about the Quickstart and some folks feeling like it was "significantly harder to understand then the 30m tutorial"
I think this is due to expectation setting. While we do have good callouts at the beginning as to what the guide is, per some suggestions I figured it might be good to mention the CLI and link to the page on it.
I specifically tried to avoid adding a `npx create-remix@latest` codeblock, because I was worried for folks who don't read and just look for code they would take it as a command. I also think it's worth reading through and understanding this guide, so I don't want to encourage people taking the "escape hatch", I just want to point it out. …

docs(quickstart): add cli link/callout to top of quickstart

---

.changeset/data-function-args.md
docs/file-conventions/entry.server.md
packages/remix-server-runtime/build.ts
packages/remix-server-runtime/data.ts
packages/remix-server-runtime/routeModules.ts
packages/remix-testing/__tests__/stub-test.tsx

This is the first of a series of PRs to implement [Client Data](https://github.com/remix-run/remix/discussions/7634) into a `feature/client-data` branch.
When `clientLoader`/`clientAction` come into play, we'll finally have a differentiation between parameters passed to `clientLoader`/`clientAction` since they'll receive a `serverLoader`/`serverAction` function to call the loader/action on the server.
We don't plan to introduce a `ClientDataFunctionArgs` because they will be different, so it will just be `ClientLoaderFunctionArgs`/`ClientActionFunctionArgs`
To keep things consistent across server and client types , this PR deprecates `DataFunctionArgs` so that folks can move to `LoaderFunctionArgs`/`ActionFunctionArgs`

Deprecate DataFunctionArgs

---

packages/remix-react/routes.tsx
packages/remix-testing/create-remix-stub.tsx

Depends on https://github.com/remix-run/remix/pull/8089
This is the second in a series of PRs to implement [Client Data](https://github.com/remix-run/remix/discussions/7634) into a `feature/client-data` branch.
This is a small reorganization of how we create client routes to make it easier to fork and add `clientLoader`/`clientAction` logic (in a subsequent PR).  This PR shouldn't have any functional impacts.

Restructure client route creation in preparation for client data

---

.changeset/shiny-timers-bake.md
packages/remix-dev/vite/plugin.ts

The integration test named `vite-dotenv-test` was consistently failing for me when testing in Safari locally and in CI. Debugging locally, I was able to see the following errors in the console:
The tests even failed when setting `optimizeDeps.force` to `true`. The only way I was able to get it to pass was to ensure that `@remix-run/node` was also included in the `optimizeDeps.include` array.

fix(vite): add remix-node to optimizeDeps.include

---

.changeset/angry-dingos-buy.md
packages/remix-dev/package.json

Before marking the Vite plugin as stable, we want to raise the minimum version of Vite that we support since this will be harder to do later.

fix(remix-dev/vite): upgrade Vite peer dep to v5

---

.changeset/wise-pumas-thank.md
integration/vite-dot-server-test.ts
packages/remix-dev/vite/plugin.ts

Remix already ensures that all code from `.server` files (and now also `.server` directories) gets replaced with an empty module, so there's no way for `.server` code to end up in the client. Ideally, all references to `.server` code get stripped in the client anyway, but this is a failsafe. In the case that there are _still_ imports for `.server` files in the client, those will correctly result in errors.
However, those errors could sometimes happen at runtime, meaning that it was possible for your CI/CD pipeline to pass and for you to deploy your app only for your users to hit a "cannot reference `.server` code within the client" error. This is already much better than leaking server data in the client, but still not ideal. Specifically, this could happen when using `default` exports …

Vite: client references to .server code result in build-time error

---

packages/remix-dev/vite/plugin.ts

chore(vite): explain why `@remix-run/node` is in `optimizeDeps.include`

---

.changeset/grumpy-cats-roll.md
docs/future/vite.md
integration/vite-route-exports-test.ts
packages/remix-dev/vite/plugin.ts

From the added docs:
With Vite, Remix gets stricter about which exports are allowed from your route modules.
Previously, Remix allowed user-defined exports from routes.
The Remix compiler would then rely on treeshaking to remove any code only intended for use on the server from the client bundle.
In contrast, Vite processes each module in isolation during development, so cross-module treeshaking is not possible.
You should already be separating server-only code into `.server` files or directories, so treeshaking isn't needed in those cases.
But routes are a special case since they intentionally blend client and server code.
Remix knows that exports like `loader`, `action`, `headers`, etc. are server-only, so it can safely remove them from the client bundle.
But there's no way to know when …

feat(vite): strict route exports

---

integration/vite-dot-server-test.ts

this was already the case, just adding a test to make it explicitly checked for

test(vite): dynamic .server imports are excluded from client

---

.changeset/relative-splat-path.md
docs/components/form.md
docs/components/link.md
docs/hooks/use-href.md
docs/hooks/use-navigate.md
docs/hooks/use-resolved-path.md
docs/hooks/use-submit.md
integration/form-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts
packages/remix-dev/package.json
packages/remix-dev/vite/plugin.ts
packages/remix-react/browser.tsx
packages/remix-react/entry.ts
packages/remix-react/package.json
packages/remix-react/server.tsx
packages/remix-server-runtime/entry.ts
packages/remix-server-runtime/package.json
packages/remix-server-runtime/server.ts
packages/remix-testing/create-remix-stub.tsx
packages/remix-testing/package.json
yarn.lock

Add the `future.v3_relativeSplatPath` flag to pass through to React Router's `v7_relativeSplatPath` flag.
Also bumps to the latest react router prerelease (which contains the flag)

Add future.v3_relativeSplatPath flag

---

.changeset/rude-keys-heal.md
packages/remix-dev/vite/plugin.ts

This changes the stubbed-out `.client` export values from `{}` to `undefined`. This matches the behaviour of the old Remix compiler, making runtime checks less error prone and providing better runtime errors if you accidentally try to use a client-only module on the server.

fix(vite): make server .client exports undefined

---

packages/remix-dev/vite/plugin.ts

This PR modifies the Vite plugin to pass the entire `future` config object through to the server entry rather than manually adding each value. This ensures that any new future flags don't also need to be added to the Vite plugin, and it also ensures that the types are always correct. If we ever need to add any Vite-specific future flags, we can handle those within the Vite plugin and then forward the rest.

refactor(vite): handle all future flags

---

.changeset/sour-snakes-melt.md
packages/remix-dev/vite/plugin.ts

This warning is present in our esbuild compiler but not in the Vite plugin.

fix(remix-dev/vite): warn on source maps in build

---

.changeset/big-cooks-confess.md
contributors.yml
packages/remix-server-runtime/routeModules.ts

Closes: There is no issue for this one yet
I have a Remix app on the latest version (`v2.3.1`) and with a lot of debugging, I've found out that the `MetaFunction` type imported from `'@remix-run/node'` differs from the `MetaFunction` from `'@remix-run/react'`. If there is an error thrown in the `loader` with `v.2.3.1`, the `error` is set as expected in JavaScript but the types yelled at me.
- Have a look at the inferred types of the `MetaFunction` imported from `'@remix-run/node'`
- Verify that the `error` property is included

Add error type to server runtime meta args

---

docs/utils/sessions.md

Just clarifying for other people who like me may be confused about how `session.id` works.

docs(utils/sessions): clarify `session.id`

---

.changeset/short-mayflies-stare.md
packages/remix-server-runtime/routes.ts

Discovered in https://github.com/remix-run/remix-website/pull/143.  These only got added to the `@remix-run/react` `EntryRoute` originally

Add missing fields to EntryRoute

---

.changeset/breezy-walls-scream.md
docs/future/vite.md
integration/helpers/vite.ts
packages/remix-dev/index.ts
packages/remix-dev/vite/index.ts
packages/remix-dev/vite/plugin.ts
packages/remix-dev/vite/server-entry-id.ts
packages/remix-dev/vite/vmod.ts
templates/unstable-vite-express/server.mjs

As the changeset says, this change was made to avoid issues where `@remix-run/dev` could be inadvertently required in your server's production dependencies. Rather than encouraging another dynamic import, we're just going to make the virtual module name public API instead since it's much simpler.

fix(vite): remove virtual server build ID export

---

docs/future/vite.md
integration/helpers/vite.ts
templates/unstable-vite-express/server.mjs

This renames the `vite` variable to `viteDevServer`, which also frees up the `vite` variable name for dynamic imports of Vite itself.

refactor(vite): rename Vite dev server variable

---

.changeset/breezy-grapes-roll.md
integration/package.json
integration/vite-dot-server-test.ts
packages/remix-dev/vite/plugin.ts
yarn.lock

https://github.com/remix-run/remix/assets/1477317/77eceb06-034a-4f6f-89a0-a2215686ada2

feat(vite): error messages when .server files are referenced by client

---

contributors.yml
docs/discussion/server-vs-client.md

The `Server vs. Client Code Execution` example was missing the `formData` variable initialization in the `action`

docs(discussion/server-vs-client) Add missing `formData` to `action` example

---

packages/remix-dev/__tests__/fixtures/cloudflare/.eslintrc.cjs
packages/remix-dev/__tests__/fixtures/cloudflare/package.json
packages/remix-dev/__tests__/fixtures/node/.eslintrc.js
packages/remix-dev/__tests__/fixtures/node/package.json

Forked off from #7597 since this touches unit tests so should technically merge to `dev`.  The unit tests are testing `remix dev` behavior so linting is irrelevant in the fixtures

Remove @remix-run/eslint-config references from unit test fixtures

---

CHANGELOG.md
contributors.yml

Fixes `clientAction` link url from the v2.4.0 Changelog release, that wrongfully points to https://remix.run/route/client-loader

docs(changelog): fix client-action link in changelog

---

contributors.yml
docs/start/tutorial.md

The shell script code block is missing the `shellscript nonumber` tag in the index route step of the tutorial

add codeblock tag

---

contributors.yml
docs/utils/parse-multipart-form-data.md

Since the only link was to the `File` API, I didn't realize that the methods from `Blob` were available too - those of us who dealt with files in the bad old days are likely to try using `FileReader` before reaching for convenient methods like `.text()`
For the grumpy background behind this PR, my [discussion topic](https://github.com/remix-run/remix/discussions/8278) of the journey of figuring out the way to read a file 😆

Add helpful pointer for how to read uploaded files

---

templates/unstable-vite-express/vite.config.ts
templates/unstable-vite/vite.config.ts

`yarn lint` passes without these eslint ignores

fix(templates/vite): remove unnecessary eslint ignore

---

contributors.yml
docs/file-conventions/remix-config.md

Because of the `.md` extension, this link didn't work on the website, only GitHub. Thanks!

docs: fix link in `remix-config.md`

---

docs/start/v2.md

The @remix-run/v1-route-convention package should be installed as a dev dependency so that @remix-run/dev doesn't get pulled into production dependencies. This saved about 100mb on my docker image and removed critical vulnerabilities 🙈

Update v2.md to specify installing v1 route convention as dev dep

---

docs/future/vite.md

```diff
- COPY --from=build /myapp/server/build /myapp/server/build
- COPY --from=build /myapp/client/build /myapp/client/build
+ COPY --from=build /myapp/build/server /myapp/build/server
+ COPY --from=build /myapp/build/client /myapp/build/client
```

docs(vite): fix incorrect build output path

---

docs/future/vite.md

The docs mention using `tsx server.tsx`, but the `.tsx` extension is for React related [TypeScript XML](https://www.typescriptlang.org/docs/handbook/jsx.html) files, which isn't relevant to the server file.
[`tsx`](https://github.com/privatenumber/tsx#readme-ov-file) is a `node` CLI replacement to run TypeScript & ESM files. There is a [note](https://github.com/privatenumber/tsx#why-is-it-named-tsx) in their documentation about the unfortunate naming overlap.

docs(vite) use server.ts as file name, not server.tsx

---

.changeset/angry-poets-accept.md
contributors.yml
packages/remix-serve/cli.ts
templates/express/server.js

This PR fixes an issue where the leading slash on source map paths would cause remix-serve to crash when an error gets thrown on Windows.
Tested both on Windows and Mac.
Closes: [8309](https://github.com/remix-run/remix/issues/8309)

fix (remix-serve): convert file url to path when loading source maps

---

packages/remix-dev/vite/build.ts
packages/remix-dev/vite/dev.ts

Now that we've introduced Vite-specific CLI commands, we have two new entrypoints into a Vite context. We need to call our `preloadViteEsm` function at the top of these commands to ensure any calls to `loadViteEsmSync` don't fail.

fix(remix-dev/vite): preload Vite ESM build in CLI

---

packages/remix-dev/vite/plugin.ts

Closes: https://github.com/remix-run/remix/issues/8313
Vite introduced `server.watch: null` in https://github.com/vitejs/vite/pull/14208. Initial use case was for Vitest, but reading the thread there, it looks like Astro also had such use case.
I think disabling `server.watch` during dev might be also fine since currently child compiler doesn't make use of Vite's caching/invalidation so watcher might not be necessary as well. But for now, disabling for build seems obvious, so I only did that here.
I cannot think of a way to verify the change exactly... Maybe better to ask the issue author to verify this by patching it locally.

fix(vite): disable `server.watch` for child compiler during build

---

.changeset/curly-coats-reflect.md
packages/remix-dev/vite/plugin.ts

Testing strategy:
Tried it locally with `LOCAL_BUILD_DIRECTORY` on a simple express + vite app that was having the same error before.

fix(vite): fix errors for non-existent `index.html` importer

---

.changeset/twelve-cars-work.md
packages/remix-react/index.tsx

Export these from the react package for use in `clientLoader`/`clientAction` since users cannot use them from `@remix-run/node` in client bundles.  right now, the workaround is to import from `@remix-run/server-runtime`.
See: https://github.com/remix-run/remix/discussions/7634#discussioncomment-7867885

Re-export response helpers through react package

---

integration/vite-server-bundles-test.ts
packages/remix-dev/vite/build.ts

I'd renamed `routeIdToBundleId` to `routeIdToServerBundleId` in the docs but hadn't updated it in the code.

fix(remix-dev/vite): rename bundles manifest key

---

contributors.yml
templates/remix-tutorial/package.json

The `.eslintrc.js` configuration in `templates/remix-tutorial` contains references to plugins that aren't included in the existing `package.json`. Add these missing dependencies to satisfy eslint:
- `eslint-plugin-import`
- `eslint-plugin-jsx-a11y`
- `eslint-plugin-react-hooks`
See Ryan F request: https://twitter.com/ryanflorence/status/1737890101194293405

Add missing eslint dependencies to templates/remix-tutorial

---

.changeset/fair-bobcats-walk.md
integration/vite-node-env-test.ts
packages/remix-dev/vite/build.ts

Fixes #8364.
This PR implements the fix suggested here: https://github.com/remix-run/remix/pull/8365#issuecomment-1868309373
I've also added a test and ensured that it fails without the provided fix.

fix(remix-dev/vite): default NODE_ENV in build

---

docs/other-api/testing.md

This is a simple docs change. Wrapping a `find*` query in `waitFor` is unnecessary since that's what it's doing anyway.

docs(testing): remove redundant usage of `waitFor`

---

templates/arc/.eslintrc.cjs
templates/arc/package.json
templates/cloudflare-pages/.eslintrc.cjs
templates/cloudflare-pages/package.json
templates/cloudflare-workers/.eslintrc.cjs
templates/express/.eslintrc.cjs
templates/express/package.json
templates/fly/.eslintrc.cjs
templates/fly/package.json
templates/remix-tutorial/.eslintrc.js
templates/remix-tutorial/package.json
templates/remix/.eslintrc.cjs
templates/remix/package.json
templates/unstable-vite-express/.eslintrc.cjs
templates/unstable-vite/.eslintrc.cjs

Fix issues with templates lint configs when adding path aliases.  
* Adding the package as a dependency fixes the ability to import CSS files
* Adding the setting to the config allows path aliases to be used
Closes #8336 
Supersedes #8337 and #8435

Fix templates eslint issue when using ~ alias

---

docs/guides/client-data.md

Starting quotes were added to the file names within code examples that weren't needed.  I've compared them to the other code blocks with file names such as [here](https://remix.run/docs/en/main/file-conventions/entry.client) and the filenames had no quotes around them

docs(guides/client-data): Remove extra quote

---

docs/future/vite.md
templates/unstable-vite-express/tsconfig.json
templates/unstable-vite/tsconfig.json

Closes #8443
As discussed in the linked issue, there are type clashes between the module types coming from `@remix-run/dev` and `vite/client` due to the fact that they both register types for files like `"*.css"`, `"*.mdx"` etc.
Even though we've removed `/// <reference types="@remix-run/dev" />` from the Vite templates' `env.d.ts` files, it turns out the global module types are still included implicitly because `@remix-run/dev/dist/index.d.ts` imports from `modules.d.ts` as a top-level side effect. This means that it's currently impossible to avoid including the modules types from the old compiler. These type errors slipped through because this doesn't raise a type error in your editor, only when running `tsc`.
We could fix this by decoupling `modules.d.ts` from …

templates(vite): enable skipLibCheck in tsconfig

---

.changeset/wicked-suits-heal.md
contributors.yml
packages/create-remix/__tests__/create-remix-test.ts
packages/create-remix/__tests__/fixtures/stack/package.json
packages/create-remix/index.ts

This PR updates `create-remix` so that it only updates "*" dependencies for `@remix-run/*` packages.
For example, when create-remix runs, we currently get this change
```diff
"dependencies": {
-  "@remix-run/react": "*",
+  "@remix-run/react": "^2.4.1",
```
Unfortunately, this also affects non-Remix dependencies, such as:
```diff
"dependencies": {
-  "@remix-run/react": "*",
+  "@remix-run/react": "^2.4.1",
-  "@myorg/some-random-dep": "*"
+  "@myorg/some-random-dep": "^2.4.1"
```
which breaks when version 2.4.1 (or whatever the current Remix release is) doesn't exist.
Closes: # n/a
Unit test

fix(create-remix): only update "*" versions for Remix dependencies

---

.changeset/ninety-ducks-sin.md
packages/remix-react/browser.tsx
packages/remix-react/routeModules.ts

This PR is another fix related to #8443.
The global `import.meta.hot` types defined in `@remix-run/react` are clashing with the types provided by Vite. Since these types were not intended for consumers, I've opted to simplify and just use `@ts-expect-error` directives in the two spots that we use `import.meta.hot` (which was typed as `any` anyway).

fix(remix-run/react): fix import.meta.hot type clash

---

.changeset/dry-books-hug.md
packages/remix-serve/cli.ts
templates/express/server.js

Another update to source map loading. This should resolve issues where people reported getting server crashes when they had source maps disabled or when errors were being thrown by 3rd party packages (since source maps aren't available for those). All this does really is check that the file exists before loading it, and returning null if it doesn't (using the original path as a fallback). Mostly based on the patch suggested here: https://github.com/remix-run/remix/issues/8309#issuecomment-1868374521
Testing:
**3rd party error (tiny-invariant)**
**generic error**
**generic error after manually deleting source map**
Closes: #8309

fix (remix-serve): fallback to default path if source maps aren't available when building stack trace

---

.changeset/polite-weeks-poke.md
integration/vite-unused-route-exports-test.ts
packages/remix-dev/vite/plugin.ts

Similar to our existing compiler, this PR wraps all client route modules with a virtual module that re-exports all Remix client route exports. This means that any custom route exports that aren't consumed within the client module graph will be removed in the production build. I've added a test asserting that this is the case.
Note that while this is only of value in the production build, I've used the same technique in dev for consistency. This makes it easier to understand how Remix works from both a debugging and a teaching perspective.

fix(remix-dev/vite): tree-shake unused route exports

---

.changeset/twenty-pandas-attend.md
docs/future/vite.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/vite/build.ts
packages/remix-dev/vite/dev.ts
packages/remix-dev/vite/profiler.ts

---
Creates `.cpuprofile`s that can be uploaded to speedscope.app

vite: profiling

---

.changeset/fresh-shoes-drive.md
packages/remix-dev/server-build.ts

Fixes a type error in the cloudflare pages server (and potentially other spots) where the server build is imoprted from the virtual module:

Add isSpaMode to server build virtual module type

---

.changeset/breezy-cows-battle.md
packages/create-remix/index.ts

`bgWhite` and `whiteBright` are the same color in many terminal colorthemes, which was causing it to render as illegible white-on-white.
For some reason the `done` section was already `bgWhite`/`black` and was working properly 🤷

create-remix: high-contrast fg/bg for header colors

---

docs/future/vite.md

vite: realistic example for `process` in client

---

package.json

This field is being added to support [vite-ecosystem-ci](https://github.com/vitejs/vite-ecosystem-ci) since they use Corepack to manage package managers across the various consumer repos. I've added the version of Yarn that's running in CI.

chore: add packageManager field to package.json

---

.changeset/wild-timers-impress.md
contributors.yml
integration/helpers/create-fixture.ts
integration/spa-mode-test.ts
packages/remix-dev/config/defaults/entry.server.spa.tsx
templates/spa/app/entry.server.tsx

1. Set up a new Remix app using the instructions for [SPA Mode](https://remix.run/docs/en/main/future/spa-mode#usage)
1. Start the dev server with `remix vite:dev`
1. Open Firefox Dev Tools and observe the warning:
```
This page is in Quirks Mode. Page layout may be impacted. For Standards Mode use “<!DOCTYPE html>”
```

Fix quirks mode warning for SPA template

---

docs/file-conventions/asset-imports.md

This documentation is currently misleading – only a subset of files are importable with asset imports. This links to the source code and summarizes its scope.

docs(assets): link to supported asset file types

---

docs/future/vite.md

Document adding additional Vite dev server options.

docs(vite): document adding additional Vite dev server options

---

packages/remix-dev/vite/build.ts
packages/remix-dev/vite/plugin.ts

All paths on the resolved Remix config should be absolute but `serverBuildDirectory` was root-relative which made it awkward for any consuming code.
Since we're now resolving options from the Vite plugin, I've refactored the code to make it clearer that we're only calling `resolveConfig` for options that are compatible with the Remix esbuild compiler.

refactor(remix-dev/vite): resolve absolute serverBuildDirectory

---

packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts
packages/remix-dev/vite/build.ts
packages/remix-dev/vite/plugin.ts

This PR cleans up the resolved config objects a little. The goal is to make the resolved Vite plugin config suitable to be exposed via public APIs, e.g. the new adapter `buildEnd` hook.
For the resolved Vite plugin config, I've replaced `isSpaMode` with `ssr` and removed `relativeAssetsBuildDirectory` so that the object mirrors what was passed in.
I also removed `isSpaMode` from the resolved config for the old compiler since it's unused in that context.

refactor(remix-dev): clean resolved config

---

templates/unstable-vite-express/.eslintrc.cjs
templates/unstable-vite-express/package.json
templates/unstable-vite-express/server.mjs

- Set eslint node environment for server.mjs
- Use compression and disable x-powered-by in express
- Use morgan for logging requests
- Make port configurable by environment variable
These changes make the express server behavior more like the normal express from the official template: https://github.com/remix-run/remix/tree/main/templates/express 
I made these changes after running `create-remix` with the `remix-run/remix/templates/unstable-vite-express` template. I tested both `dev` and `buld`/`start` modes.
After updating the source, I then ran the following:
```ps1
npx create-remix@latest --template /dev/OSS/remix/templates/unstable-vite-express
```
And again the install worked along with the `dev`, `build`, and `start` commands.

template(vite): Improve vite-express template to match official express template server behavior

---

templates/express/.eslintrc.cjs
templates/express/server.js
templates/unstable-vite-express/.eslintrc.cjs
templates/unstable-vite-express/package.json
templates/unstable-vite-express/server.js

This is a follow-up to #8564. This further aligns with the `express` template:
- Renamed `server.mjs` to `server.js` since it's an ESM project.
- Extracted the Remix request handler into a `remixHandler` variable.
- Fixed the asset fingerprint comment to reference Vite rather than Remix (i.e. the Remix compiler).
As part of the alignment, the following have been fixed across both `express` and `vite-express` templates:
- Fixed the `".eslintrc.cjs"` path within the ESLint config itself.
- Added a full localhost URL to the console log for quick access during local dev in the `express` template.

template(vite-express): align with express template

---

docs/future/vite.md

The `serverBuildPath` option from `remix.config.js` has been replaced with `serverBuildFile` in the Vite plugin so that we can support server bundles.

docs(vite): remove outdated serverBuildPath docs

---

contributors.yml
docs/future/server-bundles.md

Fixing url to remix vite plugin. Linking to .md file and therefore being incorrectly routed.

Update server-bundles.md (fix broken link)

---

.changeset/bright-days-brush.md
.changeset/thirty-coins-give.md
docs/future/vite.md
integration/vite-adapter-test.ts
integration/vite-build-manifest-test.ts
integration/vite-server-bundles-test.ts
packages/remix-dev/index.ts
packages/remix-dev/vite/build.ts
packages/remix-dev/vite/index.ts
packages/remix-dev/vite/plugin.ts

This PR makes a few interrelated changes:
- To future proof the server bundles `bundles.json` concept, the `build/server/bundles.json` file has been replaced with a more general `build/manifest.json` file. This allows us to add more build metadata in the future without having multiple manifest files on disk.
- The build manifest on disk feels like noise for most consumers. So, similar to many other build tools ([including Vite](https://vitejs.dev/config/build-options#build-manifest)) we don't write a manifest by default.
- In order to know where to write the build manifest to, we need to know where the overall build root is. We currently do not have this knowledge since the server and client build output paths are independently configurable. To address this, we're now replacing the …

feat(remix-dev/vite): add buildDirectory and manifest options

---

.changeset/great-mice-march.md
packages/remix-dev/vite/plugin.ts

Vite v4 is not supported by our peer dependency range, but this backwards compatibility layer was still left in the code temporarily just in case someone was stuck on v4 in the short term. Now that we're getting close to being stable, it's a good time to remove this layer and fully commit to v5 as the new minimum version.

fix(remix-dev/vite): remove Vite v4 back compat

---

docs/start/tutorial.md

Addressing #8565 and point 2 of #8395
- Adds callouts before TS errors are introduced
- Adds a `key` to a `Form` to avoid navigation bug

docs(tutorial): add callouts in the tutorial when type errors are introduced

---

packages/remix-dev/vite/build.ts
packages/remix-dev/vite/plugin.ts
packages/remix-dev/vite/styles.ts

This is a follow-up to https://github.com/remix-run/remix/pull/8582, in preparation to expose the resolved Remix config as public API (e.g. via the adapter buildEnd hook).
The only remaining properties on the resolved `remixConfig` object that aren't present in the user-facing config type are `rootDirectory`, `entryClientFilePath` and `entryServerFilePath`. These have now been moved to the `buildContext` object. Since a lot of code assumes these are on `remixConfig`, it required a bit of a refactor to accomodate this.

refactor(remix-dev/vite): clean resolved Remix config

---

integration/vite-adapter-test.ts
packages/remix-dev/vite/build.ts
packages/remix-dev/vite/plugin.ts

This also removes the internal aliasing of `unstable_ssr` as just `ssr` so we don't need a translation layer when passing the resolved config back out to `buildEnd`.

feat(remix-dev/vite): pass entire remixConfig to buildEnd

---

.changeset/two-pumpkins-vanish.md
docs/future/server-bundles.md
docs/future/vite.md
integration/vite-adapter-test.ts
integration/vite-server-bundles-test.ts
packages/remix-dev/vite/build.ts
packages/remix-dev/vite/plugin.ts

Since this option is being used for hosting provider integrations, we want to ensure that it's relatively stable within the context of the Vite plugin.
At this moment it's still technically considered unstable because the entire Vite plugin is unstable, but we can't see this API changing any more than the other plugin options, if at all.

feat(remix-dev/vite): remove unstable prefix from serverBundles

---

.changeset/cyan-dingos-care.md
packages/remix-dev/vite/build.ts

Since server bundle IDs are used as folder names and we're also currently considering using ID as part of filenames (e.g. a manifest file like `server-${serverBundleId}-manifest.json`), we want to ensure that the character set is limited.

fix(remix-dev/vite): validate server bundle IDs

---

.changeset/thin-rings-eat.md
packages/remix-dev/vite/plugin.ts
packages/remix-dev/vite/static/refresh-utils.cjs

👆 The `?import&t=` request is redundant. Same module as the `?t=` request (both are 8.1kb)

vite: reduce network calls for route modules during HMR

---

packages/remix-dev/vite/plugin.ts

instead, we pass a list of special Remix exports to accept during HMR and invalidate when any other non-component exports are encountered

remove unused experimental flag `hmrPartialAccept`

---

docs/discussion/runtimes.md
docs/other-api/adapter.md

At Fastly, we have unified our branding for edge computing with the name "Fastly Compute".
This pull request updates references in the docs to our product to this name.
These are docs-only, so it's been branched from the main branch.

Unify Fastly Compute product name in docs

---

.changeset/tender-cherries-taste.md
packages/remix-dev/vite/plugin.ts
packages/remix-server-runtime/build.ts

Reported in discord - TS was throwing an error in the vite express template if you use a `server.ts`

Add mode field into generated vite server build

---

.changeset/green-baboons-punch.md
docs/future/vite.md
integration/vite-build-test.ts
integration/vite-dev-test.ts
packages/remix-dev/vite/plugin.ts

tl;dr: we were abusing `enforce: "post"` so that `mdx` plugin could be place after `remix` plugin. Instead, we should either expect plugins like `mdx` to self-declare as `pre` or rely on Vite plugin ordering.
"Post" plugins are meant primarily for build analysis. Previously we were relying on `enforce: "post"` to ensure that plugins that transpile other languages to JS/TS ran before the Remix plugin. However, it should be the responsability of _those_ plugins to declare themselves with `enforce: "pre"`. In the case of MDX, the canonical plugin is not a Vite plugin, but rather a Rollup plugin so it cannot set `enforce` as that is a Vite-only API.
Ideally, someone would wrap the MDX Rollup plugin and declare it as `enforce: "pre"`. This can also be done in userland through a simple object …

vite: no `enforce: "post"`

---

.changeset/curly-camels-applaud.md
packages/remix-dev/cli/run.ts
packages/remix-dev/vite/build.ts

vite: add sourcemap flags

---

docs/future/spa-mode.md

In spa-mode.md, I found the description "Automatic route-based code-spitting via [`route.lazy`](https://reactrouter.com/en/main/route/lazy)", but I confirmed that the page of [`route.lazy`](https://reactrouter.com/en/main/route/lazy) describes "route-based code-splitting".
I have never seen the word `"code-spitting"`, and I have confirmed that the word `"code-splitting"` is used on the page of [`route.lazy`](https://reactrouter.com/en/main/route/lazy), so I judged that the description in spa-mode.md is incorrect and corrected it.

docs(spa-mode): fix typo in route-based code-splitting

---

.changeset/spicy-buses-play.md
docs/future/vite.md
integration/vite-cloudflare-test.ts
packages/remix-dev/index.ts
packages/remix-dev/vite/index.ts
packages/remix-dev/vite/plugin.ts
packages/remix-dev/vite/presets/cloudflare.ts
templates/unstable-vite-cloudflare/vite.config.ts

vite: cloudflare preset load context

---

packages/remix-react/browser.tsx

This is just a minor clean up to reduce global noise in production.

Only handle critical CSS globals in development

---

.changeset/cool-fishes-attack.md
docs/future/presets.md
docs/future/server-bundles.md
docs/future/vite.md
packages/remix-dev/index.ts
packages/remix-dev/vite/index.ts
packages/remix-dev/vite/plugin.ts

This PR was primarily about adding documentation for the new `presets` option, but writing these docs highlighted that we're missing a couple of exported types for preset authors.

Export more Vite types, document presets

---

docs/future/vite.md
templates/unstable-vite-cloudflare/vite.config.ts

In the docs, I noticed that Vite's `ssr.resolve.externalConditions` option wasn't being set in our first Cloudflare preset example and that we only mentioned this in the migration guide. While fixing this, I decided it's better to keep the Remix plugin at the top of the Vite config, so I've refactored all examples and the Cloudflare Vite templated to follow this pattern.

Make Cloudflare preset usage consistent

---

docs/future/vite.md

The line highlighting in the Vite MDX docs got out of sync when we removed our usage of `enfore: 'pre'` from the Remix Vite plugin and made it so that the MDX plugin needs to come before Remix.

Fix highlighting in Vite MDX docs

---

contributors.yml
templates/cloudflare-pages/package.json
templates/cloudflare-workers/package.json

bump the wrangler version present in the cloudflare template's dev dependency from 3.8.0 to ^3.24.0, this matches the peer dependency present in remix-dev (without this change the current template would not work with the current remix-dev package becuase of the wrangler version missmatch)
____
To manually test the changes, run `create-remix` and pass to it the official repo's cloudflare-pages template:
```sh
npx create-remix@latest --template https://github.com/remix-run/remix/tree/main/templates/cloudflare-pages
```
and notice that create-remix fails when trying to install the npm dependencies:
Then try running `create-remix` with the template from this PR's branch:
```sh
npx create-remix@latest --template https://github.com/dario-piotrowicz/remix/tree/cloudflare-templates-bump-wrangler/t …
```

fix(templates): bump the wrangler version up in the cloudflare templates

---

.changeset/shaggy-sheep-cheer.md
docs/future/vite.md
integration/helpers/vite-template/package.json
integration/vite-css-test.ts
package.json
packages/remix-dev/package.json
packages/remix-dev/vite/plugin.ts
yarn.lock

Fixes https://github.com/remix-run/remix/issues/7786
This adds built in support for `.css?url` imports in Vite v5.1.0 (currently in beta) to ease migration of [Remix's regular CSS imports.](https://remix.run/docs/en/main/styling/css)
```diff
-import styles from "~/styles/dashboard.css";
+import styles from "~/styles/dashboard.css?url";
```
The only thing we need to do to support this out of the box is to enable `build.cssMinify` in server builds by default. If we don't do this, content hashes differ between server and client since the server doesn't have minification enabled by default.
I've opted to call out the beta status of this feature rather than waiting for Vite 5.1.0 so that it doesn't need to be a blocker for a stable release of the Remix Vite plugin.
We had an existing test for …

Support Vite v5.1.0's `.css?url` imports

---

contributors.yml
docs/discussion/data-flow.md

It wasn't immediately obvious where `<Form />` was coming from, and I _think_ that this is its expected import (from `@remix-run/react`).

docs: add `<Form />` import to data-flow.md

---

contributors.yml
docs/start/tutorial.md

From what I can read from the preceding and following text, I felt that the 'formData.get' part should be highlighted here.

docs: fix tutorial contact action highlight line numbers

---

integration/helpers/vite.ts
integration/vite-cloudflare-test.ts
integration/vite-css-test.ts
integration/vite-dot-server-test.ts
integration/vite-dotenv-test.ts
integration/vite-hmr-hdr-test.ts
integration/vite-loader-context-test.ts
integration/vite-manifests-test.ts
integration/vite-node-env-test.ts
integration/vite-presets-test.ts
integration/vite-route-added-test.ts
integration/vite-route-exports-modified-offscreen-test.ts
integration/vite-server-bundles-test.ts

Our `VITE_CONFIG` template helper incentivized test fixture code to use tricks like dynamic imports that are not representative of user code. The API for `VITE_CONFIG` has grown complex and inconsistent. This PR breaks down `VITE_CONFIG` into two pieces:
- `viteConfig.basic` as a convenience method to quickly configure Vite for our integration tests without any fluff
- `viteConfig.server` helper to construct _just_ the `server` field while letting the test define a custom `vite.config.ts`

test: refactor vite config templates

---

.changeset/forty-squids-travel.md
integration/vite-plugin-order-validation-test.ts
packages/remix-dev/vite/plugin.ts

With the introduction of https://github.com/remix-run/remix/pull/8627, plugin order now matters when using Rollup plugins since only Vite plugins can set `enforce: "pre"`. Most commonly, this is going to cause errors if consumers have added the MDX Rollup plugin after the Remix plugin in their Vite plugins array.
Inspired by [vite-plugin-react-swc](https://github.com/vitejs/vite-plugin-react-swc), this PR adds an explicit error message when the MDX plugin is in the wrong order rather than allowing a lower level error message to surface when Remix tries to work with unprocessed MDX files.
I've written the code in a way that makes it easy to add more plugin order checks in the future. I've also added a test to ensure the validation works as expected.

Vite: Validate MDX Rollup plugin order

---

docs/future/vite.md

Just a couple of tweaks to the basename and publicPath docs to improve link legibility and streamline some of the wording.

Update Vite basename and publicPath docs

---

docs/future/presets.md

The presets docs were still using the old API.

Update presets example to new Cloudflare preset API

---

.changeset/brown-rats-flow.md
docs/guides/envvars.md
docs/guides/manual-mode.md
docs/other-api/dev.md
integration/helpers/deno-template/server.ts
packages/remix-cloudflare-pages/worker.ts
packages/remix-dev/__tests__/fixtures/cloudflare/server.ts
packages/remix-dev/__tests__/fixtures/deno/server.ts
templates/arc/server.ts
templates/cloudflare-pages/server.ts
templates/deno/server.ts
templates/express/server.js

vite: make getLoadContext optional for cloudflare pages handler

---

.changeset/wet-bulldogs-appear.md
integration/vite-hmr-hdr-test.ts
packages/remix-dev/vite/plugin.ts

Vite: Enable HMR for .md and .mdx files

---

integration/helpers/vite-template/package.json
package.json
packages/remix-dev/package.json
yarn.lock

Just ensuring our tests are passing against the latest beta ahead of Vite's 5.1.0 release.

Update Vite dev dep to 5.1.0-beta.7

---

contributors.yml
docs/guides/client-data.md

I was reading [this page](https://remix.run/docs/en/main/guides/client-data) and noticed an example for
> A route that only depends on a client loader looks like this.
still included a call to `serverLoader()`. This seems wrong, so this PR removes that call.

Don't call serverLoader for client-only example

---

.changeset/tender-pens-tan.md
packages/remix-dev/vite/plugin.ts
templates/spa/README.md
templates/spa/package.json

This enables use of `vite preview` for serving built SPA sites. This works better than `http-server` because it correctly supports the SPA fallback (i.e. serving a statically deployed site with all routes being served from a root `/index.html`).
This is more than a template change because the Remix Vite plugin was setting `appType: "custom"`, preventing `vite preview` from working in `"spa"` mode. The patch also sets the `build.outDir` when previewing so additional command line options aren't needed.
The SPA template has been updated to use `npm run preview` (or `yarn preview`) to preview the built site. The `start` script (`npm run start`) has been removed from the SPA template because it isn't something that should be used in production.
Closes: #8623
I opened up my …

vite: Enable use of `vite preview` to preview built SPA sites

---

.changeset/fresh-knives-deliver.md
docs/components/scripts.md
docs/file-conventions/root.md
integration/client-data-test.ts
integration/root-route-test.ts
packages/remix-dev/vite/plugin.ts
packages/remix-react/routeModules.ts
packages/remix-react/routes.tsx
packages/remix-server-runtime/routeModules.ts
templates/arc/app/root.tsx
templates/cloudflare-pages/app/root.tsx
templates/cloudflare-workers/app/root.tsx
templates/deno/app/root.tsx
templates/express/app/root.tsx
templates/fly/app/root.tsx
templates/remix-javascript/app/root.jsx
templates/remix/app/root.tsx
templates/spa/app/root.tsx
templates/unstable-vite-cloudflare/app/root.tsx
templates/unstable-vite-express/app/root.tsx
templates/unstable-vite/app/root.tsx

RFC https://github.com/remix-run/remix/discussions/8702
Closes https://github.com/remix-run/remix/discussions/8703

Support an optional Layout export from the root route

---

.changeset/eighty-years-accept.md
integration/helpers/create-fixture.ts
integration/spa-mode-test.ts
packages/remix-dev/vite/plugin.ts

Fix SPA Mode issue when using a basename

---

templates/spa/README.md

Because this also fixes the typo of "yo" -> "to" this pull request supersedes #8639.
Because `http-server` isn't able to serve the `index.html` file as a fallback for what would otherwise be 404 routes (see #8624) it is best to suggest a different server to preview or run a built SPA application. This change doesn't change how the `start` script in `package.json` uses `http-server` because that is not specifically addressed in the `README.md`.
This change includes part of the `README.md` updates from #8624, but without the changes to `packages/remix-dev/vite/plugin.ts` needed to support `vite preview`.

template(spa): Provide example of server that can handle SPA routes

---

.changeset/vite-whatwg-querystring.md
contributors.yml
packages/remix-dev/vite/plugin.ts

Issue if you have middleware that pass query string through any processing. anything WHATWG compatible will render a query param without a value ending with `=` this breaks matching in the vite plugin.
Included code so that vite plugin will match against the supported query string if it ends in '='.
another solution would just change the query string to something a bit more compatible like `?client-route=1` Would be willing to open a PR for that. I went for this one due to it being compatible with current solution.
Tested on a custom express server  that had a searchParams filter that parses the query string that transforms `?client-route` into `?client-route=` because of how WhatWG URL serializes searchParams.
the middleware mock basically looks like this (with …

Fix Vite client route requests with pre-processed search params

---

packages/remix-dev/vite/plugin.ts

This is a follow-up to https://github.com/remix-run/remix/pull/8740.
As suggested by @cythrawll, this can be simplified by changing our client route query string into a format that will be identical after being parsed and serialized.

Simplify Vite client route query string logic

---

.changeset/quiet-cups-attack.md
packages/remix-dev/config.ts

Remix config options are type checked in Vite when using `vite.config.ts`. This has highlighted a gap in our config types where a sync `routes` function is a type error even though it works fine.
A good example of this is when using the [v1 route convention package](https://github.com/remix-run/v1-compat-utils/tree/main/packages/v1-route-convention) which is sync. From the readme:
```ts
// remix.config.js
const { createRoutesFromFolders } = require("@remix-run/v1-route-convention");
/** @type {import('@remix-run/dev').AppConfig} */
module.exports = {
// Tell Remix to ignore everything in the routes directory.
// We'll let `createRoutesFromFolders` take care of that.
ignoredRouteFiles: ["**/*"],
routes: (defineRoutes) => {
// `createRoutesFromFolders` will create routes for all files in …
```

Fix sync `routes` config type error

---

.changeset/nice-jobs-boil.md
packages/remix-dev/vite/styles.ts

Hi 👋 
While integrating Remix<>Hydrogen in workerd, I found a weird issue with path resolution when applying critical CSS. Turns out it was resolving `app/entry.client.tsx` using `process.cwd()` (by omission) instead of `rootDirectory`, which can be different in some situations.

Fix Vite critical CSS resolution when cwd differs from project root

---

contributors.yml
docs/components/link.md
docs/hooks/use-navigate.md

- Add `to` prop to `Link` docs page.
- Also renames prop type `To` in the docs from to `Path` which better matches the typescript type.
- I believe this is a better name because `To` is defined as `export type To = string | Partial<Path>;` and the docs are referring to the `Path` part of that type.

docs: add `to` prop to link, rename `To` to `Path`.

---

.changeset/brave-yaks-vanish.md
packages/remix-dev/vite/plugin.ts

vite: fix server export dead-code elimination for routes outside of app dir

---

.changeset/orange-cherries-flow.md
integration/vite-build-test.ts
packages/remix-dev/vite/plugin.ts

Fixes #8786.
We already had a similar test for generic assets using a `.txt` import, but `.css?url` imports need to be handled separately, so I've added another test case for this.

Vite: Move SSR-only CSS files to client build

---

.changeset/mighty-carpets-lie.md
docs/future/presets.md
integration/vite-presets-test.ts
packages/remix-dev/vite/plugin.ts

This change allows presets to configure Remix differently based on the user config.
The use case driving this change is to allow Vercel to avoid setting `serverBundles` when consumers have enabled SPA mode, otherwise Vercel preset consumers get the following warning and there's no way to avoid it:
> ⚠️  SPA Mode: the serverBundles config is invalid with unstable_ssr:false and will be ignored

Vite: Pass `remixUserConfig` to preset config hook

---

.changeset/long-walls-rescue.md
packages/remix-dev/vite/plugin.ts

Closes: #8805
I've used the reproduction in the linked issue to test that this works and the errors went away.

chore: fix Windows path normalization in Vite

---

.changeset/shy-gifts-ring.md
docs/file-conventions/remix-config.md
docs/future/vite.md
docs/guides/migrating-react-router-app.md
integration/flat-routes-test.ts
integration/helpers/cf-template/remix.config.js
integration/helpers/deno-template/remix.config.js
integration/helpers/node-template/remix.config.js
packages/create-remix/__tests__/fixtures/stack/remix.config.js
packages/remix-dev/__tests__/fixtures/cloudflare/remix.config.js
packages/remix-dev/__tests__/fixtures/deno/remix.config.js
packages/remix-dev/__tests__/fixtures/node/remix.config.js
packages/remix-dev/__tests__/fixtures/stack/remix.config.js
packages/remix-dev/config/flat-routes.ts
scripts/playground/template/remix.config.js
templates/arc/remix.config.js
templates/cloudflare-pages/remix.config.js
templates/cloudflare-workers/remix.config.js
templates/deno/remix.config.js
templates/express/remix.config.js
templates/fly/remix.config.js
templates/remix-javascript/remix.config.js
templates/remix-tutorial/remix.config.js
templates/remix/remix.config.js

This change is in response to the following issue: #8744
Having dotfiles like `.DS_Store` in the routes directory causes hard-to-debug errors when `"**/.*"` is not configured in `ignoredRouteFiles`. This is particularly notable when using the Vite plugin since we've encourage usage without any config (i.e. `remix()` in the plugins array). Currently none of the Vite templates have `ignoredRouteFiles` set.
Since we've moved to flat routes, it no longer makes sense to have route files starting with a `.` character since it's meant to be a delimiter denoting a `/` in the URL. As a result, rather than doubling down and adding `remix({ ignoredRouteFiles: ["**/.*"] })` to all Vite templates, it makes more sense to always ignore route files starting with `.`.
The bulk of this PR is just updating …

Always ignore route files starting with `.`

---

.changeset/cold-suns-notice.md
integration/helpers/vite-template/package.json
integration/helpers/vite.ts
integration/vite-css-test.ts
package.json
packages/remix-dev/package.json
packages/remix-dev/vite/plugin.ts
yarn.lock

Fixes #8813
The linked issue was introduced in #8796 but slipped through because the Vite CSS test didn't assert the build command succeeded without any output to `stderr`. The test still managed to pass because the build output still worked if you ignored the error message which meant all of our assertions still passed. I've updated the test to catch this issue along with the fix.

Fix build errors with Vite `.css?url` imports

---

contributors.yml
docs/future/vite.md

This pull request updates the Cloudflare documentation for Vite regarding [augmenting load context](https://remix.run/docs/en/main/future/vite#augmenting-load-context) to include a global declaration of the `Env` type, matching the `vite-cloudflare` template [here](https://github.com/remix-run/remix/blob/main/templates/vite-cloudflare/load-context.ts#L3-L9). The current documentation does not define `Env`.

docs(future/vite): bring in line with template

---

.changeset/layout-error-boundary.md
integration/root-route-test.ts
packages/remix-react/errorBoundaries.tsx

fix: account for presence of Layout in default error boundary

---

docs/future/vite.md

I had previously updated [these docs](https://remix.run/docs/en/main/future/vite#augmenting-load-context) which include a highlighted code snippet but neglected to update the line numbers for highlighting. This PR should fix the highlighting.

docs(future/vite): update code highlighting

---

.changeset/silver-years-roll.md
integration/vite-server-bundles-test.ts
packages/remix-dev/vite/plugin.ts

This issue meant that each server bundle generated a separate subset of the browser manifest rather than generating a single unified browser manifest. To fix this issue I've had to split the singular Remix manifest into a separate manifest for both client and server. This ensures that while the server bundle only contains a subset of the manifest, the client always receives the full manifest.
cc @TooTallNate.

Fix `serverBundles` issue with multiple browser manifests

---

.changeset/tender-keys-develop.md
contributors.yml
packages/remix-dev/vite/plugin.ts

I was in need of having the assets directory in a different location due to a proxy. Leveraging Vite's `build#assetsDir`, I was able to achieve most of what I needed, but there was a straggler file at `build/client/assets/manifest-{hash}.js` even though the configuration of the asset was set to a different directory. To ensure this file adheres to the Vite configuration, I've added handling to build the path from the Vite configuration.
I wasn't able to find any test regarding the Vite plugin functionality so I ended up utilizing manual testing using the playground. To recreate this, I leveraged the `template.local` feature of the `scripts/playground` directory.
1. Run the following from the project root `npx create-remix@latest ./scripts/playground/template.local …

Support custom Vite `build.assetsDir` option

---

docs/discussion/server-vs-client.md
docs/file-conventions/routes.md
docs/guides/file-uploads.md

While reading the [Route File Naming docs](https://remix.run/docs/en/main/file-conventions/routes#folders-for-organization) , I got confused by the route examples `.server.tsx`. The names of the files implie no JSX return, so I guess it should be a `.server.ts` file instead.
Even more, if you read the [docs](https://remix.run/docs/en/main/file-conventions/-server) for `*.server.ts`, it doesn't mention the `tsx` extension.
While it seems that both `.tsx` and `.ts` work (haven't thoroughly checked tho), I think those examples should be a `.ts` extension to reinforce the idea of extract colocating logic next to components, like Ryan brilliantly explained in [this video](https://www.youtube.com/watch?v=xEl8OCMOf_I).
I also changed `.client.tsx` to `.client.ts` in the `server-vs-client.md` …

docs: update `*.server.tsx` to `*.server.ts`

---

templates/vite-cloudflare/app/entry.client.tsx
templates/vite-cloudflare/app/entry.server.tsx
templates/vite-express/app/entry.client.tsx
templates/vite-express/app/entry.server.tsx
templates/vite/app/entry.client.tsx
templates/vite/app/entry.server.tsx
templates/vite/vite.config.ts

Align vite templates with others:
**1.** `entry.*` files are included by default and can be removed if no customization is needed
```
> cp templates/remix/app/entry.* templates/vite/app/
> cp templates/express/app/entry.* templates/vite-express/app/
> cp templates/cloudflare-workers/app/entry.* templates/vite-cloudflare/app/
```
**2.** `installGlobals` is called by default and can be removed if desired (this also ensures that `vite dev` and `remix-serve` behave the same).  This is only needed for `templates/vite` since it's in the express server in `vite-express` and not needed for `vite-cloudflare`

Sync vite templates with others re: entry files and polyfills

---

integration/client-data-test.ts
packages/remix-dev/package.json
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
yarn.lock

Bump router to latest prerelease and add an integration test for https://github.com/remix-run/remix/issues/8889 which is fixed in RR 6.22.2

Bump Router prerelease

---

contributors.yml
templates/vite-cloudflare/tsconfig.json
templates/vite-express/tsconfig.json
templates/vite/tsconfig.json

Closes: #8898 
I edited the provided StackBlitz link on the issue with the new `tsconfig.json` on this PR.
Note:
1. For the `node` type, I'm not sure if we still need it or not. If we need it, then I will put it back and install the `@types/node` on the `devDependencies`.
2. For the `include` field, I only added `.ts` files to detect, let me know if I also need to include `.tsx` files.

Type check `.server`/`.client` dirs in Vite templates

---

contributors.yml
templates/vite-express/tsconfig.json
templates/vite/tsconfig.json

On `vite` and `vite-express` template. We don't need the `node` type because we already have the `@remix-run/node` type.
This PR is created based on this feedback: https://github.com/remix-run/remix/pull/8899#pullrequestreview-1902442836, which is related to issue #8898.

Remove `node` type from Vite template tsconfigs

---

integration/headers-test.ts
packages/remix-dev/config/defaults/entry.server.cloudflare.tsx
packages/remix-dev/config/defaults/entry.server.deno.tsx
packages/remix-dev/config/defaults/entry.server.node.tsx
templates/arc/app/entry.server.tsx
templates/cloudflare-pages/app/entry.server.tsx
templates/cloudflare-workers/app/entry.server.tsx
templates/deno/app/entry.server.tsx
templates/express/app/entry.server.tsx
templates/fly/app/entry.server.tsx
templates/remix-javascript/app/entry.server.jsx
templates/remix/app/entry.server.tsx
templates/vite-cloudflare/app/entry.server.tsx
templates/vite-express/app/entry.server.tsx
templates/vite/app/entry.server.tsx

- properly handle errors in Cloudflare template
- drastically simplify node templates
Closes: #

chore: simplify template entry.server files

---

.changeset/curly-apples-exercise.md
packages/remix-dev/cli/commands.ts
packages/remix-dev/cli/run.ts
packages/remix-dev/config/format.ts
packages/remix-dev/vite/build.ts
packages/remix-dev/vite/plugin.ts

Read Vite config in `reveal`/`routes` commands

---

templates/spa/vite.config.ts
templates/vite-cloudflare/vite.config.ts
templates/vite-express/vite.config.ts
templates/vite/vite.config.ts

This gives consumers a more locked-down dev server by default without forcing it on every plugin consumer. We may want to revisit this, but this is a safe first step since consumers can always modify/delete it if it's causing trouble.
https://vitejs.dev/config/server-options.html#server-fs-allow

Add `server.fs.allow` to Vite templates

---

templates/spa/vite.config.ts

The SPA template is currently broken due to this setting. In dev mode, I get the following error:
```
[vite] Internal server error: module is not defined
at eval (/path/to/project/node_modules/react/jsx-dev-runtime.js:8:3)
at instantiateModule (file:///path/to/project/node_modules/vite/dist/node/chunks/dep-jDlpJiMN.js:54725:15)
```
During the build I also see this:
```
x Build failed in 124ms
Error [RollupError]: [commonjs--resolver] Cannot bundle Node.js built-in "stream" imported from "node_modules/react-dom/cjs/react-dom-server-legacy.node.production.min.js". Consider disabling ssr.noExternal or remove the built-in dependency.
file: /path/to/project/node_modules/react-dom/server.node.js
```
Rather than simply removing `ssr.noExternal`, I tried to fix it by also setting `ssr.external` …

Remove `ssr.noExternal` from SPA template

---

.github/workflows/test-pr-ubuntu.yml

None of our CI Build/Unit/E2E test stuff checks any `templates` I don't think?

Don't run Build/Test CI on PR's that only touch templates

---

contributors.yml
docs/discussion/data-flow.md

Quick typo fix of `complets` --> `completes`.
Cheers!

Fix typo in data flow docs

---

.changeset/little-turtles-applaud.md
packages/remix-dev/vite/build.ts

Fixes #8935
The Remix CLI was defaulting `build.sourcemap` to `false` in the inline Vite config object passed to `vite.build`, but this was taking higher precedence than `build.sourcemap` in the user's Vite config. This meant that the only way to generate sourcemaps was via the `--sourcemapServer` and `--sourcemapClient` CLI flags. To avoid this, we need to default the values for these options to `undefined` rather than `false`.

Vite: Fix `build.sourcemap` config support

---

.changeset/tall-frogs-visit.md
integration/helpers/vite.ts
integration/vite-server-fs-allow-test.ts
packages/remix-dev/vite/plugin.ts

When using Vite's `server.fs.allow` option (https://vitejs.dev/config/server-options#server-fs-allow), the default client entry file throws an error when used because it's not in the allow list. To fix this, we detect whether `server.fs.allow` has been defined, and if so, we ensure that all default entry files are included in the allow list.
I've included a test case that fails when the fix hasn't been applied.

Vite: Fix `server.fs.allow` with default entry

---

docs/file-conventions/root.md

Added some docs to clear up confusion around the inability to use `useLoaderData` in a `Layout` component when rendering an error boundary
See https://github.com/remix-run/remix/issues/8951 and https://github.com/remix-run/remix/discussions/8846.

Add note to docs on layout useLoaderData restriction

---

docs/future/spa-mode.md

Follow up to https://github.com/remix-run/remix/pull/8952

Update docs regarding SPA Template ssr.noExternal setting

---

templates/spa/vite.config.ts
templates/vite-cloudflare/vite.config.ts
templates/vite-express/vite.config.ts
templates/vite/vite.config.ts

This reverts #8950.
Upon further discussion, we think this is overly protective as a default since most consumers don't need this and it's more likely to just cause them issues.

Remove `server.fs.allow` from Vite templates

---

.eslintignore

`pnpm format` is currently formatting `pnpm-lock.yaml` because it's using `.eslintignore` as the ignore file.

Add `pnpm-lock.yaml` to `.eslintignore`

---

.github/workflows/test-full.yml

This PR is a temporary fix to unblock CI.
Playwright tests are hanging in CI when running against Node 20, currently 20.11.1. I've narrowed it down to this line that's hanging indefinitely: https://github.com/remix-run/remix/blob/cc4dcf1e9f244341d4c73cfc614dd082ac95c65b/integration/helpers/create-fixture.ts#L94
If I try to import the server build file directly within Node, everything works fine. I tried commenting out the contents of the server build to further narrow it down and found that it only hangs when importing Remix packages. I'm not sure why this is happening since the move to pnpm, but this import statement doesn't hang in Node 20.5.1, so I'm updating our workflows to use this version until we can properly fix it.

Pin Playwright to Node 20.5.1 to fix hanging tests

---

contributors.yml
templates/deno/README.md

This PR updates a link to Deno's import maps in the Deno template that was 404ing.

templates(deno): fix import maps docs link

---

.github/workflows/nightly.yml

It looks like your nightly releases [broke](https://github.com/remix-run/remix/actions/workflows/nightly.yml) with the `pnpm` switch.  Since the nightly workflow runs on a cron job, it always uses the workflow file from `main`, even though it checks out the source code from `dev` - per this comment I found when I went to check out the workflow 🤣 
```
```
This copies the updated file from `dev` down to `main` and hopefully tonights nightly release will pass 🤞

Update nightly release to use pnpm since it checks out the dev branch

---

integration/vite-build-test.ts

This fixes an issue where the old test helpers hang in Node 20.6+ which is currently preventing our Vite tests from running in vite-ecosystem-ci.

Migrate Vite build test to Vite test helpers

---

.changeset/shy-buttons-buy.md
packages/remix-react/single-fetch.tsx

fix: escape single fetch transfer

---

.changeset/single-fetch-client-loaders.md
integration/single-fetch-test.ts
packages/remix-react/components.tsx
packages/remix-react/single-fetch.tsx

Change the logic for `serverLoader` calls from `clientLoader`'s in single fetch mode so we're not over-fetching on the server if a `clientLoader` never calls `serverLoader`.
Todo:

Update single fetch logic when clientLoaders are present

---

templates/remix-javascript/vite.config.js

This file wasn't cleaned up when copying from the `remix` template.

Remove vite-tsconfig-paths from remix-javascript template

---

.changeset/odd-frogs-attend.md
packages/remix-server-runtime/__tests__/server-test.ts
packages/remix-server-runtime/server.ts

fix: handle net new redirects created by handleDataRequest

---

docs/guides/css-files.md

Now that we're on Vite, this guide covers the pros and cons of bundled CSS vs Vite's `?url` CSS imports. This topic comes up quite a bit so I thought it'd be good to have a guide we can point people to.

Add "CSS Files" guide

---

jest/jest.config.shared.js
package.json
packages/remix-architect/__tests__/server-test.ts
packages/remix-architect/server.ts
packages/remix-express/__tests__/server-test.ts
packages/remix-node/__tests__/fileUploadHandler-test.ts
packages/remix-node/globals.ts
packages/remix-node/package.json
packages/remix-react/__tests__/setup.ts
packages/remix-server-runtime/__tests__/formData-test.ts
packages/remix-testing/jest.setup.js
packages/remix-testing/package.json
pnpm-lock.yaml
scripts/bump-fetch-versions.sh
scripts/deployment-test/_shared.mjs
scripts/deployment-test/cf-pages.mjs
scripts/deployment-test/cf-workers.mjs

Use undici as our fetch polyfill going forward. This will allow us to firstly (and my my favorite part), stop maintaining our own, and secondly and arguably more important, will allow us to smoothly upgrade our users to the Node.js fetch when they are on a node 20+ as they will already be using it via the polyfill. Undici is the node fetch implementation, and now all our installGlobals() will be doing is giving you the latest version regardless of your node version, and I think that's pretty sweet.
Closes: #

feat: use undici as fetch polyfill

---

templates/vite-cloudflare/.eslintrc.cjs
templates/vite-express/.eslintrc.cjs
templates/vite/.eslintrc.cjs

chore: fix eslint ignore patterns for vite

---

integration/single-fetch-test.ts
packages/remix-server-runtime/server.ts

Follow up to https://github.com/remix-run/remix/pull/9104 to send back turbo-stream encoded responses when single fetch is enabled

Fix handleDataRequest redirects in single fetch

---

packages/remix-server-runtime/server.ts

chore: consolidate typescript versions
Closes: #

chore: use proxy for response stub cache to simplify call site use

---

.changeset/popular-adults-remain.md
integration/package.json
packages/remix-dev/package.json
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-server-runtime/single-fetch.ts
packages/remix-testing/package.json
pnpm-lock.yaml

Move `skipLoaders`/`loadRouteIds` logic to `dataStrategy` now that it's request specific so we can remove them from the router API: https://github.com/remix-run/react-router/pull/11384

Simplify implementation

---

.changeset/hot-suits-jam.md
packages/remix-dev/vite/styles.ts

👋 Hey
I was trying to start using Remix presets to add some dev-only routes we have in Hydrogen, such as `/graphiql`. It mostly works but when it requests the critical CSS, it fails because it only supports files that are within the `app` directory. Our route files come from `node_modules` using absolute paths.
This small change does the trick because `path.resolve` does not modify absolute paths 👍

Fix Vite critical CSS resolution for route files with absolute paths

---

.changeset/good-buses-divide.md
integration/error-data-request-test.ts
integration/helpers/create-fixture.ts
integration/helpers/vite.ts
integration/hmr-test.ts
integration/vite-basename-test.ts
package.json
packages/remix-architect/__tests__/setup.ts
packages/remix-express/__tests__/setup.ts
packages/remix-node/__tests__/setup.ts
packages/remix-node/globals.ts
packages/remix-node/package.json
packages/remix-node/rollup.config.js
packages/remix-react/__tests__/setup.ts
packages/remix-serve/cli.ts
packages/remix-server-runtime/__tests__/setup.ts
packages/remix-testing/jest.config.js
packages/remix-testing/jest.setup.js
pnpm-lock.yaml
templates/classic-remix-compiler/arc/server.ts

chore(remix-serve): default to native fetch for single-fetch
Since there are some quite major differences between our, and native fetch implementations we have opted to keep our polyfill around for existing apps until the next major to avoid introducing unexpected issues for users specifically around the garbage collection behavior of response bodies.
Due to reliance on a more spec compliant headers implementation for single fetch, single fetch opts you into native fetch.

chore(remix-node): put native fetch behind config option

---

contributors.yml
docs/discussion/server-vs-client.md
docs/file-conventions/remix-config.md

Fixed link to vite-config where it had been linked to in the docs as vite-configuration

Update vite-configuration link to vite-config where linked to in docs

---

.github/workflows/test-full.yml
.github/workflows/test-pr-ubuntu.yml
.github/workflows/test-pr-windows-macos.yml
integration/playwright.config.ts

This reverts https://github.com/remix-run/remix/pull/9000.
Since moving to pnpm, we've had issues with Playwright tests hanging in Node 20.5.2+. I was able to narrow it down to workspace package imports being the cause. With pnpm, our built code no longer resides in a `node_modules` directory but is linked to the `packages` directory instead which means that Playwright no longer treats it as external. If we mark the packages dir as external, the tests don't hang anymore.

Fix Playwright hanging in Node 20.5.2+

---

contributors.yml
docs/route/headers.md

The current example uses `users.userId.users.tsx` when it is previously defined and expected that the parent `users.tsx` will pass headers down to the nested/lead routes. This change clears up an otherwise rather confusing example. The changes should read very clearly now to anyone familiar with the headers control system in Remix.

Fix wrong file path in headers.md

---

contributors.yml
templates/cloudflare/package.json

The template `remix-run/remix/templates/cloudflare` has fallen major versions behind some packages. Moreover, it is quite far behind in terms of `wrangler` which has gone through a large amount of updates recently.
This PR aims to bring the package versions up to the their respective latest versions
Edit: As per review request, only Cloudflare related packages have been bumped.
```
@cloudflare/workers-types         ^4.20230518.0  →  ^4.20240405.0
miniflare                         ^3.20231030.4  →  ^3.20240404.0
wrangler                                ^3.24.0  →        ^3.48.0
```
Local testing by creating a brand new remix app using `npx create-remix@latest --template ~/personal/forks/remix/templates/cloudflare` (pointed at the local versions with changes)
Once the local test app has been …

template(cloudflare): Update remix cloudflare template to latest package versions

---

.changeset/tame-otters-clap.md
packages/remix-dev/vite/plugin.ts

Since `configFile` and `babelrc` options weren't disabled when running `babel.transformAsync`, we were inadvertently picking up Babel config files from consumers' projects when applying the dev-only `react-refresh` Babel transform.

Ignore Babel config for `react-refresh` transform

---

.changeset/nice-beds-sneeze.md
packages/remix-server-runtime/routeModules.ts
packages/remix-server-runtime/routes.ts
packages/remix-server-runtime/single-fetch.ts

Fix typings for response in LoaderFunctonArgs/ActionFunctionArgs

---

.changeset/young-eagles-grab.md
docs/guides/single-fetch.md
packages/remix-react/future/single-fetch.d.ts
packages/remix-react/index.tsx
packages/remix-react/rollup.config.js

Note: using `include` rather than `typeRoots`/`types` since those are designed for `@types` packages and `include` is lighter weight

opt-in type inference for single-fetch

---

.changeset/thirty-donuts-clean.md
packages/remix-dev/vite/plugin.ts

As noted by the changeset, this fixes an issue where consumers who had added Remix packages to Vite's `ssr.noExternal` option were being overridden by the Remix Vite plugin adding Remix packages to Vite's `ssr.external` option.
Our use of `ssr.noExternal` (fixing a Vite issue within the Remix repo) was incorrectly thought to be a no-op for consumers, so instead we now detect when we're in the Remix repo before applying the fix.

Only add Remix packages to `ssr.external` in Remix repo

---

docs/guides/single-fetch.md

This pull request updates the documentation for the [Single Fetch guide](https://remix.run/docs/en/main/guides/single-fetch).
A typo is fixed and a missing parenthesis is added.

docs(single-fetch): typo & missing parens around function

---

.changeset/five-planets-grin.md
packages/remix-dev/vite/plugin.ts

This fixes the issue raised in #9239.
This issue occurs when a server asset is present in the client build but isn't present in any of the client manifest's `assets` arrays. Unfortunately I wasn't able to work out _why_ this can happen, but we can still handle this case regardless.
The list of client assets was only used to determine whether to _move_ a server asset or _remove_ it. This means it's safe to expand the list of client assets to be the list of all files in the client build, regardless of whether they're considered assets or not. The server asset detection logic remains the same so we won't be moving additional files.

Fix `dest already exists` error during Vite build

---

CHANGELOG.md
docs/guides/single-fetch.md

Closes https://github.com/remix-run/remix/issues/9330

Change single fetch type override recommendation

---

scripts/utils.js

The nightly build is currently [failing](https://github.com/remix-run/remix/actions/runs/8919927675/job/24496985160#step:7:33) with 
```
[Error: ENOENT: no such file or directory, open '/home/runner/work/remix/remix/templates/deno/.vscode/resolve_npm_imports.json']
```
because the deno template was moved in #9077.
This PR updates the path in the `incrementRemixVersion` utility to solve that.

fix(ci): Update deno template path

---

contributors.yml
docs/file-conventions/routes.md

First of all, thank you for maintaining this project. I'm a fan of this.
There was a difference between the file path and the actual routing in the document `Route File Naming`.
This can be confusing for readers, so we've updated all routes to match file paths.

docs: made example in `Route File Nmaing` stricter

---

.changeset/rare-dodos-push.md
integration/single-fetch-test.ts
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/single-fetch.ts

Dont log single fetch thrown redirect response stubs via handleError

---

.changeset/nasty-vans-brake.md
docs/guides/single-fetch.md
integration/single-fetch-test.ts
packages/remix-react/server.tsx
packages/remix-react/single-fetch.tsx

Closes: #9359
I added a test case to `integration/single-fetch-test.ts`, and I patched `@remix-run/react` in our application with these changes and saw that it fixed our CSP violations.

Allow a nonce to be set on single fetch stream transfer inline scripts

---

.changeset/slimy-shrimps-roll.md
packages/remix-dev/vite/plugin.ts

This PR is aiming to address two things:
1) Support the move to vite-plugin-react-swc: https://github.com/remix-run/remix/pull/9092
2) Potentially unlock this fix in Hydrogen: https://github.com/Shopify/hydrogen/pull/2078
The `?client-route=1` virtual modules that wrap all client routes are only necessary for a build optimisation that removes unused exports from route files on the client. The only reason these virtual modules were used in development was to keep the dev and build code paths as similar as possible. However, since it's causing other issues, and it also necessitated _extra_ code in dev to special-case HMR for these files, we're opting to remove `?client-route=1` usage in dev entirely.

Clean redundant `?client-route=1` usage in dev

---

.changeset/fresh-pigs-leave.md
packages/remix-server-runtime/data.ts
packages/remix-server-runtime/routeModules.ts
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/single-fetch.ts

Minor follow ups to https://github.com/remix-run/remix/pull/9372

Remove response stub from LoaderFunctionArgs/ActionFunctionArgs

---

.changeset/fresh-pigs-leave.md
packages/remix-server-runtime/routeModules.ts

Partial revert of #9398 since it's too confusing to take this away for v2 (and explain to folks how to properly do resource routes) when it'll always be there in the future.

Add back optional response stub for v2

---

.github/workflows/release.yml

I noticed that CI wasn't commenting on issues after releases recently, and it looks like the `Find Package` job was failing due to a missing `npm->pnpm` update so it was looking for a `package-lock.json` file and erroring out: https://github.com/remix-run/remix/actions/runs/8818933926/job/24209000833
I also commented out the deployments and stacks tests since I don't think they've passed in quite some time.  Maybe after things simplify in the next version we can revisit that idea - would be great to have those running reliably again - even if on a subset of platforms: https://github.com/remix-run/remix/actions/runs/8162173613

Fix post-release workflows

---

contributors.yml
packages/remix/README.md

Inspired by https://twitter.com/ryanflorence/status/1790041089778373076.
[The `remix` package on npm](https://www.npmjs.com/package/remix) is the first thing that comes up when one searches "remix" (as the exact match), appears updated regularly, and has no indication that it's no longer used. To hopefully mitigate this, this PR adds an explanation to point people to places they probably intended to go to.
This confusion is probably quite bad: of the 9 public dependents (npm says there are 11 but only lists 9, so I'm assuming the other 2 are private): one (`remix-redis-session`) has ~4000 weekly downloads (it depends on 1.3), the others all have 2 or 1 digit weekly downloads. That leaves about 18000 new downloads stepping into the footgun, which is comparatively about 4x (`remix` divided …

docs: try to prevent "remix" package footgun

---

contributors.yml
docs/route/loader.md

Add missing `useRouteError` import in loader docs

---

templates/classic-remix-compiler/deno/server.ts

deno std http server is marked as deprecated, and `Deno.serve` is the preferred api to use. 
https://deno.land/std@0.221.0/http/server.ts
https://docs.deno.com/runtime/manual/runtime/http_server_apis

update deno to use built in http server

---

docs/guides/single-fetch.md

Expanded the Single Fetch example to include a an example of returning a `Promise` as well.
Let me know if you see any silly mistakes in my code

docs: add returned promise in single fetch example

---

integration/helpers/deno-template/app/root.tsx
integration/helpers/deno-template/app/routes/_index.tsx

Following [this update from Deno Lint](https://github.com/denoland/deno_lint/pull/1277), JSX files are now considered by the `no-unused-vars` deno lint rule.
I tried a few options:
- Adding `deno.json` 
- Adding a `tsconfig.json` (a bit redundant according to Deno docs)
- Removing those imports
All the solutions have some pros/cons, I've personally never used deno so I don't feel 100% confident implementing the first solution (My IDE was still complaining).
Feedback from Deno users are more than welcome 🙏 
I would not mind removing all those `import * as React from "react";` since we're using React ^18.
Another solution would be to at least [pin the Deno version](https://github.com/remix-run/remix/blob/ad7f1eabf1956d1ac1012de7cf18521e869742fd/.github/workflows/lint.yml#L46) in the Github …

chore: fix `lint:deno` script

---

templates/cloudflare-workers/README.md
templates/cloudflare-workers/app/routes/_index.tsx
templates/cloudflare/README.md
templates/cloudflare/app/routes/_index.tsx
templates/express/README.md
templates/express/app/routes/_index.tsx
templates/remix-javascript/README.md
templates/remix-javascript/app/routes/_index.jsx
templates/remix/README.md
templates/remix/app/routes/_index.tsx
templates/spa/README.md

Starting to update our templates just a bit. This is the first step:
- Remove unnecessary mention of Vite -- people trying out Remix for the first time don't need to know about the compiler, this made more sense
- Update links from old tutorials to the current ones

Update Template READMEs and links

---

contributors.yml
docs/guides/single-fetch.md

Some recommended docs changes.
Feel free to edit on top of if as you see fix 🙏

docs(guides/single-fetch): add some recommended steps

---

.changeset/shiny-bags-breathe.md
integration/vite-basename-test.ts
packages/remix-react/browser.tsx

Closes https://github.com/remix-run/remix/issues/9583

Fix initial hydration matching when using a basename

---

.changeset/neat-ghosts-thank.md
integration/action-test.ts
integration/single-fetch-test.ts
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/single-fetch.ts

Use a 202 to avoid any automatic caching we might get from a 200 since a "temporary" redirect should not be cached. 
This lets the user control cache behavior via `Cache-Control`.
Closes #9500

Update single fetch redirects to use a 202 status code on data requests

---

.changeset/heavy-ways-rule.md
integration/client-data-test.ts
packages/remix-react/links.ts

Dont prefetch server loader when client loader exists

---

.changeset/mighty-experts-agree.md
integration/root-route-test.ts
packages/remix-react/errorBoundaries.tsx

If you have a root `Layout` we will try to render that on the success _and_ error flows.  If the error flow _also_ throws during hydration (i.e., from a delayed resolved promise render) and we bubble to our default error boundary, then we can get into an infinite loop because we choose _not_ to render the surrounding `<html>` in the error boundary when a `Layout` exists.
Instead, if we are inside the default error boundary and the root route has both a `Layout` and an `ErrorBoundary` then we must have thrown trying to render the error via the `Layout` and we _should_ render the default `<html>` shell.  Otherwise we get into a react hydration loop because the DOM rejects when we try to add our default error boundary children (`h1`, `pre`) as children of `#document`.
Closes #9553

Avoid hydration loops when layout error renders also throw

---

.changeset/tall-news-trade.md
integration/fog-of-war-test.ts
packages/remix-react/fog-of-war.ts
packages/remix-server-runtime/server.ts

* Using the abort controller causes log noise in `StrictMode`, and there's no real benefit to aborting since the response is still valid so might as well patch those routes to avoid subsequent requests if we navigate back to those routes.
* Switch to a `POST` request if the URL goes beyond 4196 characters (a fairly conservative limit) to avoid running into URL or Request size limits
* Only GET requests get the built-in `Cache-Control` response header

Remove AbortController and respect URL length limits

---

.changeset/shiny-dolphins-mate.md
integration/client-data-test.ts
integration/fog-of-war-test.ts
integration/package.json
integration/prefetch-test.ts
packages/remix-dev/package.json
packages/remix-react/__tests__/exports-test.tsx
packages/remix-react/components.tsx
packages/remix-react/fog-of-war.ts
packages/remix-react/index.tsx
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
pnpm-lock.yaml

* We forgot to enable Fog of War discovery for `<Form>` components in the first pass
* Add an E2E test to ensure that we can prefetch after FOW discovery - requires an RR prerelease before CI will pass

Support Fog of War form discovery and fix link prefetching

---

.changeset/cyan-dingos-report.md
packages/remix-server-runtime/__tests__/server-test.ts
packages/remix-server-runtime/server.ts

Fix native fetch immutable headers issue

---

.changeset/fluffy-ways-bathe.md
packages/remix-react/single-fetch.tsx

Single Fetch: proxy request signal through on interrupted loader calls

---

.changeset/log-module-error.md
packages/remix-react/routeModules.ts

Log route module errors prior to reloading the page

---

.changeset/quiet-pugs-allow.md
docs/guides/single-fetch.md
integration/package.json
packages/remix-dev/package.json
packages/remix-react/browser.tsx
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
pnpm-lock.yaml

Remix Sibling PR to https://github.com/remix-run/react-router/pull/11769
This will fail CI until we get an RR experimental or prerelease out with the name change

Adopt RR stabilized v7_skipActionErrorRevalidation flag

---

contributors.yml
docs/hooks/use-action-data.md

The current documentation for the `useActionData` hook might unintentionally imply that it can be used to access data from any route action. However, the hook is limited to accessing data associated with the current route action where it's called.
This PR clarifies this limitation in the documentation to prevent confusion.
See #9717 for more information.

Docs: Clarify `useActionData` Hook Scope

---

.changeset/happy-dots-sleep.md
docs/components/link.md
docs/guides/lazy-route-discovery.md
docs/start/future-flags.md
integration/fog-of-war-test.ts
integration/prefetch-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts
packages/remix-react/entry.ts
packages/remix-react/fog-of-war.ts
packages/remix-server-runtime/entry.ts
packages/remix-testing/create-remix-stub.tsx

The "fog of war" phrasing is a nice metaphor for this and works well in blog posts but it's pretty confusing to see as a future flag without the proper context or video game familiarity.  We're going to rename the flag for clarity and we'll still use the "fog of war" metaphor in docs and blog posts etc.

Rename future flag from fogOfWar to lazyRouteDiscovery

---

.changeset/curvy-vans-remember.md
integration/package.json
integration/redirects-test.ts
integration/single-fetch-test.ts
packages/remix-cloudflare/index.ts
packages/remix-deno/index.ts
packages/remix-dev/package.json
packages/remix-node/index.ts
packages/remix-react/index.tsx
packages/remix-react/package.json
packages/remix-react/routes.tsx
packages/remix-react/single-fetch.tsx
packages/remix-server-runtime/index.ts
packages/remix-server-runtime/package.json
packages/remix-server-runtime/responses.ts
packages/remix-server-runtime/single-fetch.ts
packages/remix-testing/package.json
pnpm-lock.yaml

Sibling React Router PR: https://github.com/remix-run/react-router/pull/11811

Add support for replace() redirects

---

contributors.yml
docs/discussion/pending-ui.md

I believe the starred icons has been swapped in the example

fix: update pending-ui.md starred icons

---

.changeset/tender-elephants-kneel.md
packages/remix-react/__tests__/components-test.tsx
packages/remix-react/browser.tsx
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/serverHandoff.ts

The original issue this check was fixing was https://github.com/remix-run/remix/issues/1757 - see about reproducing that in today's landscape - maybe the original infinite loop is no longer an issue? 
**Update:** I'm having trouble reproducing the original issue so I'm inclined to remove this check from RR v7 entirely.  But for now, switching to matches should make it less error-prone.
Closes https://github.com/remix-run/remix/issues/9692, https://github.com/remix-run/remix/issues/8872, https://github.com/remix-run/remix/issues/7529

Change hydration check from URL to matches

---

.changeset/large-donkeys-remember.md
packages/remix-react/single-fetch.tsx

Noticed this doing some testing on RR v7 - fixing it here and then will copy the fix over to RR v7

Trim trailing slashes from single fetch data URLs

---

.changeset/add-unstable-data.md
.changeset/polite-pumas-visit.md
.changeset/remove-response-stub.md
docs/guides/single-fetch.md
docs/utils/data.md
integration/helpers/vite.ts
integration/package.json
integration/single-fetch-test.ts
packages/remix-cloudflare/index.ts
packages/remix-deno/index.ts
packages/remix-dev/package.json
packages/remix-node/index.ts
packages/remix-react/__tests__/exports-test.tsx
packages/remix-react/index.tsx
packages/remix-react/package.json
packages/remix-react/single-fetch.tsx
packages/remix-server-runtime/data.ts
packages/remix-server-runtime/index.ts
packages/remix-server-runtime/package.json
packages/remix-server-runtime/routeModules.ts
packages/remix-server-runtime/routes.ts
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/single-fetch.ts
packages/remix-testing/package.json
pnpm-lock.yaml

Sibling React Router PR: https://github.com/remix-run/react-router/pull/11836
TODO:
See below for details but the **tl;dr;** here is that for Single Fetch (unstable) we're removing `ResponseStub` and bringing back `headers()` which will be the place to merge headers for both document and data requests when single fetch is enabled.
**Background**
* The original implementation was based on an assumption that an eventual middleware implementation would _require_ something like `ResponseStub` so users could mutate status/headers in middleware before/after handlers and during handlers
* We wanted to align how headers got merged between document and data requests
* So we made document requests also use `ResponseStub` and removed the usage of `headers` in single fetch
* The realization/alignment …

Remove single fetch response stub, add headers

---

templates/cloudflare/README.md

Two months ago, cloudflare [announced](https://blog.cloudflare.com/pages-workers-integrations-monorepos-nextjs-wrangler#configure-pages-projects-with-wranglertoml) that:
> you can now configure Pages projects using wrangler.toml — the same configuration file format that is already used for configuring Workers.
Considering that change, it seems like this warning is defunct and will cause unnecessary complexity for users when trying to set up a remix cloudflare pages application.

templates(cloudflare): remove `wrangler.toml` bindings warning

---

.changeset/silver-laws-invite.md
packages/remix-react/future/single-fetch.d.ts

It was mentioned in https://github.com/remix-run/remix/issues/9793#issuecomment-2251424789 that the `useRouteLoaderData` Single Fetch override was losing the `| undefined`

Single Fetch: Add undefined to the useRouteLoaderData type override

---

contributors.yml
docs/guides/data-loading.md

The suggested controlled SearchCheckbox component didn't work for me - when checking a checkbox it would flick to checked and then revert to unchecked.
I suspect this was the useEffect running unexpectedly, maybe because of the arrays and objects in the dependency array.
React docs: [Removing unnecessary object dependencies](https://github.com/remix-run/remix/blob/main/CONTRIBUTING.md).
This updates the required dependencies to a single string variable and seems to work better.
My first PR here, let me know what I've missed! 👍 🙏

docs(data-loading): fix SearchCheckbox snippet

---

.changeset/rich-teachers-warn.md
integration/single-fetch-test.ts
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/single-fetch.ts

Closes https://github.com/remix-run/remix/issues/9586

Fix single fetch redirects whena basename is present

---

.changeset/sweet-roses-shake.md
packages/remix-react/package.json
packages/remix-server-runtime/package.json
pnpm-lock.yaml

fix: stabilize object key order for unstable_singleFetch
fix: unstable_singleFetch can now have payloads as large as you have memory
Closes: https://github.com/remix-run/remix/issues/9421

fix: update turbo-stream to v2.3.0

---

.changeset/dirty-adults-sparkle.md
integration/fog-of-war-test.ts
packages/remix-react/fog-of-war.ts

Closes https://github.com/remix-run/remix/discussions/9885

Sort lazy route discovery manifest request params

---

.changeset/khaki-ads-buy.md
packages/remix-react/browser.tsx
packages/remix-server-runtime/server.ts
packages/remix-server-runtime/serverHandoff.ts

**tl;dr;** this was only needed in React 17 and can be dropped now that Remix v2 requires React 18.  This will get rid of some false-positive scenarios we have today.
See changeset and https://github.com/remix-run/remix/issues/1757#issuecomment-2294186651 for details.
Closes #8872, #7529

Remove hydration URL check

---

.changeset/tiny-crabs-deliver.md
packages/remix-dev/vite/plugin.ts

Fixes #9498.
This fix was inspired by #9800, but I decided to make this more error-proof by inspecting files on disk rather than inspecting the Vite manifest files/assets and potentially getting it wrong (as we have already).

Fix `dest already exists` build errors

---

integration/blocking-test.ts
integration/helpers/create-fixture.ts
integration/helpers/deno-template/remix.config.js
integration/package.json
packages/remix-dev/package.json
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
pnpm-lock.yaml

Add a failing integration test for https://github.com/remix-run/react-router/issues/11613 since it relies on specific behavior of browser `history.go` calls that doesn't seem to be accurately implemented in JSDOM.
This should fail initially and be fixed once we point to an experimental RR release with the fix from https://github.com/remix-run/react-router/pull/11930

Add failing test for syncronous blocker.proceed calls

---

contributors.yml
docs/utils/sessions.md

Closes: #9918 
Fixed a typo in createSessionStorage
---
Orignal:

[docs] Fix Typo in createSessionStorage

---

.changeset/hot-dogs-applaud.md
package.json
packages/remix-dev/vite/plugin.ts
pnpm-lock.yaml

Fixes #8917 #9798
Might fix #8803 #8876
See changeset for description

Optimize dependencies found through route module graphs

---

packages/remix-dev/vite/plugin.ts

Automatically optimize dependencies of the client entry

---

contributors.yml
docs/start/tutorial.md

It was just a bit of a typo: replace "clientside" with "client side".

docs: replace 'clientside' with 'client side'

---

.changeset/bright-rabbits-attend.md
integration/helpers/create-fixture.ts
integration/single-fetch-test.ts
packages/remix-server-runtime/server.ts

Fix issue with 304 response sin single fetch

---

.changeset/moody-cups-give.md
.changeset/neat-mayflies-design.md
packages/remix-server-runtime/single-fetch.ts

RELEASE: fix json and defer when using single fetch types

---

.changeset/gorgeous-toys-flash.md
packages/remix-server-runtime/single-fetch.ts

RELEASE: backcompat for generic cast in single-fetch types

---

.changeset/slow-socks-juggle.md
integration/single-fetch-test.ts
packages/remix-server-runtime/server.ts

Same fix as https://github.com/remix-run/remix/pull/9941 (for https://github.com/remix-run/remix/issues/9930) but for document requests

Support 304 responses on document requests

---

.changeset/light-moons-reply.md
packages/remix-server-runtime/serialize.ts

We had _two_ checks to ensure that the generic type was a function. For back compat, we need to allow non-function types, but #9948 only removed one of the checks. This removes the other check.
Type tests didn't catch this as we only check single-fetch types assuming the outer checks that rely on interface merging pass. We can't test the whole `SerializeFrom` type with interface merging in our repo as that will override types in the entire repo to be single-fetch aware.

RELEASE: fix single fetch generic as cast (again)

---

contributors.yml
docs/file-conventions/root.md

This PR removes the repeated word `can't`.

docs(file-conventions/root): fix wording

---

.changeset/hungry-experts-suffer.md
packages/remix-dev/vite/cloudflare-proxy-plugin.ts
packages/remix-dev/vite/node-adapter.ts
packages/remix-dev/vite/plugin.ts

Found this wasn't working right while testing https://github.com/remix-run/remix/pull/9975.  Aligned with how we do it in the express adapter.
Closes https://github.com/remix-run/remix/issues/9438

Proxy request.signal through in vite dev

---

docs/guides/single-fetch.md

There are still a couple of references to the old way of configuring type inference for single fetch in the docs; this PR updates them with the new way of doing things.

docs(guides/single-fetch): update references

---

.changeset/many-donuts-tie.md
packages/remix-server-runtime/single-fetch.ts

Supercedes #9834
Fixes #9826 , #9998

fix single-fetch types for functions that return unions

---

contributors.yml
docs/guides/envvars.md

[Current docs](https://remix.run/docs/en/main/guides/envvars#local-development) say that env variables in Cloudflare environment are accessible through `context.env`, which was true for the classic compiler, but doesn't work with Vite.
Now as Vite is the default for Remix, env variables in Cloudflare are accessible through `context.cloudflare.env`. This PR reflects this change.

Fix docs for environment variables in Cloudflare

---

contributors.yml
docs/start/tutorial.md

placekitten.com seems to be down and searching seems to suggest it has been for a while (or is frequently?)
I updated the tutorial link to use https://placecats.com/ instead for the profile images.

docs(start/tutorial): replace `placekitten` service with `placecats`

---

contributors.yml
docs/guides/single-fetch.md

As of 2.12, the `Future` type thing is in `@remix-run/server-runtime`, not `@remix-run/node`. I was very confused about why it wasn't working.
https://github.com/remix-run/remix/blob/6f83cf3d11436f6306a5d5f2468ce2cc4fe8e3ea/CHANGELOG.md#L256-L284

docs(guides/single-fetch): fix type override

---

.changeset/spotty-papayas-remember.md
integration/client-data-test.ts
packages/remix-react/routes.tsx

Stacked on https://github.com/remix-run/remix/pull/9980
Remix half of https://github.com/remix-run/react-router/pull/12070.  Originally reported in discord via https://github.com/rossipedia/hydrate-error-shenanigans

Fix bug with clientLoader.hydrate when hydrating with bubbled errors

---

contributors.yml
docs/guides/single-fetch.md

The Single Fetch docs are mentioning `unstable_singleFetch` in the text where they should be saying `v3_singleFetch` by now (after `2.13.0`)

docs(guides/single-fetch): use stabilized flag

---

docs/start/future-flags.md

Stacked on https://github.com/remix-run/remix/pull/10107.

routes.ts Add docs to future flags guide

---

.changeset/twenty-waves-cheer.md
integration/single-fetch-test.ts
packages/remix-react/components.tsx
packages/remix-react/links.ts
packages/remix-react/routes.tsx

Fix defaultShouldRevalidate when using single fetch

---

.changeset/grumpy-llamas-leave.md
integration/single-fetch-test.ts
packages/remix-server-runtime/deprecations.ts

Resource routes can no longer just return null, call this out in the deprecation notice.
It just took me a minute to realise it was the null which was triggering the message.

Update single fetch deprecation notice to also include info about null

---

docs/start/future-flags.md
integration/helpers/vite.ts
integration/vite-fs-routes-test.ts
integration/vite-route-config-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts

Stacked on https://github.com/remix-run/remix/pull/10107.
This ensures that projects with an existing `app/routes.ts` file aren't broken. This also brings behaviour slightly closer to React Router v7 since a missing `routes.ts` file is now an error when the future flag is enabled.

routes.ts: Add `v3_routeConfig` future flag

---

templates/cloudflare-workers/env.d.ts
templates/cloudflare-workers/load-context.ts
templates/cloudflare-workers/package.json
templates/cloudflare-workers/server.ts
templates/cloudflare-workers/vite.config.ts
templates/cloudflare-workers/wrangler.toml

This PR updates the cloudflare-workers template to use the Static Assets feature [announced today](https://blog.cloudflare.com/builder-day-2024-announcements/#static-asset-hosting).
> Note: Static assets is currently in open beta
You can learn more about Static Assets in the [documentation](https://developers.cloudflare.com/workers/static-assets/?cf_history_state=%7B%22guid%22%3A%22C255D9FF78CD46CDA4F76812EA68C350%22%2C%22historyId%22%3A14%2C%22targetId%22%3A%22167AF5232FF9C5279F7F203D0E95B587%22%7D).
Closes: #
To test, please run `create-remix` with the template on my fork 
```sh
npx create-remix@latest --template edmundhung/remix/templates/cloudflare-workers
```
Then deploy it with wrangler by running:
```sh
npm run deploy
```
Woohoo! Your Remix app is now running on …

templates(cloudflare-workers): use static assets

---

contributors.yml
docs/start/tutorial.md

While running through the [tutorial](https://remix.run/docs/en/main/start/tutorial), I noticed the _Delete_ button didn't work unless I renamed `contacts.$contactId.destroy.tsx` `contacts.$contactId_.destroy.tsx`, similar to the _edit_ action.

docs(start/tutorial): fix typo

---

contributors.yml
docs/hooks/use-view-transition-state.md

href is not defined, you should be to

docs(hooks/use-view-transition-state): fix typo

---

.changeset/popular-humans-attend.md
docs/start/future-flags.md
integration/helpers/vite.ts
integration/vite-fs-routes-test.ts
integration/vite-route-config-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts

Until React Router v7 is released and we know the API is stable, we're opting to mark `routes.ts` support as unstable.

fix(remix-dev): mark `routes.ts` support unstable

---

contributors.yml
templates/cloudflare-workers/tailwind.config.ts
templates/cloudflare/tailwind.config.ts
templates/express/tailwind.config.ts
templates/remix-javascript/tailwind.config.js
templates/remix/tailwind.config.ts
templates/spa/tailwind.config.ts

Removed unnecessary quotes around font names in the `fontFamily.sans` array of the Tailwind CSS configuration file for improved readability and consistency.
Closes: #
This is the first time I am contributing to remix. I would appreciate it if you could let me know if I need to add any tests.

templates: fix `fontFamily` in `tailwind.config.ts`

---

.changeset/sour-years-cover.md
docs/start/future-flags.md
integration/vite-fs-routes-test.ts
integration/vite-route-config-test.ts
packages/remix-dev/config.ts
packages/remix-dev/config/routes.ts

Replay of https://github.com/remix-run/react-router/pull/12305, aligning with the updated React Router v7 API.

Make routes the default export in `routes.ts`

---

.changeset/sour-years-cover.md
docs/start/future-flags.md
integration/helpers/vite.ts
integration/vite-fs-routes-test.ts
integration/vite-route-config-test.ts
packages/remix-dev/__tests__/readConfig-test.ts
packages/remix-dev/config.ts

To coincide with the release of React Router v7, this stabilizes the `routes.ts` future flag.

Stabilize `future.v3_routeConfig`

---

contributors.yml
docs/start/future-flags.md

Hey Folks 👋
Just a tiny update in the docs. I came to this while migrating my Remix app from 2.14 to 2.15 so I can go safely to react router 7.

docs(start/future-flags): fix `flatRoutes` example

---

.changeset/unlucky-melons-promise.md
packages/remix-react/single-fetch.tsx

Align the logic with [non-Single Fetch](https://github.com/remix-run/remix/blob/main/packages/remix-react/routes.tsx#L588) to always throw redirects from the client loader so short circuit any further processing and avoid type inference mismatches
Closes #10208

Throw single fetch redirects fetched from the server

---

.changeset/curly-comics-bake.md
packages/remix-dev/config.ts
packages/remix-react/package.json
packages/remix-testing/package.json
pnpm-lock.yaml

Remix version of https://github.com/remix-run/react-router/pull/12441
Also bumps to the latest RR 6.28.1 stable release

Allow future flag warning supression with explicit false setting

---

.changeset/giant-dolls-wonder.md
.gitignore
integration/package.json
integration/single-fetch-test.ts
package.json
packages/remix-react/single-fetch.tsx
packages/remix-server-runtime/server.ts
pnpm-lock.yaml

Remix v2 version of https://github.com/remix-run/react-router/pull/12760 to ease the upgrade path to `v3_singleFetch -> RR v7`
Closes #10328

Properly handle empty responses in single fetch requests

---

docs/route/headers.md

This adds the `$` omitted from the file names.

docs(route/headers): fix typo

---

.changeset/dull-files-warn.md
integration/fog-of-war-test.ts
integration/package.json
packages/remix-dev/package.json
packages/remix-react/fog-of-war.ts
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-testing/package.json
pnpm-lock.yaml

Sibling RR PR: https://github.com/remix-run/react-router/pull/12900
Closes #10397

Properly handle interrupted __manifest requests in lazy route discovery

---

.changeset/clean-kangaroos-juggle.md
integration/vite-spa-mode-test.ts
packages/remix-react/browser.tsx

Closes https://github.com/remix-run/react-router/issues/12740 for Remix v2 to ease single fetch flag  adoption

Don't apply single fetch revalidation de-optimization in SPA Mode

---

contributors.yml
docs/guides/migrating-react-router-app.md

This PR updates the hydration mismatch reference in the Remix documentation, replacing the outdated link to the **legacy React docs** (`legacy.reactjs.org`) with the correct **React 18+ documentation** (`react.dev/reference/react-dom/client/hydrateRoot`).
- The old link points to deprecated React docs.
- React 18+ introduced `hydrateRoot`, which is the recommended approach for hydration.
- The new link provides up-to-date guidance on handling hydration in modern React applications.
- **Updated link:** `legacy.reactjs.org/docs/react-dom.html#hydrate` → `react.dev/reference/react-dom/client/hydrateRoot`
This ensures Remix users get the most accurate and relevant information when handling hydration mismatches. 🚀

docs: update hydration mismatch link to React 18+ documentation

---

.changeset/moody-onions-hunt.md
integration/package.json
packages/remix-dev/package.json
packages/remix-react/fog-of-war.ts
packages/remix-react/package.json
packages/remix-server-runtime/package.json
packages/remix-server-runtime/server.ts
packages/remix-testing/package.json
pnpm-lock.yaml

Remix v2 version of https://github.com/remix-run/react-router/pull/13061

Detect lazy route discovery manifest version mismatches and trigger reloads

---

packages/remix-fs-routes/rollup.config.js
packages/remix-route-config/rollup.config.js
packages/remix-routes-option-adapter/rollup.config.js

Since `package.json` files aren't being copied to the `build` directory for these new packages, publishing of experimental and nightly releases are currently failing. I've added the missing targets that are present in other packages. This was missed because these packages were back-ported from React Router where the build setup is different and a singular `build` directory isn't present.

Fix experimental and nightly releases

---

.changeset/slow-jars-yell.md
packages/remix-dev/compiler/js/plugins/hmr.ts
packages/remix-react/browser.tsx

If `@remix-run/react` is not marked as external, Vite's import analysis trips up on our call to `import.meta.hot.accept` which is only valid for the classic compiler. This PR does a couple of things to address this:
- Replaces `import.meta.hot.accept` with `import.meta.hot["accept"]` so Vite's static analysis doesn't pick it up.
- Adds a new `__remixCompiler` flag to our custom `import.meta.hot` implementation in the classic compiler. This then allows us to ensure that this custom HMR logic isn't executed when using Vite.

Fix Vite import analysis of `@remix-run/react`

---

.changeset/eleven-oranges-lie.md
integration/fog-of-war-test.ts
packages/remix-server-runtime/server.ts

Backport of https://github.com/remix-run/react-router/pull/13203 for Remix v2

Ensure ancestor pathless/index routes are loaded via manifest requests

---

contributors.yml
packages/remix-server-runtime/responses.ts

- [ x] Docs
I don't think this is the best way to write it, but it was difficult for me to find the equivalent of `json`, and I'd already opted into single fetch so needed to remove `json` to get the turbostream deserialization (keep `Date` typing). I think we should add info about `data` to the deprecation notice.
Similar issue: https://github.com/remix-run/remix/discussions/10233

add info about "data" method to json deprecation annotation

---

.changeset/young-avocados-ring.md
packages/remix-node/package.json
packages/remix-server-runtime/__tests__/server-test.ts
pnpm-lock.yaml

Replaces https://github.com/remix-run/remix/pull/10428
See https://github.com/nodejs/undici/releases/tag/v6.21.1

chore: bump `undici`

---

.changeset/tall-mirrors-glow.md
packages/remix-react/single-fetch.tsx

Backport the same change from https://github.com/remix-run/react-router/pull/11522
Closes https://github.com/remix-run/remix/issues/10474

Fix window error in PrefetchPageLinks during SSR in Single Fetch

---

contributors.yml
docs/start/tutorial.md

This is a simple docs change for the tutorial file.
`json` function is deprecated in favor of opting into Single Fetch via `future.v3_singleFetch` and returning raw objects.
This PR attempts to remove this deprecated function from the tutorial file.

docs(tutorial): remove `json` references

---

docs/hooks/use-revalidator.md

The original example looks like a GPT solution, the interval was never accounted for and the useEffect would just keep running immediately as soon as the revalidation completes
Closes: #

docs(hooks/use-revalidator): update code example

---

contributors.yml
docs/start/quickstart.md

Current versions of vite warn that esmodule support is required for future versions. Moving this step earlier will avoid confusion.
Closes: #

docs(start/quickstart): add future Vite compatibility

---

contributors.yml
docs/hooks/use-fetcher.md

Adds additional doc to clarify how to use `load` on index routes. It was a bummer to find [this excellent explanation](https://github.com/remix-run/remix/discussions/3494#discussioncomment-2966946) of our problem buried in a discussion rather than in the docs themselves.

docs(hooks/use-fetcher): add notice about index routes in `load` section

---

contributors.yml
templates/remix/README.md

Replaced incorrect `shellscript` code block with `sh` in README for proper syntax highlighting.

templates(remix): fix syntax highlighting in `README`

---

packages/route-pattern/src/lib/href.test.ts
packages/route-pattern/src/lib/params.test.ts
packages/route-pattern/src/lib/split.test.ts
packages/route-pattern/src/lib/variant.test.ts
packages/route-pattern/src/lib/variant.ts
packages/route-pattern/src/type-utils.d.ts

move out of `src/lib/` and remove unused `Pretty` type

route-pattern: type testing utilities

---

.github/workflows/publish-v2.yaml

This is a copy of the [`publish.yaml`](https://github.com/remix-run/remix/blob/main/.github/workflows/publish.yaml) workflow but instead of ignoring `remix@x.y.z` tags it will only kick off for those tags, and thus will only be triggered for releases from the v2 branch.
Sibling PR to update the v2 branch to follow the same github release flow where we tag locally and push to github for publishing from CI: https://github.com/remix-run/remix/pull/10748

Add github workflow for v2 publishes
