remix-run/remix

- contributors.yml
- packages/create-remix/templates/netlify/README.md
- packages/create-remix/templates/netlify/netlify.toml
- packages/create-remix/templates/netlify/package.json
Hello!
We've [updated the Netlify CLI](https://github.com/netlify/cli/pull/3662) to make the DX better for Remix, removing the need to run two commands. This PR updates the template to add the new instructions and configuration.
We will soon be adding auto-detection for Remix too, which will remove the need for most of the configuration too. I will do another PR when that is ready.
Keep up the great work!
> chore(create-remix): simplify Netlify template

- packages/remix-server-runtime/responses.ts
- packages/remix-server-runtime/server.ts
fix: pass full request to handleDataRequest, not stripped
> fix: null for body to conform to standards

- docs/api/remix.md
- docs/tutorials/blog.md
As asked by @kentcdodds in https://github.com/remix-run/remix/pull/536#issuecomment-981809059
> fix(docs): fix line highlights

- contributors.yml
- docs/api/remix.md
just fix the doc, change function to async
> fix(docs): async function

- contributors.yml
- docs/tutorials/jokes.md
The starter project structure has been updated so that it no longer includes `utils.server.tsx` and `remix.css` so I've updated the tutorial to remove those files.
> chore(docs): Update Jokes tutorial to use the latest project structure

- examples/basic/app/routes/demos/params.tsx
- examples/basic/app/routes/demos/params/$id.tsx
- examples/basic/app/routes/demos/params/index.tsx
- examples/blog-tutorial/app/root.tsx
- examples/blog-tutorial/app/routes/admin.tsx
- examples/blog-tutorial/app/routes/demos/actions.tsx
- examples/blog-tutorial/app/routes/demos/params.tsx
- examples/blog-tutorial/app/routes/demos/params/$id.tsx
- examples/blog-tutorial/app/routes/demos/params/index.tsx
- examples/blog-tutorial/app/routes/posts/$slug.tsx
- examples/blog-tutorial/app/routes/posts/index.tsx
- fixtures/gists-app/app/routes/index.jsx
- fixtures/gists-app/app/routes/nested-forms/nested/index.tsx
- fixtures/gists-app/app/routes/resources/settings.tsx
- packages/create-remix/templates/_shared_js/app/routes/demos/actions.jsx
- packages/create-remix/templates/_shared_js/app/routes/demos/params.jsx
- packages/create-remix/templates/_shared_js/app/routes/demos/params/$id.jsx
- packages/create-remix/templates/_shared_js/app/routes/demos/params/index.jsx
- packages/create-remix/templates/_shared_ts/app/routes/demos/actions.tsx
- packages/create-remix/templates/_shared_ts/app/routes/demos/params.tsx
- packages/create-remix/templates/_shared_ts/app/routes/demos/params/$id.tsx
- packages/create-remix/templates/_shared_ts/app/routes/demos/params/index.tsx
- packages/remix-dev/config/routesConvention.ts
- packages/remix-node/fetch.ts
> chore: fix ESLint errors & warnings

- contributors.yml
- docs/tutorials/jokes.md
> Prisma fix

- docs/api/remix.md
- packages/remix-architect/__tests__/server-test.ts
- packages/remix-express/__tests__/server-test.ts
- packages/remix-netlify/__tests__/server-test.ts
- packages/remix-vercel/__tests__/server-test.ts
Building further on @jacob-ebey's work in #743
> fix: use `null` body instead of empty string

- .github/workflows/format.yml
example repo: https://github.com/mcansh/test-repo
> chore: add format GitHub action

- docs/other-api/serve.md
[reported](https://canary.discord.com/channels/770287896669978684/771068344320786452/912752477718331442) [on discord](https://canary.discord.com/channels/770287896669978684/771068344320786452/912753007651876937)
> docs(other-api/serve): update link to adapter

- contributors.yml
- docs/guides/data-writes.md
Just a small tweak to make copying/pasting the example work.
> Add `async` to action function example

- docs/api/conventions.md
This started as fixing one link, and then I found several more. I've committed related bits separately to hopefully make review easier, but if you prefer to squash these all to a general "fix links" go ahead. 🙂
> docs: Fix some broken links

- contributors.yml
- docs/tutorials/blog.md
Hello,
first time contributor here! 👋 
While I was going through the [Developer Blog tutorial](https://remix.run/docs/en/v1/tutorials/blog) I noticed some smaller things that could be updated.
It's mostly around the code examples and changed lines that weren't highlighted yet.
While I was at it I also took liberty in updating some copy in a few sentences. Not sure what the procedure around that is yet, but please let me know if you'd like it removed. I'm not a native speaker myself, so I'm happy for any feedback around that.
I'll leave some explanations in this PR myself to give context about the changes.
One question, though: Is there a way to build the docs locally? [All I could find](https://github.com/remix-run/remix/blob/a7712f27002cbedbdf145787216b9fc2f04fd186/.github/workflows/websi …
> Docs - Some fixes in blog tutorial

- contributors.yml
- docs/guides/envvars.md
> Fix Grammatical Error In Docs

- contributors.yml
- packages/remix-cloudflare-workers/sessions/cloudflareKVSessionStorage.ts
Fixes #414 and #839.
Description of fix here: https://github.com/remix-run/remix/issues/839#issuecomment-986295640.
> Use seconds in KV session storage expiration

- docs/api/remix.md
- fixtures/gists-app/app/routes/__layout.tsx
- fixtures/gists-app/app/routes/__layout/with-layout.tsx
- fixtures/gists-app/tests/layout-routes-test.ts
- packages/remix-react/components.tsx
- packages/remix-react/index.tsx
- packages/remix-react/magicExports/client.ts
closes [REM-576](https://linear.app/remix-run/issue/REM-576)
> feat: Add <Outlet context> prop

- .github/workflows/test.yml
- fixtures/gists-app/tests/actions-test.ts
As @mcansh noticed in https://github.com/remix-run/remix/pull/787#issuecomment-989148724
> chore: run tests on PRs

- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/compiler.ts
- packages/remix-dev/config.ts
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix/package.json
- rollup.config.js
chore: updated package.json from "browser" to "module" field
> feat: allow ESM output of server builds

- fixtures/gists-app/app/routes/.blargh
- packages/remix-dev/config/routesConvention.ts
Resolves https://github.com/remix-run/remix/issues/391, #811, #116
> fix(dev): Ignore dotfiles in routes directory

- contributors.yml
- docs/api/remix.md
Also added `Form` import to make copy & paste easier
> docs: fix api/remix.md extra semicolon

- contributors.yml
- docs/tutorials/jokes.md
> Fixed a typo

- contributors.yml
- docs/guides/styling.md
> Fix (another) typo

- docs/api/remix.md
- docs/guides/disabling-javascript.md
To make @kentcdodds happy
https://kentcdodds.com/blog/use-ternaries-rather-than-and-and-in-jsx
---
Same as #536
> refactor: use ternaries rather than && in JSX

- contributors.yml
- docs/other-api/react-router.md
add missing word to fix sentence fragment
> chore(docs): fix sentence fragment

- .github/workflows/format.yml
- .husky/pre-commit
- package.json
- yarn.lock
> chore: remove husky and lint staged, rely on github action

- package.json
- packages/create-remix/templates/cloudflare-pages/README.md
- packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
- packages/create-remix/templates/cloudflare-pages/gitignore
- packages/create-remix/templates/cloudflare-pages/package.json
- packages/create-remix/templates/cloudflare-pages/remix.config.js
- packages/create-remix/templates/cloudflare-pages_ts/remix.env.d.ts
- packages/create-remix/templates/cloudflare-workers/package.json
- packages/remix-cloudflare-pages/README.md
- packages/remix-cloudflare-pages/cookieSigning.ts
- packages/remix-cloudflare-pages/globals.ts
- packages/remix-cloudflare-pages/index.ts
- packages/remix-cloudflare-pages/magicExports/platform.ts
- packages/remix-cloudflare-pages/package.json
- packages/remix-cloudflare-pages/responses.ts
- packages/remix-cloudflare-pages/sessions/cloudflareKVSessionStorage.ts
- packages/remix-cloudflare-pages/tsconfig.json
- packages/remix-cloudflare-pages/worker.ts
- packages/remix-dev/setup.ts
- rollup.config.js
- tsconfig.json
- yarn.lock
feat: added esm build for cloudflare-pages package
> wip: initial cloudflare-pages package

- packages/ADDING_A_PACKAGE.md
- packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
- packages/create-remix/templates/cloudflare-pages/package.json
- packages/create-remix/templates/cloudflare-pages/remix.config.js
- packages/create-remix/templates/cloudflare-workers/remix.config.js
- packages/remix-cloudflare-pages/package.json
- packages/remix-cloudflare-pages/worker.ts
- yarn.lock
fix: add missing content types (known CF issue)
chore: update template; missing dep and config
doc: added a little MD file to document adding a package
> fix: update pages handler to use middleware pattern for asset handling

- packages/remix-dev/compiler.ts
> fix(dev/compiler): update publicPath for server build

- contributors.yml
- docs/tutorials/jokes.md
"Update the app/routes/jokes.tsx route module to load jokes from our database and render a list of links to the jokes."
`Loader Function` was added in the first line, but it was not highlighted, so I fixed it.
> fix: code highlight

- contributors.yml
- docs/guides/styling.md
Read more: [https://tailwindcss.com/docs/optimizing-for-production](https://tailwindcss.com/docs/optimizing-for-production#:~:text=If%20you%E2%80%99re%20using%20Tailwind%20CLI%2C%20you%20can%20minify%20your%20CSS%20by%20adding%20the%20%2D%2Dminify%20flag%3A)
> docs: guides/styling#tailwind: added `--minify` flag on build command

- contributors.yml
Need to sign CLA for https://github.com/remix-run/remix/pull/948
> chore: add bogas04 to contributors

- contributors.yml
- docs/api/conventions.md
I have added a little section to explain the data passed to meta function. I feel like a list is not the ideal way to describe these but could not come up with anything better for the time being. So if anyone has any suggestions, I'm all ears.
> Meta function's arguments in Conventions page

- packages/create-remix/templates/cloudflare-pages/functions/[[path]].js
- packages/create-remix/templates/cloudflare-pages/package.json
- packages/remix-cloudflare-pages/worker.ts
> feat: hide CF bug fix in adapter

- fixtures/gists-app/package.json
- package.json
- packages/remix-react/package.json
- packages/remix-react/transition.ts
- packages/remix-server-runtime/package.json
- yarn.lock
Also fixed some of the broken types as a result of the History changes that should improve type narrowing a bit.
> chore: Bump react-router-dom dependency

- packages/remix-dev/cli/commands.ts
- packages/remix-serve/cli.ts
> chore(remix-server): update Remix App Server log to use local ip 

- contributors.yml
- docs/guides/typescript.md
I have added the TypeScript guide as mentioned in [issue24](https://github.com/remix-run/remix/issues/24).
> docs: Add TypeScript guide.

- .github/workflows/format.yml
I'm pretty sure this will work, though I'm not 100% certain. I would expect we'd have to have a token somewhere to authenticate which user is doing the committing/pushing. But it was working before so maybe it's fine?
> chore(format): use the actual bot email

- .github/workflows/format.yml
I'm like 60% sure this will work. If it doesn't then it's probably because we need to figure out a way to authenticate as a specific user before committing/pushing.
> chore(format): use the actual bot email (#1452)

- examples/sass/app/root.tsx
turns out i also had the original PR pointed to dev... - after merging, can you cherry-pick the 2 commits over <3
> docs(examples): add style import to sass

- contributors.yml
- docs/guides/resource-routes.md
cc @kentcdodds 
This PR adds a webhook section to the resource route doc page. 
Discord discussion: https://discord.com/channels/770287896669978684/920713036199776306/920779886824661062
> docs: Add webhooks section to resource route docs

- contributors.yml
- packages/remix-server-runtime/__tests__/data-test.ts
- packages/remix-server-runtime/data.ts
Fixes https://github.com/remix-run/remix/issues/1525
> Fixes error message when `loader` returns undefined

- docs/api/conventions.md
Should've had this a long time ago.
> docs: add docs for ignoredRouteFiles

- docs/api/conventions.md
- docs/api/remix.md
Great work on these @ryanflorence 👏👏
> docs(singles): add links to remix singles in docs

- contributors.yml
- docs/pages/faq.md
Just adding `async` to the function
> docs: add async to function

- docs/guides/envvars.md
> docs: Fix typo

- examples/tailwindcss/app/routes/index.tsx
- examples/tailwindcss/package.json
As requested by @ryanflorence in https://github.com/remix-run/remix/pull/1666#issuecomment-1025079203
> docs(examples): add `prettier-plugin-tailwindcss` to Tailwind example

- contributors.yml
- docs/tutorials/jokes.md
> fix typo documentation Jokes App Tutorial

- contributors.yml
- docs/tutorials/blog.md
> Update highlighted lines in blog tutorial

- contributors.yml
- docs/guides/resource-routes.md
The code example was missing an import
> docs: Update imports for resource routes code example

- contributors.yml
- docs/guides/not-found.md
Fixed a sentence regard whether a document is or is not present.
> TYPO Added a _not_ in the sentence about 404 

- contributors.yml
- docs/tutorials/blog.md
#1598
Changed the text so be somewhat easier for beginners to follow along the tutorial.
> chore(docs): innacurate statement

- packages/create-remix/cli.ts
- packages/create-remix/index.ts
- packages/create-remix/templates/deno/README.md
- packages/create-remix/templates/deno/gitignore
- packages/create-remix/templates/deno/package.json
- packages/create-remix/templates/deno/remix.config.js
- packages/create-remix/templates/deno/server.js
- packages/create-remix/templates/deno_ts/app/entry.client.tsx
- packages/create-remix/templates/deno_ts/app/entry.server.tsx
- packages/create-remix/templates/deno_ts/app/root.tsx
- packages/create-remix/templates/deno_ts/app/routes/index.tsx
- packages/create-remix/templates/deno_ts/import_map.json
- packages/create-remix/templates/deno_ts/remix.env.d.ts
- packages/remix-deno/deno.d.ts
- packages/remix-deno/globals.ts
- packages/remix-deno/index.ts
- packages/remix-deno/magicExports/platform.ts
- packages/remix-deno/server.ts
- packages/remix-deno/sessions/fileStorage.ts
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli.ts
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
- packages/remix-dev/config.ts
- packages/remix-dev/setup.ts
- rollup.config.js
This PR introduces a create-remix template option for Deno.
> feat: add deno template

- packages/create-remix/templates/arc/preferences.arc
- packages/create-remix/templates/deno_ts/tsconfig.json
chore: update arc to support dev auto reload
> chore: template updates

- contributors.yml
- docs/tutorials/jokes.md
In Jokes tutorial, fix a summary of `app/routes/login.tsx` which has divergent imports from previous summaries.
> docs(jokes): fix divergent login.tsx import example

- packages/remix-architect/magicExports/platform.ts
> chore: add magic export for createArcTableSessionStorage

- contributors.yml
- packages/remix-react/__tests__/components-test.tsx
- packages/remix-react/components.tsx
Add the composed prefetch handlers last so they don't get clobbered by explicit ones.
> fix(Link,NavLink) ensure prefetch works with explicit event handlers

- contributors.yml
- docs/api/conventions.md
> fix(docs): typo in conventions.md

- README.md
- examples/catch-boundary/README.md
- examples/client-side-validation/README.md
- examples/combobox-resource-route/app/routes/index.tsx
- examples/multiple-forms/README.md
- examples/nprogress/README.md
- examples/pathless-routes/README.md
- examples/redis-upstash-session/app/sessions/upstash.server.ts
- examples/remix-auth-supabase/app/supabase.ts
- examples/sharing-loader-data/README.md
- examples/socket.io/README.md
- examples/strapi/README.md
- examples/tailwindcss/README.md
- packages/remix-server-runtime/sessions.ts
@ryanflorence This one's running against `main`
#1843 still needs to be merged as it's also changing things that are (currently) only in `dev`
> chore: update docs links (`main` branch)

- contributors.yml
- docs/guides/data-loading.md
> fix(docs): add missing await for External APIs

- contributors.yml
- docs/api/remix.md
Updated the correct example for 'useMemorySessionStorage()'.
> updated the correct example for `createMemorySessionStorage()`

- docs/pages/faq.md
- examples/dataloader/app/routes/index.tsx
- examples/remix-auth-auth0/app/routes/auth0.tsx
- examples/remix-auth-auth0/app/routes/callback.tsx
- examples/route-modal/app/routes/invoices/$id/edit.tsx
- examples/routes-gen/app/routes/products/index.tsx
> chore: use `async` `action`/`loader` functions

- docs/pages/faq.md
@ryanflorence merged #1850 too quickly 🙈
> chore: fix formatting

- .github/workflows/arc-prerelease-deployment.test.yml
- .github/workflows/cf-pages-prerelease-deployment.test.yml
- .github/workflows/cf-workers-prerelease-deployment.test.yml
- .github/workflows/fly-prerelease-deployment-test.yml
- .github/workflows/format.yml
- .github/workflows/netlify-prerelease-deployment-test.yml
- .github/workflows/vercel-prerelease-deployment-test.yml
This was causing failures on my fork
https://github.com/MichaelDeBoey/remix/actions/runs/1814587667
> chore: run workflows on main repo only (`main` branch)

- .eslintrc.js
Reverts c1ccb953
CC/ @ryanflorence
> chore: enable MD codeblock linting again

- contributors.yml
- fixtures/gists-app/app/routes/methods.tsx
- integration/form-test.ts
- packages/remix-react/components.tsx
I found this bug yesterday and realise it is because of a simple check on the click handler.
Not sure if this worths an extra test case or not.
fix #651
> fix: button data is missing if clicking on the svg element within the button

- contributors.yml
- packages/remix-react/__tests__/components-test.tsx
- packages/remix-react/components.tsx
They were made from `main`, just cherry picked from dev.
> cherry pick 1685 commits

- contributors.yml
- docs/pages/contributing.md
- packages/create-remix/index.ts
This PR closes #1637 
**Solution**
Changed `mkdir` to `mkdirp`
> fix: adds support for creating new projects with nested paths

- examples/redis-upstash-session/app/sessions/upstash.server.ts
Removing  unneeded while loop in the Upstash example.
Thanks @donavon for letting me know.
> Remove unneeded while loop

- packages/remix-server-runtime/__tests__/cookies-test.ts
- packages/remix-server-runtime/__tests__/sessions-test.ts
- packages/remix-server-runtime/cookies.ts
Closes https://github.com/remix-run/remix/issues/1162
> [Feature]: Make the default path of cookies to be /

- .github/workflows/no-response.yml
All workflows failed due to invalid inputs
https://github.com/remix-run/remix/actions/workflows/no-response.yml
CC/ @ryanflorence
> chore: fix 'No Response' workflow

- packages/remix-eslint-config/package.json
- yarn.lock
> fix(remix-eslint-config): fix dependencies

- contributors.yml
- examples/socket.io/server/index.js
cherry-picked commits from PR #491
> chore: added warning about the unavailability of build

- packages/remix-node/index.ts
- packages/remix-node/magicExports/platform.ts
> feat: expose upload handler types

- docs/api/remix.md
- examples/bullmq-task-queue/app/queues/notifier.server.ts
- examples/bullmq-task-queue/app/routes/index.tsx
- examples/bullmq-task-queue/app/utils/redis.server.ts
Formatting workflow is stuck again.
I **really** think we should start including formatting in PRs, so we don't have these type of things anymore 🤔
https://github.com/remix-run/remix/runs/5170162309?check_suite_focus=true#step:6:1163
CC/ @ryanflorence
> chore: fix ESLint errors

- packages/remix-architect/__tests__/server-test.ts
- packages/remix-architect/server.ts
- packages/remix-netlify/__tests__/server-test.ts
- packages/remix-netlify/server.ts
> fix(remix-architect,remix-netlify): update binary data responses

- .gitignore
- .vscode/settings.json
> chore: have VS Code use project typescript version

- packages/remix-dev/package.json
- yarn.lock
https://github.com/evanw/esbuild/issues/2019
> chore: revert esbuild version

- packages/create-remix/cli.ts
they're not quite ready, but we can keep them around while we continue to cook them up
> chore: make stacks a hidden option

- contributors.yml
- docs/guides/data-loading.md
Hey people,
I just updated a highlighting "error" in the data-loading docs markdown file. Please review.
> docs: update highlighting in data loading

- docs/api/remix.md
> docs: update cloudinary stream upload

- packages/remix-eslint-config/index.js
- packages/remix-eslint-config/package.json
- packages/remix-eslint-config/rules/jsx-a11y.js
- packages/remix-eslint-config/rules/react.js
- packages/remix-eslint-config/settings/import.js
- packages/remix-eslint-config/settings/react.js
- packages/remix-react/components.tsx
Further steps towards integrating the eslint-config
> chore: ESLint integration

- contributors.yml
- docs/guides/data-writes.md
> docs: Update small typos in data-writes.md

- contributors.yml
- examples/chakra-ui/README.md
> Small typo fix Update README.md

- contributors.yml
- examples/file-and-cloudinary-upload/README.md
Corrected a typo in the readme.
> docs: Update README.md

- README.md
- contributors.yml
> docs: URL typo fix for contributing markdown file

- docs/tutorials/jokes.md
- examples/jokes/app/utils/session.server.ts
We can utilize the helper function created before to get the session instead of implementing it again.
> docs(jokes): reduce duplicate code

- contributors.yml
- docs/tutorials/jokes.md
> docs(jokes): typo fix

- docs/tutorials/blog.md
Types should be added as a Development dependency
> docs: fix typo in tutorials/blog

- .github/workflows/deployment-test.yml
- .github/workflows/format.yml
- .github/workflows/release-private.yml
- .github/workflows/release.yml
- .github/workflows/test.yml
- .github/workflows/website.yml
- packages/create-remix/templates/arc-stack/github/workflows/deploy.yml
- packages/create-remix/templates/fly-stack/github/workflows/deploy.production.yml
- packages/create-remix/templates/fly-stack/github/workflows/deploy.staging.yml
If wanted, I can create a @dependabot file, so PRs are created automatically for these.
> chore(CI): update workflow action versions

- examples/tailwindcss/.eslintrc.js
- examples/tailwindcss/.gitignore
- examples/tailwindcss/app/entry.server.tsx
- examples/tailwindcss/app/root.tsx
- examples/tailwindcss/package.json
- examples/tailwindcss/remix.config.js
- examples/tailwindcss/sandbox.config.json
- examples/tailwindcss/tsconfig.json
Bringing the Tailwind CSS example in line with the new templates + changes I made in #2143
> docs(examples): update Tailwind CSS example

- docs/guides/styling.md
I noticed the `package.json` was outdated & all templates/stacks are suggesting to use `npm-run-all`
> docs(styling): update Tailwind CSS docs

- examples/multiple-params/.eslintrc.js
@kentcdodds Simplify what you did in cabcb02
> docs(examples): simplify ESLint config for sanity example

- docs/tutorials/jokes.md
> docs(tutorials/jokes): fix highlighted lines

- integration/fetcher-test.ts
- integration/helpers/create-fixture.tsx
There doesn't appear to be anything that needs to be done here.
Closes: #
> test: added fixture test from Logan for fetcher resource routes

- docs/pages/philosophy.md
- docs/pages/stacks.md
- docs/pages/technical-explanation.md
> docs: add remix stacks docs

- integration/fetcher-layout-test.ts
- packages/remix-react/transition.ts
Closes: https://github.com/remix-run/remix/issues/1291
> fix: disambiguate layout vs index route fetcher submissions

- templates/deno-ts/README.md
> docs(templates/deno): mark deno template as experimental

- docs/guides/disabling-javascript.md
- docs/guides/styling.md
- docs/tutorials/jokes.md
> docs: remove `charSet` `meta` tags

- docs/api/remix.md
Was missed in #2250 (see https://github.com/remix-run/remix/pull/2250#discussion_r821211974)
> docs(api/remix): fix highlighted lines

- examples/multiple-forms/README.md
- examples/multiple-forms/app/routes/invitations.tsx
- integration/transition-test.ts
As follow-up of @ryanflorence's f47a5114
> chore: use `action` field instead of `_action`

- packages/remix-eslint-config/package.json
> chore(eslint-config): fix `repository` field in `package.json`

- templates/arc-ts/package.json
- templates/arc/package.json
- templates/cloudflare-pages-ts/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers-ts/package.json
- templates/cloudflare-workers/package.json
- templates/deno-ts/package.json
- templates/express-ts/package.json
- templates/express/package.json
- templates/fly-ts/package.json
- templates/fly/package.json
- templates/netlify-ts/package.json
- templates/netlify/package.json
- templates/remix-ts/package.json
- templates/remix/package.json
- templates/vercel-ts/package.json
- templates/vercel/package.json
Version isn't updated anymore since `templates` were moved to root of the project
---
Follow-up of #2189
CC/ @mcansh
> fix(templates): fix version of remix packages

- contributors.yml
- docs/pages/stacks.md
> Fix amusing typo (carrot -> caret) 🥕 

- examples/emotion/package.json
- examples/msw/package.json
- examples/multiple-params/package.json
- examples/stripe-integration/package.json
- package.json
- scripts/patchup-example-names.mjs
> feat(scripts): sort updated files in `patchup-example-names` script

- packages/remix-serve/index.ts
- templates/express-ts/server.js
- templates/express/server.js
> fix: update remix app server caching

- docs/guides/styling.md
> fix: typo in the word “tool”

- contributors.yml
- docs/tutorials/jokes.md
Correcting text description of validation.
> docs(jokes): Fix text description of validation

- examples/tailwindcss/README.md
Added .gitignore to the "Relevant files" section
> docs(tailwind): Add .gitignore to relevant files

- contributors.yml
- docs/api/remix.md
> docs(useFormAction): delete is not a valid form method

- contributors.yml
- docs/guides/routing.md
> docs(routing): remove TODO item from guide navigation

- .github/ISSUE_TEMPLATE/config.yml
- contributors.yml
1.  update `config.yml` file to help direct current & potential remix users to the helpful pages
- adds helpful tips for user's during the process of creating a bug/issue report
- bring awareness to other Remix resources to grow the awesome remix community 🤝 📀👥
> chore: update config.yml; add more community remix official resource links

- contributors.yml
- examples/collected-notes/README.md
Fixes broken code sandbox url in `collected-notes` example. "Open in CodeSandbox" did not work before.
> docs(example): Fix broken CodeSandbox url in `collected-notes` example

- scripts/deployment-test/arc.mjs
- scripts/deployment-test/package.json
AWS has a 100 s3 bucket per account limit and we've quickly reached that, this PR removes the oldest deployment prior to making a new one
Closes: REM-901
> ci: re-use arc app

- contributors.yml
- docs/tutorials/blog.md
Hi 👋 ,
I was going through Remix blog tutorial and noticed there is room for improvement in TS support.
These are just minor changes that aim to improve DX.
> docs(tutorials): improve blog tutorial TS support

- packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/cleanup-package-json.ts
- packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/get-jscodeshift-extra-options.ts
- packages/remix-dev/cli/codemod/run/transforms/update-remix-imports/index.ts
> fix(remix-dev): add runtime to `package.json` in `update-remix-imports` codemod

- integration/transition-test.ts
- packages/remix-react/routes.tsx
> fix(remix-react): add missing hash when redirecting client side

- integration/form-data-bad-content-type-test.ts
- integration/form-data-test.ts
- packages/remix-node/fetch.ts
- packages/remix-node/parseMultipartFormData.ts
Closes: https://github.com/remix-run/remix/issues/2522
> fix: validate content-type for request.formData()

- contributors.yml
- examples/blog-tutorial/README.md
"Now that every is set up you can commit and push your changes to your repo."
> docs(tutorial): improve a sentence in `blog-tutorial` README

- packages/remix-dev/cli/migrate/jscodeshift.ts
- packages/remix-dev/cli/migrate/migrations/index.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/getTransformOptions.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/transform/index.ts
- packages/remix-dev/cli/migrate/resolveInput.ts
> fix(remix-dev/cli/migrate): bug fixes & improved DX

- contributors.yml
- docs/api/conventions.md
- docs/api/remix.md
> docs: use ASCII characters

- integration/fetcher-test.ts
- packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
> fix(remix-dev): resource route module making it to the browser

- packages/remix-netlify/server.ts
> fix(remix-netlify): don't parse multipart `formData` to string

- docs/api/conventions.md
- docs/guides/errors.md
- docs/guides/routing.md
- docs/tutorials/jokes.md
- examples/sanity/studio/README.md
> docs: replace `[NBSP]` with normal space

- .github/workflows/release.yml
> ci: update deploy requirement

- integration/compiler-test.ts
- packages/remix-dev/compiler/plugins/serverBareModulesPlugin.ts
> fix(remix-dev): manually resolve package.json for deps

- package.json
- yarn.lock
Seems like this one was missed in #2634
> chore: remove `pptr-testing-library` dependency

- docs/pages/faq.md
Copy/pasted @ryanflorence answer on discord : https://discord.com/channels/770287896669978684/770287896669978687/963430734234783754
> docs(faq): Explain the difference between CatchBoundary and ErrorBoundary

- packages/remix-dev/colors.ts
> fix(cli/migrate): `gray` should be gray, not blue

- packages/remix-dev/cli/migrate/migrations/replace-remix-imports/index.ts
> fix(cli/migrate): use best version spec as remix version

- templates/deno/app/deps/@remix-run/react.ts
- templates/deno/app/deps/@remix-run/server-runtime.ts
- templates/deno/app/deps/react-dom-server.ts
- templates/deno/app/deps/react-dom.ts
- templates/deno/app/deps/react.ts
- templates/deno/app/entry.server.tsx
- templates/deno/app/root.tsx
- templates/deno/deno.json
- templates/deno/package.json
- templates/deno/remix-deno/deps/@remix-run/server-runtime.ts
> fix(templates/deno): `build` and `start` run without errors

- .github/workflows/test.yml
(cherry picked from commit 652c72f)
follow up of #2771 for `main`
Closes: #
> ci(test): cache playwright binaries

- .github/workflows/nightly.yml
> ci(nightly): set up git

- examples/google-analytics/README.md
Corrects a broken link on the google analytics example
> docs(example): Fix link in google analytics example

- packages/remix-dev/cli/commands.ts
> fix(remix-dev): either use provided env port, or randomize from 3000 to 3100

- .github/workflows/nightly.yml
- scripts/publish.js
> ci(publish.js): a few more nightly adjustments

- .github/workflows/nightly.yml
> ci: add note to nightly workflow

- .github/workflows/test.yml
> ci: update playwright caching to work across matrix

- examples/dark-mode/app/utils/theme-provider.tsx
https://remix.run/docs/en/v1/pages/gotchas#typeof-window-checks
> docs(examples): replace `window` check with `document` check in `dark-mode` example

- docs/api/conventions.md
> docs(conventions): ignore dotfiles in route subdirectories too

- .github/workflows/test.yml
- packages/remix-dev/__tests__/create-test.ts
> test: run against node 14 and node 16

- contributors.yml
- examples/socket.io/README.md
- examples/socket.io/package.json
Closes: #2860
The `"dev"` script was changed from `"remix dev"` to `"remix watch"` to solve problems when working on the application as described in #2860.
> docs(examples): update `socket.io` example

- contributors.yml
- docs/tutorials/jokes.md
In the Jokes tutorial where it adds the line `return createUserSession(user.id, redirectTo);`, I had trouble finding it at first because it wasn't highlighted as new code.
> docs(tutorials/jokes): update line highlights

- packages/remix-dev/compiler.ts
> fix: updated conditions for deno and netlify edge

- .github/workflows/nightly.yml
- .github/workflows/release-comments.yml
- .github/workflows/release.yml
- scripts/release/constants.mjs
I'll need to cherry-pick this over to `dev` as well due to changing `scripts/release`
> ci: add content-type to curl, rename `GITHUB_REF` to `VERSION`

- .github/workflows/nightly.yml
- .github/workflows/release.yml
https://github.com/marketplace/actions/repository-dispatch
> ci(nightly,release): use repository-dispatch action

- .github/workflows/deployments.yml
> ci(deployments): disable lockfile usage for bahmutov/npm-install action

- packages/remix-dev/cli/commands.ts
> Revert "feat: clean directories before initial builds"

- scripts/deployment-test/arc.mjs
continued from https://github.com/remix-run/remix/pull/2447
https://github.com/remix-run/remix/runs/6170940717?check_suite_focus=true#step:7:159
> ci(deployment-tests): update deleting of old arc app

- contributors.yml
- packages/create-remix/templates/express/README.md
Just a small change on the README.
> docs: refine README for create-remix/express

- contributors.yml
- docs/guides/constraints.md
> docs(guides/constraints): fix typo

- scripts/release/comment.mjs
- scripts/release/constants.mjs
- scripts/release/octokit.mjs
(cherry picked from commit 94ae714)
> ci: tweak "found x prs since..." message to include versions

- packages/remix-react/components.tsx
> feat(remix-react): clean up which button clicked submit implementation

- examples/session-flash/app/root.tsx
- examples/session-flash/app/routes/index.tsx
> chore: fix unfixable eslint errors

- contributors.yml
- examples/jokes/app/utils/session.server.ts
Hello,
A tiny change to use the already defined function `getUser` to get the `userId`
> chore(examples): use helper functions as much as possible in `jokes` example

- packages/remix-dev/__tests__/cli-test.ts
Cherry-picking https://github.com/remix-run/remix/pull/3079 into dev as well
> ci: bump cli test process timeout

- .github/workflows/test.yml
https://nodejs.org/en/blog/announcements/v18-release-announce
> chore(tests): run against Node v18

- packages/remix-netlify/package.json
- templates/netlify/package.json
- yarn.lock
As suggested in https://github.com/remix-run/remix/pull/3104#discussion_r866382710, extracted this to not pollute #3104
> feat(remix-netlify): broaden `peerDependencies`

- .github/workflows/test.yml
https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#running-your-workflow-based-on-files-changed-in-a-pull-request-1
closes REM-1072
> ci: skip tests if PR only touches docs

- docs/pages/contributing.md
Just to clear things up for contributors.
> docs(contributing): clarify that template changes go to main

- docs/guides/migrating-react-router-app.md
> docs(guides/migrating-react-router-app): fix highlight

- docs/guides/typescript.md
> docs: update `tsconfig`

- integration/helpers/cf-template/jsconfig.json
- integration/helpers/node-template/jsconfig.json
- packages/remix-dev/__tests__/fixtures/stack/tsconfig.json
> tests: update `tsconfig`

- packages/remix-dev/cli/run.ts
Deno support is considered "stable" now, so we can re-add it to Create Remix.
Closes: #
> chore(create-remix): add deno to template choices

- templates/cloudflare-workers/remix.env.d.ts
> fix(templates/cloudflare-workers): fix runtime globals reference

- decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
- decisions/0002-do-not-clone-request.md
- decisions/index.md
- decisions/template.md
frontmatter and index file are not necessary since decision docs are not part of the web docs for
remix
> docs(decisions): remove frontmatter and index file

- docs/tutorials/jokes.md
Adding an additional line about remembering to restart your dev server when resetting the local prisma database.
> docs(jokes): Clarify restart of dev server when resetting prisma db

- docs/api/remix.md
> docs: update uploadHandler docs

- integration/helpers/cf-template/package.json
- integration/helpers/node-template/package.json
- packages/remix-dev/__tests__/fixtures/replace-remix-imports/package.json
- packages/remix-dev/__tests__/fixtures/stack/package.json
- scripts/playground/template/package.json
> tests: remove `description` & `license` keys from `package.json`

- templates/vercel/vercel.json
[Vercel recently added support for `$schema`](https://vercel.com/changelog/schema-autocomplete-and-validation-for-vercel-json) in the `vercel.json` to enable autocompletion and valdiation of the config file.
This PR add the `$schema` to the Vercel template.
> feat(templates/vercel): add `$schema` in vercel config file

- packages/remix-dev/package.json
- yarn.lock
I also took the liberty of updating all `@babel/*` deps to their latest minor
---
Fixes https://github.com/remix-run/indie-stack/issues/97
> fix(remix-dev): add `@babel/preset-env` in `dependencies`

- .github/workflows/stacks.yml
- .github/workflows/website.yml
Needed for at least `grunge-stack`
> chore: update GitHub Actions

- packages/remix-dev/__tests__/fixtures/replace-remix-imports/package.json
- packages/remix-dev/__tests__/fixtures/replace-remix-imports/tailwind.config.js
- scripts/playground/template/package.json
- scripts/playground/template/tailwind.config.js
https://tailwindcss.com/blog/tailwindcss-v3-1#first-party-type-script-types
> tests: update Tailwind config in tests

- docs/tutorials/jokes.md
> docs(tutorials/jokes): update code highlighting

- .github/workflows/nightly.yml
see successful skipping here 👉 https://github.com/mcansh/nightly-release-test/runs/6888945529?check_suite_focus=true
Closes: #
> ci: dont cut a nightly if the latest dev commit was the last nightly

- contributors.yml
- docs/tutorials/jokes.md
- Fix diff lines for index route
- Consistently use `IndexRoute` as the default exported component in `routes/index.tsx`
> docs(tutorials/jokes): fix typo

- templates/vercel/package.json
This reverts commit 6a2bf52d9ca60e2ce6459ebe72df28e6a568ed26.
Closes: #
> Revert "chore(templates): update `vercel` template (#3381)"

- .github/workflows/nightly.yml
> ci(nightly): fix NEXT_VERSION

- .github/workflows/deployments.yml
- .github/workflows/nightly.yml
- .github/workflows/release.yml
https://github.com/remix-run/remix/actions/runs/2513898715
Closes: #
> ci(deployments): define required secrets

- .github/workflows/nightly.yml
- .github/workflows/release.yml
step 3 from https://docs.github.com/en/actions/using-workflows/reusing-workflows#using-inputs-and-secrets-in-a-reusable-workflow
Closes: #
> ci: update how secrets are passed to reusable workflows

- docs/tutorials/blog.md
For production deploy you will need db migrations for your schema changes
Closes: #3246
> docs(tutorials/blog): add 'create migration' step

- contributors.yml
- docs/api/conventions.md
Closes: #3630
Testing Strategy: Local testing for docs
> docs(api/conventions): Fix broken routing guide link

- .github/workflows/stacks.yml
Verified caching here: https://github.com/jenseng/remix/actions/runs/2584832365
See prior PR for more context: https://github.com/remix-run/remix/pull/3593
> chore: remove last usage of bahmutov/npm-install

- contributors.yml
- docs/api/remix.md
- docs/tutorials/jokes.md
Update the docs
Closes: #
Testing Strategy: It is a documentation update, so tested it by checking the preview
> fix: Update the installation step for the jokes app

- examples/theme-ui/app/entry.client.tsx
- examples/theme-ui/app/entry.server.tsx
- examples/theme-ui/app/root.tsx
- examples/theme-ui/app/routes/index.tsx
- examples/theme-ui/app/routes/jokes.tsx
- examples/theme-ui/app/styles/context.tsx
- examples/theme-ui/app/styles/createEmotionCache.tsx
> chore(examples): fix ESLint warnings in `theme-ui` example

- packages/remix-react/routeModules.ts
> feat(remix-react): add magic comment to allow `webpack` bundling

- templates/cloudflare-workers/package.json
> fix(templates/cloudflare-workers): prevent building twice with `wrangler publish`

- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/transition.ts
Closes: #3712
Testing Strategy: Unit test + confirmed this fixes the issue in the reproduction provided in the issue
> fix(remix-react): fix `shouldReload` bug for deferred cancellations on fetcher submissions

- .github/workflows/release-experimental.yml
> chore(ci): Add workflow for experimental releases

- contributors.yml
- docs/tutorials/blog.md
> docs(tutorial/blog): Instruct to restart the dev server after marked install

- docs/tutorials/blog.md
> docs(tutorials/blog): add message about TS2305 warning

- docs/api/conventions.md
- docs/api/remix.md
- docs/guides/bff.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/guides/mdx.md
- docs/guides/optimistic-ui.md
- docs/guides/resource-routes.md
- docs/guides/styling.md
- docs/other-api/node.md
- docs/other-api/serve.md
- docs/pages/faq.md
- docs/pages/gotchas.md
- docs/pages/philosophy.md
Just like @pcattori did in #3072 for `@remix-run/cloudflare`
> docs: add `@remix-run/deno` reference in import comments

- contributors.yml
- docs/guides/migrating-react-router-app.md
> docs(guide): Fix a typo in migrating-react-router-app.md

- .changeset/neat-nymphs.md
- contributors.yml
- docs/guides/mdx.md
- integration/mdx-test.ts
- packages/remix-dev/compiler/plugins/mdx.ts
> feat(mdx): support exporting links function

- docs/pages/contributing.md
> docs: add basic doc entry for how nightly releases work and how they run

- .changeset/five-kiwis-type.md
- packages/remix-deno/package.json
require.resolve doesn't look for ts unless you explicitly set it :)
Closes: #
> fix: add main field to remix-run/deno

- .changeset/chilled-ants-care.md
- packages/remix-dev/cli/run.ts
which is incompatible with node 14.
Closes #3877
> fix(remix-dev): Remove logical nullish assignment

- .github/workflows/release-test.yml
> ci: run nightly releases against all supported node versions

- contributors.yml
- docs/api/remix.md
Hi 👋 
Noticed a typo in API docs, thought I'd fix it.
> docs(api/remix): fix typo

- contributors.yml
- examples/client-side-validation/README.md
> docs(examples/client-side-validation): fix file path

- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli/run.ts
> tests: fix failing tests

- .changeset/stale-worms-laugh.md
- packages/remix-dev/cli/checkGitStatus.ts
- packages/remix-dev/config.ts
> fix(remix-dev): convert config file path to file url

- .github/workflows/reusable-test.yml
- .github/workflows/stacks.yml
- integration/playwright.config.ts
- integration/upload-test.ts
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/__tests__/migrations/convert-to-javascript-test.ts
- packages/remix-dev/__tests__/replace-remix-imports-test.ts
- packages/remix-dev/__tests__/setupAfterEnv.ts
Cherry-pick of #3915 against `dev`
> test: windows testing updates

- .changeset/green-crabs-join.md
- contributors.yml
- packages/remix-dev/compiler/loaders.ts
- packages/remix-dev/modules.ts
Added support for `.zip` files.
> feat(remix-dev): allow importing `.zip` files

- examples/turborepo-vercel/apps/remix-app/package.json
- examples/turborepo-vercel/packages/ui/package.json
quick follow up to https://github.com/remix-run/remix/pull/3984.
tried to be lightweight in what i brought over, but looks like name and version are required for the workspace projects, quick follow up PR inbound
Closes: #
> examples(turborepo): add name and version to workspace projects

- examples/framer-route-animation/README.md
> docs(examples/framer-route-animation): fix react router links in README

- scripts/deployment-test/netlify.mjs
> ci(deployments): update netlify deploy command

- scripts/deployment-test/arc.mjs
> ci(deployments): fix destroying s3 buckets

- .eslintrc.js
- templates/.eslintrc.js
- templates/cloudflare-pages/app/entry.server.tsx
- templates/cloudflare-workers/app/entry.server.tsx
- templates/express/app/entry.server.tsx
- templates/express/server.js
- templates/fly/app/entry.server.tsx
- templates/netlify/server.js
- templates/remix/app/entry.server.tsx
Both `format` & `lint` workflows are failing since ba5c8486
https://github.com/remix-run/remix/runs/7908428299?check_suite_focus=true
https://github.com/remix-run/remix/runs/7908428662?check_suite_focus=true
> chore(templates): fix ESLint errors

- .github/workflows/nightly.yml
- .github/workflows/postrelease.yml
- .github/workflows/release-comments.yml
- scripts/release/constants.ts
- scripts/release/github.ts
- scripts/release/package-lock.json
- scripts/release/utils.ts
this brings ci on dev in line with what's on main
the comment script is failing on main, but i'm not seeing any of the added logging over there, which makes me think that GitHub changed something so this actually runs where you'd think it would. I've tested it countless times locally (with commenting disabled) and it runs perfectly fine
Closes: #
> ci: use graphql api for tags

- docs/guides/browser-support.md
based on https://discord.com/channels/770287896669978684/770287896669978687/1012758574411305031
Also mentioned in [#2906](https://discord.com/channels/770287896669978684/770287896669978687/1012758574411305031)
> docs(guides): Add note about CSRF support

- docs/pages/gotchas.md
Closes: #3051
Tested locally on one of my projects, got the same problem as OP. This change fixes it.
> docs(gotcha): Fix fs-extra re-export sample

- contributors.yml
- docs/other-api/dev.md
> fix link to remix app server page

- examples/turborepo-vercel/README.md
> chore(examples): update turborepo example readme

- scripts/release/comment.ts
> ci: use `Promise.allSettled` when commenting to prevent errors when commenting on issues that were converted to discussions

- .changeset/cyan-cats-sip.md
- examples/session-flash/package.json
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- yarn.lock
> chore: lock RR version

- docs/api/conventions.md
- docs/api/remix.md
- docs/guides/migrating-react-router-app.md
- docs/guides/styling.md
- docs/index.md
- docs/pages/community.md
- docs/pages/contributing.md
- docs/tutorials/jokes.md
Updated all links to examples in the documentation.
> docs(examples): Update references to the examples repository

- docs/api/conventions.md
> docs(api/conventions): fix broken link

- contributors.yml
- docs/tutorials/jokes.md
Added highlighting to lines 27 and 28 because these are new changes from the last time jokes.tsx was updated in the tutorial. This tells the user following the tutorial to also change these lines to use the new `data` const that is created in this step.
<!--
👋 Hey, thanks for your interest in contributing to Remix!
> docs(tutorials/jokes): fix code highlighting

- integration/tsconfig-test.ts
> chore: fix a borked test caused by shallow clone

- .changeset/poor-sloths-whisper.md
> chore: add changeset for #4041

- integration/helpers/node-template/app/entry.client.tsx
- integration/helpers/node-template/app/entry.server.tsx
- integration/helpers/node-template/package.json
- package.json
- yarn.lock
> feat(integration): bring React 18 fixtures in line with `indie-stack` updates

- integration/catch-boundary-data-test.ts
- integration/catch-boundary-test.ts
- integration/redirects-test.ts
- integration/set-cookie-revalidation-test.ts
- integration/transition-test.ts
> chore: make tests more reliable

- packages/remix-react/transition.ts
This prevents a false negative on `node >= 15` where `AbortController` exists on the server:
I wasn't able to add an integration test for this since if you actually do fetch in SSR, it kills the server since it's an uncaught promise rejection _after_ the render pass has completed
> fix(remix-react): update server-side check to use window.document instead of AbortController

- .eslintrc.js
- packages/remix-eslint-config/internal.js
- packages/remix-eslint-config/package.json
Follow-up of https://github.com/remix-run/examples/pull/14
> fix(remix-eslint-config): update `internal` ESLint config

- contributors.yml
- templates/deno/.vscode/resolve_npm_imports.json
fix(remix-deno): deno fix type reexport from server-runtime not working
> fix(templates/deno): fix type re-export from `@remix-run/server-runtime`

- .github/workflows/no-response.yml
this stopped working, but is working on the examples repo, so i've migrated changes from there
Closes: #
> ci: update stale workflow

- scripts/deployment-test/cf-workers.mjs
> ci(deployment-test/cf-workers): update worker url

- contributors.yml
- decisions/0001-use-npm-to-manage-npm-dependencies-for-deno-projects.md
> docs(decisions): fix typos

- contributors.yml
- packages/remix/index.ts
> chore(remix): fix typo

- .changeset/moody-cats-relax.md
- packages/remix-architect/__tests__/server-test.ts
- packages/remix-express/__tests__/server-test.ts
- packages/remix-netlify/__tests__/server-test.ts
- packages/remix-node/package.json
- packages/remix-vercel/__tests__/server-test.ts
- yarn.lock
> fix(remix-node): update `@remix-run/web-fetch` to 4.3.2

- .changeset/sharp-weeks-rush.md
- rollup.utils.js
https://github.com/remix-run/remix/pull/4661#issuecomment-1324275806
> chore: add JSDoc deprecation to CJS exports

- packages/remix-react/__tests__/transition-test.tsx
- packages/remix-react/browser.tsx
- packages/remix-react/components.tsx
- packages/remix-react/errorBoundaries.tsx
- packages/remix-react/links.ts
- packages/remix-react/package.json
- packages/remix-react/routeMatching.ts
- packages/remix-react/routeModules.ts
- packages/remix-react/server.tsx
- packages/remix-react/transition.ts
- packages/remix-server-runtime/routeModules.ts
- yarn.lock
Remove the `history` dependency entirely and bump to the latest `react-router-dom@6.4.4-pre.1` release
> Bump remix to RR 6.4.4 and drop history dependency

- .changeset/weak-beds-thank.md
> chore: add changeset for #4709

- docs/guides/data-writes.md
- docs/guides/optimistic-ui.md
> docs: fix code highlighting

- .github/workflows/nightly.yml
https://github.com/remix-run/remix/actions/runs/3590285381/jobs/6043522215#step:7:82
x-ref: #4715
Closes: #
> ci(nightly): add deno for typechecking deno files

- package.json
- yarn.lock
same as https://github.com/remix-run/remix/pull/4749, but for the `main` branch
(cherry picked from commit 48349f49d3a6798d24a2f94ea1bbb6d6446b5a3e)
Closes: #
> chore: bump @playwright/test to latest

- integration/transition-state-test.ts
> test: add transition integration tests

- .github/workflows/merged-pr.yml
> ci: only apply `awaiting release` label to prs related to `./packages`

- .changeset/moody-pants-own.md
- contributors.yml
> fix: wrong parentheses in the optional segments changeset

- .github/workflows/nightly.yml
TODOs before merging: 
Closes: #
> ci(nightly): remove need for xargs, only get diff names

- .changeset/late-peas-hang.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- yarn.lock
> Bump RR deps

- .changeset/clean-clocks-float.md
- .github/workflows/nightly.yml
- .github/workflows/reusable-test.yml
- packages/remix-deno/server.ts
- scripts/build.mjs
This partially reverts #4715.
running into issues with package publishing due to Deno trying to fetch the new version before it's published - will look into bringing it back after the fact
Closes: #
> Revert "ci: add typechecking for deno (#4715)"

- integration/revalidate-test.ts
- packages/remix-dev/compiler/plugins/browserRouteModulesPlugin.ts
Forgot one `unstable_shouldReload -> shouldRevalidate` update that was preventing it from making it into the client bundles.  also added a few tests for that and `useRevalidator`
> Include shouldRevalidate in client bundles

- integration/fetcher-state-test.ts
- packages/remix-react/components.tsx
- packages/remix-react/index.tsx
- packages/remix-react/transition.ts
Missed a few re-exports and missed keeping the flattened data on fetchers
> Add a few missed re-exports and back-compat

- .changeset/rotten-bulldogs-reply.md
- packages/remix-server-runtime/routeModules.ts
> fix: `V2_MetaFunction` should return `V2_HtmlMetaDescriptor[]`

- .changeset/metal-birds-tease.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Lock into 6.6.1/1.2.1 versions
> Bump router versions to stable

- .changeset/big-geese-cry.md
- packages/remix-react/data.ts
> fix: pass through request abort signal

- packages/remix-deno/server.ts
> fix: fix Deno lint errors

- integration/catch-boundary-test.ts
Added integration tests around 404 + root loader behavior to ensure 1.10 matches 1.7.6 behavior.
To run these new tests against `1.7.6` locally:
```
git checkout remix@1.7.6
git checkout -b temp
git cherry-pick 2961255c7
yarn
npx playwright install
yarn test:integration catch-boundary
```
> Add integration test for 404 loader behavior

- .changeset/few-seas-hunt.md
- packages/remix-react/package.json
- packages/remix-testing/package.json
- yarn.lock
> Bump RR to 6.6.2-pre.0

- scripts/release/comment.ts
- scripts/release/constants.ts
- scripts/release/github.ts
- scripts/release/utils.ts
`1.10.1-pre.0` used a nightly release as it diff check and commented on things it shouldn't have.
https://github.com/remix-run/remix/actions/runs/3893803233/jobs/6646943719#step:5:12
sync from https://github.com/mcansh/nightly-release-test/compare/5abb4066af899088a1e0c28795595a1673a55cde...c552cf8b951d14507224e2b1bc1572967fd8e330
```log
Getting PRs merged 1.9.0...1.10.0
Getting PRs merged 1.10.1-pre.0...1.10.1-pre.1
Getting PRs merged 1.10.0...1.10.1-pre.0
Getting PRs merged v0.0.0-nightly-d9ecd5d-20230110...v0.0.0-nightly-f5475db-20230111
```
Closes: #
> ci: update previous release detection

- docs/guides/typescript.md
- packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
- packages/remix-dev/__tests__/migrations/fixtures/indie-stack/package.json
- templates/arc/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers/package.json
- templates/express/package.json
- templates/fly/package.json
- templates/netlify/package.json
- templates/remix/package.json
- templates/vercel/package.json
> chore(docs,templates): update `typecheck` script

- docs/components/await.md
- docs/guides/streaming.md
- docs/utils/defer.md
> docs: initial defer docs

- packages/remix-react/components.tsx
> chore: update to ReactNode instead of Element

- contributors.yml
- docs/components/await.md
> docs(Await): Fix `useLoaderData` link

- packages/remix-react/CHANGELOG.md
- packages/remix-server-runtime/CHANGELOG.md
> chore: fix lint errors

- .changeset/mean-clocks-bow.md
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/config.ts
- packages/remix-dev/devServer2.ts
> fix(dev): keep dev server process alive after initial build

- integration/playwright.config.ts
> ci: update playwright reporter in ci

- contributors.yml
- docs/tutorials/blog.md
little fix on highlighting the correct line.
> docs(tutorials/blog): fix code highlighting

- packages/remix-dev/compiler/utils/fs.ts
- packages/remix-dev/config.ts
> refactor(dev): simplifications

- .changeset/tender-turtles-wash.md
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/devServer/liveReload.ts
- packages/remix-dev/devServer/serve.ts
- packages/remix-dev/devServer2.ts
> fix(dev): dev server maintains clean build directories

- .changeset/silver-rockets-remember.md
- packages/remix-cloudflare/index.ts
- packages/remix-deno/index.ts
> fix(remix-cloudflare,remix-deno): export `JsonFunction` type

- .github/ISSUE_TEMPLATE/bug_report.yml
- contributors.yml
> fix: bug report yaml parsing Yes as Boolean

- docs/guides/streaming.md
I guess the prop was changed because TypeScript was bugging me.
> docs(guides/streaming): update `serverAbortDelay` to `abortDelay`

- contributors.yml
- docs/guides/styling.md
Doing this from my phone while getting my kid ready for school forgive me for not being able to fill in the template 😅
> docs(guides/styling): fix Tailwind CSS installation instructions

- contributors.yml
- docs/file-conventions/route-files-v2.md
> docs(file-conventions/route-files-v2): fix typo

- docs/route/meta.md
> docs(route/meta): cleanup

- packages/remix-dev/cli/commands.ts
- packages/remix-dev/devServer/serve.ts
> fix(dev): keep dev server process alive

- docs/guides/data-writes.md
> docs(guide/data-writes.md): fix linting

- docs/guides/bff.md
- docs/guides/browser-support.md
- docs/guides/data-loading.md
- docs/guides/data-writes.md
- docs/guides/errors.md
- docs/guides/migrating-react-router-app.md
- docs/guides/optimistic-ui.md
- docs/guides/performance.md
- docs/guides/resource-routes.md
- docs/guides/routing.md
- docs/guides/streaming.md
- docs/guides/styling.md
- docs/guides/typescript.md
- docs/route/meta.md
Continuation of https://github.com/remix-run/remix/pull/5320
Probably the last of its kind, as I finished reading through the docs.
Hopefully more substantial contributions in the future 😂
> docs: more punctuation

- .changeset/olive-jokes-invent.md
- packages/remix-react/__tests__/components-test.tsx
- packages/remix-react/components.tsx
> fix(react): live reload works without scripts

- .github/workflows/release.yml
- scripts/release/find-release-from-changeset.js
something something `SnaKE_CasE` being the root of all evil
Closes: #
> ci: uppercase ENV, changesets output is camelCase

- .changeset/eleven-plums-film.md
> add serverBuildTarget deprecation changeset

- contributors.yml
- docs/route/meta.md
> docs(route/meta): fix grammar

- .github/workflows/release.yml
> ci(release): fix find_package_version output

- .changeset/forty-bees-collect.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Bump 1.13.0 to the latest react router versions
> Bump react router versions

- DEVELOPMENT.md
Sibling to https://github.com/remix-run/react-router/pull/10065
> Sync up release docs with react router

- .changeset/empty-ligers-sell.md
- packages/remix-dev/devServer/liveReload.ts
- packages/remix-dev/devServer2.ts
> fix(dev): ignore failed clean up attempts

- DEVELOPMENT.md
- contributors.yml
- docs/file-conventions/route-files-v2.md
> docs: fix typos

- docs/other-api/adapter.md
> docs(other-api/adapter): add `@mcansh/remix-fastify` & `@mcansh/remix-rap-http` to community adapters list

- .github/workflows/lint.yml
- jest.config.js
> ci: disable jest and eslint github annotations

- .github/workflows/reusable-test.yml
> ci: bump styfle/cancel-workflow-action to latest

- packages/remix-dev/__tests__/reveal-test.ts
> test(reveal): prevent jest from leaking logs

- contributors.yml
- docs/utils/sessions.md
> docs(utils/sessions): fixs typo in sessions filename

- integration/defer-test.ts
Bring `bug-report-test.ts` changes tests from https://github.com/remix-run/remix/pull/5346 into `defer-test.ts`
> Add tests for defer returning custom headers

- .changeset/cool-wombats-chew.md
- docs/file-conventions/remix-config.md
- packages/remix-dev/__tests__/fixtures/cloudflare/remix.config.js
- packages/remix-dev/__tests__/fixtures/deno/remix.config.js
- packages/remix-dev/__tests__/fixtures/stack/remix.config.js
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/config.ts
docs: update docs to reference removal of serverBuildTarget
Closes: #
Existing tests cover codepaths
> feat!: remove serverBuildTarget codepaths

- scripts/deployment-test/_shared.mjs
- scripts/deployment-test/arc.mjs
- scripts/deployment-test/cf-pages.mjs
- scripts/deployment-test/cf-workers.mjs
- scripts/deployment-test/deno-deploy.mjs
- scripts/deployment-test/fly.mjs
- scripts/deployment-test/netlify.mjs
- scripts/deployment-test/package.json
- scripts/deployment-test/vercel.mjs
... this may or may not have been deploying 1.6.4 apps since we switched to changesets 🙈
Closes: #
> ci: update deploy tests to use create-remix cli

- docs/other-api/dev.md
- docs/pages/stacks.md
> chore(docs): add docs about `remix init` command

- .changeset/vanilla-extract-cache.md
I missed a couple of packages since the changes were made after I generated the initial changeset.
> Update changeset for Vanilla Extract cache

- .changeset/wild-beers-agree.md
- packages/remix-dev/config.ts
This will warn people about #5703
> feat(remix-dev): show deprecation warning when `serverBuildDirectory` config is used

- integration/helpers/cf-template/app/root.tsx
- integration/helpers/deno-template/app/root.tsx
- integration/helpers/node-template/app/root.tsx
> test(integration/templates): remove `meta` from `root` files

- packages/remix-react/components.tsx
> Fix missing meta/mutation bugs

- templates/arc/remix.config.js
- templates/cloudflare-pages/remix.config.js
- templates/cloudflare-workers/remix.config.js
- templates/deno/remix.config.js
- templates/express/remix.config.js
- templates/fly/remix.config.js
- templates/netlify/remix.config.js
- templates/remix/remix.config.js
- templates/vercel/remix.config.js
> Use `{ v2_errorBoundary: true }` in all templates

- contributors.yml
- docs/tutorials/jokes.md
Hello👋 I made small update on the docs by removing some imports that are not used anywhere in that file.
> docs(tutorials/jokes): remove unused imports

- .changeset/young-clocks-wink.md
- integration/tailwind-test.ts
- package.json
- packages/remix-dev/compiler/utils/postcss.ts
- yarn.lock
https://github.com/tailwindlabs/tailwindcss/pull/10785
currently only on the `insiders` channel so i've updated our root package.json's tailwind version temporarily.
Closes: #
> feat(remix-dev): add support for tailwind.config.{mjs,ts}

- packages/remix-dev/config/defaults/entry.server.cloudflare.tsx
- packages/remix-dev/config/defaults/entry.server.deno.tsx
- packages/remix-dev/config/defaults/entry.server.node.tsx
- templates/arc/app/entry.client.tsx
- templates/arc/app/entry.server.tsx
- templates/arc/package.json
- templates/cloudflare-pages/app/entry.client.tsx
- templates/cloudflare-pages/app/entry.server.tsx
- templates/cloudflare-workers/app/entry.client.tsx
- templates/cloudflare-workers/app/entry.server.tsx
- templates/deno/app/entry.client.tsx
- templates/deno/app/entry.server.tsx
- templates/express/app/entry.client.tsx
- templates/express/app/entry.server.tsx
- templates/fly/app/entry.client.tsx
- templates/fly/app/entry.server.tsx
- templates/netlify/app/entry.client.tsx
- templates/netlify/app/entry.server.tsx
- templates/netlify/package.json
- templates/remix/app/entry.client.tsx
- templates/remix/app/entry.server.tsx
- templates/vercel/app/entry.client.tsx
- templates/vercel/app/entry.server.tsx
- templates/vercel/package.json
Reverts remix-run/remix#5455
todo
> chore(templates): restore optional entry files

- package.json
- yarn.lock
[ESM & TS support is now officially released](https://tailwindcss.com/blog/tailwindcss-v3-3#esm-and-typescript-support)! 🥳🎉
> chore: update `tailwindcss` version

- packages/remix-eslint-config/package.json
- yarn.lock
This will also fix the ESLint errors from #5947
> chore(remix-eslint-config): update dependencies to latest minor

- contributors.yml
- docs/pages/v2.md
Update docs to avoid confusion.
> docs(pages/v2): fix typo in `serverBuildTarget` section

- docs/guides/typescript.md
- package.json
- packages/remix-dev/__tests__/fixtures/cloudflare/package.json
- packages/remix-dev/__tests__/fixtures/indie-stack/package.json
- packages/remix-dev/__tests__/fixtures/node/package.json
- packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
- packages/remix-eslint-config/package.json
- packages/remix-testing/package.json
- scripts/playground/template/package.json
- templates/arc/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers/package.json
- templates/express/package.json
- templates/fly/package.json
- templates/netlify/package.json
- templates/remix/package.json
- templates/vercel/package.json
- yarn.lock
> feat: add TS 5 support

- packages/remix-dev/config/flat-routes.ts
- packages/remix-dev/config/routesConvention.ts
- packages/remix-dev/package.json
- yarn.lock
> chore(deps): bump minimatch to latest

- docs/utils/is-route-error-response.md
It didn't exist yet, but I referenced it in the updated Jokes tutorial 🙈
> docs: add docs for `isRouteErrorResponse`

- .changeset/wicked-hairs-tell.md
- packages/remix-eslint-config/jest.js
This will warn people about #5696
> feat(remix-eslint-config): add deprecation warning to `@remix-run/eslint-config/jest` ESLint config

- packages/remix-dev/config/flat-routes.ts
- packages/remix-dev/config/routesConvention.ts
- packages/remix-dev/package.json
- yarn.lock
This PR is a combination of @mcansh's #6039 & #6042
> chore(deps): bump `minimatch` to latest

- packages/remix-dev/cli.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/error.ts
- packages/remix-dev/compiler/options.ts
- packages/remix-dev/compiler/server/index.ts
- packages/remix-dev/devServer/liveReload.ts
- packages/remix-dev/devServer_unstable/index.ts
- packages/remix-dev/index.ts
- packages/remix-dev/logging.ts
> refactor(dev): clean up

- .changeset/seven-queens-try.md
- packages/remix-cloudflare-pages/package.json
- packages/remix-cloudflare-workers/package.json
- packages/remix-cloudflare/package.json
- templates/cloudflare-pages/package.json
- templates/cloudflare-workers/package.json
- yarn.lock
@lkwr & @zhuhaow might want to have some remarks as they were active on #5425
---
Closes #5425
> feat!(remix-cloudflare,remix-cloudflare-pages,remix-cloudflare-workers): drop `@cloudflare/workers-types` v2 & v3 support

- LICENSE.md
Bring in line with what we have in the RR repo
https://github.com/remix-run/react-router/blob/main/LICENSE.md
> chore: update `LICENSE`

- templates/arc/app/routes/_index.tsx
- templates/cloudflare-pages/app/routes/_index.tsx
- templates/cloudflare-workers/app/routes/_index.tsx
- templates/deno/app/routes/_index.tsx
- templates/express/app/routes/_index.tsx
- templates/fly/app/routes/_index.tsx
- templates/netlify/app/routes/_index.tsx
- templates/remix/app/routes/_index.tsx
- templates/vercel/app/routes/_index.tsx
> fix(templates): import metafunction from remix runtime pkg

- integration/mdx-test.ts
> test(mdx): create referenced css file

- integration/hmr-test.ts
- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): handle rebuilds that start before previous one finished

- .changeset/dev-server.md
- integration/hmr-test.ts
- packages/remix-cloudflare/index.ts
- packages/remix-deno/index.ts
- packages/remix-dev/index.ts
- packages/remix-node/index.ts
- packages/remix-server-runtime/dev.ts
- packages/remix-server-runtime/index.ts
> fix(dev): export `devReady` from runtime packages

- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): reliably detect path to bin for deps

- .changeset/dev-server.md
- integration/hmr-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/devServer_unstable/index.ts
> feat(dev): dev command defaults to remix-serve

- contributors.yml
- docs/pages/stacks.md
> docs(pages/stacks): Fix typo

- templates/express/.gitignore
- templates/express/package.json
- templates/express/server.js
> revert template changes from merge

- .changeset/dry-buses-care.md
- packages/remix-dev/compiler/js/compiler.ts
- packages/remix-dev/config/defaults/entry.dev.ts
- packages/remix-react/browser.tsx
> fix(react,dev): dev chunking and refresh race condition

- templates/express/server.js
Brought this in line with how we do this in the `blues-stack`
https://github.com/remix-run/blues-stack/blob/24727ddd8be6db76b3cef20142334bc88c467399/package.json#L6-L9
https://github.com/remix-run/blues-stack/blob/24727ddd8be6db76b3cef20142334bc88c467399/package.json#L10-L14
https://github.com/remix-run/blues-stack/blob/24727ddd8be6db76b3cef20142334bc88c467399/package.json#L20
---
Follow-up of #5822
Closes #6119
Closes #6161
Thanks @lili21 & @rossipedia for noticing this! 🙏
> templates(express): fix `build`, `dev` & `start` scripts

- templates/remix/remix.config.js
> chore: quiet warnings in remix template

- templates/express/server.js
> fix: use renamed devReady method

- .changeset/dev-server.md
> chore(changeset): update dev server changeset

- templates/cloudflare-pages/app/root.tsx
- templates/cloudflare-workers/app/root.tsx
> chore: fix cf template imports

- .changeset/clever-hairs-live.md
- integration/compiler-mjs-output-test.ts
- packages/remix-dev/compiler/server/write.ts
> chore: write mjs server output files

- .changeset/afraid-mice-remain.md
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/dependencies.ts
> fix: look for @remix-run/serve in devDependencies

- .changeset/stable-router-versions.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
> bump router to stable

- .changeset/ninety-flies-allow.md
- integration/hmr-log-test.ts
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
- packages/remix-dev/compiler/js/compiler.ts
- packages/remix-dev/config.ts
- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): serve any non-Remix assets from `public/`

- .github/workflows/release-comments.yml
> ci(comment): bump comment action version

- .changeset/big-carrots-attend.md
- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): dev server creates cross-platform PATH envvar

- docs/tutorials/jokes.md
> docs(tutorials/jokes): Silence typescript error

- .changeset/five-poems-stare.md
- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): kill app server when dev server exits

- docs/pages/v2.md
See https://discord.com/channels/770287896669978684/1104772116659834941
> docs(pages/v2): move `formMethod` section

- docs/file-conventions/route-files-v2.md
- docs/file-conventions/routes-files.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/mdx.md
- docs/guides/migrating-react-router-app.md
- docs/guides/resource-routes.md
- docs/guides/routing.md
- docs/hooks/use-fetcher.md
- docs/hooks/use-matches.md
- docs/hooks/use-route-loader-data.md
- docs/pages/faq.md
- docs/route/should-reload.md
- docs/route/should-revalidate.md
- docs/utils/defer.md
- packages/remix-dev/config/routes.ts
> docs: use TS files where possible

- integration/hmr-log-test.ts
- integration/hmr-test.ts
> test(hmr): expect exactly 2 console errors in browser

- .changeset/ninety-hornets-brake.md
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
- packages/remix-dev/config.ts
- packages/remix-dev/devServer_unstable/index.ts
> feat(dev): built-in tls support

- .changeset/serious-wolves-attend.md
- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): color output for app server

- docs/guides/migrating-react-router-app.md
Re-submission of @vcheeze's #5847
---
Closes #4623
> docs(guides/migrating-react-router-app): mention `_index` file

- packages/remix-dev/compiler/plugins/cssSideEffectImports.ts
> fix(dev): only apply hmr for remix routes

- contributors.yml
- docs/tutorials/jokes.md
Prisma will return null if user isn't found, so the current try/catch will not work.
> docs(tutorials/jokes): fix `getUser` function

- integration/helpers/create-fixture.ts
This code was accidentally leftover while working on #6508.
> refactor: clean up leftover debugging code

- templates/arc/remix.config.js
- templates/cloudflare-pages/remix.config.js
- templates/cloudflare-workers/remix.config.js
- templates/deno/remix.config.js
- templates/express/remix.config.js
- templates/fly/remix.config.js
- templates/netlify/remix.config.js
- templates/remix/remix.config.js
- templates/vercel/remix.config.js
Follow-up of #6431 
Since it's not released yet, I targeted `dev`
> templates: enable `v2_headers` future flag

- package.json
- packages/remix-dev/__tests__/fixtures/replace-remix-magic-imports/package.json
- packages/remix-dev/package.json
- yarn.lock
> fix(remix-dev): loosen `prettier` version

- packages/remix-react/components.tsx
- packages/remix-react/data.ts
Follow-up of @hjonasson's #5417
> refactor(remix-react): remove unnecessary type-checks

- docs/route/error-boundary-v2.md
> docs(route/error-boundary-v2): fix broken link

- packages/remix-server-runtime/serialize.ts
> fix(dev): only apply pretty types for objects

- .changeset/thin-rings-sparkle.md
- packages/remix-dev/devServer_unstable/index.ts
> refactor(dev): group rebuild logs with surrounding whitespace

- packages/remix-dev/devServer_unstable/index.ts
> fix(dev): do not crash when app server process is already dead on windows

- docs/other-api/dev-v2.md
- docs/pages/v2.md
> docs(v2_dev): edits

- packages/remix-dev/compiler/js/compiler.ts
> perf(dev): @remix-run/{cloudflare,deno,node} as empty modules for browser

- docs/other-api/dev-v2.md
> docs(dev-v2): complete tls instructions

- .changeset/famous-games-film.md
- packages/remix-dev/config/defaults/entry.dev.ts
> fix(dev): ignore missing react-dom/client for react 17

- .changeset/stale-houses-grin.md
- packages/remix-react/package.json
- packages/remix-testing/package.json
- scripts/bump-router-versions.sh
- yarn.lock
Bump React Router to pick up https://github.com/remix-run/react-router/pull/10652 which closes https://github.com/remix-run/remix/issues/6704
> Bump router to 6.14.1-pre.0

- .changeset/angry-flowers-matter.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
> Bump router

- docs/other-api/dev-v2.md
> docs(dev-v2): links to v2_dev videos

- docs/other-api/dev-v2.md
Follow-up of @pcattori's #6771
> docs(other-api/dev-v2): fix video link

- packages/remix-dev/devServer_unstable/proc.ts
Fixes #6768
Since we already have checks in place later to ensure that all processes related to the app server are killed, we can warn here instead.
> fix(dev): log instead of throw when process cannot be killed

- templates/arc/package.json
> Don't restart `arc sandbox` on code changes

- .changeset/strange-mayflies-relax.md
- docs/guides/manual-mode.md
- docs/other-api/dev-v2.md
> v2_dev docs improvements

- docs/tutorials/jokes.md
See https://github.com/remix-run/examples/pull/288
> docs(tutorials/jokes): fix `getUser`

- .changeset/long-teachers-marry.md
- packages/remix-dev/compiler/plugins/cssImports.ts
Fixes #6799
Tested by using the airplane.jpg reproduction from #6799
> fix(dev): always rewrite css-derived assets

- docs/other-api/dev-v2.md
Remove reference to binode
Closes: #
> docs(other-api/dev-v2): update MSW explanation

- .changeset/popular-insects-visit.md
- packages/remix-react/index.tsx
I'm not sure anything else than this is necessary, but happy to make any requested changes
> chore: re-export some react-router-dom things from @remix-run/react

- templates/express/README.md
- templates/remix/README.md
> Update template instructions on copying to a newly created remix app

- .changeset/silver-readers-think.md
- packages/remix-dev/config.ts
> feat(remix-dev)!: remove `browserBuildDirectory` config option

- .changeset/cool-wombats-chew.md
- docs/api/conventions.md
- docs/file-conventions/remix-config.md
- packages/remix-dev/__tests__/fixtures/cloudflare/remix.config.js
- packages/remix-dev/__tests__/fixtures/deno/remix.config.js
- packages/remix-dev/__tests__/fixtures/stack/remix.config.js
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/config.ts
> feat(remix-dev)!: remove `serverBuildTarget` config option

- .changeset/tame-moons-buy.md
- packages/remix-dev/config.ts
> feat(remix-dev)!: remove `serverBuildDirectory` config option

- packages/remix-dev/devServer/liveReload.ts
> Revert "liveReload: add hearbeat for keepalive"

- .changeset/shake-it-out.md
- packages/remix-dev/compiler/js/compiler.ts
Something something Taylor Swift meme.
> chore: shake out HMR code from production build

- .changeset/brown-gifts-chew.md
- packages/remix-netlify/package.json
> feat(remix-netlify)!: drop `@netlify/functions` v0.x support

- .changeset/big-papayas-jam.md
- packages/remix-vercel/package.json
> feat(remix-vercel)!: drop `@vercel/node` v1 support

- packages/remix-dev/config.ts
> refactor!(dev): remove deprecated dev config

- contributors.yml
- docs/guides/streaming.md
Fixes grammatical error "your" to "you".
> docs(guides/streaming): fix typo

- docs/components/form.md
- docs/guides/api-routes.md
- docs/guides/constraints.md
- docs/guides/data-loading.md
- docs/guides/errors.md
- docs/guides/routing.md
- docs/guides/styling.md
- docs/hooks/use-fetcher.md
- docs/route/action.md
- docs/route/headers.md
- docs/route/loader.md
- docs/route/meta-v2.md
- docs/route/should-revalidate.md
- packages/remix-dev/__tests__/defineRoutes-test.ts
Follow-up of @markdalgleish's #6969
> docs: use V2 routing convention

- templates/cloudflare-workers/package.json
> templates(cloudflare-workers): add `@cloudflare/kv-asset-handler` to `dependencies`

- .changeset/rotten-penguins-eat.md
- integration/hmr-log-test.ts
- integration/hmr-test.ts
- integration/shared-route-imports-test.ts
- packages/remix-dev/__tests__/cli-test.ts
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/cli/commands.ts
- packages/remix-dev/cli/run.ts
- packages/remix-dev/compiler/js/compiler.ts
- packages/remix-dev/config.ts
- packages/remix-react/entry.ts
- packages/remix-serve/cli.ts
- packages/remix-server-runtime/__tests__/utils.ts
- packages/remix-server-runtime/entry.ts
- packages/remix-testing/create-remix-stub.tsx
> refactor!: replace `config.future.v2_dev` with `config.dev`

- templates/netlify/README.md
- templates/netlify/package.json
- templates/netlify/server.ts
Deprecation warning to our own adapter will be added in #6937
> templates(netlify): use official Netlify adapter

- docs/components/nav-link.md
Same update as https://github.com/remix-run/react-router/pull/10757
> Update NavLink docs for end prop on root route links

- docs/other-api/node.md
Add docs on Remix support for Node LTS versions
> Add docs on node lts strategy

- .changeset/lovely-drinks-bow.md
- packages/remix-dev/compiler/js/plugins/hmr.ts
> fix(dev): allow jsx in js files during hmr

- .github/workflows/deduplicate-yarn.yml
> chore: fix `deduplicate-yarn` workflow

- docs/guides/typescript.md
- packages/remix-cloudflare-workers/package.json
- packages/remix-dev/__tests__/fixtures/cloudflare/package.json
- packages/remix-dev/__tests__/fixtures/indie-stack/package.json
- packages/remix-dev/__tests__/fixtures/node/package.json
- packages/remix-eslint-config/package.json
- packages/remix-express/package.json
- packages/remix-node/package.json
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- scripts/playground/template/package.json
- templates/arc/package.json
- templates/cloudflare-workers/package.json
- templates/express/package.json
- templates/fly/package.json
- templates/remix/package.json
- yarn.lock
I hope this one will now trigger the dedupe workflow 🙏
> chore: update `typescript`

- contributors.yml
- templates/cloudflare-workers/package.json
> templates(cloudflare-workers): use `wrangler deploy`

- templates/cloudflare-workers/package.json
- templates/cloudflare-workers/wrangler.toml
Same as we did in #2079, but this was by accident reverted in @pcattori's #6650
> templates(cloudflare-workers): prevent building twice

- docs/pages/v2.md
Looks like a copy/paste/replace mistake
> docs(pages/v2): fix `useFetcher` example

- .changeset/shiny-teachers-cheer.md
- packages/remix-dev/compiler/watch.ts
> fix(dev): do not trigger rebuild when .DS_Store changes

- .changeset/v2-serve-dynamic-import.md
- packages/remix-serve/rollup.config.js
> chore: preserve dynamic import for remix-serve

- .changeset/khaki-roses-matter.md
- packages/remix-dev/compiler/js/plugins/hmr.ts
- packages/remix-dev/devServer_unstable/proc.ts
- packages/remix-dev/package.json
- yarn.lock
> fix(dev): allow decorators in app code during dev

- integration/bug-report-test.ts
- integration/helpers/create-fixture.ts
- integration/remix-serve-test.ts
- packages/remix-serve/cli.ts
- rollup.utils.js
> fix(remix-serve): update shared build utils to preserve dynamic imports for CLIs

- docs/other-api/node.md
> docs(other-api/node): remove Cloudflare/Deno references

- .changeset/remove-stream-recursion.md
- packages/remix-node/stream.ts
Closes: #
Existing tests cover usage of utilities
> refactor(remix-node): remove recursion from stream utilities

- contributors.yml
- docs/discussion/01-runtimes.md
- docs/start/tutorial.md
Small contributions to new Docs
> Docs contributions

- docs/start/quickstart.md
Follow-up of @ryanflorence's e9768e8c after going through the tutorial
> docs(start/quickstart): bring in line with other tutorials

- .changeset/beige-pugs-drive.md
- packages/remix-serve/cli.ts
- packages/remix-serve/package.json
- yarn.lock
> feat!(serve): pick an open port when 3000 is already taken

- .changeset/young-pants-buy.md
- packages/remix-dev/compiler/server/compiler.ts
> compile server build to node 18

- docs/guides/errors.md
This has come up in Discord a few times so I added a section on error sanitization to the `Error Handling` docs
> Add docs on error santization

- .changeset/brown-flowers-push.md
- packages/remix-react/index.tsx
Re-export https://github.com/remix-run/react-router/pull/10797 through `@remix-run/react`
> feat(remix-react): re-export `ShouldRevalidateFunctionArgs`

- contributors.yml
- docs/start/tutorial.md
Mostly just updating
- `LoaderArgs` -> `LoaderFunctionArgs`
- `ActionArgs` -> `ActionFunctionArgs`
Otherwise just fixing some line highlighting. Had a few comments/questions I'll call out in code comments
> docs(start/tutorial): update APIs and line numbers

- docs/start/v2.md
> docs: v2_dev after upgrading from v1 to v2

- docs/guides/manual-mode.md
> docs(manual-mode): add instructions for remix-serve

- docs/guides/local-tls.md
- docs/other-api/dev.md
> docs(guides/local-tls): dedicated guide for setting up local TLS

- .changeset/bump-web-fetch.md
- packages/remix-node/package.json
- yarn.lock
> Update to latest version of @remix-run/web-fetch

- README.md
- contributors.yml
Fixes the "Technical Explanation" link that currently points to a 404 page.
> Fixes README link to technical explanation

- templates/cloudflare-pages/tsconfig.json
> fix(templates/cloudflare-pages): skiplibcheck

- contributors.yml
- docs/start/tutorial.md
Some referenced app/routes/root.tsx , replacing those with app/root.tsx
**If this is a simple docs change, go ahead and delete all this.**
> docs(start/tutorial): fix filenames

- docs/other-api/dev.md
> docs: react fast refresh limitations

- contributors.yml
- docs/discussion/runtimes.md
> docs(discussion/runtime): Update code sample with respective comments.

- docs/start/tutorial.md
> docs(start/tutorial): fix code highlighting

- contributors.yml
- docs/start/v2.md
This is a simple docs change to fix a missing slash.
> Add missing folder slash to v2.md

- .changeset/express-flush-stream-headers.md
- packages/remix-express/server.ts
> chore: flush headers for event-stream responses

- .changeset/start-view-transition.md
- docs/components/form.md
- docs/components/link.md
- docs/components/nav-link.md
- docs/hooks/use-view-transition-state.md
- packages/remix-react/index.tsx
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Remix updates for `startViewTransition` support
React Router PR: https://github.com/remix-run/react-router/pull/10916
> Add startViewTransition support

- docs/future/vite.md
> docs(vite): fix link to react keys

- .changeset/nine-knives-compare.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
> Lock into stable react router version

- docs/future/vite.md
- integration/vite-build-test.ts
- integration/vite-css-build-test.ts
- integration/vite-css-dev-test.ts
- integration/vite-css-legacy-build-test.ts
- integration/vite-dev-test.ts
> use .ts for vite config

- contributors.yml
- docs/discussion/state-management.md
Fixes a small typo! Let me know if you need me to do anything else.
> docs(discussion/state-management): fix typo

- integration/vite-dev-express-test.ts
> test(vite): use .ts for vite config

- packages/remix-dev/vite/node/adapter.ts
see https://developer.mozilla.org/en-US/docs/Web/HTTP/Methods
Closes: #
> vite: allow request body for post, put, delete, patch

- docs/future/vite.md
- docs/other-api/dev.md
> fix links to HMR discussion

- docs/future/vite.md
- docs/other-api/dev.md
> fix HMR discussion links... again

- docs/future/vite.md
- templates/unstable-vite-express/package.json
- templates/unstable-vite/package.json
> rewrite getting started and adapt existing migration guide

- docs/future/vite.md
> fix link to unstable vite template

- docs/future/vite.md
> docs(vite): step-by-step migration guide

- docs/future/vite.md
> docs(vite): fix rendering of typescript for custom server instructions

- docs/future/vite.md
> docs(vite): polish migrating guide

- contributors.yml
- docs/hooks/use-navigation.md
> docs(hooks/use-navigation): fix typo

- docs/future/vite.md
also, bold step-by-step instructions and fix info arch levels
Closes: #
> docs(vite): move legacy css instructions into the migration guide

- contributors.yml
- packages/remix-react/components.tsx
Changes:
- [CLA signed](https://github.com/remix-run/remix/commit/cea6f18a5930851744c1b0f6dc6c74a63dc17588)
- [Update the Link component comment](https://github.com/remix-run/remix/commit/b07927d97507381c718ef61b5f69da18b079a6bf) to include all accepted properties (matching the [docs](https://remix.run/docs/en/main/components/link#prefetch)).
> chore(remix-react): update `Link`'s `prefetch` comment

- .changeset/spotty-timers-swim.md
- packages/remix-dev/package.json
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Pull in changes from https://github.com/remix-run/react-router/pull/10977
> Bump to latest router prerelease

- docs/future/vite.md
> docs(vite): remove redundant server scripts heading

- docs/future/vite.md
- templates/unstable-vite-express/README.md
- templates/unstable-vite/README.md
> docs: fix @nightly to @latest for vite inits

- docs/future/vite.md
> docs(vite): troubleshooting for esm/cjs interop

- docs/utils/defer.md
> docs: Fix broken link

- contributors.yml
- docs/discussion/state-management.md
`cookie.parse()` can return null.
> docs: Improve cookie example code

- .github/ISSUE_TEMPLATE/bug_report.yml
- more guidance on helpful reproductions
- require system info (and provide link for easy way to get it)
- ask for package manager
> rewrite bug report template

- contributors.yml
- docs/discussion/hot-module-replacement.md
Fix an issue in the diff section of hot-module-replacement showing the change of a key in loader data.
> docs(discussion/hot-module-replacement): Fix diff

- .changeset/breezy-emus-fold.md
- packages/remix-dev/package.json
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
Bump router to latest prerelease
> Update router versions

- integration/helpers/dev.ts
- integration/vite-css-dev-express-test.ts
- integration/vite-dotenv-test.ts
- integration/vite-hmr-hdr-test.ts
- integration/vite-loader-context-test.ts
> test(vite): test `vite dev` against hmr/hdr flow

- integration/helpers/vite.ts
- integration/vite-css-dev-express-test.ts
- integration/vite-dotenv-test.ts
- integration/vite-hmr-hdr-test.ts
- integration/vite-loader-context-test.ts
- Rename `integration/helpers/dev.ts` to `integration/helpers/vite.ts`
- Add template prop for request handler args (to inject load context)
> test(vite): refactor

- packages/remix-dev/vite/plugin.ts
> refactor(vite): disable hmr for child compiler

- docs/future/vite.md
Closes: https://github.com/remix-run/remix/issues/7953 https://github.com/remix-run/remix/issues/8094
> docs(vite): add `vite.config.ts` examples for vitest and storybook

- docs/future/vite.md
> docs(vite): .server directories

- docs/future/vite.md
> docs(vite): align squiggly

- docs/future/vite.md
> docs(vite): add example to beginning of strict exports section

- .changeset/client-data.md
- .changeset/data-function-args.md
- docs/route/client-action.md
- docs/route/client-loader.md
- docs/route/hydrate-fallback.md
- docs/route/loader.md
> Client Data Documentation Updates

- .changeset/fast-cars-poke.md
- packages/remix-node/package.json
- yarn.lock
Bump web fetch to pick up https://github.com/remix-run/web-std-io/pull/55
> Bump web fetch dep

- yarn.lock
Cherry picks 3 dependabot PRs in order to point them at dev
https://github.com/remix-run/remix/pull/7860
https://github.com/remix-run/remix/pull/7862
https://github.com/remix-run/remix/pull/7859
> Cherry-pick dependabot updates

- docs/future/vite.md
Some minor migration guide updates based on my own migration experience.
> docs(vite): Update TypeScript integration guide

- docs/future/vite.md
- packages/remix-dev/vite/plugin.ts
This is the next best thing to marking it as stable 🚀
> fix(vite): Remove Vite production use warnings

- docs/hooks/use-submit.md
This is documented in RR but never made it into the Remix version
> Add encType application/json to useSubmit docs

- templates/unstable-vite/vite.config.ts
Brings templates inline with our integration tests
> fix(templates/vite): no polyfills by default

- docs/future/vite.md
> docs(vite): migrating full stack components

- .changeset/seven-bees-thank.md
Follow up to https://github.com/remix-run/remix/pull/8320.
> chore(vite): add changeset for disabling build watch

- docs/future/vite.md
> docs(vite): fix typo

- LICENSE.md
- contributors.yml
> Update copyright year to 2024

- decisions/0009-do-not-rely-on-treeshaking-for-correctness.md
nitty gritty technical details behind #8413
> docs(decisions): do not rely on treeshaking for correctness

- decisions/0009-do-not-rely-on-treeshaking-for-correctness.md
> docs(decisions): add md title for 0009

- docs/future/vite.md
> docs(vite): troubleshooting w/ vite-plugin-inspect

- decisions/0009-do-not-rely-on-treeshaking-for-correctness.md
> docs(decisions): clarify server-only handling in consequences

- decisions/0009-do-not-rely-on-treeshaking-for-correctness.md
> docs(decisions/0009): esbuild minify considerations link

- packages/remix-dev/package.json
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-testing/package.json
- yarn.lock
> Bump router version

- docs/future/vite.md
> docs: server-only isolation in vite

- docs/start/quickstart.md
Thanks @rickhanlonii
- Adds `npx create-remix@latest` explicitly to the quickstart guide
- Updates the link to find templates
[Credit](https://twitter.com/rickhanlonii/status/1745473046507381058)
> docs: Add cli command and update templates link

- contributors.yml
- docs/other-api/adapter.md
Adds `@scandinavianairlines/remix-azure-functions` to the community adapters list
> docs(other-api/adapters): add remix-azure-functions to adapters

- docs/future/vite.md
This PR adds a section to the Vite troubleshooting guide explaining the issue with disappearing styles in dev and a couple of ways to fix it.
> docs(vite): add troubleshooting for disappearing styles

- docs/future/vite.md
This PR makes a few tweaks to this section of the Vite docs:
- Re-orders the paragraphs so it's more tl;dr friendly. Up front, you get a short explanation of the problem followed by the solution. Deeper explanation is provided later.
- Removes the root-layout workaround since it doesn't work for HydrateFallback, and it's generally awkward and not preferable to adopting a canary version of React. We're planning to add more docs for this, but this is enough for now to fix the current guidance for Vite consumers.
- Adds a note about hydration errors causing remounts.
- Generally rewords a few things to improve the flow.
> docs(vite): update style remount troubleshooting

- docs/future/vite.md
Based on feedback from @pcattori.
> docs(vite): reword style remount troubleshooting

- packages/remix-dev/vite/build.ts
- packages/remix-dev/vite/plugin.ts
When exploring replacing the separate `serverBuildDirectory` and `assetsBuildDirectory` options with a single `buildDirectory` option, I realised that a blocker for this would be the fact that the mechanism for building server bundles is coupled to the `serverBuildDirectory` option.
To address this, this PR decouples the two so that now, the Remix CLI only injects the `serverBundleId`, not its resolved output directory. Once this lands, it'll be trivial to change the shape of our config without having to touch the server bundle build process.
> refactor(vite): decouple server bundle config from serverBuildDirectory

- docs/future/vite.md
Adding a link to the [video](https://www.youtube.com/watch?v=jmNuEEtwkD4) I made for fixing cjs/esm issues.
Feel free to suggest changes to the language or order in the docs
> docs: add how to fix cjs/esm bugs video link

- contributors.yml
- docs/guides/envvars.md
Small update so the link to CF docs page works.
> Update "Environment Variables" page w/ proper CF docs link

- .changeset/fast-dodos-yell.md
- packages/remix-dev/vite/plugin.ts
> vite: fix "could not fast refresh" false alarm

- packages/remix-dev/vite/build.ts
- packages/remix-dev/vite/plugin.ts
This refactor is in preparation to expose the resolved Remix config as public API (e.g. via the adapter `buildEnd` hook). One thing holding this back was that the private `serverBundleId` property was part of the resolved config type even though it'll never be present from a consumer perspective.
As part of this refactor I realised `serverBundleId` should have been on the `ssrBuildContext` object all along. To raise its prominence, I've renamed this to just `buildContext`.
> refactor(remix-dev/vite): move server bundle ID to build context

- templates/arc/tsconfig.json
- templates/cloudflare-pages/tsconfig.json
- templates/cloudflare-workers/tsconfig.json
- templates/express/tsconfig.json
- templates/fly/tsconfig.json
- templates/remix-tutorial/tsconfig.json
- templates/remix/tsconfig.json
- templates/spa/tsconfig.json
> templates: enable `skipLibCheck`

- docs/future/vite.md
> vite: link to cloudflare docs for proxy features

- decisions/0010-splitting-up-client-and-server-code-in-vite.md
> decision: splitting up client and server code in vite

- decisions/0010-splitting-up-client-and-server-code-in-vite.md
> decisions(0010): fix link

- decisions/0010-splitting-up-client-and-server-code-in-vite.md
> decisions(0010): add checkmarks for goals 3 and 4

- .changeset/tender-pens-tan.md
- packages/remix-dev/vite/plugin.ts
- templates/spa/README.md
Minor updates to follow up #8624
> Minor updates for SPA Mode + vite preview

- .changeset/cyan-snails-provide.md
- docs/future/spa-mode.md
- integration/spa-mode-test.ts
- packages/remix-dev/config/defaults/entry.server.spa.tsx
- templates/spa/app/entry.server.tsx
The conditional we had in here wasn't necessary since users have full control via `npx remix reveal`
> Always prepend DOCTYPE in SPA mode entry.server.tsx

- .changeset/fluffy-peas-promise.md
- integration/resource-routes-test.ts
- packages/remix-server-runtime/server.ts
Enhance error message per https://github.com/remix-run/remix/pull/8714
> Throw a more specific error if a user returns defer from a resource route

- docs/future/vite.md
- templates/vite-cloudflare/README.md
> vite: cloudflare docs + templates fixes

- docs/future/server-bundles.md
These docs weren't updated to the new manifest structure.
> Update server bundles manifest docs

- .changeset/great-jokes-destroy.md
- packages/remix-cloudflare-pages/worker.ts
> fix(cloudflare-pages): cloudflare context at top level for back compat

- templates/arc/app/root.tsx
- templates/cloudflare-pages/app/root.tsx
- templates/cloudflare-workers/app/root.tsx
- templates/deno/app/root.tsx
- templates/express/app/root.tsx
- templates/fly/app/root.tsx
- templates/remix-javascript/app/root.jsx
- templates/remix/app/root.tsx
> fix hydration errors by reverting `Layout` in non-Vite templates

- .changeset/many-grapes-confess.md
- packages/remix-dev/compiler/js/plugins/routes.ts
> fix: mark Layout as browser safe route export

- contributors.yml
- docs/future/vite.md
This pull request updates the documentation for the Vite [example using Vitest](https://remix.run/docs/en/main/future/vite#plugin-usage-with-other-vite-based-tools-eg-vitest-storybook).
More specifically it updates the highlighted lines in the Vitest example.
Related #8788
> docs(vite): update `vite.config.ts` example for Vitest

- contributors.yml
- templates/arc/.eslintrc.cjs
- templates/cloudflare-pages/.eslintrc.cjs
- templates/cloudflare-workers/.eslintrc.cjs
- templates/fly/.eslintrc.cjs
- templates/remix-javascript/.eslintrc.cjs
- templates/remix/.eslintrc.cjs
- templates/spa/.eslintrc.cjs
- templates/vite-cloudflare/.eslintrc.cjs
- templates/vite/.eslintrc.cjs
Closes: #
I ran `yarn lint` only on the part (Node) I fixed.
**Before fix**
**After fix**
> templates: fix typos in `eslintrc.cjs`

- templates/vite-cloudflare/env.d.ts
- templates/vite-cloudflare/tsconfig.json
- templates/vite-express/env.d.ts
- templates/vite-express/tsconfig.json
- templates/vite/env.d.ts
- templates/vite/tsconfig.json
> chore: remove .d.ts files from templates in favor of tsconfig.json types

- contributors.yml
- docs/guides/templates.md
Added new vite templates
Closes: #
> Docs: Add Vite templates to official templates list

- contributors.yml
- templates/cloudflare-pages/.gitignore
Add the `.wrangler` directory created by `wrangler` command  to the `.gitignore` file, ensuring it is not tracked by Git.
> remix/templates/cloudflare-pages: ignore .wrangler directory on .gitignore

- .github/ISSUE_TEMPLATE/bug_report.yml
> Switch StackBlitz link to use remix.new

- .changeset/layout-error-boundary.md
- .changeset/layout-hydrate-fallback.md
- integration/spa-mode-test.ts
- packages/remix-react/errorBoundaries.tsx
- packages/remix-react/fallback.tsx
Same as #8859 but for the default root `HydrateFallback`
Closes #8880
> Fix root default HydrateFallback when Layout exists

- contributors.yml
- docs/hooks/use-fetcher.md
Add mention that any JSON data can be submitted with `useFetcher`.
Improves documentation as explained here https://github.com/remix-run/remix/discussions/1959#discussioncomment-8510081
> docs: Update useFetcher to include mention of JSON data

- .changeset/few-rice-join.md
- integration/root-route-test.ts
- integration/spa-mode-test.ts
- packages/remix-react/errorBoundaries.tsx
- packages/remix-react/fallback.tsx
Follow up to https://github.com/remix-run/remix/pull/8892
> Fix BoundaryShell usage in default HydrateFallback

- integration/headers-test.ts
- packages/remix-dev/config/defaults/entry.server.cloudflare.tsx
- packages/remix-dev/config/defaults/entry.server.deno.tsx
- packages/remix-dev/config/defaults/entry.server.node.tsx
- templates/arc/app/entry.server.tsx
- templates/cloudflare-pages/app/entry.server.tsx
- templates/cloudflare-workers/app/entry.server.tsx
- templates/deno/app/entry.server.tsx
- templates/express/app/entry.server.tsx
- templates/fly/app/entry.server.tsx
- templates/remix-javascript/app/entry.server.jsx
- templates/remix/app/entry.server.tsx
- templates/vite-cloudflare/app/entry.server.tsx
- templates/vite-express/app/entry.server.tsx
- templates/vite/app/entry.server.tsx
> Revert "chore: simplify template entry.server files"

- .changeset/loud-games-reply.md
- packages/remix-react/routeModules.ts
- packages/remix-react/routes.tsx
Closes https://github.com/remix-run/remix/issues/8849
> Enhance the LayoutComponent type

- contributors.yml
- docs/start/tutorial.md
> docs: docs/start/tutorial.md supplementary file reference information

- contributors.yml
- docs/start/quickstart.md
This is just a tiny one character suggestion.
Closes: #
> Fix typo in quick start guide

- docs/discussion/form-vs-fetcher.md
Fixes to code in Form vs. Fetcher Recipes example.
> Fix "Form vs. fetcher" docs example code

- contributors.yml
- docs/future/vite.md
Language here was bothering me.
Feel free to close if you disagree!
> docs(future/vite): fix grammar

- contributors.yml
- docs/guides/migrating-react-router-app.md
Update client-only-component example usage link
Closes: #
> docs(guides/migrating-react-router-app): update repo link

- .changeset/brave-cars-approve.md
> forgot to add a changeset

- contributors.yml
- docs/guides/errors.md
Correct a type from `then` to `them`
> Update errors.md for typo of "then"

- docs/discussion/routes.md
Replaces https://github.com/remix-run/remix/pull/9261
> Update route docs

- .changeset/sweet-falcons-relax.md
- packages/remix-react/tsconfig.json
Closes https://github.com/remix-run/remix/issues/9295
> Ignore future d.ts files from TS build

- packages/remix-dev/vite/resolve-file-url.ts
explictly -> explicitly
refs: https://github.com/remix-run/remix/pull/9373
> refactor(remix-dev/vite): fix typo in resolve-file-url.ts

- contributors.yml
- docs/start/quickstart.md
Missing verb. If meant to be shorthand, the rest of the document should follow suit.
Closes: #
> docs(start/quickstart): Fix typo

- contributors.yml
- docs/guides/single-fetch.md
> Fixes spelling error from "than" to "then"

- templates/cloudflare-workers/.gitignore
- templates/cloudflare-workers/package.json
- templates/cloudflare/package.json
We've had a number of issues in the past with wrangler updating and breaking things. Going to resume pinning the version and update some docs while I'm here
Closes: #8288
> chore: pin wrangler, update cf packages, add .dev.vars to gitignore

- docs/guides/single-fetch.md
- Small typos
- Consistency regarding `Single Fetch` "branding" (80% was already using pascal case)
- Changed the `json` import to `@remix-run/node`, they're the same but it always feels weird to me to import a `Response` utility from a "client" package
- Routes consistency
- N/A Tests
> docs: fix single fetch typos

- contributors.yml
- docs/start/tutorial.md
The route appears to have been simplified to `/<width>/<height>/`.
> fix(docs): update URL for placekitten.com

- docs/guides/single-fetch.md
> docs: update flow and language of single-fetch.md

- contributors.yml
- docs/guides/single-fetch.md
> typos single-fetch.md

- docs/guides/api-development-strategy.md
- docs/start/future-flags.md
> Update future flags guide

- docs/discussion/pending-ui.md
Some minor improvements to the Pending UI docs
Closes: #
- N/A Tests
> docs(discussion/pending-ui): minor improvements

- integration/helpers/deno-template/app/root.tsx
- integration/helpers/deno-template/app/routes/_index.tsx
Just like #9540, fixing Deno linting on `dev` now
> chore: fix `lint:deno` script

- docs/guides/vite.md
- docs/start/future-flags.md
> docs: add Vite section to Future Flags docs

- docs/hooks/use-fetcher.md
> docs: add note about fetcher.load revalidation

- .changeset/forty-gifts-boil.md
- integration/single-fetch-test.ts
- packages/remix-server-runtime/server.ts
- packages/remix-server-runtime/single-fetch.ts
> Properly handle thrown 4xx/5xx response stubs in single fetch

- .changeset/strange-chefs-think.md
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- pnpm-lock.yaml
> Update turbo-stream to latest

- contributors.yml
- templates/express/package.json
> fix: remove duplicated `cross-env` dependency from express template

- contributors.yml
- docs/guides/css-files.md
> Correct CSS docs example using links export in route file

- contributors.yml
- docs/guides/faq.md
Closes: #9704
Related to my previous PR #9737
> docs: add info on FormData submitter and SubmitEvent compatibility

- contributors.yml
- docs/guides/single-fetch.md
> remove redundent word

- .changeset/shy-ducks-repeat.md
- integration/fog-of-war-test.ts
- integration/package.json
- packages/remix-dev/package.json
- packages/remix-react/browser.tsx
- packages/remix-react/fog-of-war.ts
- packages/remix-react/package.json
- packages/remix-server-runtime/package.json
- packages/remix-server-runtime/server.ts
- packages/remix-testing/package.json
- pnpm-lock.yaml
Remix portion of https://github.com/remix-run/react-router/pull/11883
Closes https://github.com/remix-run/remix/issues/9799
> Handle fog of war edge cases with server-known higher-scoring routes

- .changeset/popular-meals-hide.md
- integration/single-fetch-test.ts
- packages/remix-react/single-fetch.tsx
- packages/remix-server-runtime/server.ts
Closes https://github.com/remix-run/remix/issues/9884
> Change content type on single fetch requests

- .changeset/two-chicken-provide.md
- packages/remix-react/fallback.tsx
Closes https://github.com/remix-run/remix/issues/9897
> Clarify wording in default  console warning

- packages/remix-server-runtime/single-fetch.ts
to be compatible with `interface`s
> lenient return type for `unstable_data`

- packages/remix-server-runtime/serialize.ts
not just functions without parameters
> fix single-fetch types: correctly check for arbitrary functions

- .changeset/hot-dogs-applaud.md
- docs/guides/dependency-optimization.md
- docs/guides/single-fetch.md
- docs/start/future-flags.md
- packages/remix-dev/__tests__/readConfig-test.ts
- packages/remix-dev/config.ts
- packages/remix-dev/vite/plugin.ts
> future flag for automatic optimize deps

- contributors.yml
- docs/file-conventions/routes.md
> [docs] fix layout in nested-layouts-without-nested-urls section

- docs/route/loader.md
just a parameter which is not used in the function body
> docs(route/loader): fix example

- contributors.yml
- templates/cloudflare/app/root.tsx
- templates/cloudflare/app/routes/_index.tsx
Fixed incorrect module imports for Cloudflare templates.
> Fix Cloudflare template imports

- contributors.yml
- docs/guides/resource-routes.md
Fixed an incorrect example. This threw me off a bit and cost me a bit of time! Such is life.
> docs(guides/resource-routes): fix example

- contributors.yml
- docs/start/tutorial.md
This PR sorts the props of components in several sample codes throughout the tutorial (ignore this if you intended to place them in the current way). No functional changes have been made.
> docs(start/tutorial): sort arguments

- README.md
- contributors.yml
Let this sentence end like the other ones in the readme file.
_This is a hacktoberfest demo PR during an introduction to Open Source contribution_
_Feel free to close this in case this is to spammy_  😗
> [Grammar] Add missing period after sentence.

- templates/cloudflare-workers/app/root.tsx
- templates/cloudflare-workers/app/routes/_index.tsx
- templates/cloudflare-workers/vite.config.ts
- templates/cloudflare/vite.config.ts
- templates/express/vite.config.ts
- templates/remix-javascript/vite.config.js
- templates/remix/vite.config.ts
- templates/spa/vite.config.ts
> Enable all stable future flags in templates

- contributors.yml
- docs/file-conventions/routes.md
Fixes a minor grammar issue by pluralizing "hundred" to "hundreds".
> docs(file-conventions): fix grammar

- docs/start/future-flags.md
> docs: update future flags guide

- CHANGELOG.md
- contributors.yml
Date should be in 2024 rather than future
Closes: #
> docs: fix release notes date

- contributors.yml
- docs/start/future-flags.md
Corrected a typo 'doing do' → 'doing so'
> Fix typo in future-flags.md

- docs/guides/templates.md
- docs/index.md
- docs/other-api/create-remix.md
- docs/start/quickstart.md
- docs/start/tutorial.md
Happy to change the copy if necessary. I'm pretty sure I've got all of the major starting point pages covered.
> docs: add warnings to use React Router

- .changeset/blue-mirrors-shout.md
- integration/headers-test.ts
- packages/remix-server-runtime/headers.ts
Closes https://github.com/remix-run/remix/issues/10421
> Avoid duplicated set-cookie headers

- .changeset/happy-ravens-burn.md
- packages/remix-dev/vite/plugin.ts
> Clean up vite-node dev server after build

- .changeset/old-plums-perform.md
- packages/remix-express/__tests__/server-test.ts
- packages/remix-express/server.ts
> host parse

- .changeset/shiny-suns-dance.md
- packages/remix-dev/package.json
- pnpm-lock.yaml
Fix for https://github.com/vitest-dev/vitest/security/advisories/GHSA-9crc-q9x8-hgqq & https://github.com/vitest-dev/vitest/security/advisories/GHSA-8gvc-j273-4wm5
---
CC/ @platocrat
> fix(dev): update `vite-node`

- README.md
- contributors.yml
N/A
Note:
Avoided adding changeset since that's readme update only 😃
> docs(README): fix typo

- .changeset/quiet-shirts-hear.md
- packages/create-remix/package.json
- packages/remix-dev/package.json
- pnpm-lock.yaml
Just like https://github.com/remix-run/react-router/pull/13675
> Fixes https://github.com/advisories/GHSA-pq67-2wwv-3xjx
> v2: update `tar-fs`
